Jann 30/objects/Approver_Group__c.object
<CustomObject>
    <description>Approver Groups</description>
    <fields>
        <fullName>Approver_GroupName__c</fullName>
        <formula>TEXT(Level__c)   &amp;  &apos; &apos; &amp;   Approver_Role__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approver Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Group_Description__c</fullName>
        <description>Approver Group Description</description>
        <label>Approver Group Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Role__c</fullName>
        <description>Approver Role</description>
        <label>Approver Role</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>Level</description>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>KEYOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. EXEC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA Approver Group</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Approver Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approver Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA_GroupApprover__c.object
<CustomObject>
    <description>This stores the Approver users list</description>
    <fields>
        <fullName>Approver_Group_Description__c</fullName>
        <description>Approver Group Description</description>
        <label>Approver Group Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Group__c</fullName>
        <description>Approver Group</description>
        <label>Approver Group</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approver Name</description>
        <label>Approver Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFA_Approver_Name</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver_Role__c</fullName>
        <description>Approver Roles</description>
        <label>Approver Role</label>
        <picklist>
            <picklistValues>
                <fullName>ABC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>Business Unit name from Profit center</description>
        <formula>Profit_Center__r.Business_Unit_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <formula>Profit_Center__r.GroupName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Operation__c</fullName>
        <description>Key Operation from Profit Center</description>
        <formula>Profit_Center__r.KeyOperationName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Key Operation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>KEYOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr EXEC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Profit_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA Approvers</relationshipLabel>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RFA Approver</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>RFA Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_Approver.cls
public class RFA_VFC_Approver 
{
    public RFA_GroupApprover__c GrpApprverObj {get;set;}
    public String selectedLevel{set;get;}
    public List<SelectOption> ApproverLevels{set;get;}
    
    
    public String selectedApproverRole{set;get;}
    public List<SelectOption> ApproverRole{set;get;}
    public Boolean ApproverRoles{set;get;}
    public Decimal sequence{get;set;}
     public Boolean ApproverGroups{set;get;}
    
    public String selectedGroup{set;get;}
    public List<SelectOption> ApproverGroup{set;get;}
    
    public boolean editMode{get;set;}
    public boolean viewMode{get;set;}
    String GroupDescription;
    public boolean showmessage {get;set;}
    String ProfileName;
    Id username;
    public Boolean FieldMsgs{set;get;} 
    public RFA_VFC_Approver(apexpages.StandardController appCtrl)
    {
        ApproverRoles = false;
        showmessage = false;
        FieldMsgs = false;
        //Coordinator Level security
        username = userinfo.getUserId();
        Id profileId=userinfo.getProfileId();
        ProfileName = [Select Id,Name from Profile where Id=:profileId].Name;
        if(ProfileName != null && ProfileName == 'RFA - Standard User' )
           {
              List<ProfitCenterUserRole__c> PCUobj = [select Level__c from ProfitCenterUserRole__c where UserName__c = : username and UserType__c = 'Location Coordinator' ];
               if(PCUobj != null && PCUobj.size() >0 )
               {
                 getAvailableLevels(); 
                 editmode = true;
               }
               else
               {
                  ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'You Donot Have Permissions to Edit Approver'));  
                  showmessage = true ; 
                   FieldMsgs = false;
                   editmode = false;
               }    
           }
        //End here
    if(showmessage == false)
    {
        GrpApprverObj = (RFA_GroupApprover__c)appCtrl.getRecord();
        System.debug('GrpApprverObj'+GrpApprverObj);
        System.debug('GrpApprverObj.Id'+GrpApprverObj.Id);
        if(GrpApprverObj.Id!=null)
        {
            System.debug('hi iam null');
            GrpApprverObj=[select Profit_Center__c,Approver_Name__c,Approver_Group__c,Approver_Group_Description__c,Sequence__c ,Approver_Role__c,Level__c ,Key_Operation__c ,Business_Unit__c, Group__c,LastModifiedById, createdById   from RFA_GroupApprover__c  where id=:GrpApprverObj.id ];
            sequence = GrpApprverObj.Sequence__c;
            selectedLevel = GrpApprverObj.Level__c;
            selectedApproverRole = GrpApprverObj.Approver_Role__c;
            selectedGroup = GrpApprverObj.Approver_Group__c; 
        }
        
        //Populating selected Group
        ApproverGroup= new List<SelectOption>();
        if(selectedGroup!=null)
        {
            ApproverGroup.add(new SelectOption('--Select--','--Select--'));
            ApproverGroup.add(new SelectOption(selectedGroup,selectedGroup));
        }
         
        
       
        System.debug('Levels that can be accessed '+ApproverLevels);
            
        /*Schema.DescribeFieldResult ApproverLevelsResult = RFA_GroupApprover__c.Level__c.getDescribe();
         
        ApproverLevels.add(new SelectOption('--Select--','--Select--'));
        for (Schema.PicklistEntry ApproverLevelpicklist : ApproverLevelsResult.getPicklistValues())
        {
                System.debug('ApproverLevelpicklist label '+ApproverLevelpicklist.getLabel());
                ApproverLevels.add(new SelectOption(ApproverLevelpicklist.getValue(),ApproverLevelpicklist.getLabel()));
        }  
        */
        
        
        
        /*if(ApexPages.currentPage().getParameters().get('save_new') != null || (ApexPages.currentPage().getParameters().get('id') == null && ApexPages.currentPage().getParameters().get('retURL') != null))
        {
            editMode = false;
            viewMode = false;
        }
        else if(ApexPages.currentPage().getParameters().get('id') != null && ApexPages.currentPage().getParameters().get('retURL') != null)
        {
            editMode = true;
            viewMode = false;
        }
        else
        {
            editMode = false;
            viewMode = true;
        }*/
        string url = ApexPages.currentPage().getURL();
        if(ApexPages.currentPage().getParameters().get('Id')!=null&& !url.contains('retURL'))       
        {  
            System.debug('You opened in detail mode');
            EditMode=false;
           
        }
         else
        {
            System.debug('You opened in EDIT mode');
            EditMode=true;
            getAvailableLevels();
        } 
        }
    }
    /*
    Public void getApproverRoles()
    {
        ApproverRole = new List<SelectOption>();
        ApproverRoles=true;
        system.debug('Level is..'+GrpApprveRObj.Level__c);
        system.debug('selectedLevel Level is..'+selectedLevel);
         
        if(selectedLevel!=null&&selectedLevel!='')
        { 
        
        List<Approver_Group__c> GroupsList = [Select Approver_GroupName__c,Approver_Role__c from Approver_Group__c where level__C=:selectedLevel];
        System.debug('Groups are: '+GroupsList);
        ApproverRole.add(new SelectOption('--Select--','--Select--'));
        for(Approver_Group__c eachGrp: GroupsList)
        {
            ApproverRole.add(new SelectOption(eachGrp.Approver_Role__c,eachGrp.Approver_Role__c));
        }
        }
    }
    */
    
    Public void getApproverGroups()
    {
        ApproverGroups = true;
         
        List<Approver_Group__c> GroupsList = [Select Approver_GroupName__c,Approver_Group_Description__c from Approver_Group__c where Approver_GroupName__c like :selectedLevel+'%'];
        System.debug('GroupsList'+GroupsList);
        ApproverGroup = new List<SelectOption>();
        for(Approver_Group__c eachGrp : GroupsList)
        {
            ApproverGroup.add(new selectOption(eachGrp.Approver_GroupName__c,eachGrp.Approver_GroupName__c));
             
        } 
    }
    public void getAvailableLevels()
    {
        ApproverLevels = new List<SelectOption>();         
        //Populating Approver Level values
        ApproverLevels = RFA_VFC_CoordinatorLevelHelper.getAvailableLevels();
    }
    /*
    Public void getApproverGroups()
    {
        ApproverGroups = true;
        String LevelRole=selectedLevel+' '+selectedApproverRole;
        system.debug('Level Role combination '+LevelRole);
        List<Approver_Group__c> GroupsList = [Select Approver_GroupName__c,Approver_Group_Description__c from Approver_Group__c where Approver_GroupName__c=:LevelRole];
        System.debug('GroupsList'+GroupsList);
        ApproverGroup = new List<SelectOption>();
        for(Approver_Group__c eachGrp : GroupsList)
        {
            ApproverGroup.add(new selectOption(eachGrp.Approver_GroupName__c,eachGrp.Approver_GroupName__c));
            GroupDescription = eachGrp.Approver_Group_Description__c;
        } 
    }*/
    
    public PageReference saveApprover()
    {
        try{
        if(selectedGroup=='--Select--' && ApproverGroup.size()>1)
        {
            FieldMsgs = true;
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please Select Approver Group'));
        }
        else{
            if(selectedGroup=='--Select--')
            {
                selectedGroup=null;
            }
            EditMode=false;
            System.debug('GrpApprveRObj '+GrpApprveRObj);
            System.debug('GrpApprveRObj.sequence'+sequence);
            GrpApprveRObj.sequence__c=sequence;
            GrpApprveRObj.Approver_Role__c=selectedApproverRole;
            GrpApprveRObj.Level__c = selectedLevel;
            GrpApprveRObj.Approver_Group__c=selectedGroup;
            List<Approver_Group__c> Groupdesc=[select Approver_Group_Description__c from Approver_Group__c where Approver_GroupName__c=:selectedGroup];
            System.debug('Group descripton'+Groupdesc);
            if(Groupdesc!=null)
            {
             GrpApprveRObj.Approver_Group_Description__c= Groupdesc.get(0).Approver_Group_Description__c;   
            }
            
            //GrpApprveRObj.Approver_Name__c=
            upsert GrpApprveRObj;
            }
        }
            catch(System.DmlException  e)
            {
                 EditMode=true;
                  FieldMsgs = true;
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getDMLMessage(0)));        
            }
        
        return null;
    }
    public PageReference EditApprover()
    {
        editMode = true;
        return null;
    }
    public PageReference CancelApprover()
    {
        editMode=false;
        System.debug('hi null'+GrpApprverObj.Id);
        if(GrpApprverObj.Id==null)
        {
            System.debug('hi null');
            return new PageReference('/a1o/o');
        }
        else
        {
             System.debug('hi null');
              return null ;
        }
    }
    public PageReference DeleteApprover()
    {
        editMode=false;
        delete GrpApprveRObj;
        return new PageReference('/a1o/o');
            
    }
    
    public pagereference Bck()
    {
      pagereference pref = new pagereference('/a1o?fcf=00Bg00000016xp9');
      return pref;
    }
    
    
}