Jann 30/objects/ApprovalProcess__c.object
<CustomObject>
    <fields>
        <fullName>RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Approval Processes</relationshipLabel>
        <relationshipName>Approval_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Process</label>
    <nameField>
        <displayFormat>AP#-{00000}</displayFormat>
        <label>Approval Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ReportingUnit__c.object
<CustomObject>
    <description>RFA R1 - Stores all Reporting Units within the RFA Application to be referenced on a specific RFA.</description>
    <fields>
        <fullName>ActiveInactive__c</fullName>
        <label>Active/Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reporting_Unit_Name__c</fullName>
        <label>Reporting Unit Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reporting Unit</label>
    <nameField>
        <label>Reporting Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Units</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>ExecutiveSummaryGuideline__c</fullName>
        <defaultValue>&quot;Provide a concise, high-level description of the requested transaction sufficient to allow an executive to make a well informed decision. Include the following to the extent relevant:&quot; +BR()+
&quot; - Key Objectives/ Background/ Rationale&quot; +BR()+
&quot; - Key Cost Estimates&quot; +BR()+
&quot; - Key Benefits, Financial Metrics and Assumptions&quot; +BR()+
&quot; - Key Risks and Alternatives&quot; +BR()+
&quot; - Key Other Considerations&quot; +BR()+BR()+

&quot;Also, include the following in the Executive Summary as relevant:&quot; +BR()+
&quot; - Describe the components of the RFA “request amount”.&quot; +BR()+
&quot; - Describe the reporting units (legal entities) impacted by this transaction. Include, as applicable, a description of how the transaction will be funded (e.g. capital contribution, inter-company loan) and how the funding will flow through the hierarchy of legal entities. Additionally, describe the current ownership structure (i.e. parents) of the legal entities involved and any impact to the ownership structure as a result of the transaction.&quot;</defaultValue>
        <label>Executive Summary Guideline</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PrimaryDOACategorySubCategory__c</fullName>
        <inlineHelpText>This field allows the RFA Creator to select up to 3  DOA Categories that apply to the requested transaction.</inlineHelpText>
        <label>Primary DOA Category / Sub Category *</label>
        <picklist>
            <picklistValues>
                <fullName>1.A.1	Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.a	Capital Expenditures - Unbudgeted CPR or SPR Covered by Budget Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.b	Capital Expenditures - Unbudgeted CPR or SPR Funded Partially or Fully from Corporate Reserve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.3	Capital Expenditures - Increase or Scope Change to Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.4	Capital Expenditures - Transfer of Capital Budget across Groups for a Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.5	Capital Expenditures - Foreign Exchange Fluctuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.8	Capital Expenditures - Advance Appropriations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.B	Capital Expenditures - Capability and Performance Programs (CAPPrs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.C	Capital Expenditures - Bottles and Cases, Including Overages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.	IT Investments and Website Presence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.A	Real Property -  Acquisitions and Sales or Other Disposals of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.B	Real Property -  Donations of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.C	Real Property - Condemnations or Easements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.A	Leases - Operating Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.B	Leases - Capital Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.A	Inventory Adjustments and Disposals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.B	Other Asset Impairments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.C	Asset Transfers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.D	Asset Disposals (Tangible Assets excluding Real Property and Inventory)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.A	Treasury - Banking Information Reports (BIR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.B	Treasury - External Borrowings and Lines of Credit (RFFs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.C	Treasury - Intercompany Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.D	Treasury - Loans Third Parties (Including CCFC Target Loan Programs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.1	Treasury - Guarantees to Third Parties - General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.2	Treasury - Guarantees Related to Tax Disputes or Other Matters Involving Governmental Bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.F	Treasury - Comfort Letters and Other Financial Security Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.G	Treasury - Accommodation Purchases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.H	Treasury - Credit Terms/Policies or Incentives for Sales to Customers, Bottlers or Distributors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.1	Treasury - Exemption from Bad Debt Reserve Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.2	Treasury - Write-offs of Uncollectible Accounts Receivable from Bad Debt Reserve</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PrimaryReportingUnitNumber__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reporting Unit (RU) is the same as Co. Code and is either a legal entity or an acctg location.  RU is a four-digit code with an “RU” prefix in this system (e.g. RU0101 – North America).  Select the RU(s) recording the transaction.</inlineHelpText>
        <label>Primary Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase.  (e.g.,  Write-off  45 non-working vending machines in Atlanta sales center)</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondReportingUnitNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A four-digit code that is the lowest level at which consolidation occurs. Same as Co. code and is either a legal entity or an acctg. location (e.g., 0101 - North America). Select the reporting unit(s) recording the transaction.</inlineHelpText>
        <label>Second Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA (Secondary Reporting Unit Number)</relationshipLabel>
        <relationshipName>RFA1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ThirdReportingUnitNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A four-digit code that is the lowest level at which consolidation occurs. Same as Co. code and is either a legal entity or an acctg. location (e.g., 0101 - North America). Select the reporting unit(s) recording the transaction.</inlineHelpText>
        <label>Third Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA (Third Reporting Unit Number)</relationshipLabel>
        <relationshipName>RFA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_WS04_setRecommendation_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class RFA_WS04_setRecommendation_Test {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
          test.StartTest();
        User testUsr1 = AdminUser('standt1'); 
        insert testUsr1;
        User testUsr2 = AdminUser('standt2'); 
        insert testUsr2;
        User testUsr3 = AdminUser('standt3'); 
        insert testUsr3;
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFATestData.getRecordType('General Request', 'RFA__c');
        String rt2 = RFATestData.getRecordType('Approver', 'RFAUserRole__c');
        ReportingUnit__c testReportingUnit=new ReportingUnit__c();
        testReportingUnit.ActiveInactive__c = 'Active';
        testReportingUnit.Name = 'USA Reporting Unit NA';
        testReportingUnit.Reporting_Unit_Name__c = 'Atlanta Bottling Company, Limited';
        insert testReportingUnit;
        ReportingUnit__c testReportingUnit1=new ReportingUnit__c();
        testReportingUnit1.ActiveInactive__c = 'Active';
        testReportingUnit1.Name = 'India Reporting Unit NA';
        testReportingUnit1.Reporting_Unit_Name__c = 'Bottling Company, Limited';
        insert testReportingUnit1;
        ReportingUnit__c testReportingUnit2=new ReportingUnit__c();
        testReportingUnit2.ActiveInactive__c = 'Active';
        testReportingUnit2.Name = 'USAUnit NA';
        testReportingUnit2.Reporting_Unit_Name__c = 'Atlanta Bottling';
        insert testReportingUnit2;
        
        RFA__c testRFA = new RFA__c();
        testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
        testRFA.RecordTypeId =  rt;
        
        testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
        testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
        testRFA.Stage__c = 'Draft';
        
        testRFA.PrimaryReportingUnitNumber__c=testReportingUnit.Id;
        testRFA.SecondReportingUnitNumber__c=testReportingUnit1.Id;
        testRFA.ThirdReportingUnitNumber__c=testReportingUnit2.Id;
        insert testRFA;
/***********************/
        //create PPOC
        User pocUser = new User();
        pocUser = testData.createUser(RFATestData.rfaStandardUserProfile, 'ppoc', 'ppoc', pocUser);
        RFAUserRole__c ppocUserRole = RFATestData.buildPPOC(testRFA.Id, pocUser);
        insert ppocUserRole;
/***********************/
        
        testRFA.ExecutiveSummaryGuideline__c='test';
        testRfa.PrimaryDOACategorySubCategory__c='rr';
        RFATestData.updateThreeYearCashSpentForRFA(testRFA,Double.valueof('99.0'));
        testRFA.Stage__c = 'Circulation';
        testRFA.Level__c = '1. Key Operations';
        testRFA.DataClassification__c = 'Internal Use';
        testRFA.AREMonth__c = 'February';
        testRFA.InitialBudgetYear__c = '2013';
        testRFA.BudgetType__c = 'Formal';
        testRFA.IsthisanAnnualCapitalPlanrequest__c = 'No';
        testRFA.RequestAmountFunctionalCurrency__c=99.0;
        testRFA.ExecutiveSummary__c = 'This is for the purpose of testing';
        testRFA.PrimaryDOACategorySubCategory__c = '1.A.1   Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
        testRFA.Functional_Currency__c = RFATestData.testARE.Id;
        update testRFA;
        
        
        System.runAs(RFATestData.requester)
        {
            try{
            RFA_WS04_KOApprove_setRecommendation.setRecommendation(null,null,null,null);
            }catch(Exception e)
            {
            }
            
            
        }
        try{
        RFA_WS04_KOApprove_setRecommendation.setRecommendation(null,null,null,null);
        }catch(Exception e)
        {
        
        }
        /*RFAUserRole__c rfaUser = new RFAUserRole__c(level__C='1. Key Operations', RFA__c = testRFA.Id, ApprovalRecommendation__c='Awaiting Approval', UserName__c = userinfo.getUserId(),
                                                    Agent1__c = testUsr1.Id, Agent2__c = testUsr2.Id, Agent3__c = testUsr3.Id,recordTypeId=rt2);
        insert rfaUser;*/
        
        RFAUserRole__c rfaUser = RFATestData.buildApprover(testRFA.Id, testRFA.level__c);
        rfaUser.UserName__c = UserInfo.getUserId();
        rfaUser.Agent1__c = testUsr1.Id;
        rfaUser.Agent2__c = testUsr2.Id;
        rfaUser.Agent3__c = testUsr3.Id;
        insert rfaUser;
        
        ApprovalProcess__c testProcess = new ApprovalProcess__c();
        Database.UpsertResult upsertResult = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
        if(upsertResult.isSuccess())
        {
            rfaUser.ApprovalProcess__c = upsertResult.getId();
            rfaUser.ApprovalOrder__c = 1;
            rfaUser.ApprovalRecommendation__c = 'Awaiting Approval';
            update rfaUser;
                
        }
        
        RFA_WS02_KOApprove_getAllRequests.statusMessageWrapper message=new RFA_WS02_KOApprove_getAllRequests.statusMessageWrapper('d','d');//Message class instance
        
        //RFA_WS04_KOApprove_setRecommendation.response(message);
        
        RFA_WS04_KOApprove_setRecommendation.setRecommendation('Test comments','Approved','standt1@coke.com',rfaUser.id);
        
    
    }
      public static User AdminUser(String alias){
        Profile profile = [select id from profile where name='System Administrator'];
        User user = new User(alias = alias, email=alias + '@coke.com',
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
            localesidkey='en_US', profileid = profile.Id,FederationIdentifier=alias + '@coke.com',
            timezonesidkey='Europe/London', username=alias + '@coke.com');
        return user;
    }
}