Jann 30/objects/ApprovalProcess__c.object
<CustomObject>
    <fields>
        <fullName>RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Approval Processes</relationshipLabel>
        <relationshipName>Approval_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Process</label>
    <nameField>
        <displayFormat>AP#-{00000}</displayFormat>
        <label>Approval Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PrimaryReportingUnitNumber__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reporting Unit (RU) is the same as Co. Code and is either a legal entity or an acctg location.  RU is a four-digit code with an “RU” prefix in this system (e.g. RU0101 – North America).  Select the RU(s) recording the transaction.</inlineHelpText>
        <label>Primary Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase.  (e.g.,  Write-off  45 non-working vending machines in Atlanta sales center)</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0)</defaultValue>
        <inlineHelpText>This field is used to sequence the order of approvals during circulation.  Notifications will be sent to approvers in order from the lowest to highest number.  Approvers with the same order number will receive notifications at the same time.</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Process</label>
        <referenceTo>ApprovalProcess__c</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_WS02_KOApprove_getAllRequests_TEST.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes 
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class  RFA_WS02_KOApprove_getAllRequests_TEST 
{
    static testmethod void RFA_AP01_Test()
     {      
        test.StartTest();
        User testUsr1 = AdminUser('standt1'); 
        insert testUsr1;
        User testUsr2 = AdminUser('standt2'); 
        insert testUsr2;
        User testUsr3 = AdminUser('standt3'); 
        insert testUsr3;
        RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt = RFATestData.getRecordType('Capital Project Request', 'RFA__c');
    	
    	System.runAs(RFATestData.requester)
    	{
    	
    	RFA_WS02_KOApprove_getAllRequests.getAllRFADetails();
    	
    
    	RFA_WS02_KOApprove_getAllRequests.statusMessageWrapper message=new RFA_WS02_KOApprove_getAllRequests.statusMessageWrapper('d','d');//Message class instance
    	RFA_WS02_KOApprove_getAllRequests.rfaFinalWrapper finalWrapper=new RFA_WS02_KOApprove_getAllRequests.rfaFinalWrapper();
    	RFA_WS02_KOApprove_getAllRequests.rfaDataContainer dataContainer=new RFA_WS02_KOApprove_getAllRequests.rfaDataContainer();
    	RFA_WS02_KOApprove_getAllRequests.rfaWrappersForAllRequests allRequests=new RFA_WS02_KOApprove_getAllRequests.rfaWrappersForAllRequests(); 
    	}
    	RFA__c testRFA = new RFA__c();
    	/*testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
    	testRFA.RecordTypeId = 	rt;
    	testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
    	testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
    	testRFA.Stage__c = 'Draft';
    	insert testRFA;*/
    	//testRFA = new RFA__c(ProfitCenterNumber__c = RFATestData.testProfitCenter.Id, RequestTitle__c = 'Capital Project Request RFA Title', 
           //                 PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id, Stage__c = 'Draft');      
        //insert testRFA;
        
        /*
        RFAUserRole__c rfaUser = new RFAUserRole__c( RFA__c = testRFA.Id, ApprovalRecommendation__c='Awaiting Approval', UserName__c = userinfo.getUserId(),
                                                    Agent1__c = testUsr1.Id, Agent2__c = testUsr2.Id, Agent3__c = testUsr3.Id);
        insert rfaUser;*/
        
        testRFA = RFATestData.buildTestRFA(testRFA, rt);
        
        User approverUser = new User();
		approverUser = testData.createUser(RFATestData.rfaStandardUserProfile, 'app1', 'app1', approverUser);
		RFAUserRole__c approver = RFATestData.buildApprover(testRFA.Id, approverUser, testRFA.level__c);
		insert approver;
        ApprovalProcess__c testProcess = new ApprovalProcess__c();
		Database.UpsertResult upsertResult = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
		if(upsertResult.isSuccess())
		{
			approver.ApprovalProcess__c = upsertResult.getId();
			approver.ApprovalOrder__c = 1;
			approver.ApprovalRecommendation__c = 'Awaiting Approval';
			update approver;	
		}
        Attachment attRec = new Attachment(ParentId = testRFA.Id, Name = 'Test Attachment', body = blob.valueOf('Test Body'));
        insert attRec;
        
        RFA_WS02_KOApprove_getAllRequests.getAllRFADetails();
        test.stopTest();
    	
     }
     
     public static User AdminUser(String alias){
        Profile profile = [select id from profile where name='System Administrator'];
        User user = new User(alias = alias, email=alias + '@bel.com',
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
            localesidkey='en_US', profileid = profile.Id,FederationIdentifier=alias + '@bel.com',
            timezonesidkey='Europe/London', username=alias + '@bel.com');
        return user;
    }
}