Jann 30/objects/ApprovalProcess__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalProcessLevel__c</fullName>
        <label>Approval Process Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Approval Processes</relationshipLabel>
        <relationshipName>Approval_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Approval Process</label>
    <nameField>
        <displayFormat>AP#-{00000}</displayFormat>
        <label>Approval Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0)</defaultValue>
        <inlineHelpText>This field is used to sequence the order of approvals during circulation.  Notifications will be sent to approvers in order from the lowest to highest number.  Approvers with the same order number will receive notifications at the same time.</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Process</label>
        <referenceTo>ApprovalProcess__c</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC04_ApprovalProcessController_Test.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@isTest(SeeAllData=true)
private class RFA_VFC04_ApprovalProcessController_Test
{
    static testmethod void RFA_VFC04_ApprovalProcess_Test1()
    {
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        RFA__c testRFA; 
        User approverUser;
        
        System.runAs(RFATestData.requester)
        {
            testRFA = RFATestData.buildTestRFA(testRFA, rt);
            
        }
        
        System.runAs(RFATestData.levelLCUserMap.get(testRFA.Level__c))
        {
            approverUser = new User();
            approverUser = testData.createUser(RFATestData.rfaStandardUserProfile, 'app1', 'app1', approverUser);
            RFAUserRole__c approver = RFATestData.buildApprover(testRFA.Id, approverUser, testRFA.level__c);
            insert approver;
            ApprovalProcess__c testProcess = new ApprovalProcess__c();
            Database.UpsertResult upsertResult = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
            if(upsertResult.isSuccess())
            {
                approver.ApprovalProcess__c = upsertResult.getId();
                approver.ApprovalOrder__c = 1;
                approver.ApprovalRecommendation__c = 'Awaiting Approval';
                update approver;    
            }
            RFA__c rfaVsal = [Select Id, Level__c, Stage__c FROM RFA__c where Id =: testRFA.Id];
            System.assertEquals('1. Key Operations', rfaVsal.Level__c);
            System.assertEquals('Circulation', rfaVsal.Stage__c);
        } 
        Test.startTest();
        ApexPages.Standardcontroller stdController;
        RFA_VFC04_ApprovalProcessController controller;
        System.runAs(approverUser)
        {
            Map<String, String> urlParams = new Map<String, String>{
                'Id' => testRFA.Id
                    };
                        Test.setCurrentPage(getPageReference('RFA_VFP02_Override', urlParams));
            
            stdController = new ApexPages.Standardcontroller(testRFA);
            controller = new RFA_VFC04_ApprovalProcessController(stdController);
            controller.prepareWorkItem();
            List<SelectOption> recomOptions = controller.recommendationOptions;
            controller.selectedRecommendation = 'Unconditionally Approved';
            controller.selectedWorkItem = controller.workItemOptions[0].getValue();
            
            
        }
        controller.submitRecommendation();
        ApprovalProcess__c processVal = [Select ApprovalProcessLevel__c, RFA__r.Level__c, RFA__r.Stage__c, Status__c FROM ApprovalProcess__c WHERE RFA__c =: testRFA.Id];
        System.assertEquals('Completed', processVal.Status__c);
        System.assertEquals('1. Key Operations', processVal.RFA__r.Level__c);
        System.assertEquals('Post-Circulation', processVal.RFA__r.Stage__c);     
        Test.StopTest();
    }
    
    static testmethod void RFA_VFC04_ApprovalProcess_Test2()
    {
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        RFA__c testRFA; 
        User approverUser;
        
        System.runAs(RFATestData.requester)
        {
            testRFA = RFATestData.buildTestRFA(testRFA, rt);
            
        }
        
        System.runAs(RFATestData.levelLCUserMap.get(testRFA.Level__c))
        {
            approverUser = new User();
            approverUser = testData.createUser(RFATestData.rfaStandardUserProfile, 'app1', 'app1', approverUser);
            RFAUserRole__c approver = RFATestData.buildApprover(testRFA.Id, approverUser, testRFA.level__c);
            insert approver;
            ApprovalProcess__c testProcess = new ApprovalProcess__c();
            Database.UpsertResult upsertResult = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
            if(upsertResult.isSuccess())
            {
                approver.ApprovalProcess__c = upsertResult.getId();
                approver.ApprovalOrder__c = 1;
                approver.ApprovalRecommendation__c = 'Awaiting Approval';
                update approver;    
            }
            RFA__c rfaVsal = [Select Id, Level__c, Stage__c FROM RFA__c where Id =: testRFA.Id];
            System.assertEquals('1. Key Operations', rfaVsal.Level__c);
            System.assertEquals('Circulation', rfaVsal.Stage__c);
        } 
        Test.startTest();
        ApexPages.Standardcontroller stdController;
        RFA_VFC04_ApprovalProcessController controller;
        System.runAs(approverUser)
        {
            Map<String, String> urlParams = new Map<String, String>{
                'Id' => testRFA.Id
                    };
                        Test.setCurrentPage(getPageReference('RFA_VFP02_Override', urlParams));
            
            stdController = new ApexPages.Standardcontroller(testRFA);
            controller = new RFA_VFC04_ApprovalProcessController(stdController);
            controller.prepareWorkItem();
            List<SelectOption> recomOptions = controller.recommendationOptions;
            controller.selectedRecommendation = 'Unconditionally Approved';
            //controller.selectedWorkItem = controller.workItemOptions[0].getValue();
            
            
        }
        controller.submitRecommendation();
        ApprovalProcess__c processVal = [Select ApprovalProcessLevel__c, RFA__r.Level__c, RFA__r.Stage__c, Status__c FROM ApprovalProcess__c WHERE RFA__c =: testRFA.Id];
        
        Test.StopTest();
    }
    
    
    //For REQ 23.12
    static testmethod void RFA_VFC04_ApprovalProcess_Test3()
    {
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        RFA__c testRFA;	
        User approverUser;
        User approverAgent1;
        
        System.runAs(RFATestData.requester)
        {
            testRFA = RFATestData.buildTestRFA(testRFA, rt);
            
        }
        
        System.runAs(RFATestData.levelLCUserMap.get(testRFA.Level__c))
        {
            approverUser = new User();
            approverUser = testData.createUser(RFATestData.rfaStandardUserProfile, 'apr1', 'apr1', approverUser);
            
            approverAgent1 = new User();
            approverAgent1 = testData.createUserasAgent(RFATestData.rfaStandardUserProfile, 'Agnt', approverAgent1);
            
            RFAUserRole__c approver = RFATestData.buildApprover(testRFA.Id, approverUser, testRFA.level__c);
            
            //approver.ApprovalRecommendation__c = 'Awaiting Approval';
            system.debug('approverUser is '+approverAgent1);
            system.debug('approver '+approverAgent1.id);
            approver.Agent1__c =  approverAgent1.id;
            //approver.UserName__c = approverUser.id;
            insert approver;
            ApprovalProcess__c testProcess = new ApprovalProcess__c();
            Database.UpsertResult upsertResult = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
            if(upsertResult.isSuccess())
            {
                approver.ApprovalProcess__c = upsertResult.getId();
                approver.ApprovalOrder__c = 1;
                approver.ApprovalRecommendation__c = 'Awaiting Approval';
                update approver;	
            }
            
            RFA__c rfaVsal = [Select Id, Level__c, Stage__c FROM RFA__c where Id =: testRFA.Id];
            System.assertEquals('1. Key Operations', rfaVsal.Level__c);
            System.assertEquals('Circulation', rfaVsal.Stage__c);
        } 
        Test.startTest();
        ApexPages.Standardcontroller stdController;
        RFA_VFC04_ApprovalProcessController controller;
        System.runAs(approverUser)
        {
            Map<String, String> urlParams = new Map<String, String>{
                'Id' => testRFA.Id
                    };
                        Test.setCurrentPage(getPageReference('RFA_VFP02_Override', urlParams));
            
            stdController = new ApexPages.Standardcontroller(testRFA);
            controller = new RFA_VFC04_ApprovalProcessController(stdController);
            controller.prepareWorkItem();
            List<SelectOption> recomOptions = controller.recommendationOptions;
            controller.selectedRecommendation = 'Rejected';
            controller.approvalComments='rej';
            
            
            controller.selectedWorkItem = controller.workItemOptions[0].getValue();
            
            
            
        }
        controller.submitRecommendation();
        
        ApprovalProcess__c processVal = [Select ApprovalProcessLevel__c, RFA__r.Level__c, RFA__r.Stage__c, Status__c FROM ApprovalProcess__c WHERE RFA__c =: testRFA.Id];
        
        System.assertEquals('Completed', processVal.Status__c);
        System.assertEquals('1. Key Operations', processVal.RFA__r.Level__c);
        System.assertEquals('Post-Circulation', processVal.RFA__r.Stage__c);  	 
        Test.StopTest();
    }
    
    
    
    static PageReference getPageReference(String page, Map<String, String> params) {
        String url = '/apex/'+page+'?';
        for (String param : params.keySet()) {
            url += param + '=' + params.get(param) + '&';
        }
        PageReference p = new PageReference(url);
        return p;
    }
    
}