Jann 30/objects/ApprovalProcess__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalProcessLevel__c</fullName>
        <label>Approval Process Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Approval Processes</relationshipLabel>
        <relationshipName>Approval_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Approval Process</label>
    <nameField>
        <displayFormat>AP#-{00000}</displayFormat>
        <label>Approval Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalOrder__c</fullName>
        <defaultValue>IF( $RecordType.Name  = &quot;Approver&quot;, 1,0)</defaultValue>
        <inlineHelpText>This field is used to sequence the order of approvals during circulation.  Notifications will be sent to approvers in order from the lowest to highest number.  Approvers with the same order number will receive notifications at the same time.</inlineHelpText>
        <label>Approval Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApprovalProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Process</label>
        <referenceTo>ApprovalProcess__c</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFAStage__c</fullName>
        <formula>TEXT(RFA__r.Stage__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RFAStage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_ApprovalProcess_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RFA_ApprovalProcess_Test {

    static testMethod void testSubmitForApproval() {
        Map<String, RFA__Share> rfaShareMap = new Map<String, RFA__Share>();
        Map<String, List<RFAUserRole__c>> approverLevelMap = new Map<String, List<RFAUserRole__c>>();
        List<RFAUserRole__c> cocreators = new List<RFAUserRole__c>();
        List<RFAUserRole__c> reviewers = new List<RFAUserRole__c>();
    	RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
    	
    	RFA__c testRFA;
    	
    	System.runAs(RFATestData.requester)
    	{
    		testRFA = RFATestData.buildTestRFA(testRFA, rt);
    	}
    	
    	User approver1 = new User();
    	approver1 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app1', 'app1', approver1);
    	
    	User approver2 = new User();
    	approver2 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app2', 'app2', approver2);
    	
    	RFAUserRole__c rfaApprover1 = RFATestData.buildApprover(testRFA.Id, approver1, '1. Key Operations');
    	RFAUserRole__c rfaApprover2 = RFATestData.buildApprover(testRFA.Id, approver2, '1. Key Operations');
    	approverLevelMap.put('1. Key Operations', new List<RFAUserRole__c>{rfaApprover1, rfaApprover2});
    	insert approverlevelMap.get('1. Key Operations');
    	
    	ApprovalProcess__c testProcess = new ApprovalProcess__c();
    	
    	Database.UpsertResult result = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
    	
    	System.assert(result.isSuccess());
    	
    	rfaApprover1.ApprovalRecommendation__c = 'Awaiting Approval';
    	rfaApprover1.ApprovalOrder__c = 1;
    	rfaApprover1.ApprovalProcess__c = result.getId();
    	update rfaApprover1;
    	
    	rfaApprover2.ApprovalRecommendation__c = 'Awaiting Approval';
    	rfaApprover2.ApprovalOrder__c = 1;
    	rfaApprover2.ApprovalProcess__c = result.getId();
    	update rfaApprover2;
    	
    	testRFA.Stage__c = 'Circulation';
    	update testRFA;
    	
    	Test.startTest();
    	
    	RFA__Share[] rfaShareRecords = [Select parentId, RowCause, UserOrGroupId, AccessLevel From RFA__Share where parentId =: testRFA.Id];
		System.debug('\n rfa share records :'+rfaShareRecords);
    	for(RFA__Share share : rfaShareRecords)
    	{
    		rfaShareMap.put(share.UserOrGroupId, share);
    	}
    	System.assertEquals('Read', rfaShareMap.get(approver1.Id).AccessLevel);
    	System.assertEquals('Read', rfaShareMap.get(approver2.Id).AccessLevel);
    	
    	rfaApprover1.ApprovalRecommendation__c = 'Unconditionally Approved';
    	update rfaApprover1;
    	
    	rfaApprover2.ApprovalRecommendation__c = 'Unconditionally Approved';
    	update rfaApprover2;
    	
    	Test.stopTest();
    	
    	
    }
    
    static testMethod void testSubmitForApproval2() {
        Map<String, RFA__Share> rfaShareMap = new Map<String, RFA__Share>();
        Map<String, List<RFAUserRole__c>> approverLevelMap = new Map<String, List<RFAUserRole__c>>();
        List<RFAUserRole__c> cocreators = new List<RFAUserRole__c>();
        List<RFAUserRole__c> reviewers = new List<RFAUserRole__c>();
    	RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
    	
    	RFA__c testRFA;
    	
    	System.runAs(RFATestData.requester)
    	{
    		testRFA = RFATestData.buildTestRFA(testRFA, rt);
    	}
    	
    	User approver1 = new User();
    	approver1 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app1', 'app1', approver1);
    	
    	User approver2 = new User();
    	approver2 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app2', 'app2', approver2);
    	
    	RFAUserRole__c rfaApprover1 = RFATestData.buildApprover(testRFA.Id, approver1, '1. Key Operations');
    	RFAUserRole__c rfaApprover2 = RFATestData.buildApprover(testRFA.Id, approver2, '1. Key Operations');
    	approverLevelMap.put('1. Key Operations', new List<RFAUserRole__c>{rfaApprover1, rfaApprover2});
    	insert approverlevelMap.get('1. Key Operations');
    	
    	ApprovalProcess__c testProcess = new ApprovalProcess__c();
    	
    	Database.UpsertResult result = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
    	
    	System.assert(result.isSuccess());
    	
    	rfaApprover1.ApprovalRecommendation__c = 'Awaiting Approval';
    	rfaApprover1.ApprovalOrder__c = 1;
    	rfaApprover1.ApprovalProcess__c = result.getId();
    	update rfaApprover1;
    	
    	rfaApprover2.ApprovalRecommendation__c = 'Awaiting Approval';
    	rfaApprover2.ApprovalOrder__c = 2;
    	rfaApprover2.ApprovalProcess__c = result.getId();
    	update rfaApprover2;
    	
    	testRFA.Stage__c = 'Circulation';
    	update testRFA;
    	
    	Test.startTest();
    	
    	RFA__Share[] rfaShareRecords = [Select parentId, RowCause, UserOrGroupId, AccessLevel From RFA__Share where parentId =: testRFA.Id];
		System.debug('\n rfa share records :'+rfaShareRecords);
    	for(RFA__Share share : rfaShareRecords)
    	{
    		rfaShareMap.put(share.UserOrGroupId, share);
    	}
    	    	
    	
    	rfaApprover1.ApprovalRecommendation__c = 'Unconditionally Approved';
    	update rfaApprover1;
    	
    	rfaApprover2.ApprovalRecommendation__c = 'Unconditionally Approved';
    	update rfaApprover2;
    	
    	Test.stopTest();
    	
    	
    }
    
    static testMethod void testDeleteApprover() {
        Map<String, RFA__Share> rfaShareMap = new Map<String, RFA__Share>();
        Map<String, List<RFAUserRole__c>> approverLevelMap = new Map<String, List<RFAUserRole__c>>();
        List<RFAUserRole__c> cocreators = new List<RFAUserRole__c>();
        List<RFAUserRole__c> reviewers = new List<RFAUserRole__c>();
    	RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
    	
    	RFA__c testRFA;
    	
    	System.runAs(RFATestData.requester)
    	{
    		testRFA = RFATestData.buildTestRFA(testRFA, rt);
    	}
    	
    	User approver1 = new User();
    	approver1 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app1', 'app1', approver1);
    	
    	User approver2 = new User();
    	approver2 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app2', 'app2', approver2);
    	
    	RFAUserRole__c rfaApprover1 = RFATestData.buildApprover(testRFA.Id, approver1, '1. Key Operations');
    	RFAUserRole__c rfaApprover2 = RFATestData.buildApprover(testRFA.Id, approver2, '1. Key Operations');
    	approverLevelMap.put('1. Key Operations', new List<RFAUserRole__c>{rfaApprover1, rfaApprover2});
    	insert approverlevelMap.get('1. Key Operations');
    	
    	ApprovalProcess__c testProcess = new ApprovalProcess__c();
    	
    	Database.UpsertResult result = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
    	
    	System.assert(result.isSuccess());
    	
    	rfaApprover1.ApprovalRecommendation__c = 'Awaiting Approval';
    	rfaApprover1.ApprovalOrder__c = 1;
    	rfaApprover1.ApprovalProcess__c = result.getId();
    	update rfaApprover1;
    	
    	rfaApprover2.ApprovalRecommendation__c = 'Awaiting Approval';
    	rfaApprover2.ApprovalOrder__c = 1;
    	rfaApprover2.ApprovalProcess__c = result.getId();
    	update rfaApprover2;
    	
    	testRFA.Stage__c = 'Circulation';
    	update testRFA;
    	
    	Test.startTest();
    	
    	RFA__Share[] rfaShareRecords = [Select parentId, RowCause, UserOrGroupId, AccessLevel From RFA__Share where parentId =: testRFA.Id];
		System.debug('\n rfa share records :'+rfaShareRecords);
    	for(RFA__Share share : rfaShareRecords)
    	{
    		rfaShareMap.put(share.UserOrGroupId, share);
    	}
    	System.assertEquals('Read', rfaShareMap.get(approver1.Id).AccessLevel);
    	System.assertEquals('Read', rfaShareMap.get(approver2.Id).AccessLevel);
    	
    	rfaApprover1.ApprovalRecommendation__c = 'Unconditionally Approved';
    	update rfaApprover1;
    	
    	//=========================START of Fix for INC0432162 - BSA - 18-Mar-2013 ==========================================
    	rfaApprover1.ApprovalRecommendation__c = 'No Longer Needed';
    	update rfaApprover2;
    	
    	testRFA.Stage__c = 'Post-Circulation';
    	update testRFA;
    	//=========================END of Fix for INC0432162 - BSA - 18-Mar-2013 ==========================================
    	     	
    	RFA__c rfaValidate = [Select Level__c, Stage__c FROM RFA__c where Id = : testRFA.Id];
    	
    	ApprovalProcess__c processValidate = [Select ApprovalProcessLevel__c, Status__c FROM ApprovalProcess__c where RFA__c =: testRFA.Id];
    	
    	System.assertEquals('Post-Circulation', rfaValidate.Stage__c);
    	
      	//System.assertEquals('Completed', processValidate.status__c);
    	
    	
    	//=========================START of Fix for INC0432162 - BSA - 18-Mar-2013 ==========================================
    	//delete rfaApprover2; - commented out BSA
    		try {
            if (rfaApprover2.RFAStage__c!=RFAGlobalConstants.RFA_CIRCULATION_STAGE){
            delete rfaApprover2;
            }
        } catch (DmlException e) {
            //Assert Error Message
            System.assert( e.getMessage().contains('You cannot delete Approver during Circulation Stage'), e.getMessage() );
        }
    	//=========================END of Fix for INC0432162 - BSA - 18-Mar-2013 ==========================================
    	
    	
    	Test.stopTest();
    	
    	
    }
    
    static testMethod void testAddApprover() {
        Map<String, RFA__Share> rfaShareMap = new Map<String, RFA__Share>();
        Map<String, List<RFAUserRole__c>> approverLevelMap = new Map<String, List<RFAUserRole__c>>();
        List<RFAUserRole__c> cocreators = new List<RFAUserRole__c>();
        List<RFAUserRole__c> reviewers = new List<RFAUserRole__c>();
    	RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
    	
    	RFA__c testRFA;
    	
    	System.runAs(RFATestData.requester)
    	{
    		testRFA = RFATestData.buildTestRFA(testRFA, rt);
    	}
    	
    	User approver1 = new User();
    	approver1 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app1', 'app1', approver1);
    	
    	User approver2 = new User();
    	approver2 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app2', 'app2', approver2);
    	
    	RFAUserRole__c rfaApprover1 = RFATestData.buildApprover(testRFA.Id, approver1, '1. Key Operations');
    	//RFAUserRole__c rfaApprover2 = RFATestData.buildApprover(testRFA.Id, approver2, '1. Key Operations');
    	approverLevelMap.put('1. Key Operations', new List<RFAUserRole__c>{rfaApprover1});
    	insert approverlevelMap.get('1. Key Operations');
    	
    	ApprovalProcess__c testProcess = new ApprovalProcess__c();
    	
    	Database.UpsertResult result = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
    	
    	System.assert(result.isSuccess());
    	
    	rfaApprover1.ApprovalRecommendation__c = 'Awaiting Approval';
    	rfaApprover1.ApprovalOrder__c = 1;
    	rfaApprover1.ApprovalProcess__c = result.getId();
    	update rfaApprover1;
    	
    	    	
    	testRFA.Stage__c = 'Circulation';
    	update testRFA;
    	
    	Test.startTest();
    	
    	RFAUserRole__c rfaApprover2 = RFATestData.buildApprover(testRFA.Id, approver2, '1. Key Operations');
    	insert rfaApprover2;
    	
    	Test.stopTest();
    	
    	
    }
    
    static testMethod void testAddApprover2() {
        Map<String, RFA__Share> rfaShareMap = new Map<String, RFA__Share>();
        Map<String, List<RFAUserRole__c>> approverLevelMap = new Map<String, List<RFAUserRole__c>>();
        List<RFAUserRole__c> cocreators = new List<RFAUserRole__c>();
        List<RFAUserRole__c> reviewers = new List<RFAUserRole__c>();
    	RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
    	
    	RFA__c testRFA;
    	
    	System.runAs(RFATestData.requester)
    	{
    		testRFA = RFATestData.buildTestRFA(testRFA, rt);
    	}
    	testRFA.Level__c = '2. Business Unit';
    	update testRFA;
    	
    	User approver1 = new User();
    	approver1 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app1', 'app1', approver1);
    	
    	User approver2 = new User();
    	approver2 = testData.createUser(RFATestData.rfaStandardUserProfile, 'app2', 'app2', approver2);
    	
    	RFAUserRole__c rfaApprover1 = RFATestData.buildApprover(testRFA.Id, approver1, '2. Business Unit');
    	
    	insert rfaApprover1;
    	
    	Test.startTest();
    	
    	ApprovalProcess__c testProcess = new ApprovalProcess__c();
    	
    	Database.UpsertResult result = RFA_AP03_ApprovalProcessHelper.submitForApproval(testProcess, testRFA);
    	
    	System.assert(result.isSuccess());
    	
    	rfaApprover1.ApprovalRecommendation__c = 'Awaiting Approval';
    	
    	rfaApprover1.ApprovalOrder__c = 1;
    	
    	rfaApprover1.ApprovalProcess__c = result.getId();
    	
    	update rfaApprover1;
    	    	    	
    	testRFA.Stage__c = 'Circulation';
    	
    	update testRFA;
    	
    	RFAUserRole__c rfaApprover2 = RFATestData.buildApprover(testRFA.Id, approver2, '1. Key Operations');
    	
    	insert rfaApprover2;
    	
    	Test.stopTest();   	
    	
    }
}