Jann 30/objects/ApprovalProcess__c.object
<CustomObject>
    <fields>
        <fullName>RFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>Approval Processes</relationshipLabel>
        <relationshipName>Approval_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval Process</label>
    <nameField>
        <displayFormat>AP#-{00000}</displayFormat>
        <label>Approval Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreviousLevel__c</fullName>
        <description>Preserves the Stage value when the RFA is put into &quot;Return to Sender&quot;, &quot;Capital Management Hold&quot; or &quot;Pending Board Review&quot; stage</description>
        <label>Previous Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReturnReason__c</fullName>
        <description>Comments to be entered by a Location Coordinator or Capital Management team member when an RFA is placed into Return to Sender Stage.</description>
        <label>Return Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC03_OverrideController.cls
/****************************************************************************************************************************************
****************************************************************************************************************************************    
*  Class            : RFA_VFC03_OverrideController
*  Author           : Accenture
*  Version History  : 1.0
*  Creation         : 05/15/2012
*  Assumptions      : N/A
*  Description      : This class is called from the visualforce page RFA_VFP02_Override and contains logic to


****************************************************************************************************************************************
****************************************************************************************************************************************/

public class RFA_VFC03_OverrideController extends RFA_Util_SecurityMatrix {
    
    /*~~~~Start of Variable Initialization~~~~*/
    public RFA__c rfaObj{get;set;}
    
    public Id profitCenterId{get;set;}
    
    public String selectedStage{get;set;}
    
    public String selectedLevel{get;set;}
    
    private Boolean allowAccess=false;
    
    public boolean hasError{get;private set;}
    
    public String returnReason{get;set;}
    
    private String currentLevel;
    
    private String currentStage;
    
    private String lc; //Added by BSA for INC0346541 - 14-Feb-2013
    
    //added by mpsacua@coca-cola.com Aug 28,2013 for FR1.5 Q3
    public static Map<String, Map<String, RecordType>> RECORDTYPESMAP = RFAGlobalConstants.RECORDTYPESMAP;
    public static Map<String, RecordType> rfaRecordTypeMap = RECORDTYPESMAP.get(Schema.sObjectType.RFA__c.getName());
    public Map<Id, List<ProfitCenterUserRole__c>> profitCenterMap {get;set;}
    //public List<ProfitCenter__c> pcList {get;set;}
    /*~~~~End of Variable Initialization~~~~*/
    
    
    // constructor for the class.
    public RFA_VFC03_OverrideController(ApexPages.StandardController controller) 
    {
        super(controller);
        this.rfaObj=(RFA__c)controller.getRecord();
        List<RFA__c> rfaList = [SELECT Id, Name, Level__c, Stage__c, ProfitCenterNumber__c, ReturnReason__c, RecordTypeId FROM RFA__c WHERE Id =: this.rfaObj.Id LIMIT 1];
        if(rfaList.size() > 0){
            this.rfaObj = rfaList[0];
        }
        this.profitCenterMap = new Map<Id, List<ProfitCenterUserRole__c>>();
        //this.pcList = new List<ProfitCenter__c>();
        if(this.rfaObj.Id <> null)
        {
            this.currentLevel = rfaObj.Level__c;
            
            this.currentStage = rfaObj.Stage__c;
            
        }
    }
    
    public List<SelectOption> getStages()
    {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('--None--','--None--'));
        options.add(new SelectOption(RFAGlobalConstants.PRE_CIRCULATION,RFAGlobalConstants.PRE_CIRCULATION));
        options.add(new SelectOption(RFAGlobalConstants.POST_CIRCULATION,RFAGlobalConstants.POST_CIRCULATION));
        //options.add(new SelectOption(RFAGlobalConstants.RETURN_TO_SENDER,RFAGlobalConstants.RETURN_TO_SENDER));        
        return options;    
    }    
    
    public List<SelectOption> getLevel()
    {
        List<SelectOption> options = new List<SelectOption>();
        Set<String> uniqueLevel = new Set<String>();
        
        //added by mpsacua@coca-cola.com Aug 28,2013 for FR1.33 Level should be taken from Profit Center
        //moved Sept 6, 2013 mpascua@coca-cola.com
        this.profitCenterId = rfaObj.ProfitCenterNumber__c;  
        //this.pcList = [Select Id, name from ProfitCenter__c where Id =: profitCenterId LIMIT 1]; 
        List<ProfitCenterUserRole__c> pcauList = new List<ProfitCenterUserRole__c>();  
        pcauList = [Select id,UserName__c,Level__c,Usertype__c FROM ProfitCenterUserRole__c where UserType__c='Location Coordinator' AND ProfitCenter__c =: this.profitCenterId LIMIT 1000];
        this.profitCenterMap.put(this.profitCenterId, pcauList);            
        //-----------
        
        for(ProfitCenterUserRole__c tempMap: this.profitCenterMap.get(rfaObj.profitCenterNumber__c) )
        {
            if(tempMap.Level__c != null){
                if(uniqueLevel.isEmpty()){
                    uniqueLevel.add(tempMap.Level__c);    
                    options.add(new SelectOption(tempMap.Level__c, tempMap.Level__c));
                }else{
                    
                    if(!(uniqueLevel.contains(tempMap.Level__c))){
                        options.add(new SelectOption(tempMap.Level__c, tempMap.Level__c));
                        uniqueLevel.add(tempMap.Level__c);
                    }  
                }
            }  
        }
        
        options.add(new SelectOption('Return To Sender', 'Return To Sender'));
        options.add(new SelectOption('Capital Management Hold', 'Capital Management Hold'));
        if(rfaObj.RecordTypeId != rfaRecordTypeMap.get(RFAGlobalConstants.RECORDTYPE_POLICY_EXEMPTION_REQUEST).Id){
            options.add(new SelectOption('Pending Board Review', 'Pending Board Review'));
        }
        
        options.sort();        
        return options; 
    }
    
    
    
    public pageReference updateRFA()
    {
        System.savepoint sp = Database.setSavepoint();
        
        //FOR REQ 23.3 This is set to True for validation of the level whether RFA has to skip the level (If no location coordinator is present)
        RFAStaticVariables.doskiplevelProcess=true;
        
        try
        {
            //reset error variable
            hasError = false;
            User usr=[Select Profile.Name, id from User where id=:UserInfo.getUserId() Limit 1]; // User query to fetch profile Name for logged In user to bypass the custom validation
            String UserNameProfile=usr.Profile.Name;
            System.debug('\n Selected level :'+selectedLevel + RFAGlobalConstants.RETURN_TO_SENDER);
            System.debug('\n Selected Stage :'+selectedStage);
            System.debug('\n returned reason from db :'+rfaObj.ReturnReason__c);
            System.debug('\n returned reason from ui :'+returnReason);
            if(!selectedlevel.equalsIgnoreCase(RFAGlobalConstants.RETURN_TO_SENDER)
               && !selectedLevel.equalsIgnoreCase(RFAGlobalConstants.CAPITAL_MGMT_HOLD)
               && !selectedLevel.equalsIgnoreCase(RFAGlobalConstants.PENDING_BOARD_REVIEW)
               && (selectedStage == null || selectedStage.equalsIgnoreCase('--None--')))
            {
                rfaObj.addError('Please select a stage for overriding the RFA');
                hasError = true;
                return null;
            }
            //moved to constructor Sept 6, 2013 mpascua@coca-cola.com
            //this.profitCenterId = rfaObj.ProfitCenterNumber__c; 
            
            //Map<Id, List<ProfitCenterUserRole__c>> profitCenterMap=new Map<Id, List<ProfitCenterUserRole__c>>();
            
            //for(ProfitCenter__c profitCenter: [Select Id, (Select id,UserName__c,Level__c,Usertype__c from Profit_Center_Associated_Users__r where UserType__c='Location Coordinator'),name from ProfitCenter__c where Id =: profitCenterId ])
            //{
            //   profitCenterMap.put(profitCenter.Id, profitCenter.Profit_Center_Associated_Users__r);        
            //}
            //-----------
            
            if((selectedLevel.equalsIgnoreCase(RFAGlobalConstants.PENDING_BOARD_REVIEW) ) && UserNameProfile!=Label.RFA_CL052 && UserNameProfile!=Label.RFA_CL053 && UserNameProfile!=Label.RFA_CL054 && UserNameProfile!=Label.Rfa_CL055)
            {
                rfaObj.addError(Label.RFA_CL102);
                hasError = true;
                return null;
            }
            if(!selectedlevel.equalsIgnoreCase(RFAGlobalConstants.RETURN_TO_SENDER)
               && !selectedLevel.equalsIgnoreCase(RFAGlobalConstants.PENDING_BOARD_REVIEW)&& ((UserNameProfile!=Label.RFA_CL053 &&  UserNameProfile!=Label.RFA_CL052 && UserNameProfile!=Label.RFA_CL054 && UserNameProfile!=Label.RFA_CL055)))// Bypass for System Admin profile
            { 
                validateOperation(this.profitCenterMap);
            }
            if(ApexPages.hasMessages()) 
            {
                hasError = true;
                return null;                                       
            }
            if(currentStage == RFAGlobalConstants.RFA_CIRCULATION_STAGE)
            {
                Map<Id, ApprovalProcess__c> approvalProcessMap = RFA_AP03_ApprovalProcessHelper.getActiveProcessInstances(new Set<String>{rfaObj.Id});
                
                if(!approvalProcessMap.isEmpty()) RFA_AP03_ApprovalProcessHelper.resetApprovalWorkItems(approvalProcessMap);
            }
            
            if(selectedLevel == RFAGlobalConstants.PENDING_BOARD_REVIEW || selectedLevel == RFAGlobalConstants.CAPITAL_MGMT_HOLD || selectedlevel == RFAGlobalConstants.RETURN_TO_SENDER)
            {
                rfaObj.Level__c = selectedLevel;    
                if(selectedlevel == RFAGlobalConstants.RETURN_TO_SENDER)
                {
                    //rfaObj.PreviousLevel__c = currentLevel;
                    rfaObj.ReturnReason__c = returnReason;    
                }
                rfaObj.Stage__c = '';
            }else{
                rfaObj.Stage__c = selectedStage;
                rfaObj.Level__c = selectedLevel;    
            }
            
            update rfaObj;
            
            
            //Database.Saveresult result = Database.update(rfaObj);
            
            
        }catch(Exception ex)
        {
            System.debug('\n Exception caught');
            hasError = true;
            if(!ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'))              
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage())); 
            Database.rollback(sp);
            
            return null;
            
        }
        return null;
        // new PageReference('/'+rfaObj.Id);
    }
    
    
    public void validateOperation(Map<Id, List<ProfitCenterUserRole__c>> pCenterMap)
    {
        
        //<Start> - Added by BSA for INC0346541 - 14-Feb-2013
        lc=null;
        ProfitCenter__c pc= [SELECT Id, Name, (Select id,UserName__c,Level__c,Usertype__c from Profit_Center_Associated_Users__r where UserType__c='Location Coordinator' AND Level__c=: selectedLevel AND UserName__c = :UserInfo.getUserId() Limit 1)
                             FROM ProfitCenter__c
                             WHERE Id=:profitCenterId];
        List<ProfitCenterUserRole__c> locCoordinator  = pc.Profit_Center_Associated_Users__r;
        
        if(locCoordinator.size()>0)
        {
            ProfitCenterUserRole__c lc = locCoordinator.get(0);
        }
        else
        {
            lc='';
        } 
        //<End> - Added by BSA for INC0346541 - 14-Feb-2013
        
        
        for(ProfitCenterUserRole__c tempMap: pCenterMap.get(rfaObj.profitCenterNumber__c) )
        {
            
            
            if(tempMap.UserName__C==UserInfo.getUserId())// UserInfo.getProfileId()!='00ed00000012gBs'  )
            {
                allowAccess=True;             
            }
            
            if(tempMap.UserName__C==UserInfo.getUserId() && tempMap.UserType__c!='Location Coordinator')// UserInfo.getProfileId()!='00ed00000012gBs'  )
            {
                hasError = true; 
                rfaObj.addError(Label.RFA_CL100);
                
            }   
            
            else if(tempMap.UserName__C==UserInfo.getUserId() && selectedLevel=='6. Senior Executive' && (tempMap.Level__c=='1. Key Operations' || tempMap.Level__c=='2. Business Unit' || tempMap.Level__c=='3. Group' || rfaObj.Level__c=='4. Corporate' || rfaObj.Level__c=='5. Executive' ) )// UserInfo.getProfileId()!='00ed00000012gBs'  )
            {
                if(lc <>'') //<Start> - Added this if condition by BSA for INC0346541 - 14-Feb-2013
                {
                    //continue allow override..
                } 
                else
                {
                    hasError = true;
                    rfaObj.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                }
            }  
            else if(tempMap.UserName__C==UserInfo.getUserId() && selectedLevel=='5. Executive' && (tempMap.Level__c=='1. Key Operations' || tempMap.Level__c=='2. Business Unit' || tempMap.Level__c=='3. Group' || tempMap.Level__c=='4. Corporate' ) )// UserInfo.getProfileId()!='00ed00000012gBs'  )
            {
                if(lc <>'') //<Start> - Added this if condition by BSA for INC0346541 - 14-Feb-2013
                {
                    //continue allow override..
                } 
                else
                {
                    hasError = true;
                    rfaObj.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                }
                
            } 
            
            else if(tempMap.UserName__C==UserInfo.getUserId() && selectedLevel=='4. Corporate' && ( tempMap.Level__c=='1. Key Operations' || tempMap.Level__c=='2. Business Unit' || tempMap.Level__c=='3. Group'))
            {
                
                if(lc <>'') //<Start> - Added this if condition by BSA for INC0346541 - 14-Feb-2013
                {
                    //continue allow override..
                } 
                else
                {
                    hasError = true;
                    rfaObj.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                }
                
            } 
            else if(tempMap.UserName__C==UserInfo.getUserId() && selectedLevel=='3. Group' && ( tempMap.Level__c=='1. Key Operations' || tempMap.Level__c=='2. Business Unit' ))
            {
                if(lc <>'') //<Start> - Added this if condition by BSA for INC0346541 - 14-Feb-2013
                {
                    //continue allow override..
                } 
                else
                {
                    hasError = true;
                    rfaObj.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                }
                
            } 
            else if(tempMap.UserName__C==UserInfo.getUserId() && selectedLevel=='2. Business Unit' && (   tempMap.Level__c=='1. Key Operations') )// UserInfo.getProfileId()!='00ed00000012gBs'  )
            {
                if(lc <>'') //<Start> - Added this if condition by BSA for INC0346541 - 14-Feb-2013
                {
                    //continue allow override..
                } 
                else
                {
                    hasError = true;
                    rfaObj.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                }
                
            }
        }
        
        if(allowAccess==false)rfaObj.addError(RFAGlobalConstants.EXCEPTION_NOT_PART_OF_PC);
        
    }
    
    
    
}