Jann 30/objects/Approver_Group__c.object
<CustomObject>
    <description>Approver Groups</description>
    <fields>
        <fullName>Approver_GroupName__c</fullName>
        <formula>TEXT(Level__c)   &amp;  &apos; &apos; &amp;   Approver_Role__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approver Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>Level</description>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>KEYOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. EXEC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA Approver Group</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Approver Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approver Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFA_DOA__c.object
<CustomObject>
    <description>This store the DOA category, Amount Ranges, Approver levels and Approver Groups.</description>
    <fields>
        <fullName>Amount_Lower_limit__c</fullName>
        <label>Amount (Lower limit)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_Upper_limit__c</fullName>
        <label>Amount (Upper limit)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approver_Group__c</fullName>
        <label>Approver Group</label>
        <picklist>
            <picklistValues>
                <fullName>ABC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Level__c</fullName>
        <description>Approver Level</description>
        <label>Approver Level</label>
        <picklist>
            <picklistValues>
                <fullName>KEYOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CORP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr. EXEC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver_Type__c</fullName>
        <label>Approver Type</label>
        <picklist>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comments</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DOA_Control_Level__c</fullName>
        <description>This field will determine which coordinator level can control the levels</description>
        <label>DOA Control Level</label>
        <picklist>
            <picklistValues>
                <fullName>KEYOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CORP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_DOA_Category__c</fullName>
        <description>RFA Primary DOA Categorys</description>
        <label>Primary DOA Category</label>
        <picklist>
            <picklistValues>
                <fullName>1.A.1 Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.a Capital Expenditures - Unbudgeted CPR or SPR Covered by Budget Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.b Capital Expenditures - Unbudgeted CPR or SPR Funded Partially or Fully from Corporate Reserve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.3 Capital Expenditures - Increase or Scope Change to Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.4 Capital Expenditures - Transfer of Capital Budget across Groups for a Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.5 Capital Expenditures - Foreign Exchange Fluctuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.8 Capital Expenditures - Advance Appropriations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.B Capital Expenditures - Capability and Performance Programs (CAPPrs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.C Capital Expenditures - Bottles and Cases, Including Overages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. IT Investments and Website Presence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.A Real Property - Acquisitions and Sales or Other Disposals of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.B Real Property - Donations of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.C Real Property - Condemnations or Easements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.A Leases - Operating Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.B Leases - Capital Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.A Inventory Adjustments and Disposals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.B Other Asset Impairments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.C Asset Transfers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.D Asset Disposals (Tangible Assets excluding Real Property and Inventory)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.A Treasury - Banking Information Reports (BIR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.B Treasury - External Borrowings and Lines of Credit (RFFs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.C Treasury - Intercompany Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.D Treasury - Loans Third Parties (Including CCFC Target Loan Programs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.1 Treasury - Guarantees to Third Parties - General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.2 Treasury - Guarantees Related to Tax Disputes or Other Matters Involving Governmental Bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.F Treasury - Comfort Letters and Other Financial Security Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.G Treasury - Accommodation Purchases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.H Treasury - Credit Terms/Policies or Incentives for Sales to Customers, Bottlers or Distributors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.1 Treasury - Exemption from Bad Debt Reserve Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.2 Treasury - Write-offs of Uncollectible Accounts Receivable from Bad Debt Reserve</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA DOA</label>
    <nameField>
        <displayFormat>DOA-{0000}</displayFormat>
        <label>DOA  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA DOAs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_DOAController.cls
public  with sharing class RFA_VFC_DOAController {
    Public RFA_DOA__c DOAObj{set;get;}
    Public List<selectOption> DOACategory{set;get;}
    Public String selectedDOACategory{set;get;}   
    Public List<selectOption> DOAControlLevel{set;get;}
    Public String selectedDOAControlLevel{set;get;} 
    Public Decimal  AmountUpperLimit{set;get;}
    Public Decimal  AmountLowerLimit{set;get;}
    Public String Comments{set;get;}
    Public List<selectOption> ControlLevel{set;get;}
    Public String selectedControlLevel{set;get;}
    
    Public List<selectOption> ApproverLevel{set;get;}
    Public String selectedApproverLevel{set;get;}
    Public List<selectOption> Approvergroup{set;get;}
    Public String selectedApprovergroup{set;get;}
    Public List<selectOption>approverType{set;get;}
    Public String selectedapproverType{set;get;}
    Public Boolean IsEditMode{set;get;}
    
    Public Boolean Grpapprover{set;get;}
    Public Boolean AppLevel{set;get;}
    Public RFA_VFC_DOAController(ApexPages.StandardController DOActrl)
    {
        Grpapprover=false;
        AppLevel = false;
        System.debug('Hello World');
        System.debug('Param value is::'+ApexPages.currentPage().getParameters().get('Id'));
        string url = ApexPages.currentPage().getURL();
        if(ApexPages.currentPage().getParameters().get('Id')!=null&& !url.contains('retURL'))       
        {  
            System.debug('You opened in detail mode');
            IsEditMode=false;
           
        }
        else
        {
            System.debug('You opened in EDIT mode');
            IsEditMode=true;
        } 
         Id DOARec = ApexPages.currentPage().getParameters().get('Id');
        if(DOARec!=null)
        {
            
        DOAObj = (RFA_DOA__c)DOActrl.getRecord();  
        DOAObj = [Select Primary_DOA_Category__c ,DOA_Control_Level__c,Approver_Level__c,Amount_Upper_limit__c,Amount_Lower_limit__c,Comments__c,Approver_Group__c,Approver_Type__c,CreatedById,CreatedDate,LastModifiedById,LastModifiedDate from RFA_DOA__c  where id=:DOARec];
            
            selectedDOACategory = DOAObj.Primary_DOA_Category__c;            
            selectedDOAControlLevel = DOAObj.DOA_Control_Level__c;
            AmountUpperLimit = DOAObj.Amount_Upper_limit__c;
                AmountLowerLimit = DOAObj.Amount_Lower_limit__c;
                Comments = DOAObj.Comments__c;
                selectedApproverLevel = DOAObj.Approver_Level__c;
                selectedApprovergroup = DOAObj.Approver_Group__c;
                selectedapproverType = DOAObj.Approver_Type__c;
        }      
        //Populating DOA Category values
        Schema.DescribeFieldResult DOACategories = RFA_DOA__c.Primary_DOA_Category__c.getDescribe();
        DOACategory = new list<SelectOption>();
        DOACategory.add(new SelectOption('--Select--','--Select--'));
        for (Schema.PicklistEntry picklistEntry : DOACategories.getPicklistValues())
        {
                DOACategory.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
        } 
         
        //Populating DOA_Control_Level__c values
        /*Schema.DescribeFieldResult DOAControlLevels = RFA_DOA__c.DOA_Control_Level__c.getDescribe();
        DOAControlLevel = new list<SelectOption>();
        DOAControlLevel.add(new SelectOption('--Select--','--Select--'));
        for (Schema.PicklistEntry DOAControlLevelpicklist : DOAControlLevels.getPicklistValues())
        {
                DOAControlLevel.add(new SelectOption(DOAControlLevelpicklist.getValue(),DOAControlLevelpicklist.getLabel()));
        } */
        DOAControlLevel = RFA_VFC_CoordinatorLevelHelper.getAvailableControlLevels();
        System.debug('Levels that can be accessed '+DOAControlLevel);
         
        //Populating Approver Level values
         ApproverLevel= new List<SelectOption>();
        if(selectedApproverLevel!=null)
        {
         	ApproverLevel.add(new SelectOption('--Select--','--Select--'));
         	ApproverLevel.add(new SelectOption(selectedApproverLevel,selectedApproverLevel));
        }
         
         //Populating Approver Group values
         Approvergroup= new List<SelectOption>();
        if(selectedApprovergroup!=null)
        {
            Approvergroup.add(new SelectOption('--Select--','--Select--'));
         	Approvergroup.add(new SelectOption(selectedApprovergroup,selectedApprovergroup));
        }
         
            
        //Populating Approver Type values
        Schema.DescribeFieldResult ApproverTypes = RFA_DOA__c.Approver_Type__c.getDescribe();
        approverType = new list<SelectOption>();
        approverType.add(new SelectOption('--Select--','--Select--'));
        for (Schema.PicklistEntry ApproverTypepicklist : ApproverTypes.getPicklistValues())
        {
                approverType.add(new SelectOption(ApproverTypepicklist.getValue(),ApproverTypepicklist.getLabel()));
        }  
    } 
    // This poupulates the Approver levels based on the selected control level
    public void getApproverLevels()
    {
        AppLevel= true;
        Map<String,List<String>> availableLevels = new Map<String,List<String>>();
        availableLevels.put('KEYOP', new  List <String> {'KEYOP'});
        availableLevels.put('BU', new  List <String> {'KEYOP','BU'});
        availableLevels.put('GROUP', new  List <String> {'KEYOP','BU','GROUP'});
        availableLevels.put('CORP', new  List <String> {'KEYOP','BU','GROUP','CORP','EXEC','Sr. EXEC'}); 
        System.debug('Map is: '+availableLevels);
        System.debug('selectedDOAControlLevel is'+selectedDOAControlLevel);
        System.debug('Levels set'+availableLevels.get(selectedDOAControlLevel));
        List<String> levels=availableLevels.get(selectedDOAControlLevel);
        ApproverLevel = new List<SelectOption>();
        ApproverLevel.add(new SelectOption('--Select--','--Select--'));
        for(String eachLevel: levels )
        {
            ApproverLevel.add(new SelectOption(eachLevel,eachLevel));
        }
    }
    //This fetches the Approver groups based on the selected "Level"
    public Void getApprovergroup()
    {
        System.debug('Hello..1');
        Grpapprover=true;
            
        Approvergroup =  new list<SelectOption>();
        List<Approver_Group__c> Groups=[select id,Approver_GroupName__c from Approver_Group__c where Level__c='Group'];
        for(Approver_Group__c eachGrp:Groups)
        {
            Approvergroup.add(new SelectOption(eachGrp.Approver_GroupName__c,eachGrp.Approver_GroupName__c));
        } 
        System.debug('Value of Approvergroup'+Approvergroup);
      //  return Approvergroup;
    }
    Public PageReference EditDOA()
    {
        System.debug('You clicked EDIT');
        IsEditMode=true;
        return null;
    }
    Public PageReference DeleteDOA()
    {
        IsEditMode=false;
        delete DOAObj;
        return new PageReference('/a1n/o');
    }
    
    Public PageReference SaveDOA()
    {
        try{
        if(selectedApprovergroup=='--Select--' && Approvergroup.size()>1)
        {
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please Select Approver Group'));
        }  
        else
        {
        DOAObj.Primary_DOA_Category__c=selectedDOACategory;
        DOAObj.DOA_Control_Level__c=selectedDOAControlLevel;
        DOAObj.Amount_Upper_limit__c=AmountUpperLimit;
        DOAObj.Amount_Lower_limit__c=AmountLowerLimit;
        DOAObj.Comments__c=Comments;
        DOAObj.Approver_Level__c=selectedApproverLevel;
        if(selectedApprovergroup=='--Select--')
        {
            selectedApprovergroup=null;
        }         
       DOAObj.Approver_Group__c=selectedApprovergroup;
        DOAObj.Approver_Type__c=selectedapproverType;
        System.debug('Primary_DOA_Category__c'+selectedDOACategory);
        system.debug('DOA_Control_Level__c'+selectedDOAControlLevel);
        system.debug('AmountUpperLimit'+AmountUpperLimit);
        system.debug('AmountLowerLimit'+AmountLowerLimit);
        system.debug('Comments'+Comments);
        system.debug('selectedApproverLevel'+selectedApproverLevel);
        system.debug('selectedApprovergroup'+selectedApprovergroup);
        system.debug('selectedapproverType'+selectedapproverType);
        
        upsert DOAObj;
        DOAObj  = [select CreatedById,CreatedDate,LastModifiedById,LastModifiedDate from RFA_DOA__c where id=:DOAObj.id];
        IsEditMode=false;
    	}
        }
        catch(System.DmlException  e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getDMLMessage(0)));        
        }
        return null;
    }
    Public PageReference CancelDOA()
    {
        IsEditMode=false;
        
        return null;
    }
    
    Public void getApproverGroups()
    {
        System.debug('Hello Value --->');
        Grpapprover=true;
       Approvergroup =  new list<SelectOption>();
        List<Approver_Group__c> Groups=[select id,Approver_GroupName__c from Approver_Group__c where Level__c=:selectedApproverLevel];
        System.debug('selectedApproverLevel is '+selectedApproverLevel);
        System.debug('Groups'+Groups);
        Approvergroup.add(new SelectOption('--Select--','--Select--'));
        for(Approver_Group__c eachGrp:Groups)
        {
            Approvergroup.add(new SelectOption(eachGrp.Approver_GroupName__c,eachGrp.Approver_GroupName__c));
        }
        System.debug('Value of Approvergroup'+Approvergroup); 
    }
    
    
}