Jann 30/objects/Assignment_Routing_Rules__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Assets &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application and SaaS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/Preferred Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Supplier Vendor Governance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Routing_Rules2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>GIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Routing_Rules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change In Existing Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Of Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Access Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Legal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_Governance_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Governance User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Routing_Rules4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IT-SES Assignment Routing Rules</label>
    <nameField>
        <displayFormat>ASR-{0000}</displayFormat>
        <label>Assignment Routing Rules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES Assignment Routing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Category is the IT Procurement category for which you are requesting assistance.  Please see the attached PDF entitled “IT-SES Categories” for a depiction of the categories.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Assets &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application and SaaS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/Preferred Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Supplier Vendor Governance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Finance_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_this_NDA_to_be_mutual_or_will_the_com__c</fullName>
        <inlineHelpText>Indicate whether this project is for the Freestyle program.</inlineHelpText>
        <label>Is This a Freestyle Project?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7m</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <inlineHelpText>This is the TCCC company which has budget responsibility for the request.  This field drives both initial assignment and Chart of Authority during the approval process.</inlineHelpText>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>GIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Use this field to identify the type of assistance you are requesting.  Please see the attached PDF entitled “Request Type” for a definition of the different request types.</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change In Existing Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Of Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Access Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Legal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State_Or_Country_Of_Formation__c</fullName>
        <inlineHelpText>Please enter the state or country in which the supplier&apos;s firm was formed as a corporation, LLC, etc.</inlineHelpText>
        <label>State Or Country Of Formation</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_By_Phone_Number__c</fullName>
        <label>Submitted By Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Email__c</fullName>
        <inlineHelpText>Enter the email address for the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Name__c</fullName>
        <inlineHelpText>Enter the name of the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Phone_Number__c</fullName>
        <inlineHelpText>Enter the telephone number for the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter the name of the company which the contract will be with. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IT-SES</relationshipLabel>
        <relationshipName>ITPR1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Physical_Address__c</fullName>
        <inlineHelpText>Please enter the full physical address, including street, city, state, zip code and country if not in the US.</inlineHelpText>
        <label>Supplier Physical Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Supplier_s_Legal_Entity_Name__c</fullName>
        <inlineHelpText>Provide the legal entity name including type (e.g. Inc., LLC, Corp)</inlineHelpText>
        <label>Supplier&apos;s Legal Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_Of_Information__c</fullName>
        <inlineHelpText>Please indicate the type of information which will be disclosed (i.e. supply chain, financials, information processes, heating systems, software, employee statistics, etc.)</inlineHelpText>
        <label>Type Of Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Who_Will_Be_Disclosing_Information__c</fullName>
        <inlineHelpText>Indicate who will be disclosing confidential information.  This determines which NDA form to prepare.</inlineHelpText>
        <label>Who Will Be Disclosing Information?</label>
        <picklist>
            <picklistValues>
                <fullName>Supplier Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCCC Entity Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/ITSES_Wave1Approver2AsLegalAssigneeTest.cls
@isTest
public class ITSES_Wave1Approver2AsLegalAssigneeTest {

  static testMethod void w1a1f1() {
    ITPR__c itpr = new ITPR__c();         

    Account testAccount = new Account( Name = 'Capgemini');
    insert testAccount;

    Profile p = [SELECT Id FROM Profile WHERE Name='ITSES - Legal Business Administrator'];

    System.debug('ITSES' +p);    

    User ProcurementAssignee = new User(Alias = 'user', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserr@testorg.com',ITPR_Department__c='ITSES - Procurement');
    insert ProcurementAssignee;

    User LegalAssignee = new User(Alias = 'user1', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserlegal@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert LegalAssignee;

    /* User FinanceAssignee = new User(Alias = 'user2', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserfinance@testorg.com',ITPR_Department__c='ITSES - Finance');
    insert FinanceAssignee; */

    User VendorGoverAssignee = new User(Alias = 'user3', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserVGA@testorg.com',ITPR_Department__c='ITSES - Vendor Governance');
    insert VendorGoverAssignee;

    User Wave2App1 = new User(Alias = 'user4', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW2AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave2App1;        

    User Wave3App1 = new User(Alias = 'user5', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW3AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave3App1;

    User Wave1App1 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App1;

    User Wave1App2 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP2@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App2;


    User Wave1App3 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP3@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App3;

    Assignment_Routing_Rules__c ar = new Assignment_Routing_Rules__c();
    ar.Organization__c = 'GIT';
    ar.Request_Type__c = 'NDA';
    ar.Category__c = 'Telecom';
    ar.Legal_Assignee__c = LegalAssignee.id;
    ar.Procurement_Assignee__c = ProcurementAssignee.id;
    ar.Vendor_Governance_User__c = VendorGoverAssignee.id;

    insert ar;

    itpr.Organization__c = 'GIT';
    itpr.Request_Type__c = 'NDA';
    itpr.Category__c = 'Telecom';
    itpr.Submitted_By_Phone_Number__c = '12345';
    itpr.Supplier_Name__c = testAccount.Id;
    itpr.Supplier_Contact_Name__c = 'test';
    itpr.Supplier_Contact_Email__c = 'test@test.com';
    itpr.Supplier_Contact_Phone_Number__c = '12345';
    itpr.Finance_Assignee__c = null;

    //NDA Fields
    itpr.Who_Will_Be_Disclosing_Information__c = 'Both';
    itpr.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';
    itpr.Supplier_s_Legal_Entity_Name__c = 'test';
    itpr.Supplier_Physical_Address__c = 'test';
    itpr.Type_Of_Information__c = 'test';
    itpr.State_Or_Country_Of_Formation__c = 'test';
    itpr.Addressee_Name__c = 'test';
    itpr.Duration_Of_NDA__c = 2;



    //Assignee Details
    //itpr.Procurement_Assignee__c = ProcurementAssignee.Id;
    //itpr.Legal_Assignee__c = LegalAssignee.Id;
    //itpr.Finance_Assignee__c = FinanceAssignee.Id;
    //itpr.Vendor_Governance__c = VendorGoverAssignee.Id;

    //itpr.Wave1_Approver_1__c = Wave1App1.Id;
    //itpr.Wave1_Approver_1__c = LegalAssignee.Id;
    itpr.Wave1_Approver_1__c = ar.Legal_Assignee__c;
    //itpr.Wave1_Approver_2__c = Wave1App2.Id;
    //itpr.Wave1_Approver_3__c = Wave1App3.Id;

    itpr.Wave2_Approver_1__c = Wave2App1.Id;
    // itpr.Wave2_Approver_1__c = Approver3.Id;
    itpr.Wave3_Approver_1__c = Wave3App1.Id;
    //itpr.Legal_Assignee__c = u.Id; */

    insert itpr ;
    ITPR__c itpr1 = [SELECT ID, Wave1_Approver_1__c FROM ITPR__c WHERE Id =: itpr.id];
    system.assertEquals(ar.Legal_Assignee__c, itpr1.Wave1_Approver_1__c);
  }


  static testMethod void w2n() {
    ITPR__c itpr = new ITPR__c();         

    Account testAccount = new Account( Name = 'Capgemini');
    insert testAccount;

    Profile p = [SELECT Id FROM Profile WHERE Name='ITSES - Legal Business Administrator'];

    System.debug('ITSES' +p);    

    User ProcurementAssignee = new User(Alias = 'user', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserr@testorg.com',ITPR_Department__c='ITSES - Procurement');
    insert ProcurementAssignee;

    User LegalAssignee = new User(Alias = 'user1', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserlegal@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert LegalAssignee;

    User FinanceAssignee = new User(Alias = 'user2', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserfinance@testorg.com',ITPR_Department__c='ITSES - Finance');
    insert FinanceAssignee;

    User VendorGoverAssignee = new User(Alias = 'user3', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserVGA@testorg.com',ITPR_Department__c='ITSES - Vendor Governance');
    insert VendorGoverAssignee;

    User Wave2App1 = new User(Alias = 'user4', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW2AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave2App1;        

    User Wave3App1 = new User(Alias = 'user5', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW3AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave3App1;

    User Wave1App1 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App1; 

    Assignment_Routing_Rules__c ar = new Assignment_Routing_Rules__c();
    ar.Organization__c = 'GIT';
    ar.Request_Type__c = 'NDA';
    ar.Category__c = 'Telecom';
    ar.Legal_Assignee__c = LegalAssignee.id;
    ar.Procurement_Assignee__c = ProcurementAssignee.id;
    ar.Vendor_Governance_User__c = VendorGoverAssignee.id;
    insert ar;

    itpr.Organization__c = 'GIT';
    itpr.Request_Type__c = 'NDA';
    itpr.Category__c = 'Telecom';
    itpr.Submitted_By_Phone_Number__c = '12345';
    itpr.Supplier_Name__c = testAccount.Id;
    itpr.Supplier_Contact_Name__c = 'test';
    itpr.Supplier_Contact_Email__c = 'test@test.com';
    itpr.Supplier_Contact_Phone_Number__c = '12345';

    //NDA Fields
    itpr.Who_Will_Be_Disclosing_Information__c = 'Both';
    itpr.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';
    itpr.Supplier_s_Legal_Entity_Name__c = 'test';
    itpr.Supplier_Physical_Address__c = 'test';
    itpr.Type_Of_Information__c = 'test';
    itpr.State_Or_Country_Of_Formation__c = 'test';
    itpr.Addressee_Name__c = 'test';
    itpr.Duration_Of_NDA__c = 2;



    //Assignee Details
    //itpr.Procurement_Assignee__c = ProcurementAssignee.Id;
    //itpr.Legal_Assignee__c = LegalAssignee.Id;
    itpr.Finance_Assignee__c = FinanceAssignee.Id;
    //itpr.Vendor_Governance__c = VendorGoverAssignee.Id;

    itpr.Wave1_Approver_1__c = Wave1App1.Id;
    //itpr.Wave1_Approver_2__c = LegalAssignee.Id;
    itpr.Wave2_Approver_1__c = Wave2App1.Id;
    // itpr.Wave2_Approver_1__c = Approver3.Id;
    itpr.Wave3_Approver_1__c = Wave3App1.Id;
    //itpr.Legal_Assignee__c = u.Id; */

    insert itpr ;
    ITPR__c itpr1 = [SELECT ID, Wave1_Approver_2__c FROM ITPR__c WHERE Id =: itpr.id];
    system.assertEquals(LegalAssignee.Id, itpr1.Wave1_Approver_2__c);
  }

  static testMethod void w3n() {
    ITPR__c itpr = new ITPR__c();         

    Account testAccount = new Account( Name = 'Capgemini');
    insert testAccount;

    Profile p = [SELECT Id FROM Profile WHERE Name='ITSES - Legal Business Administrator'];

    System.debug('ITSES' +p);    

    User ProcurementAssignee = new User(Alias = 'user', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserr@testorg.com',ITPR_Department__c='ITSES - Procurement');
    insert ProcurementAssignee;

    User LegalAssignee = new User(Alias = 'user1', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserlegal@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert LegalAssignee;

    User FinanceAssignee = new User(Alias = 'user2', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserfinance@testorg.com',ITPR_Department__c='ITSES - Finance');
    insert FinanceAssignee;

    User VendorGoverAssignee = new User(Alias = 'user3', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserVGA@testorg.com',ITPR_Department__c='ITSES - Vendor Governance');
    insert VendorGoverAssignee;

    User Wave2App1 = new User(Alias = 'user4', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW2AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave2App1;        

    User Wave3App1 = new User(Alias = 'user5', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW3AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave3App1;

    User Wave1App1 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App1;
    User Wave1App2 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP2@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App2;

    Assignment_Routing_Rules__c ar = new Assignment_Routing_Rules__c();
    ar.Organization__c = 'GIT';
    ar.Request_Type__c = 'NDA';
    ar.Category__c = 'Telecom';
    ar.Legal_Assignee__c = LegalAssignee.id;
    ar.Procurement_Assignee__c = ProcurementAssignee.id;
    ar.Vendor_Governance_User__c = VendorGoverAssignee.id;
    insert ar;

    itpr.Organization__c = 'GIT';
    itpr.Request_Type__c = 'NDA';
    itpr.Category__c = 'Telecom';
    itpr.Submitted_By_Phone_Number__c = '12345';
    itpr.Supplier_Name__c = testAccount.Id;
    itpr.Supplier_Contact_Name__c = 'test';
    itpr.Supplier_Contact_Email__c = 'test@test.com';
    itpr.Supplier_Contact_Phone_Number__c = '12345';

    //NDA Fields
    itpr.Who_Will_Be_Disclosing_Information__c = 'Both';
    itpr.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';
    itpr.Supplier_s_Legal_Entity_Name__c = 'test';
    itpr.Supplier_Physical_Address__c = 'test';
    itpr.Type_Of_Information__c = 'test';
    itpr.State_Or_Country_Of_Formation__c = 'test';
    itpr.Addressee_Name__c = 'test';
    itpr.Duration_Of_NDA__c = 2;



    //Assignee Details
    //itpr.Procurement_Assignee__c = ProcurementAssignee.Id;
    //itpr.Legal_Assignee__c = LegalAssignee.Id;
    itpr.Finance_Assignee__c = FinanceAssignee.Id;
    //itpr.Vendor_Governance__c = VendorGoverAssignee.Id;

    itpr.Wave1_Approver_1__c = Wave1App1.Id;
    itpr.Wave1_Approver_2__c = Wave1App2.Id;
    itpr.Wave2_Approver_1__c = Wave2App1.Id;
    // itpr.Wave2_Approver_1__c = Approver3.Id;
    itpr.Wave3_Approver_1__c = Wave3App1.Id;
    //itpr.Legal_Assignee__c = u.Id; */

    insert itpr ;
    ITPR__c itpr1 = [SELECT ID, Wave1_Approver_3__c FROM ITPR__c WHERE Id =: itpr.id];
    system.assertEquals(LegalAssignee.Id, itpr1.Wave1_Approver_3__c);
  }

  static testMethod void w4n() {
    ITPR__c itpr = new ITPR__c();         

    Account testAccount = new Account( Name = 'Capgemini');
    insert testAccount;

    Profile p = [SELECT Id FROM Profile WHERE Name='ITSES - Legal Business Administrator'];

    System.debug('ITSES' +p);    

    User ProcurementAssignee = new User(Alias = 'user', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserr@testorg.com',ITPR_Department__c='ITSES - Procurement');
    insert ProcurementAssignee;

    User LegalAssignee = new User(Alias = 'user1', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserlegal@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert LegalAssignee;

    User FinanceAssignee = new User(Alias = 'user2', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserfinance@testorg.com',ITPR_Department__c='ITSES - Finance');
    insert FinanceAssignee;

    User VendorGoverAssignee = new User(Alias = 'user3', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserVGA@testorg.com',ITPR_Department__c='ITSES - Vendor Governance');
    insert VendorGoverAssignee;

    User Wave2App1 = new User(Alias = 'user4', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW2AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave2App1;        

    User Wave3App1 = new User(Alias = 'user5', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW3AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave3App1;

    User Wave1App1 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App1;
    User Wave1App2 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP2@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App2;

    User Wave1App3 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP3@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App3;

    Assignment_Routing_Rules__c ar = new Assignment_Routing_Rules__c();
    ar.Organization__c = 'GIT';
    ar.Request_Type__c = 'NDA';
    ar.Category__c = 'Telecom';
    ar.Legal_Assignee__c = LegalAssignee.id;
    ar.Procurement_Assignee__c = ProcurementAssignee.id;
    ar.Vendor_Governance_User__c = VendorGoverAssignee.id;
    insert ar;

    itpr.Organization__c = 'GIT';
    itpr.Request_Type__c = 'NDA';
    itpr.Category__c = 'Telecom';
    itpr.Submitted_By_Phone_Number__c = '12345';
    itpr.Supplier_Name__c = testAccount.Id;
    itpr.Supplier_Contact_Name__c = 'test';
    itpr.Supplier_Contact_Email__c = 'test@test.com';
    itpr.Supplier_Contact_Phone_Number__c = '12345';

    //NDA Fields
    itpr.Who_Will_Be_Disclosing_Information__c = 'Both';
    itpr.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';
    itpr.Supplier_s_Legal_Entity_Name__c = 'test';
    itpr.Supplier_Physical_Address__c = 'test';
    itpr.Type_Of_Information__c = 'test';
    itpr.State_Or_Country_Of_Formation__c = 'test';
    itpr.Addressee_Name__c = 'test';
    itpr.Duration_Of_NDA__c = 2;



    //Assignee Details
    //itpr.Procurement_Assignee__c = ProcurementAssignee.Id;
    //itpr.Legal_Assignee__c = LegalAssignee.Id;
    itpr.Finance_Assignee__c = FinanceAssignee.Id;
    //itpr.Vendor_Governance__c = VendorGoverAssignee.Id;

    itpr.Wave1_Approver_1__c = Wave1App1.Id;
    itpr.Wave1_Approver_2__c = Wave1App2.Id;
    itpr.Wave1_Approver_3__c = Wave1App3.Id;

    itpr.Wave2_Approver_1__c = Wave2App1.Id;
    // itpr.Wave2_Approver_1__c = Approver3.Id;
    itpr.Wave3_Approver_1__c = Wave3App1.Id;
    //itpr.Legal_Assignee__c = u.Id; */

    insert itpr ;
    ITPR__c itpr1 = [SELECT ID, Wave1_Approver_4__c FROM ITPR__c WHERE Id =: itpr.id];
    system.assertEquals(LegalAssignee.Id, itpr1.Wave1_Approver_4__c);
  }

  static testMethod void w5n() {
    ITPR__c itpr = new ITPR__c();         

    Account testAccount = new Account( Name = 'Capgemini');
    insert testAccount;

    Profile p = [SELECT Id FROM Profile WHERE Name='ITSES - Legal Business Administrator'];

    System.debug('ITSES' +p);    

    User ProcurementAssignee = new User(Alias = 'user', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserr@testorg.com',ITPR_Department__c='ITSES - Procurement');
    insert ProcurementAssignee;

    User LegalAssignee = new User(Alias = 'user1', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserlegal@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert LegalAssignee;

    User FinanceAssignee = new User(Alias = 'user2', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserfinance@testorg.com',ITPR_Department__c='ITSES - Finance');
    insert FinanceAssignee;

    User VendorGoverAssignee = new User(Alias = 'user3', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserVGA@testorg.com',ITPR_Department__c='ITSES - Vendor Governance');
    insert VendorGoverAssignee;

    User Wave2App1 = new User(Alias = 'user4', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW2AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave2App1;        

    User Wave3App1 = new User(Alias = 'user5', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW3AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave3App1;

    User Wave1App1 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP1@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App1;
    User Wave1App2 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP2@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App2;

    User Wave1App3 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP3@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App3;

    User Wave1App4 = new User(Alias = 'user6', Email='standarduserr@testorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduserW1AP4@testorg.com',ITPR_Department__c='ITSES - Legal');
    insert Wave1App4;

    Assignment_Routing_Rules__c ar = new Assignment_Routing_Rules__c();
    ar.Organization__c = 'GIT';
    ar.Request_Type__c = 'NDA';
    ar.Category__c = 'Telecom';
    ar.Legal_Assignee__c = LegalAssignee.id;
    ar.Procurement_Assignee__c = ProcurementAssignee.id;
    ar.Vendor_Governance_User__c = VendorGoverAssignee.id;
    insert ar;

    itpr.Organization__c = 'GIT';
    itpr.Request_Type__c = 'NDA';
    itpr.Category__c = 'Telecom';
    itpr.Submitted_By_Phone_Number__c = '12345';
    itpr.Supplier_Name__c = testAccount.Id;
    itpr.Supplier_Contact_Name__c = 'test';
    itpr.Supplier_Contact_Email__c = 'test@test.com';
    itpr.Supplier_Contact_Phone_Number__c = '12345';

    //NDA Fields
    itpr.Who_Will_Be_Disclosing_Information__c = 'Both';
    itpr.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';
    itpr.Supplier_s_Legal_Entity_Name__c = 'test';
    itpr.Supplier_Physical_Address__c = 'test';
    itpr.Type_Of_Information__c = 'test';
    itpr.State_Or_Country_Of_Formation__c = 'test';
    itpr.Addressee_Name__c = 'test';
    itpr.Duration_Of_NDA__c = 2;



    //Assignee Details
    //itpr.Procurement_Assignee__c = ProcurementAssignee.Id;
    //itpr.Legal_Assignee__c = LegalAssignee.Id;
    itpr.Finance_Assignee__c = FinanceAssignee.Id;
    //itpr.Vendor_Governance__c = VendorGoverAssignee.Id;

    itpr.Wave1_Approver_1__c = Wave1App1.Id;
    itpr.Wave1_Approver_2__c = Wave1App2.Id;
    itpr.Wave1_Approver_3__c = Wave1App3.Id;
    itpr.Wave1_Approver_4__c = Wave1App4.Id;

    itpr.Wave2_Approver_1__c = Wave2App1.Id;
    // itpr.Wave2_Approver_1__c = Approver3.Id;
    itpr.Wave3_Approver_1__c = Wave3App1.Id;
    //itpr.Legal_Assignee__c = u.Id; */

    insert itpr ;
    ITPR__c itpr1 = [SELECT ID, Wave1_Approver_5__c FROM ITPR__c WHERE Id =: itpr.id];
    system.assertEquals(LegalAssignee.Id, itpr1.Wave1_Approver_5__c);
    system.debug('Sucess');
  }

}