Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>CRS_Brand__c</referenceTo>
        <relationshipLabel>CRS for Brand</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipLabel>CRS for Business Unit</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Flow__c</fullName>
        <label>Process Flow</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CRS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>CRS_Brand__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Brand</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Business_Unit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Status__c</fullName>
        <label>Review Status</label>
        <picklist>
            <picklistValues>
                <fullName>Under Review</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Review Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestCRSReview.cls
/*
* author: Ivan_Tsitulenka
* class: CRS_CRSReview
* method: moveToReview, reviewComplete
*/
@isTest
private class CRS_TestCRSReview {

    private static CRS__c prepareData(){
    	CRS_TestHelper.prepareUnderReviewCRS();
    	CRS__c crs = [select Id, Name, Status__c, CRS_Business_Unit__c,
    	CRS_Brand__c from CRS__c limit 1];
    	crs.Status__c = CRS_CRSEdit.CRS_Status_InProcess;
    	update crs;
    	return crs;
    }
    
    static testMethod void moveToReviewTest() {
    	CRS__c crs = prepareData();
    	String crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	CRS_Review__c crsReview = [select Id, Name, Review_Status__c, CRS_Business_Unit__c,
    	CRS_Brand__c from CRS_Review__c where Id = :crsReviewId];
    	System.assert(crsReview.Name == crs.Name + 'rvw');
    	
    	crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	crs.Process_Flow__c = 'Full Review Non-Coke Branded Product';
    	update crs;
    	crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	
    	crs.Process_Flow__c = 'Full Review Coke Branded Product';
    	update crs;
    	crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	
    	crs.Process_Flow__c = 'Full Review & Notification & PAC';
    	update crs;
    	crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	
    	System.assert(crsReview.CRS_Business_Unit__c == crs.CRS_Business_Unit__c);
    	System.assert(crsReview.CRS_Brand__c == crs.CRS_Brand__c);
    }
    
     static testMethod void moveToReviewTest1() {
    	CRS__c crs = prepareData();
    	String crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	CRS_Review__c crsReview = [select Id, Name, Review_Status__c, CRS_Business_Unit__c,
    	CRS_Brand__c from CRS_Review__c where Id = :crsReviewId];
    	System.assert(crsReview.Name == crs.Name + 'rvw');
    	
    	crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	crs.Process_Flow__c = 'Full Review Coke Branded Product & PAC';
    	update crs;
    	crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	
    	crs.Process_Flow__c = 'Full Review (for gvwCRS Only)';
    	update crs;
    	crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	
    	
    	System.assert(crsReview.CRS_Business_Unit__c == crs.CRS_Business_Unit__c);
    	System.assert(crsReview.CRS_Brand__c == crs.CRS_Brand__c);
    }
    
    static testMethod void reviewCompleteTest(){
    	CRS__c crs = prepareData();
    	String crsReviewId = CRS_CRSReview.moveToReview(crs.Id);
    	String crsId = CRS_CRSReview.reviewComplete(crsReviewId);
    	crs = [select Id, Status__c from CRS__c where Id = :crsId];
    	System.assert(crs.Status__c==CRS_CRSEdit.CRS_Status_InProcess);
    	CRS_Review__c crsReview = [select Id, Review_Status__c from CRS_Review__c where Id = :crsReviewId limit 1];
    	System.assert(crsReview.Review_Status__c == 'Review Completed');
    }
}