Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_BU_Legal_Approver__c</fullName>
        <label>BU Legal Approver</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Status__c</fullName>
        <description>The field keeps information about last approved step. It is used as entry criteria for next approval process.</description>
        <label>Internal Status</label>
        <picklist>
            <picklistValues>
                <fullName>BU Legal Approver</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Field SRA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp Formula Govern Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Food Law Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate SRA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP-Chief Sc and Reg Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP-Science Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate PAC Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU PAC Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestCRSMailing.cls
/**
 * Test for CRS_Mailing
 */
@isTest
public with sharing class CRS_TestCRSMailing {
	
	private final static string TEST_EMAIL_TEMPLATE_NAME = 'test_Template_For_CRS_TestCRS_Mailing';

	static testMethod void testFindEmailTemplateIDByDeveloperName() {

		EmailTemplate testTemplate = new EmailTemplate();
		Folder folder = [SELECT id FROM Folder WHERE DeveloperName = 'CRS_Email_Templates'];

		testTemplate.DeveloperName = TEST_EMAIL_TEMPLATE_NAME;
		testTemplate.IsActive = true;
		testTemplate.Name = 'testName';
		testTemplate.FolderId = folder.Id;
		testTemplate.TemplateType = 'text';
		insert testTemplate;

		ID testTemplateId = CRS_Mailing.FindEmailTemplateIDByDeveloperName(TEST_EMAIL_TEMPLATE_NAME);
		System.assert(testTemplateId == testTemplate.Id, testTemplateId + ' != ' + testTemplate.Id);

	}
	
	static testMethod void testGetContactsForGroupNames() {
		Test.startTest();

		User user = CRS_TestHelper.createSysAdmin();

		CRS__c crs = CRS_TestHelper.prepareInProcessCRS();
		crs.Internal_Status__c = CRS_Mailing.APPROVAL_STEP_BULEGAL;
		crs.CRS_BU_Legal_Approver__c = user.Id;
		update crs;
		
		List<String> names = new List<String>();
		names.add('CAR_Corporate_Food_Law_Approver');
		
		List<Contact> contacts = CRS_Mailing.testGetContactsForGroupNames(names, crs, CRS_Mailing.Corporate_Level_Attention);

		//System.assert(!contacts.isEmpty(), 'List of Contacts is empty');
		
		Test.stopTest();
	}

	static testMethod void testGetContacts() {		
		Test.startTest();

		User user = CRS_TestHelper.createSysAdmin();

		CRS__c crs = CRS_TestHelper.prepareInProcessCRS();
		crs.Internal_Status__c = CRS_Mailing.APPROVAL_STEP_BULEGAL;
		crs.CRS_BU_Legal_Approver__c = user.Id;
		update crs;

		List<Contact> contacts = CRS_Mailing.testGetContacts(crs);

		System.assert(!contacts.isEmpty(), 'List of Contacts is empty');

		Test.stopTest();
	}

}