Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Prior_Status__c</fullName>
        <label>CRS Prior Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_In_Process_After_BU_Approval__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total # of business days the submission spent in “In Process” status AFTER entering “Under Review” status.</description>
        <label>Days In Process After BU Approval</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CRS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Days_Since_Initiated__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total # of business days from the date the submission was created until today’s system date. It should stop counting the day it gets approved/rejected the first time. If it gets reactivated, the system would add to the existing count</description>
        <label>Total Days Since Initiated</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_DaysInProcAfterBUAppr.cls
public with sharing class CRS_DaysInProcAfterBUAppr {
 //++CRS enhancement
    //count Days In Process After BU Approval
    public static void recountDaysInProcessAfterBUApproval(){
        String inProcessStatus = CRS_CRSEdit.CRS_Status_InProcess;
        List<CRS__c> lstCRS = [select Id, CreatedDate, Days_In_Process_After_BU_Approval__c , Status__c ,CRS_Prior_Status__c from CRS__c 
            where Status__c =:inProcessStatus];
            
            system.debug('1111'+lstCRS);
            for(CRS__c crs : lstCRS){
                if(!crs.CreatedDate.isSameDay(datetime.now()) && crs.CRS_Prior_Status__c != null ){
                
                if(crs.Status__c.equals('In Process') && crs.CRS_Prior_Status__c.equals('Under Review')){
                  if(crs.Days_In_Process_After_BU_Approval__c != null){
                  crs.Days_In_Process_After_BU_Approval__c++;
                  }else{
                  crs.Days_In_Process_After_BU_Approval__c =1;
                  }  
                }
              }
            }
          update lstCRS;
    }
     //++CRS enhancement
     //count Total Days Since Initiated
    public static void recountTotalDaysSinceInitiated(){
        
        List<CRS__c> lstCRSTotalDays = [select Id, CreatedDate, Total_Days_Since_Initiated__c , Status__c from CRS__c where Status__c != 'Approved' and Status__c != 'Rejected' and Status__c != 'Conditionally Approved' and Status__c != 'Abandoned' and Status__c != 'Disapproved' and Status__c != 'Approved-Obsolete'];

            for(CRS__c crs : lstCRSTotalDays){

                      if(crs.Total_Days_Since_Initiated__c!= null){
                      crs.Total_Days_Since_Initiated__c ++;
                      }else{
                      crs.Total_Days_Since_Initiated__c =1;
                      }  

              }
            
          update lstCRSTotalDays ;

    }
    
}