Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ContentWrapper__c.object
<CustomObject>
    <fields>
        <fullName>CRS__c</fullName>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Attachments</relationshipLabel>
        <relationshipName>CRS_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRS Attachment</label>
    <nameField>
        <displayFormat>CRSAttach{000000}</displayFormat>
        <label>Attachment Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ContentWrapper_Del__c.object
<CustomObject>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <label>Parent</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CRS Attachment Del</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>CRS Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Attachments Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_CRSReviewContentWrapper__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS Review Attachments</relationshipLabel>
        <relationshipName>CRS_Review_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRS Review Attachment</label>
    <nameField>
        <displayFormat>CRSRevAttach{000000}</displayFormat>
        <label>Attachment Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Review Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_ContentWrapperDeleteController.cls
public with sharing class CRS_ContentWrapperDeleteController {
    private ApexPages.StandardController stdController;
    private Boolean isCRSReviewWrapper;    
    
    public CRS_ContentWrapperDeleteController(ApexPages.StandardController controller) {
        stdController = controller;

        PageReference pageRef = ApexPages.currentPage();
        isCRSReviewWrapper = pageRef.getUrl().contains('Review');  
    
        if (!Test.isRunningTest()) {
            if (isCRSReviewWrapper) {
            	stdController.addFields(new String[]{'FileId__c', 'CRS_Review__c'});
            } else {
                stdController.addFields(new String[]{'FileId__c', 'CRS__c'});	
            }
        }
        
    }   
    
    /**
     * Deleting CRS_ContentWrapper__c or CRS_CRSReviewContentWrapper__c with corresponding ContentDocument record.
     */
    public PageReference deleteRecord() {
    	PageReference result = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));
        
        SObject wrapper = stdController.getRecord();
            	
    	String parentId = (String) ((isCRSReviewWrapper) ? wrapper.get('CRS_Review__c') : wrapper.get('CRS__c'));
    	String fileId = (String) wrapper.get('FileId__c');
    	
        // Cannot directly fetch ContentDocument by Id, thus ContentDocument is retrieved using ContentDocumentLink.
        List<ContentDocumentLink> docLinks = 
                [Select ContentDocument.LatestPublishedVersionId, ContentDocument.Id From ContentDocumentLink Where ContentDocumentId = :fileId]; 
        
        // ContentDocument related to wrapper to be deleted. 
        ContentDocument cDoc = null; 
        for (ContentDocumentLink cdl : docLinks) {
            if (cdl.ContentDocumentId == fileId) {
                cDoc = cdl.ContentDocument;     
                break;                
            }
        }	
         
        boolean isCRSSA = !([select Id from Profile where Id = :UserInfo.getProfileId() and 
			Name = :CRS_CRSEdit.getSAProfileName()].isEmpty());
        
		if (cDoc != null) {
			if(isCRSSA){
            delete cDoc;    		 	
			} else {
				CRS_ContentWrapper_Del__c attachToDel = new CRS_ContentWrapper_Del__c(ParentId__c = parentId, FileId__c = fileId);
				insert attachToDel;
			}
        }

    	delete wrapper;
    	return result;
    }
}