Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ContentWrapper__c.object
<CustomObject>
    <fields>
        <fullName>CRS__c</fullName>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Attachments</relationshipLabel>
        <relationshipName>CRS_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <label>Filename</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRS Attachment</label>
    <nameField>
        <displayFormat>CRSAttach{000000}</displayFormat>
        <label>Attachment Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ContentWrapper_Del__c.object
<CustomObject>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <label>Parent</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CRS Attachment Del</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>CRS Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Attachments Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_CRSReviewContentWrapper__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS Review Attachments</relationshipLabel>
        <relationshipName>CRS_Review_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <label>Filename</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRS Review Attachment</label>
    <nameField>
        <displayFormat>CRSRevAttach{000000}</displayFormat>
        <label>Attachment Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Review Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_ContentWrapperHelper.cls
global with sharing class CRS_ContentWrapperHelper {
	private final static String CRS_WRAPPER = 'CRS_ContentWrapper__c';
	private final static String CRS_REVIEW_WRAPPER = 'CRS_CRSReviewContentWrapper__c';
	
    /**
     * Wrappers synchronization for CRS__c object.
     */
    webservice static Integer syncCRSWrappers(String parentId) {
    	return syncWrappers(CRS_WRAPPER, parentId);
    }
    
    /**
     * Wrappers synchronization for CRS_Review__c object.
     */
    webservice static Integer syncCRSReviewWrappers(String parentId) {
        return syncWrappers(CRS_REVIEW_WRAPPER, parentId);    
    }
    
    /**
     * Synchronize wrappers and attached files -
     * create new wrappers for newly attached files.
     * We don't need to delete wrappers here, because it is impossible to know in Apex
     * which files were removed and which are not shared to current user.
     *
     * Returns number that will be considered in JS button: 
     * 0 - if everything is ok;
     * 1 - if parent CRS record is locked via approval process;
     * 2 - if some another exception is thrown;
     * 3 - if things are already in sync (there is nothing to save).
     */
    private static Integer syncWrappers(String parentObjectType, String parentId) {
        List<ContentDocumentLink> docLinks = 
                [SELECT ContentDocument.Id, ContentDocument.Title
                   FROM ContentDocumentLink
                  WHERE LinkedEntityId = :parentId]; 
        
        Set<String> wrappersToDel = new Set<String>();
        for (CRS_ContentWrapper_Del__c wrapperToDel : [SELECT Id, FileId__c FROM CRS_ContentWrapper_Del__c WHERE ParentId__c  like :parentId+'%']) {
            wrappersToDel.add(wrapperToDel.FileId__c);
        }
        
        String parentObjIdField = (parentObjectType == CRS_WRAPPER) ? 'CRS__c' : 'CRS_Review__c';
        String query = 'SELECT Id, FileId__c FROM '+parentObjectType+' WHERE '+ parentObjIdField + ' = \'' + parentId +'\''; 
        List<SObject> existingWrappers = Database.query(query);
        
        //Get map <fileId:wrapper> from wrappers list
        Map<String, SObject> wrappersByFile = new Map<String, SObject>();
        for (SObject wrapper : existingWrappers) {
            wrappersByFile.put((String)wrapper.get('FileId__c'), wrapper);
        }
        
        List<SObject> wrappersToCreate = new List<SObject>();
        for (ContentDocumentLink docLink : docLinks) {
            if (wrappersByFile.get(docLink.ContentDocument.Id) == null && !wrappersToDel.contains(docLink.ContentDocument.Id)) {
            	SObject wrapper;
            	if (parentObjectType == CRS_WRAPPER) {
	                 wrapper = new CRS_ContentWrapper__c();
            	} else if (parentObjectType == CRS_REVIEW_WRAPPER) {
	                 wrapper = new CRS_CRSReviewContentWrapper__c();
            	}
            	wrapper.put(parentObjIdField, parentId);
            	wrapper.put('FileId__c', docLink.ContentDocument.Id);
            	wrapper.put('Filename__c', docLink.ContentDocument.Title);
                if (wrapper != null) {
                    wrappersToCreate.add(wrapper);
                }               
            }
        }
        
        Integer result = 0;
        
        if (wrappersToCreate.size() > 0) {
        	try {
                insert wrappersToCreate;
        	} catch(DmlException e) {
        		system.debug('~~~:Exception during Content Wrappers creation: ' + e);
        		StatusCode exceptionStatusCode = e.getDmlType(0);
        		if (StatusCode.ENTITY_IS_LOCKED == exceptionStatusCode) {
        			result = 1;
        		} else {
        			result = 2;
        		}
        	}
        } else {
        	result = 3;
        }
        
        return result;    
    }

}