Jann 30/objects/CRS__c.object
<CustomObject>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ContentWrapper__c.object
<CustomObject>
    <fields>
        <fullName>CRS__c</fullName>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Attachments</relationshipLabel>
        <relationshipName>CRS_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CRS Attachment</label>
    <nameField>
        <displayFormat>CRSAttach{000000}</displayFormat>
        <label>Attachment Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/CRS_ContentWrapperEditController.cls
/**
 * "Without sharing" class to allow Corporate User to change
 * Document Type of CRS Attachments for CRS with "In Process" status
 */
public without sharing class CRS_ContentWrapperEditController {
    private ApexPages.StandardController stdController;
    
    public CRS_ContentWrapperEditController(ApexPages.StandardController stdController) {
        this.stdController = stdController; 
    }
    
    public PageReference doSave() {
        PageReference result = null;
        CRS_ContentWrapper__c record = (CRS_ContentWrapper__c) stdController.getRecord();
        try {
           update record;
           result = new PageReference('/'+record.CRS__c);
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }
        return result;
    }
}