Jann 30/objects/CRS_Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Role__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipName>CRS_Roles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_BU_Legal_Approver__c</fullName>
        <label>BU Legal Approver</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_BU_PAC_Approver__c</fullName>
        <label>BU PAC Approver</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Corporate_Food_Law_Approver__c</fullName>
        <label>Corporate Food Law Approver</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Corporate_Formula_Governance__c</fullName>
        <label>Corporate Formula Governance</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Corporate_Level__c</fullName>
        <label>CRS Corporate Level</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Corporate_PAC_Approver__c</fullName>
        <label>Corporate PAC Approver</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Corporate_SRA_Approver__c</fullName>
        <label>Corporate SRA Approver</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Field_SRA_Approver__c</fullName>
        <label>Field SRA Approver</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_VP_Chief_Scientific_Regulatory__c</fullName>
        <label>VP-Chief Scientific &amp; Regulatory Officer</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_VP_Science_Division__c</fullName>
        <label>VP-Science Division</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRS_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>gvwCRS_BU_Legal_Approver__c</fullName>
        <label>gvwCRS BU Legal Approver</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gvwCRS_BU_PAC_Approver__c</fullName>
        <label>gvwCRS BU PAC Approver</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gvwCRS_Corporate_Food_Law_Approver__c</fullName>
        <label>gvwCRS Corporate Food Law Approver</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gvwCRS_Corporate_Level__c</fullName>
        <label>gvwCRS Corporate Level</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gvwCRS_Corporate_PAC_Approver__c</fullName>
        <label>gvwCRS Corporate PAC Approver</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gvwCRS_Corporate_SRA_Approver__c</fullName>
        <label>gvwCRS Corporate SRA Approver</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gvwCRS_Field_SRA_Approver__c</fullName>
        <label>gvwCRS Field SRA Approver</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gvwCRS_VP_Chief_Scientific__c</fullName>
        <label>gvwCRS VP-Chief Scientific &amp; Regulatory</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS Role</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>CRS Role</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/CRS_RolesViewController.cls
public with sharing class CRS_RolesViewController {

    private final User user;
    
    public final static String USER_ID_KEY = 'userId';
    public final static integer SINGLE_USER = 0;
    
    public CRS_Role__c[] roleList {get; set;} 
    public boolean isEmptyRoleList {get; set;}
    public boolean isReadonly{get; set;}
    
    public CRS_RolesViewController(ApexPages.StandardController controller) {
        this.user = (User) controller.getRecord();
        isReadonly = ([SELECT Id, Name FROM Profile WHERE Id=:UserInfo.getProfileId()
            and (Name=:CRS_CRSEdit.getBAProfileName() OR Name=:CRS_CRSEdit.getSAProfileName())]).isEmpty();
        
        roleList = [SELECT id,
                           Name,
                           Business_Unit__c,
                           Business_Unit__r.Name,
                           CRS_BU_Legal_Approver__c,
                           CRS_BU_PAC_Approver__c,
                           CRS_Corporate_Food_Law_Approver__c,
                           CRS_Corporate_Formula_Governance__c,
                           CRS_Corporate_SRA_Approver__c,
                           CRS_Corporate_Level__c,
                           CRS_Field_SRA_Approver__c,
                           CRS_Corporate_PAC_Approver__c, //added by Ranjan 10th Oct'14
                           gvwCRS_BU_Legal_Approver__c,
                           gvwCRS_BU_PAC_Approver__c,
                           gvwCRS_Corporate_Food_Law_Approver__c,
                           gvwCRS_Corporate_Level__c,
                           gvwCRS_Corporate_SRA_Approver__c,
                           gvwCRS_Field_SRA_Approver__c,
                           gvwCRS_Corporate_PAC_Approver__c,  //added by Ranjan 10th Oct'14
                           gvwCRS_VP_Chief_Scientific__c,
                           CRS_VP_Chief_Scientific_Regulatory__c,
                           CRS_VP_Science_Division__c
                    FROM CRS_Role__c
                    WHERE User__c = :user.id order by Business_Unit__r.Name];
    }
}