Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>CRS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestHistoryComponentController.cls
@isTest(seeAllData=true)
public with sharing class CRS_TestHistoryComponentController {
	static testmethod void testCOMHistory(){
        	test.startTest();
            for(CRS__c crs : [select id 
                            from CRS__c where id in (select parentId from CRS__History) limit 1]){
					            crs.Status__c = 'Draft';
					            update crs;
					            CRS_HistoryComponentController obj = new CRS_HistoryComponentController();
					            CRS_HistoryComponentController.strObjectId = crs.id;
					            obj.myObject = crs;
					            obj.getObjectHistory();
					            CRS_HistoryComponentController.strObjectId = null;
					            obj.getObjectHistory();
					            
					            CRS_HistoryComponentController obj1 = new CRS_HistoryComponentController();
					            CRS_HistoryComponentController.strObjectId = crs.id;
					            obj1.myObject = crs;
					            obj1.getObjectHistory();

                            }
            test.stopTest();
    }
}