Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Reviewer_s__c</fullName>
        <label>Current Reviewer(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Initiated__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Date Initiated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiated For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnderReviewApprovalValidationCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UnderReviewApprovalValidationCheck</label>
        <type>Checkbox</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Tracking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CRS Tracking #</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Reviewers__c</fullName>
        <label>Current Reviewers</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_reviewer_FGD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current reviewer: FGD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_reviewer_FL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current reviewer: FL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_reviewer_PAC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current reviewer: PAC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_reviewer_SRA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Current reviewer: SRA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Initiated__c</fullName>
        <label>Date Initiated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiated For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRS_Reviews_for_Initiated_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_CRSReviewTriggerHandler.cls
public with sharing class CRS_CRSReviewTriggerHandler {

    private Integer getNumberFromName(List<CRS_Review__c> crsRvw){
        Integer idNum = 0;
        if(!crsRvw.isEmpty()){
            Pattern p = Pattern.compile('(\\d{6})');
            Matcher m = p.matcher(crsRvw[0].Name);
            if(m.find()){
                idNum = Integer.valueOf(m.group(1)) + 1;
                System.debug('~~~:' + m.group(1)); 
            }
        }
        if(idNum < 1001){
            idNum = 1001;
        }
        return idNum;
    }
    
    public void BeforeInsert(CRS_Review__c[] newCrsReview){
        Integer lastCrsRvwId = getNumberFromName(CRS_AdminActions.getIrwCRSReview());
        for(CRS_Review__c crsRvw : newCrsReview){
            if(crsRvw.Name == null || !crsRvw.Name.contains('ATL')){
                crsRvw.Name = 'Irvw' + '0'.repeat(6 - String.valueOf(lastCrsRvwId).length()) + lastCrsRvwId++;
                if(crsRvw.Initiated_By__c == null){
                    crsRvw.Initiated_By__c = Userinfo.getUserId();
                }
            }
            crsRvw.Date_Initiated__c = System.today();
        }
    }
    
    public void AfterInsert(CRS_Review__c[] newCrsReview){
        set<Id> CRSId = new set<ID>();
        for(CRS_Review__c crsRvw : newCrsReview){
            CRSId.add(crsRvw.CRS_Tracking__c);
        }
        
        list<CRS__c> lstCRStoUpdate = new list<CRS__c>();
        CRS__c objCRS = [select Id,CRS_Review__c from CRS__c where Id in :CRSId limit 1];
        for(CRS_Review__c crsRvw : newCrsReview){
            objCRS.CRS_Review__c = crsRvw.Id;
            objCRS.Current_Reviewer_s__c = crsRvw.Current_Reviewers__c;
            objCRS.UnderReviewApprovalValidationCheck__c = false;
            lstCRStoUpdate.add(objCRS);
        }
        
        upsert lstCRStoUpdate;
    }
    public void AfterUpdate(CRS_Review__c[] newCrsReview){
        set<Id> CRSId = new set<ID>();
        for(CRS_Review__c crsRvw : newCrsReview){
            CRSId.add(crsRvw.CRS_Tracking__c);
        }
        CRS__c objCRS = [select Id,CRS_Review__c,Current_Reviewer_s__c from CRS__c where Id in :CRSId limit 1];
        
        string CurrentReviewers = '';
        for(CRS_Review__c crsRvw : newCrsReview){
            if(crsRvw.Current_reviewer_FL__c){
                CurrentReviewers += 'FL,';
            }
            if(crsRvw.Current_reviewer_SRA__c){
                CurrentReviewers += 'SRA,';
            }
            if(crsRvw.Current_reviewer_FGD__c){
                CurrentReviewers += 'FGD,';
            }
            if(crsRvw.Current_reviewer_PAC__c){
                CurrentReviewers += 'PAC';
            }
        }
        
        objCRS.Current_Reviewer_s__c = CurrentReviewers;
        CRS_AdminActions.updateCRS(objCRS);
    
    }
}