Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Audit_Status__c</fullName>
        <label>Audit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Audit Selected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BBN__c</fullName>
        <defaultValue>&quot;BBN Not Available&quot;</defaultValue>
        <label>BBN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Beverage_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Beverage Category</label>
        <referenceTo>CRS_Beverage_Category__c</referenceTo>
        <relationshipLabel>CRS for Beverage Category</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>CRS_Brand__c</referenceTo>
        <relationshipLabel>CRS for Brand</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipLabel>CRS for Business Unit</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Country_Names__c</fullName>
        <label>Country</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Document_Title__c</fullName>
        <inlineHelpText>Document Title for Brochures, Web Copy, etc</inlineHelpText>
        <label>Document Title (not used)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Flavor_Names__c</fullName>
        <label>Flavor</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>CRS_Group__c</referenceTo>
        <relationshipLabel>CRS for Group</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Media_Type_Names__c</fullName>
        <label>Media Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Package_Type_Names__c</fullName>
        <label>Package Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Product_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>CRS_CRS_Product__c</referenceTo>
        <relationshipLabel>CRS for Products</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Type_Names__c</fullName>
        <label>CRS Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Reviewer_s__c</fullName>
        <label>Current Reviewer(s)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Package_Size__c</fullName>
        <defaultValue>&quot;Package Size Not Available&quot;</defaultValue>
        <label>Package Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Flow__c</fullName>
        <label>Process Flow</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CRS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_CRS__c</fullName>
        <description>How many CRS to be Approved text fields have input values in them (Individual CRS 01 - Individual CRS 10)</description>
        <inlineHelpText>How many &apos;CRS to be Approved&apos; text fields have input values in them (Individual CRS 01 - Individual CRS 10)</inlineHelpText>
        <label>Total CRS</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Page_Count__c</fullName>
        <label>Total Page Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <recordTypes>
        <fullName>CRS_submission</fullName>
        <active>true</active>
        <description>Regular CRS submission</description>
        <label>CRS submission</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Beverage_Category__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Beverage Category</label>
    <nameField>
        <label>Beverage Category ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beverage Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Brand__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Business_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BBN__c</fullName>
        <formula>CRS_Tracking__r.BBN__c</formula>
        <label>BBN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Beverage_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Beverage Category</label>
        <referenceTo>CRS_Beverage_Category__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Beverage_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>CRS_Brand__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Brand</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Business_Unit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Country_Names__c</fullName>
        <label>Country</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Document_Title__c</fullName>
        <formula>CRS_Tracking__r.CRS_Document_Title__c</formula>
        <label>Document Title (not used)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Flavor_Names__c</fullName>
        <label>Flavor</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>CRS_Group__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Media_Type_Names__c</fullName>
        <label>Media Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Package_Type_Names__c</fullName>
        <label>Package Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Product_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>CRS_CRS_Product__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Tracking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CRS Tracking #</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Type_Names__c</fullName>
        <label>CRS Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Package_Size__c</fullName>
        <formula>CRS_Tracking__r.Package_Size__c</formula>
        <label>Package Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_CRS__c</fullName>
        <formula>CRS_Tracking__r.Total_CRS__c</formula>
        <label>Total CRS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Page_Count__c</fullName>
        <formula>CRS_Tracking__r.Total_Page_Count__c</formula>
        <label>Total Page Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <recordTypes>
        <fullName>CRS_Review</fullName>
        <active>true</active>
        <description>CRS submission</description>
        <label>CRS Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>gvwCRS_Review</fullName>
        <active>true</active>
        <description>gvwCRS submission</description>
        <label>gvwCRS Review</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_CRSReview.cls
global with sharing class CRS_CRSReview {
    public final static String CRS_REVIEW_RT_CRS_REVIEW = 'CRS_Review';
    public final static String CRS_REVIEW_RT_GVWCRS_REVIEW = 'gvwCRS_Review';
    
    public final static String CRS_RT_CRS = 'CRS_submission';
    
    public final static String PROCESS_FLOW_FULL_REVIEW_NON_COKE = 'Full Review Non-Coke Branded Product'; //workflow 2
    public final static String PROCESS_FLOW_FULL_REVIEW_COKE = 'Full Review Coke Branded Product';  // work flow 3
    public final static String PROCESS_FLOW_GVW_FULL_REVIEW = 'Full Review (for gvwCRS Only)';  // workflwo 2 & 4
    public final static String PROCESS_FLOW_FULL_REVIEW_NOTIFICATION = 'Full Review & Notification';  // workflow 2
    public final static String PROCESS_FLOW_NOTIFICATION = 'Notification';   // workflow flow 1 
    public final static String PROCESS_FLOW_FULL_REVIEW_PAC_COKE = 'Full Review Coke Branded Product & PAC';  // work flow 5
    public final static String PROCESS_FLOW_FULL_REVIEW_NOTIFICATION_PAC = 'Full Review & Notification & PAC'; // work flow 4
    public final static String PROCESS_FLOW_FULL_REVIEW_PAC_NON_COKE = 'Full Review Non-Coke Branded Product & PAC'; // work flow 4
    
    @RemoteAction
    webService static String moveToReview(String crsId){
        if (!CRS_Approval.showReviewButton(crsId)){
            return 'error:CRS cannot be moved to review, because you do not have enough permissions or CRS Status does not allow this operation';
        }
        //++ frr 12, crs enhancement
        List<CRS__c> crsList = [SELECT Id, Active__c, Name, CRS_Review__c, CRS_Business_Unit__c, CRS_Group__c,
            CRS_Country_Names__c, Package_Size__c, CRS_Type_Names__c, CRS_Product_Name__c, CRS_Flavor_Names__c, CRS_Brand__c, 
            CRS_Beverage_Category__c, CRS_Package_Type_Names__c, BBN__c, CRS_Media_Type_Names__c, Total_CRS__c,
            Total_Page_Count__c, Audit_Status__c, CRS_Document_Title__c, Process_Flow__c, Current_Reviewer_s__c FROM CRS__c WHERE Id=:crsId ];

        if (crsList.size()!=0){
            CRS__c crs = crsList.get(0);
            if (crs.Active__c=='No'){
                return 'error:Cannot move to review inactive CRS';
            }
            CRS_Review__c crsReview = null;
            // Create a new one or get existing CRS Review 
            if(crs.CRS_Review__c == null){
                 crsReview = new CRS_Review__c(CRS_Tracking__c=crsId);
                 crsReview.Name=crs.Name + 'rvw';
                 RecordType crsReviewRT;
                 if([select Id, RecordTypeId from CRS__c where Id = :crs.Id].RecordTypeId == [Select Id From RecordType WHERE SobjectType='CRS__c' and DeveloperName = :CRS_RT_CRS][0].Id){
                    crsReviewRT = [Select Id From RecordType r WHERE SobjectType='CRS_Review__c' and DeveloperName = :CRS_REVIEW_RT_CRS_REVIEW];
                 } else {
                    crsReviewRT = [Select Id From RecordType r WHERE SobjectType='CRS_Review__c' and DeveloperName = :CRS_REVIEW_RT_GVWCRS_REVIEW];
                 }
                 if(crsReviewRT != null){
                    crsReview.RecordTypeId = crsReviewRT.Id;
                 }
            } else {
                List<CRS_Review__c> crsReviewList = [SELECT Id from CRS_Review__c WHERE Id=:crs.CRS_Review__c limit 1];
                if(!crsReviewList.isEmpty()){
                    crsReview = crsReviewList[0];
                }
            }
            crsReview.Active__c=crs.Active__c;
            crsReview.Beverage_Category__c=crs.CRS_Beverage_Category__c;
            crsReview.CRS_Brand__c=crs.CRS_Brand__c;
            crsReview.CRS_Business_Unit__c=crs.CRS_Business_Unit__c;
            crsReview.CRS_Country_Names__c=crs.CRS_Country_Names__c;
            crsReview.CRS_Type_Names__c=crs.CRS_Type_Names__c;
            crsReview.CRS_Flavor_Names__c=crs.CRS_Flavor_Names__c;
            crsReview.CRS_Group__c=crs.CRS_Group__c;
            crsReview.Initiated_By__c=Userinfo.getUserId();
            crsReview.CRS_Media_Type_Names__c=crs.CRS_Media_Type_Names__c;
            crsReview.CRS_Package_Type_Names__c=crs.CRS_Package_Type_Names__c;
            crsReview.CRS_Product_Name__c=crs.CRS_Product_Name__c;
            crsReview.Review_Status__c=CRS_CRSEdit.CRS_Status_UnderReview;
            
            //++ crs enahancement, frr12
            if(crs.Process_Flow__c == PROCESS_FLOW_FULL_REVIEW_NON_COKE || crs.Process_Flow__c == PROCESS_FLOW_FULL_REVIEW_NOTIFICATION){
                crsReview.Current_reviewer_FL__c = true;
                crsReview.Current_reviewer_SRA__c = true;
                crsReview.Current_reviewer_FGD__c =  false;
                crsReview.Current_reviewer_PAC__c =  false;
                crs.Current_Reviewer_s__c = 'FL,SRA';
            }
            
            // for work flow 3
            if(crs.Process_Flow__c == PROCESS_FLOW_FULL_REVIEW_COKE){
                crsReview.Current_reviewer_FL__c = true;
                crsReview.Current_reviewer_SRA__c = true;
                crsReview.Current_reviewer_FGD__c =  true;
                crsReview.Current_reviewer_PAC__c =  false;
                crs.Current_Reviewer_s__c = 'FL,SRA,FGD';
            }
            
            // for work flow 4 
            if(crs.Process_Flow__c == PROCESS_FLOW_FULL_REVIEW_NOTIFICATION_PAC || crs.Process_Flow__c == PROCESS_FLOW_FULL_REVIEW_PAC_NON_COKE){
                crsReview.Current_reviewer_FL__c = true;
                crsReview.Current_reviewer_SRA__c = true;
                crsReview.Current_reviewer_PAC__c =  true;
                crsReview.Current_reviewer_FGD__c =  false;
                crs.Current_Reviewer_s__c = 'FL,SRA,PAC';
            }
            
            // work flow 5
            if(crs.Process_Flow__c == PROCESS_FLOW_FULL_REVIEW_PAC_COKE){
                crsReview.Current_reviewer_FL__c = true;
                crsReview.Current_reviewer_SRA__c = true;
                crsReview.Current_reviewer_FGD__c =  true;
                crsReview.Current_reviewer_PAC__c =  true;
                crs.Current_Reviewer_s__c = 'FL,SRA,FGD,PAC';
            }
            
            // for gvw workflow
            if(crs.Process_Flow__c == PROCESS_FLOW_GVW_FULL_REVIEW){
                crsReview.Current_reviewer_FL__c = true;
                crsReview.Current_reviewer_SRA__c = true;
                crsReview.Current_reviewer_FGD__c =  false;
                crsReview.Current_reviewer_PAC__c =  false;
                crs.Current_Reviewer_s__c = 'FL,SRA';
            }
            
            //--
            
            
            crsReview = CRS_AdminActions.updateCRSReview(crsReview);
            // for workflow 2
            
            
            
            string CRSReviewers;
            
            crs.CRS_Review__c = crsReview.Id;
            crs.Status__c = CRS_CRSEdit.CRS_Status_UnderReview;
            crs.UnderReviewApprovalValidationCheck__c = false;
            CRS_AdminActions.updateCRS(crs);
            return crsReview.Id;
        }
        return '';
    }

    @RemoteAction
    webService static String reviewComplete(String crsReviewId){
        List<CRS_Review__c> reviewList =[SELECT Id, CRS_Tracking__c, Review_Status__c from CRS_Review__c WHERE Id=:crsReviewId];
        System.debug('~~~reviewList: '+reviewList);
        if (reviewList.size()!=0){
            CRS_Review__c review = reviewList.get(0);
            if (review.Review_Status__c=='Review Completed'){
                return 'error:Review was already completed.';
            }
            review.Review_Status__c = 'Review Completed';
            review = CRS_AdminActions.updateCRSReview(review);

            if (review.CRS_Tracking__c != null){
                CRS__c crs = [SELECT Id, Status__c FROM CRS__c WHERE Id=:review.CRS_Tracking__c];
                crs.Status__c=CRS_CRSEdit.CRS_Status_InProcess;
                CRS_AdminActions.updateCRS(crs);
                
                return review.CRS_Tracking__c;
            } else {
                return 'reload:';
            }           
        }
        return 'error:';
    }
}