Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Document_Title__c</fullName>
        <inlineHelpText>Document Title for Brochures, Web Copy, etc</inlineHelpText>
        <label>Document Title (not used)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ContentWrapper__c.object
<CustomObject>
    <fields>
        <fullName>CRS__c</fullName>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Attachments</relationshipLabel>
        <relationshipName>CRS_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRS Attachment</label>
    <nameField>
        <displayFormat>CRSAttach{000000}</displayFormat>
        <label>Attachment Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/CRS_CRSReviewContentWrapper__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS Review Attachments</relationshipLabel>
        <relationshipName>CRS_Review_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRS Review Attachment</label>
    <nameField>
        <displayFormat>CRSRevAttach{000000}</displayFormat>
        <label>Attachment Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Review Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Document_Title__c</fullName>
        <formula>CRS_Tracking__r.CRS_Document_Title__c</formula>
        <label>Document Title (not used)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Tracking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CRS Tracking #</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestContentWrapperHelper.cls
/**
 * Test for CRS_ContentWrapperHelper class.
 */
@isTest
private class CRS_TestContentWrapperHelper {
    
    /**
     * In the current API version (25) we cannot programmaticaly link ContentVersion to custom objects.
     * So full testing cannot be performed.
     */
    testMethod static void testSyncCRSWrappers() {
        CRS__c crs = new CRS__c();
        crs.CRS_Document_Title__c = 'test doc title';
        insert crs;
        CRS_ContentWrapperHelper.syncCRSWrappers(crs.Id);
        List<CRS_ContentWrapper__c> wrappers = [SELECT Id, FileId__c FROM CRS_ContentWrapper__c WHERE CRS__c = :crs.Id];
        System.assert(wrappers.size() == 0);
    }
    
    /**
     * In the current API version (25) we cannot programmaticaly link ContentVersion to custom objects.
     * So full testing cannot be performed.
     */
    testMethod static void testSyncCRSReviewWrappers() {
        CRS__c crs = CRS_TestHelper.prepareUnderReviewCRS();
        CRS_Review__c crsReview = new CRS_Review__c(CRS_Tracking__c = crs.Id);
        insert crsReview;
        CRS_ContentWrapperHelper.syncCRSReviewWrappers(crsReview.Id);
        List<CRS_CRSReviewContentWrapper__c> wrappers = [SELECT Id, FileId__c FROM CRS_CRSReviewContentWrapper__c WHERE CRS_Review__c = :crsReview.Id];
        System.assert(wrappers.size() == 0);
    }
    
}