Jann 30/objects/CRS__c.object
<CustomObject>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Message__c.object
<CustomObject>
    <description>Used to send approval notification.</description>
    <fields>
        <fullName>CRS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Messages</relationshipLabel>
        <relationshipName>CRS_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS Message</label>
    <nameField>
        <displayFormat>CMN-{000000}</displayFormat>
        <label>CRS Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestCRSResendController.cls
/*
	Test for CRS_CRSResendController.
*/
@isTest
public with sharing class CRS_TestCRSResendController {
	
	private static String CRS_ID_KEY = 'idCRS';
	
	testMethod static void testDoSendMessage() {

		CRS__c crs = new CRS__c();
		insert crs;
		
		PageReference pageRef = Page.CRS_CRSResendMessage;
		pageRef.getParameters().put(CRS_ID_KEY, crs.Id);
		Test.setCurrentPage(pageRef);
		
		CRS_Message__c message = new CRS_Message__c();
		insert message;
		
		CRS_CRSResendController controller = new CRS_CRSResendController(new ApexPages.StandardController(message));
		PageReference resultRef = controller.sendMessage();
		
		System.assert(resultRef.getUrl() == '/' + crs.Id, resultRef.getUrl() + ' != ' + crs.Id);
	}
}