Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Beverage_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Beverage Category</label>
        <referenceTo>CRS_Beverage_Category__c</referenceTo>
        <relationshipLabel>CRS for Beverage Category</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>CRS_Brand__c</referenceTo>
        <relationshipLabel>CRS for Brand</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipLabel>CRS for Business Unit</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Country_Names__c</fullName>
        <label>Country</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Flavor_Names__c</fullName>
        <label>Flavor</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>CRS_Group__c</referenceTo>
        <relationshipLabel>CRS for Group</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Package_Type_Names__c</fullName>
        <label>Package Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Product_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>CRS_CRS_Product__c</referenceTo>
        <relationshipLabel>CRS for Products</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Status2__c</fullName>
        <description>The field keeps status for Approval process. 
NotStarted means Approvals wasn&apos;t started or is recalled - it is a sign that &apos;Submit for Approval&apos; button can be shown. 
RuNext means next step of Approval Process should be started immediately.
Wait means wait response about next step or wait for approve/reject decision.</description>
        <label>Internal Status2</label>
        <picklist>
            <picklistValues>
                <fullName>NotStarted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>RunNext</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Internal_Status__c</fullName>
        <description>The field keeps information about last approved step. It is used as entry criteria for next approval process.</description>
        <label>Internal Status</label>
        <picklist>
            <picklistValues>
                <fullName>BU Legal Approver</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Field SRA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp Formula Govern Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Food Law Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate SRA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP-Chief Sc and Reg Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP-Science Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate PAC Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU PAC Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Package_Size__c</fullName>
        <defaultValue>&quot;Package Size Not Available&quot;</defaultValue>
        <label>Package Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_Flow__c</fullName>
        <label>Process Flow</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Beverage_Category__c.object
<CustomObject>
    <label>Beverage Category</label>
    <nameField>
        <label>Beverage Category ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beverage Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_CRS_Product__c.object
<CustomObject>
    <label>CRS Product</label>
    <nameField>
        <label>Beverage Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Message__c.object
<CustomObject>
    <description>Used to send approval notification.</description>
    <fields>
        <fullName>CRS_Beverage_Category__c</fullName>
        <label>CRS Beverage Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Brand__c</fullName>
        <label>CRS Brand</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <label>CRS Business Unit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Country_Names__c</fullName>
        <label>CRS Country Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Flavor_Names__c</fullName>
        <label>CRS Flavor Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Group__c</fullName>
        <label>CRS Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Link__c</fullName>
        <label>CRS Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Name__c</fullName>
        <label>CRS Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Package_Size__c</fullName>
        <label>CRS Package Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Package_Type_Names__c</fullName>
        <label>CRS Package Type Names</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Process_Flow__c</fullName>
        <label>CRS Process Flow</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS_Product_Name__c</fullName>
        <label>CRS Product Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Messages</relationshipLabel>
        <relationshipName>CRS_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification_Comment__c</fullName>
        <label>Notification Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>CRS Message</label>
    <nameField>
        <displayFormat>CMN-{000000}</displayFormat>
        <label>CRS Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/CRS_CRSResendController.cls
public with sharing class CRS_CRSResendController {
    public ApexPages.StandardController stdController;
    public CRS__c crs {get;set;}
    public boolean isShowMessageBox {get;set;}
    private PageReference redirectToCRS;
    
    public CRS_CRSResendController(ApexPages.StandardController controller) {
        this.stdController = controller;
        String crsId = ApexPages.currentPage().getParameters().get('idCRS');
        crs = [select Id, Name, OwnerId, CRS_Product_Name__r.Name, Process_Flow__c,
        CRS_Brand__r.Name, CRS_Flavor_Names__c, CRS_Beverage_Category__r.Name, 
        CRS_Package_Type_Names__c, Package_Size__c, CRS_Country_Names__c,
        CRS_Business_Unit__r.Name, CRS_Group__r.Name, Internal_Status2__c, Internal_Status__c from CRS__c where Id = :crsId];
        isShowMessageBox = crs.Internal_Status2__c != 'Wait2';

        CRS_Message__c crsMessage = (CRS_Message__c) stdController.getRecord();
        
        if (crs.Internal_Status__c != 'VP-Chief Sc and Reg Officer') {
        	crsMessage.Notification_Comment__c = '';
        }
        redirectToCRS = new PageReference('/' + crs.Id); 
        redirectToCRS.setRedirect(true);
    }
    
    public PageReference sendMessage(){
        CRS_Message__c crsMessage = (CRS_Message__c) stdController.getRecord();
        crsMessage = fillMessage(crs, crsMessage);
        upsert crsMessage;
        CRS_Mailing.resendEmail(crs.Name);
        return new PageReference('/'+crs.Id);
    }
    
    public static CRS_Message__c fillMessage(CRS__c crs, CRS_Message__c crsMessage){
    	crsMessage.CRS__c = crs.Id;
    	crsMessage.CRS_Name__c = crs.Name;
    	crsMessage.CRS_Product_Name__c = crs.CRS_Product_Name__r.Name;
    	crsMessage.CRS_Process_Flow__c = crs.Process_Flow__c;
        crsMessage.CRS_Brand__c = crs.CRS_Brand__r.Name;
        crsMessage.CRS_Flavor_Names__c = crs.CRS_Flavor_Names__c;
        crsMessage.CRS_Beverage_Category__c = crs.CRS_Beverage_Category__r.Name;
        crsMessage.CRS_Package_Type_Names__c = crs.CRS_Package_Type_Names__c;
        crsMessage.CRS_Package_Size__c = crs.Package_Size__c;
        crsMessage.CRS_Country_Names__c = crs.CRS_Country_Names__c;
        crsMessage.CRS_Business_Unit__c = crs.CRS_Business_Unit__r.Name;
        crsMessage.CRS_Group__c = crs.CRS_Group__r.Name;
        crsMessage.CRS_Link__c = URL.getSalesforceBaseUrl().toExternalForm() + '/' + crs.Id;
        return crsMessage;
    }
    
    public PageReference doCancel() {
        return redirectToCRS;
    }
}