Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Document_Title__c</fullName>
        <inlineHelpText>Document Title for Brochures, Web Copy, etc</inlineHelpText>
        <label>Document Title (not used)</label>
        <type>TextArea</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ContentWrapper__c.object
<CustomObject>
    <fields>
        <fullName>CRS__c</fullName>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Attachments</relationshipLabel>
        <relationshipName>CRS_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CRS Attachment</label>
    <nameField>
        <displayFormat>CRSAttach{000000}</displayFormat>
        <label>Attachment Wrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestContentWrapperDeleteController.cls
/**
 * Test for CRS_ContentWrapperDeleteController class
 */
@isTest
private class CRS_TestContentWrapperDeleteController {
	
    /**
     * In the current API version (25) we cannot programmaticaly link ContentVersion to custom objects.
     * So full testing cannot be performed.
     */
	/*testMethod static void testDeleteRecord() {
        PageReference pageRef = Page.CRS_ContentWrapperDelete;
        pageRef.getParameters().put('retURL', 'testUrl');
        
        Test.setCurrentPage(pageRef);
        
        CRS__c crs = new CRS__c();
        crs.CRS_Document_Title__c = 'test doc title';
        insert crs;
        
        CRS_ContentWrapper__c wrapper = new CRS_ContentWrapper__c();
        wrapper.CRS__c = crs.Id;
        insert wrapper;
        
        CRS_ContentWrapperDeleteController testController = new CRS_ContentWrapperDeleteController(new ApexPages.StandardController(wrapper));
        testController.deleteRecord();
	}
*/
}