Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Corp_Formula_Governance__c</fullName>
        <label>CRS Corporate Formula Governance</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Corp_SRA_Approver__c</fullName>
        <label>Corporate SRA Approver</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestCRSReminder.cls
@isTest
public with sharing class CRS_TestCRSReminder {
        
    static testmethod void testCRSReminderMethod()
    {
       
       CRS__c crs = CRS_TestHelper.prepareDraftCRS();
       crs.CRS_Corp_SRA_Approver__c = 'test user1;test user2';
       crs.CRS_Corp_Formula_Governance__c = 'test user1;test user2';
       update crs;
       ApexPages.StandardController sc = new ApexPages.standardController(crs);
       CRS_Reminder controller = new CRS_Reminder(sc); 
    }
      
 
}