Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Beverage_Category__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Beverage Category</label>
        <referenceTo>CRS_Beverage_Category__c</referenceTo>
        <relationshipLabel>CRS for Beverage Category</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>CRS_Brand__c</referenceTo>
        <relationshipLabel>CRS for Brand</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipLabel>CRS for Business Unit</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Flavor_Names__c</fullName>
        <label>Flavor</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>CRS_Group__c</referenceTo>
        <relationshipLabel>CRS for Group</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Media_Type_Names__c</fullName>
        <label>Media Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Package_Type_Names__c</fullName>
        <label>Package Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Product_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>CRS_CRS_Product__c</referenceTo>
        <relationshipLabel>CRS for Products</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Type_Names__c</fullName>
        <label>CRS Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Initiated__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Date Initiated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiated For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Flow__c</fullName>
        <label>Process Flow</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CRS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Beverage_Category__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Beverage Category</label>
    <nameField>
        <label>Beverage Category ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beverage Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Brand__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Business_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>CRS_Group__c</referenceTo>
        <relationshipLabel>Business Units</relationshipLabel>
        <relationshipName>Business_Units</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_CRS_Product__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS Product</label>
    <nameField>
        <label>Beverage Product ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ProductDependentFieldsSetup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CRS Product-dependent fields setup</label>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>CRS_Brand__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Brand</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Business_Unit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Flavor_Names__c</fullName>
        <label>Flavor</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>CRS_Group__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Media_Type_Names__c</fullName>
        <label>Media Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Package_Type_Names__c</fullName>
        <label>Package Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Product_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>CRS_CRS_Product__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews_for_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Type_Names__c</fullName>
        <label>CRS Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Initiated__c</fullName>
        <label>Date Initiated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiated For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRS_Reviews_for_Initiated_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Type_to_CRS__c.object
<CustomObject>
    <description>Used to model many-to-many relationship between CRS Types and CRS submissions</description>
    <fields>
        <fullName>CRS_Type__c</fullName>
        <label>CRS Type</label>
        <referenceTo>CRS_Type__c</referenceTo>
        <relationshipLabel>CRS Type to CRS</relationshipLabel>
        <relationshipName>CRS_Type_to_CRS</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>CRS__c</fullName>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Type to CRS</relationshipLabel>
        <relationshipName>CRS_Type_to_CRS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>CRS Type to CRS</label>
    <nameField>
        <displayFormat>CCT-{000000}</displayFormat>
        <label>CRS Type to CRS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Type to CRS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestCRSEdit.cls
@isTest
private class CRS_TestCRSEdit {
    
    /*
    * author: Ivan_Tsitulenka
    * class: CRS_CRSEdit
    * method: updateProcessFlow
    */
    
    static private void startProcessFlowTests(String typeName, Integer productNum, Integer[] typeNum, String result){
        CRS_TestHelper.prepareNameValueSetup();
        CRS_TestHelper.prepareProductDependentFields();
        RecordType crsGvwRecordType = [Select Id, Name From RecordType where sObjectType='CRS__c' and name = :typeName][0];
        CRS__c testCrs = new CRS__c(Status__c = CRS_CRSEdit.CRS_Status_Draft, RecordType = crsGvwRecordType, RecordTypeId = crsGvwRecordType.Id);
        CRS_CRSEdit testCrsEdit = new CRS_CRSEdit(new ApexPages.StandardController(testCrs));
        if(productNum > -1){
            testCrs.CRS_Product_Name__c = CRS_TestHelper.prepareCRSProduct(productNum).id;
        }
        String typeIds = '';
        for(CRS_Type__c types : CRS_TestHelper.prepareCRSType(typeNum)){
            typeIds += types.Id + ';';
        }
        
        if(!''.equals(typeIds)){
            testCrsEdit.selectedMultipleIds.put('CRS_Type_to_CRS__c',typeIds);
        }
        testCrsEdit.updateProcessFlow(false);
        System.assert(testCrs.Process_Flow__c == result);
    }
    
    static private void preparedDataForAllProduct(Integer i){
        CRS_TestHelper.prepareNameValueSetup();
        CRS_TestHelper.prepareProductDependentFields();
        CRS_TestHelper.prepareCRSProduct(i);
        CRS_TestHelper.prepareCRSType(new List<Integer>{i});
        CRS_TestHelper.prepareCRSBeverageCategory(i);
        CRS_TestHelper.prepareCRSBrand(i);
        CRS_TestHelper.prepareCRSFlavor(i);
        CRS_TestHelper.prepareCRSMediaType(i);
        CRS_TestHelper.prepareCRSPackageType(1);
    }
    
    static testMethod void testUpdateProcessFlowGvw() {
        Integer[] index = new List<Integer>{};
        startProcessFlowTests('glaceau vitaminwater CRS',1,index,'Full Review (for gvwCRS Only)');
    }
    
    static testMethod void testUpdateProcessFlowNoGvwPOYes() {
        Integer[] index = new List<Integer>{};      
        startProcessFlowTests('CRS submission',0,index,'Full Review Coke Branded Product');
    }   
       
    static testMethod void testUpdateProcessFlowNoGvwPONoTypeFull() {
        Integer[] index = new List<Integer>{4};
        startProcessFlowTests('CRS submission',3,index,'Full Review Non-Coke Branded Product');
    }
   
    static testMethod void testUpdateProcessFlowNoGvwPONoTypeNotification() {
        Integer[] index = new List<Integer>{0};
        startProcessFlowTests('CRS submission',3,index,'Notification');
    }
   
    static testMethod void testUpdateProcessFlowNoGvwPONoTypeNotificationFull() {
        Integer[] index = new List<Integer>{0,1};
        startProcessFlowTests('CRS submission',3,index,'Full Review & Notification');
    }
   
    static testMethod void testUpdateProcessFlowNoGvwPONoTypeNotNotification() {
        Integer[] index = new List<Integer>{1,2};
        startProcessFlowTests('CRS submission',1,index,'Full Review Non-Coke Branded Product');
    }
    
    private static CRS__c populateAllProduct(String prodName){
        Id crsProductId = [select Id from CRS_CRS_Product__c where Name = :prodName limit 1].Id;
        RecordType crsGvwRecordType = [Select Id, Name From RecordType where sObjectType='CRS__c' and name = 'CRS submission'][0];

        CRS_Business_Unit__c crsBU = createBU('testBU');

        CRS__c testCrs = new CRS__c(Status__c = CRS_CRSEdit.CRS_Status_Draft, RecordType = crsGvwRecordType,
        RecordTypeId = crsGvwRecordType.Id, Date_Initiated__c = System.today(),
        Initiated_By__c = UserInfo.getUserId());
        CRS_CRSEdit testCrsEdit = new CRS_CRSEdit(new ApexPages.StandardController(testCrs));
        PageReference pageRef = Page.CRS_CRSEdit;
        pageRef.getParameters().put('product', crsProductId);
        pageRef.getParameters().put('bu', crsBU.Id);
        Test.setCurrentPage(pageRef);
        testCrsEdit.populateBUDependencies();
        testCrsEdit.processBeverageProductChange();
        testCrsEdit.doSave();
        return [select Id, CRS_Type_Names__c, CRS_Beverage_Category__c, CRS_Brand__c, 
            CRS_Flavor_Names__c, CRS_Media_Type_Names__c, CRS_Package_Type_Names__c 
            from CRS__c limit 1];
    }
    
    static private String getPDNameFor(String settingName) {
        String result = null;
        CRS_ProductDependentFieldsSetup__c setting = CRS_ProductDependentFieldsSetup__c.getInstance(settingName);
        if (setting != null) {
             result = setting.Value__c;
        }
        return result;
    }
    
    static testMethod void testAllProductsGC(){
        preparedDataForAllProduct(1);
        CRS__c testCrs = populateAllProduct('All Products - General Communications');
        System.assert(testCrs.CRS_Beverage_Category__c == 
            [select Id from CRS_Beverage_Category__c where 
                Name = :getPDNameFor(CRS_CRSEdit.BEVERAGE_CATEGORY_NAME_GENERAL_COMMUNICATIONS) limit 1].Id);
        System.assert(testCrs.CRS_Brand__c == 
            [select Id from CRS_Brand__c where 
                Name = :getPDNameFor(CRS_CRSEdit.BRAND_NAME_GENERAL_COMMUNICATIONS) limit 1].Id);
        System.assert(testCrs.CRS_Type_Names__c == getPDNameFor(CRS_CRSEdit.CRS_TYPE_NAME_GENERAL_COMMUNICATIONS)+';');
        System.assert(testCrs.CRS_Flavor_Names__c == getPDNameFor(CRS_CRSEdit.FLAVOR_NAME_GENERAL_COMMUNICATIONS)+';');
        System.assert(testCrs.CRS_Media_Type_Names__c == getPDNameFor(CRS_CRSEdit.MEDIA_TYPE_NAME_GENERAL_COMMUNICATIONS)+';');
        System.assert(testCrs.CRS_Package_Type_Names__c == getPDNameFor(CRS_CRSEdit.PACKAGE_TYPE_NAME_GENERAL_COMMUNICATIONS)+';');
    }
    
    static testMethod void testAllProductsLP(){
        preparedDataForAllProduct(2);
        CRS__c testCrs = populateAllProduct('All Products - Live Positively');
        System.assert(testCrs.CRS_Beverage_Category__c == 
            [select Id from CRS_Beverage_Category__c where 
                Name = :getPDNameFor(CRS_CRSEdit.BEVERAGE_CATEGORY_NAME_LIVE_POSITIVELY) limit 1].Id);
        System.assert(testCrs.CRS_Brand__c == 
            [select Id from CRS_Brand__c where 
                Name = :getPDNameFor(CRS_CRSEdit.BRAND_NAME_LIVE_POSITIVELY) limit 1].Id);
        System.assert(testCrs.CRS_Type_Names__c == getPDNameFor(CRS_CRSEdit.CRS_TYPE_NAME_LIVE_POSITIVELY)+';');
        System.assert(testCrs.CRS_Flavor_Names__c == getPDNameFor(CRS_CRSEdit.FLAVOR_NAME_LIVE_POSITIVELY)+';');
        System.assert(testCrs.CRS_Media_Type_Names__c == getPDNameFor(CRS_CRSEdit.MEDIA_TYPE_NAME_LIVE_POSITIVELY)+';');
        System.assert(testCrs.CRS_Package_Type_Names__c == getPDNameFor(CRS_CRSEdit.PACKAGE_TYPE_NAME_LIVE_POSITIVELY)+';');
    }
    
    private static CRS_Business_Unit__c createBU(String buName){
        CRS_Group__c crsGroup = new CRS_Group__c(Name = buName, Active__c = 'Yes');
        insert crsGroup;
        
        CRS_Business_Unit__c crsBU = new CRS_Business_Unit__c(Name = buName, Active__c = 'Yes', Group__c = crsGroup.Id);
        insert crsBU;
        return crsBU;
    } 
    
    /*private static User createUser(String name, String BUName){
        Profile prof = [select Id from Profile where Name = 'System Administrator'];
        UserRole uRole = [select Name, Id from UserRole where Name = 'Top Level' limit 1];
        User test2 = new User(
            LastName = name+'test', Alias = name.substring(0, 3), Email = name+'@mail.com',
            username = name+'@mail.com', CommunityNickname = name,
            UserRoleId = uRole.Id, TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US', EmailEncodingKey = 'ISO-8859-1', ProfileId = prof.Id, 
            LanguageLocaleKey = 'en_US'
        );
        test2.CRS_BU_Legal_Approver__c='Yes'; 
        test2.CRS_Field_SRA_Approver__c='Yes';
        test2.CRS_Corporate_SRA_Approver__c='Yes'; 
        test2.CRS_Corporate_Food_Law_Approver__c='Yes';
        test2.CRS_Corporate_Formula_Governance__c='Yes'; 
        test2.CRS_VP_Chief_Scientific_Regulatory__c='Yes';
        test2.Business_Unit__c = BUName;
        insert test2;
        return test2;
    }*/
    /*static testMethod void testPopulateBUDependencies() {
        CRS_CRSEdit editExtController = CRS_TestHelper.prepareCRSSubmission1();
        CRS__c crs = (CRS__c) editExtController.stdController.getRecord();
        crs = crs.clone(true, true);
        System.assert(crs.CRS_Business_Unit__c == null);
        editExtController.populateBUDependencies();
        CRS__c crs2 = (CRS__c) editExtController.stdController.getRecord();
        System.assertEquals(crs, crs2);
        
        CRS_Business_Unit__c crsBU = createBU('testBU');
        createUser('uTest', crsBU.Name);
        
        CRS_Business_Unit__c bu = CRS_TestHelper.findBU();
        crs2.CRS_Business_Unit__c = bu.Id;
        editExtController.populateBUDependencies();
        System.assert(crs2.CRS_Business_Unit__c != null);
        System.assert(crs2.CRS_Group__c != null);
        System.assert(crs2.CRS_BU_Legal_Approver__c != null);
        System.assert(crs2.CRS_Field_SRA_Approver__c != null);
        System.assert(crs2.CRS_Corp_SRA_Approver__c != null);
        System.assert(crs2.CRS_Corp_Food_Law_Approver__c != null);
        System.assert(crs2.CRS_Corp_Formula_Governance__c != null);
        System.assert(crs2.CRS_VP_Chief_Scientific_Regulatory__c != null);
    }*/
    
    static testMethod void testFinishClone(){
        CRS_TestHelper.prepareUnderReviewCRS();
        CRS__c testCrs = [select Id, Name, OwnerId, Send_Corp_Form_Gov__c,
            Send_VP_Science__c, Send_VP_Chief__c, RecordTypeId,
            Total_Page_Count__c, MTR_Day_Count__c, Date_Closed__c, CRS_Review__c, 
            Internal_Status2__c, Internal_Status__c, Audit_Status__c, Date_Initiated__c,
            Initiated_By__c, Status__c,Process_Flow__c,CRS_Business_Unit__c from CRS__c limit 1];
        PageReference pageRef = Page.CRS_CRSEdit;
        pageRef.getParameters().put('clone', '1');
        Test.setCurrentPage(pageRef);
        CRS_CRSEdit testCrsEdit = new CRS_CRSEdit(new ApexPages.StandardController(testCrs));
        //testCrsEdit.finishClone(testCrs);
        System.assert(testCrs.Name == '');
        System.assert(testCrs.Status__c == CRS_CRSEdit.CRS_Status_Draft);
        System.assert(testCrs.MTR_Day_Count__c == 0);
    }
   
}