Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <description>Date when CRS record is Approved, Rejected, Disapproved or Abandoned</description>
        <inlineHelpText>Date when CRS record is Approved, Rejected, Disapproved or Abandoned</inlineHelpText>
        <label>Date Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MTR_Day_Count__c</fullName>
        <inlineHelpText>Number of business days CRS has been in &quot;Under Review&quot; status</inlineHelpText>
        <label>Days Under Review</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CRS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_ContentWrapper_Del__c.object
<CustomObject>
    <fields>
        <fullName>FileId__c</fullName>
        <label>FileId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <label>Parent</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>CRS Attachment Del</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>CRS Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Attachments Del</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Tracking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CRS Tracking #</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MTR_Day_Count__c</fullName>
        <formula>CRS_Tracking__r.MTR_Day_Count__c</formula>
        <label>Days Under Review</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_CRSSchedulerEvents.cls
public with sharing class CRS_CRSSchedulerEvents {
	public static void recountMTRDay(){
		String underReviewStatus = CRS_CRSEdit.CRS_Status_UnderReview;
		List<CRS__c> draftCRS = [select Id, CreatedDate, MTR_Day_Count__c, Status__c from CRS__c 
			where Status__c =:underReviewStatus];
		for(CRS__c crs : draftCRS){
			if(!crs.CreatedDate.isSameDay(datetime.now())){
				if(crs.MTR_Day_Count__c != null){
					crs.MTR_Day_Count__c++;
				} else {
					crs.MTR_Day_Count__c = 1;
				}
			}
		}
		update draftCRS;
	}
	
	public static void deleteTenYearsOldCRS(){
		date d = system.today().addYears(-10);
		List<Id> delIds = new List<Id>();
		List<CRS__c> listCRS = [select Id, Name, Date_Closed__c, Status__c from CRS__c 
			where Date_Closed__c <= :d];
		for(CRS__c crs: listCRS){
			delIds.add(crs.Id);
		}
		List<CRS_Review__c> crsReview = [select Id, Name from CRS_Review__c where CRS_Tracking__c in :delIds];
		if(!crsReview.isEmpty()){
			delete crsReview;
		}
		if(!listCRS.isEmpty()){
			delete listCRS;	
		}
	}
	
	public static void deleteAllAttachments(){
		List<ContentDocument> cDocs = new List<ContentDocument>();
		CRS_ContentWrapper_Del__c[] wrappers = [Select FileId__c, ParentId__c From CRS_ContentWrapper_Del__c limit 150];
		for(CRS_ContentWrapper_Del__c wrapper : wrappers){
	        cDocs.add([Select ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.Id From ContentDocumentLink Where ContentDocumentId = :wrapper.FileId__c limit 1].ContentDocument);
		}
		if(!cDocs.isEmpty()){
			delete cDocs;
		}
		delete wrappers;
	}

}