Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS Review</label>
        <referenceTo>CRS_Review__c</referenceTo>
        <relationshipLabel>CRS</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiated For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CRS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Message__c.object
<CustomObject>
    <description>Used to send approval notification.</description>
    <fields>
        <fullName>CRS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRS</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Messages</relationshipLabel>
        <relationshipName>CRS_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS Message</label>
    <nameField>
        <displayFormat>CMN-{000000}</displayFormat>
        <label>CRS Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRS Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Review__c.object
<CustomObject>
    <fields>
        <fullName>CRS_Tracking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CRS Tracking #</label>
        <referenceTo>CRS__c</referenceTo>
        <relationshipLabel>CRS Reviews</relationshipLabel>
        <relationshipName>CRS_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initiated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initiated For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CRS_Reviews_for_Initiated_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRS Review</label>
    <nameField>
        <label>Review Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/CRS_CRSDelete.cls
global with sharing class CRS_CRSDelete {

	public String message {get;set;}
	public Boolean isError {get;set;}
	public Boolean isCRSBA {get;set;}
	public Boolean isCRSSA {get;set;}
	private CRS__c crs;

	public CRS_CRSDelete(ApexPages.StandardController stdController) {
		isError = false;
		crs=(CRS__c)stdController.getRecord();
        //crs = [select Id, Initiated_By__c, Name, Status__c, OwnerId from CRS__c where Id = :Apexpages.currentPage().getParameters().get('delId')];
        isCRSBA = !([select Id from Profile where Id = :UserInfo.getProfileId() and 
			Name = :CRS_CRSEdit.getBAProfileName()].isEmpty());
		isCRSSA = !([select Id from Profile where Id = :UserInfo.getProfileId() and 
			Name = :CRS_CRSEdit.getSAProfileName()].isEmpty());
	}
	
	public void deleteCRS(){
		if(isCRSSA || isCRSBA ||
			(crs.Status__c == CRS_CRSEdit.CRS_Status_Draft && UserInfo.getUserId() == crs.OwnerId)){
	    	try{
	    		List<CRS_Message__c> crsMessages = [select Id from CRS_Message__c where CRS__c = :crs.Id];
                if(!crsMessages.isEmpty()){
                    delete crsMessages;
                }
	        	List<CRS_Review__c> reviewList = [select Id from CRS_Review__c where CRS_Tracking__c = :crs.Id];
	    		if(!reviewList.isEmpty()){
	    			delete reviewList;
	    		}
	            delete crs;
	            message = 'CRS number ' +crs.Name + ' was deleted.';
	        }catch(Exception e){
	            ApexPages.addMessages(e);
	        }
        } else {
        	isError = true;
        	message = 'You don\'t have permissions';
        }
	}
}