Jann 30/objects/CRS__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CRS_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>CRS_Business_Unit__c</referenceTo>
        <relationshipLabel>CRS for Business Unit</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRS_Document_Title__c</fullName>
        <inlineHelpText>Document Title for Brochures, Web Copy, etc</inlineHelpText>
        <label>Document Title (not used)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CRS_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>CRS_Group__c</referenceTo>
        <relationshipLabel>CRS for Group</relationshipLabel>
        <relationshipName>CRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Status__c</fullName>
        <description>The field keeps information about last approved step. It is used as entry criteria for next approval process.</description>
        <label>Internal Status</label>
        <picklist>
            <picklistValues>
                <fullName>BU Legal Approver</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Field SRA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp Formula Govern Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Food Law Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate SRA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP-Chief Sc and Reg Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP-Science Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate PAC Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU PAC Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Flow__c</fullName>
        <label>Process Flow</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CRS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disapproved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved-Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRS</label>
    <nameField>
        <label>Tracking #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Business_Unit__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>CRS_Group__c</referenceTo>
        <relationshipLabel>Business Units</relationshipLabel>
        <relationshipName>Business_Units</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/CRS_Group__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/CRS_TestCRSTrigger.cls
@isTest
private class CRS_TestCRSTrigger {
	/*
	* author: Ivan_Tsitulenka
	* class: CRS_CRSTrigger, CRS_CRSTriggerHandler
	* method: BeforeInsert, getNumberFromName
	*/
	private static CRS__c createCRS(String typeName, Id crsBUId){
		RecordType crsGvwRecordType = [Select Id, Name From RecordType where sObjectType='CRS__c' and name = :typeName][0];
		CRS__c testCrs = new CRS__c(Status__c = CRS_CRSEdit.CRS_Status_Draft, RecordType = crsGvwRecordType, RecordTypeId = crsGvwRecordType.Id, CRS_Business_Unit__c = crsBUId, CRS_Document_Title__c = 'testTitle');
		return testCrs;
	}

	private static Id prepareData(){
		CRS_Group__c crsGroup = new CRS_Group__c(Name = 'test1', Active__c = 'Yes');
		insert crsGroup;
		CRS_Business_Unit__c crsBU = new CRS_Business_Unit__c(Name = 'test2', Active__c = 'Yes', Group__c = crsGroup.Id);
		insert crsBU;
		return crsBU.Id;
	}

    static testMethod void testCreatedGvw() {
		Id crsbu = prepareData();
		CRS__c testCrs = createCRS('glaceau vitaminwater CRS', crsbu);
		System.debug('~+~'+testCRS.Name);
		insert testCrs;
		CRS__c testCrs2 = [select Name from CRS__c where Id = :testCrs.Id];
		System.debug('~~~'+testCRS2.Name);
		System.assert('ATLgvw007000' == testCrs2.Name);
		testCrs.Name = 'ATLgvw107001';
		update testCrs;
		testCrs = createCRS('glaceau vitaminwater CRS', crsbu);
		System.debug('~+~'+testCRS.Name);
		insert testCrs;
		testCrs2 = [select Name from CRS__c where Id = :testCrs.Id];
		System.debug('~~~'+testCRS2.Name);
		System.assert('ATLgvw107002' == testCrs2.Name);
    }
    
    static testMethod void testCreatedNoGvw() {
		Id crsbu = prepareData();
		CRS__c testCrs = createCRS('CRS submission', crsbu);
		insert testCrs;
		CRS__c testCrs2 = [select Name from CRS__c where Id = :testCrs.Id];
		System.assert('ATL010000' == testCrs2.Name);
		testCrs.Name = 'ATL123456';
		update testCrs;
		testCrs = createCRS('CRS submission', crsbu);
		insert testCrs;
		testCrs2 = [select Name from CRS__c where Id = :testCrs.Id];
		System.assert('ATL123457' == testCrs2.Name);
    }
    
    
    static testMethod void testAfterUpdate1(){
    	CRS__c crs = CRS_TestHelper.prepareUnderReviewCRS();
		crs.Process_Flow__c = CRS_CRSReview.PROCESS_FLOW_NOTIFICATION;
		crs.Status__c = 'In Process';
		update crs;
		crs.Status__c = 'Under Review';
		update crs;
    }
    static testMethod void testAfterUpdate2(){
    	CRS__c crs = CRS_TestHelper.prepareUnderReviewCRS();
		crs.Process_Flow__c = CRS_CRSReview.PROCESS_FLOW_FULL_REVIEW_NON_COKE;
		crs.Status__c = 'In Process';
		update crs;
		crs.Status__c = 'Under Review';
		update crs;
    }
    static testMethod void testAfterUpdate3(){
    	CRS__c crs = CRS_TestHelper.prepareUnderReviewCRS();
		crs.Process_Flow__c = CRS_CRSReview.PROCESS_FLOW_FULL_REVIEW_COKE;
		crs.Status__c = 'In Process';
		update crs;
		crs.Status__c = 'Under Review';
		crs.Internal_Status__c = 'Field SRA Approver';
		update crs;
    }
    static testMethod void testAfterUpdate4(){
    	CRS__c crs = CRS_TestHelper.prepareUnderReviewCRS();
		crs.Process_Flow__c = CRS_CRSReview.PROCESS_FLOW_FULL_REVIEW_NOTIFICATION_PAC;
		crs.Status__c = 'In Process';
		update crs;
		crs.Status__c = 'Under Review';
		update crs;
    } 
    static testMethod void testAfterUpdate5(){
    	CRS__c crs = CRS_TestHelper.prepareUnderReviewCRS();
		crs.Process_Flow__c = CRS_CRSReview.PROCESS_FLOW_FULL_REVIEW_PAC_COKE;
		crs.Status__c = 'In Process';
		update crs;
		crs.Status__c = 'Under Review';
		update crs;
    }  
    static testMethod void testAfterUpdate6(){
    	CRS__c crs = CRS_TestHelper.prepareUnderReviewCRS();
		crs.Process_Flow__c = CRS_CRSReview.PROCESS_FLOW_GVW_FULL_REVIEW;
		crs.Status__c = 'In Process';
		
		update crs;
		crs.Status__c = 'Under Review';
		update crs;
    }     
}