Jann 30/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Status_Date__c</fullName>
        <label>Current Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Associates__c</fullName>
        <label>Other Associates</label>
        <picklist>
            <picklistValues>
                <fullName>Whitney Hagan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mark Westfall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Judith Speas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stephanie Sparkmon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sandra Harvey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michelle Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne K. &apos;CCNA&apos; Taylor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matthew Sisk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloris Zhang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shellie Davis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alok Deo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Murphy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max Hyldebrandt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nancy J. Mari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jorge Perez</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penny Mayo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebecca Buehler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reem Al-Hakim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marvin Jimenez</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbara Kahn-Aitken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luciana Descio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Javier Drucker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marie Quintero-Johnson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>William W. Harkins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tim Leveridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vincent Gioe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Taylor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andriy Avramenko</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/Deal_History_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipName>Deal_History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <label>New Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Previous_Value__c</fullName>
        <label>Previous Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Deal Status Tracking</label>
    <nameField>
        <displayFormat>HIS{0000}</displayFormat>
        <label>Deal History Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Status Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/Deal_History_Tracking_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Deal History Tracking Setting</label>
</CustomObject>

Jann 30/classes/DealTriggerHandler_Test.cls
/***********************************************************************
Trigger Name  : DealTriggerHandler_Test
Created By   	: Kirti Agarwal
Created Date 	: 15th Nov,2013
Purpose      	: Test class for class DealTriggerHandler
Task         	: T-212459
************************************************************************/
@isTest
private class DealTriggerHandler_Test {

    static testMethod void DealTriggerTestForAfterInsert() {

      List<User> listOfUser = new List<User>();
      for(Integer i = 1; i<=3; i++){
	      User usr  = createUser('first'+i,'last'+i,'System Administrator',null, i);
	      usr.Deal_Management_User__c = false;
        listOfUser.add(usr);
      }
      insert listOfUser;
    	 Deal_History_Tracking_Setting__c rec = new Deal_History_Tracking_Setting__c();
    	 rec.Name = 'Current_Status__c';
    	 insert rec;
    	 List<Deal__c> dealList = new List<Deal__c>();
    	 for(integer i=0; i<100; i++) {
	       Deal__c deal = new Deal__c();
	       deal.Current_Status__c = 'test 1';
		     deal.Close_Date__c = date.today().addDays(1);
		     deal.Target__c = 'test';
		     deal.Other_Associates__c = 'first1 last1;first3 last3';
		     deal.Current_Status_Date__c = date.today();
	       dealList.add(deal);
    	 }
    	 insert dealList;

    	 Test.StartTest();
    	 List<Deal__c> dealListRec = new List<Deal__c>();
       for(Deal__c deal : dealList) {
	       deal.Current_Status__c = 'test 2';
	       deal.Other_Associates__c = 'first1 last1;first2 last2';
	       dealListRec.add(deal);
       }
       update dealListRec;

       List<Deal_History_Tracking__c> dealRecList = [SELECT id,
       																						New_Value__c,
       																						Previous_Value__c
   																				FROM Deal_History_Tracking__c
   																				WHERE Deal__c IN: dealListRec];

   		for(Deal_History_Tracking__c dealRec : dealRecList) {
	   		system.assertEquals(dealRec.New_Value__c, 'test 2');
	   	  system.assertEquals(dealRec.Previous_Value__c, 'test 1');
   		}

       Test.StopTest();
    }

    static testMethod void DealTriggerTestForBeforeInsert() {
    	Test.StartTest();
    	User usr  = createUser('first','last','System Administrator',null, 1);
    	usr.Deal_Management_User__c = false;
    	insert usr;

    	 Deal__c deal = new Deal__c();
	     deal.Current_Status__c = 'test 1';
	     deal.Close_Date__c = date.today().addDays(1);
	     deal.Target__c = 'test';
	     deal.Current_Status_Date__c = date.today();
	     deal.Other_Associates__c = usr.FirstName + ' ' + usr.LastName;
	     insert deal;
	     Test.stopTest();

	    //cann't get the share record because of we cannot change in metadata picklist value of Deal in test class

    }

     public static User createUser(String firstName,String lastName, String profileName,String Role, Integer index) {
        Profile profile;
        for(Profile p : [select Id,Name from Profile where Name =:profileName limit 1]){
            profile = p;
        }
        User user = new User();
        user.Username = firstName+Date.Today().day()+Date.Today().month()+Date.Today().year() + index +'@test.com';
        user.FirstName = firstName;
        user.LastName = lastName;
        user.Email = 'test@user.com';
        user.Alias = 'tUser' + index;
        user.CommunityNickname = 'tuser' + index;
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        if(profile != null){
            user.profileId = profile.id;
        }
        if(Role != null){
            List<UserRole> roleVal = [select Id,Name from UserRole where Name =:Role limit 1];
            if(roleVal.size() > 0)
                user.UserRoleId = roleVal.get(0).Id;
        }
        return user;
    }

}