Jann 30/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Other_Associates__c</fullName>
        <label>Other Associates</label>
        <picklist>
            <picklistValues>
                <fullName>Whitney Hagan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mark Westfall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Judith Speas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stephanie Sparkmon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sandra Harvey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michelle Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne K. &apos;CCNA&apos; Taylor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Matthew Sisk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloris Zhang</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shellie Davis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alok Deo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jim Murphy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max Hyldebrandt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nancy J. Mari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jorge Perez</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penny Mayo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebecca Buehler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reem Al-Hakim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marvin Jimenez</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbara Kahn-Aitken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luciana Descio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Javier Drucker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marie Quintero-Johnson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>William W. Harkins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tim Leveridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vincent Gioe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Taylor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andriy Avramenko</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/UserTriggerHandler.cls
/***********************************************************************
Class Name  : UserTriggerHandler
Created By      : Kirti Agarwal
Created Date    : 3rd Dec, 2013
Purpose         : Update the multiselect picklist on Deal object
Task            : T-216705
************************************************************************/
public class UserTriggerHandler {

    public static void afterInsertAndUpdate(List<User> userList, map<id,User> oldMap) {

        list<User> userListWithDeal = new list<User>();
        set<String> OtherAssociateField = new set<String>();
		    Boolean setPicklist = false;
		    for(User usr : userList){
		        if((oldMap == null && usr.Deal_Management_User__c) ||
		            (oldMap != null && oldMap.get(usr.id).Deal_Management_User__c != usr.Deal_Management_User__c)) {
		            setPicklist = true;
		            break;
		        }
		    }
		    if(setPicklist) {
		            userListWithDeal = [select id,FirstName,LastName
		            										from User
		            										where Deal_Management_User__c = true];

		            for(User usr : userListWithDeal){
		                OtherAssociateField.add(usr.FirstName + ' ' + usr.LastName);
		            }
		              UpdatePicklistField(OtherAssociateField,UserInfo.getSessionId());
		    }

    }

    @future(callout=true)
    public static void UpdatePicklistField(set<String> OtherAssociateField,String sessionId)
    {
        MetadataService.MetadataPort service = createService(sessionId);
        MetadataService.CustomField customField = new MetadataService.CustomField();
        customField.fullName = 'Deal__c.Other_Associates__c';
        customField.label = 'Other Associates';
        customField.type_x = 'MultiselectPicklist';
        customField.visibleLines = 3;
        metadataservice.Picklist pt = new metadataservice.Picklist();
        pt.sorted = false;
        pt.picklistValues = new list<metadataservice.PicklistValue>();

         if(OtherAssociateField.size() > 0) {
            for(String value : OtherAssociateField) {
                metadataservice.PicklistValue plValue = new metadataservice.PicklistValue();
                plValue.fullName = value;
                plValue.default_x = false ;
                pt.picklistValues.add(plValue);
            }
         }

        else{
          metadataservice.PicklistValue pl = new metadataservice.PicklistValue();
            pl.fullName = 'None';
            pl.default_x = false ;
            pt.picklistValues.add(pl);
        }
        customField.picklist = pt ;
        MetadataService.UpdateMetadata ut = new MetadataService.UpdateMetadata();
        ut.currentName = 'Deal__c.Other_Associates__c';
        ut.metadata= customField;
        if(!Test.isRunningTest()){
         MetadataService.AsyncResult[] results = service.updateMetadata(new List<MetadataService.updateMetadata> {ut});
        }
    }


public static MetadataService.MetadataPort createService(String sessionId)
    {
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = sessionId;
        return service;
    }

}