Jann 30/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Status_Date__c</fullName>
        <label>Current Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Target_Strategic_Analysis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Target Strategic Analysis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/Deal_Phase__c.object
<CustomObject>
    <description>where the Deal phase is kept</description>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Phases</relationshipLabel>
        <relationshipName>Deal_Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required_Attachments__c</fullName>
        <label>Required Attachments</label>
        <picklist>
            <controllingField>Phase__c</controllingField>
            <picklistValues>
                <fullName>Authorization to Investigate (ATI/A&amp;D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidentiality Agreement(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement Letters/SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFA for 3rd Party Due Diligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due Diligence Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Resolution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Definitive Agreements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Transaction Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Transaction Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Impairment Testing</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Deal Phase</label>
    <nameField>
        <displayFormat>DP-{00000}</displayFormat>
        <label>Deal Phase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/Deal_Phases__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Attachment__c</fullName>
        <label>Attachment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Field__c</fullName>
        <label>Deal Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Need_To_Set_Deal_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Need To Set Deal Field</label>
        <type>Checkbox</type>
    </fields>
    <label>Deal Phases</label>
</CustomObject>

Jann 30/classes/DealPhaseTriggerHandlerTest.cls
/***********************************************************************
Trigger Name  : DealPhaseTriggerHandlerTest
Created By   	: Kirti Agarwal
Created Date 	: 27th Nov,2013
Purpose      	: Test class for DealPhaseTriggerHandler
Task         	: T-215444
************************************************************************/
@isTest
private class DealPhaseTriggerHandlerTest {

    static testMethod void DealPhaseTriggerHandlerTest() {
       
       Deal_Phases__c rec = new Deal_Phases__c();
    	 rec.Attachment__c = 'Target Strategic Analysis';
    	 rec.Name = 'Target Strategic Analysis';
    	 rec.Deal_Field__c = 'Target_Strategic_Analysis__c';
    	 rec.Is_Need_To_Set_Deal_Field__c = true;
    	 insert rec;
    	 
    	 Deal__c deal = new Deal__c();
	     deal.Current_Status__c = 'test 1';
	     deal.Target__c = 'test';
	     deal.Close_Date__c = date.today().addDays(2);
	     deal.Current_Status_Date__c = date.today().addDays(1);
    	 insert deal;
    	 
    	 Deal_Phase__c dealPhase = new Deal_Phase__c();
    	 dealPhase.Deal__c = deal.id;
    	 dealPhase.Required_Attachments__c = 'Target Strategic Analysis';
    	 insert dealPhase;
    	 
    	 Deal__c dealRec = [SELECT id,Target_Strategic_Analysis__c 
    	 										FROM Deal__c 
    	 										WHERE id =: deal.id];
    											
    	 system.assertEquals(dealRec.Target_Strategic_Analysis__c, true);
    	 
    	 dealPhase.Required_Attachments__c = null;
    	 update dealPhase;
    	 
    	 dealRec = [SELECT id,Target_Strategic_Analysis__c 
 										FROM Deal__c 
 										WHERE id =: deal.id];
    											
    	 system.assertEquals(dealRec.Target_Strategic_Analysis__c, false);
    	 
    	  rec.Is_Need_To_Set_Deal_Field__c = false;
    	  update rec;
    	  
    	  dealPhase.Required_Attachments__c = 'Target Strategic Analysis';
    	  update dealPhase;
    	  system.assertEquals(dealRec.Target_Strategic_Analysis__c, false);
    }
    
   
}