Jann 30/objects/Deal__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/Deal_Phase__c.object
<CustomObject>
    <description>where the Deal phase is kept</description>
    <fields>
        <fullName>Deal__c</fullName>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Deal Phases</relationshipLabel>
        <relationshipName>Deal_Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required_Attachments__c</fullName>
        <label>Required Attachments</label>
        <picklist>
            <controllingField>Phase__c</controllingField>
            <picklistValues>
                <fullName>Authorization to Investigate (ATI/A&amp;D)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidentiality Agreement(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement Letters/SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFA for 3rd Party Due Diligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Due Diligence Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Resolution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Definitive Agreements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Transaction Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Transaction Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Impairment Testing</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Deal Phase</label>
    <nameField>
        <displayFormat>DP-{00000}</displayFormat>
        <label>Deal Phase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/Deal_Phases__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Attachment__c</fullName>
        <label>Attachment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal_Field__c</fullName>
        <label>Deal Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Need_To_Set_Deal_Field__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Need To Set Deal Field</label>
        <type>Checkbox</type>
    </fields>
    <label>Deal Phases</label>
</CustomObject>

Jann 30/classes/DealPhaseTriggerHandler.cls
/***********************************************************************
Trigger Name  : DealPhaseTriggerHandler
Created By   	: Kirti Agarwal
Created Date 	: 27th Nov,2013
Purpose      	: Update Deal record based on Deal Phase record
Task         	: T-215444
************************************************************************/
public class DealPhaseTriggerHandler {

/**
 * This method will be called after update or insert of deal phase record
 */
  public static void onAfterInsertUpdate(List<Deal_Phase__c> newDealPhaseList, map<id,Deal_Phase__c>oldMap) {
  		set<String> setOfDealId = new set<String>();
  		
  		for(Deal_Phase__c dealPhase : newDealPhaseList) {
  			if(dealPhase.Deal__c != null) {
  				setOfDealId.add(dealPhase.Deal__c);
  			}
  		}
  		
  		List<Deal_Phases__c> DealPhasesSetting = Deal_Phases__c.getall().values();
  		
  		map<id,Sobject> mapOfDeal = new map<id,Sobject>([SELECT id FROM Deal__c WHERE id IN: setOfDealId ]);
  		set<Sobject> setOfDeal = new set<Sobject>();
  		
  		for(Deal_Phase__c dealPhase : newDealPhaseList) {
  			if(oldMap == null || (dealPhase.Required_Attachments__c != oldMap.get(dealPhase.id).Required_Attachments__c)) {
	  			String AttachemntValue = dealPhase.Required_Attachments__c ;
	  			Sobject Deal = mapOfDeal.get(dealPhase.Deal__c);
	  			
	  			for(Deal_Phases__c setting : DealPhasesSetting) {  	
	  				Boolean isChecked;			 
	  				 if(AttachemntValue != null && AttachemntValue.contains(setting.Attachment__c)) {
	  				 	 if(setting.Is_Need_To_Set_Deal_Field__c) {
	  				 	 	 isChecked = true;
	  				 		 Deal.put(setting.Deal_Field__c, isChecked);
	  				 	
	  				 	 }else{
	  				 	 	 isChecked = false;
	  				 	 	 Deal.put(setting.Deal_Field__c, isChecked);
	  				 	 }
	  				 }
	  				 else{
	  				 	  isChecked = false; 
	  				 	 	Deal.put(setting.Deal_Field__c, isChecked);
	  				 }
	  			}
	  			setOfDeal.add(Deal);
  			}
  		}
  		
  		if(setOfDeal.size() > 0) {
  			List<Sobject> dealList = new List<Sobject>();
  			dealList.addAll(setOfDeal);
  			update dealList;
  		}	 		
  }
}