Jann 30/objects/DepartmentalSuperUser__c.object
<CustomObject>
    <description>Used to select max 5 users who will get read-only access to all IT-SES records of the logged-in user or user selected in requestor field.</description>
    <fields>
        <fullName>Additional_Access_1_Department__c</fullName>
        <formula>If( ISPICKVAL(Viewer1__r.ITPR_Department__c,&apos;ITSES - Requestor&apos;),&apos;ITSES - Requestor&apos;,
If( ISPICKVAL(Viewer1__r.ITPR_Department__c,&apos;ITSES - Legal&apos;),&apos;ITSES - Legal&apos;,
If( ISPICKVAL(Viewer1__r.ITPR_Department__c,&apos;ITSES - Finance&apos;),&apos;ITSES - Finance&apos;,
If( ISPICKVAL(Viewer1__r.ITPR_Department__c,&apos;ITSES - Procurement&apos;),&apos;ITSES - Procurement&apos;,
If( ISPICKVAL(Viewer1__r.ITPR_Department__c,&apos;ITSES - Vendor Governance&apos;),&apos;ITSES - Vendor Governance&apos;,
&apos;&apos;)
)
)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Additional Access 1 Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_Access_2_Department__c</fullName>
        <formula>If( ISPICKVAL(Viewer2__r.ITPR_Department__c,&apos;ITSES - Requestor&apos;),&apos;ITSES - Requestor&apos;, 
If( ISPICKVAL(Viewer2__r.ITPR_Department__c,&apos;ITSES - Legal&apos;),&apos;ITSES - Legal&apos;, 
If( ISPICKVAL(Viewer2__r.ITPR_Department__c,&apos;ITSES - Finance&apos;),&apos;ITSES - Finance&apos;, 
If( ISPICKVAL(Viewer2__r.ITPR_Department__c,&apos;ITSES - Procurement&apos;),&apos;ITSES - Procurement&apos;, 
If( ISPICKVAL(Viewer2__r.ITPR_Department__c,&apos;ITSES - Vendor Governance&apos;),&apos;ITSES - Vendor Governance&apos;, 
&apos;&apos;) 
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Additional Access 2 Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_Access_3_Department__c</fullName>
        <formula>If( ISPICKVAL(Viewer3__r.ITPR_Department__c,&apos;ITSES - Requestor&apos;),&apos;ITSES - Requestor&apos;, 
If( ISPICKVAL(Viewer3__r.ITPR_Department__c,&apos;ITSES - Legal&apos;),&apos;ITSES - Legal&apos;, 
If( ISPICKVAL(Viewer3__r.ITPR_Department__c,&apos;ITSES - Finance&apos;),&apos;ITSES - Finance&apos;, 
If( ISPICKVAL(Viewer3__r.ITPR_Department__c,&apos;ITSES - Procurement&apos;),&apos;ITSES - Procurement&apos;, 
If( ISPICKVAL(Viewer3__r.ITPR_Department__c,&apos;ITSES - Vendor Governance&apos;),&apos;ITSES - Vendor Governance&apos;, 
&apos;&apos;) 
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Additional Access 3 Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_Access_4_Department__c</fullName>
        <formula>If( ISPICKVAL(Viewer4__r.ITPR_Department__c,&apos;ITSES - Requestor&apos;),&apos;ITSES - Requestor&apos;, 
If( ISPICKVAL(Viewer4__r.ITPR_Department__c,&apos;ITSES - Legal&apos;),&apos;ITSES - Legal&apos;, 
If( ISPICKVAL(Viewer4__r.ITPR_Department__c,&apos;ITSES - Finance&apos;),&apos;ITSES - Finance&apos;, 
If( ISPICKVAL(Viewer4__r.ITPR_Department__c,&apos;ITSES - Procurement&apos;),&apos;ITSES - Procurement&apos;, 
If( ISPICKVAL(Viewer4__r.ITPR_Department__c,&apos;ITSES - Vendor Governance&apos;),&apos;ITSES - Vendor Governance&apos;, 
&apos;&apos;) 
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Additional Access 4 Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_Access_5_Department__c</fullName>
        <formula>If( ISPICKVAL(Viewer5__r.ITPR_Department__c,&apos;ITSES - Requestor&apos;),&apos;ITSES - Requestor&apos;, 
If( ISPICKVAL(Viewer5__r.ITPR_Department__c,&apos;ITSES - Legal&apos;),&apos;ITSES - Legal&apos;, 
If( ISPICKVAL(Viewer5__r.ITPR_Department__c,&apos;ITSES - Finance&apos;),&apos;ITSES - Finance&apos;, 
If( ISPICKVAL(Viewer5__r.ITPR_Department__c,&apos;ITSES - Procurement&apos;),&apos;ITSES - Procurement&apos;, 
If( ISPICKVAL(Viewer5__r.ITPR_Department__c,&apos;ITSES - Vendor Governance&apos;),&apos;ITSES - Vendor Governance&apos;, 
&apos;&apos;) 
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Additional Access 5 Department</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Access_1__c</fullName>
        <description>After selecting the user to know which type of user can allow to use</description>
        <inlineHelpText>Please select a value</inlineHelpText>
        <label>Type of Access 1</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Access_2__c</fullName>
        <label>Type of Access 2</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Access_3__c</fullName>
        <label>Type of Access 3</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Access_4__c</fullName>
        <label>Type of Access 4</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read_Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Access_5__c</fullName>
        <label>Type of Access 5</label>
        <picklist>
            <picklistValues>
                <fullName>Read Only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Viewer1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This user will have full read-only access to all requests created by the requestor</description>
        <inlineHelpText>Add a user here to have the type of access you select for each user, for all of your requests</inlineHelpText>
        <label>Additional Access 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Departmental_Super_Users_Viewer1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Viewer2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This user will have full read-only access to all requests created by the requestor</description>
        <inlineHelpText>Add a user here to have the type of access you select for each user, for all of your requests</inlineHelpText>
        <label>Additional Access 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Departmental_Super_Users_Viewer2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Viewer3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This user will have full read-only access to all requests created by the requestor</description>
        <inlineHelpText>Add a user here to have the type of access you select for each user, for all of your requests</inlineHelpText>
        <label>Additional Access 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Departmental_Super_Users_Viewer3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Viewer4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This user will have full read-only access to all requests created by the requestor</description>
        <inlineHelpText>Add a user here to have the type of access you select for each user, for all of your requests</inlineHelpText>
        <label>Additional Access 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Departmental_Super_Users_Viewer4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Viewer5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This user will have full read-only access to all requests created by the requestor</description>
        <inlineHelpText>Add a user here to have the type of access you select for each user, for all of your requests</inlineHelpText>
        <label>Additional Access 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Departmental_Super_Users_Viewer5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Departmental Super User</label>
    <nameField>
        <displayFormat>DSU-{00000}</displayFormat>
        <label>DepartmentalSuperUser ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departmental Super Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Finance_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7m</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Indicates where the request is in the process flow.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending More Info Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Project Final Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Digital Initials Obtained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reactivate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed and Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Executed and Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_Governance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Governance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU81</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/ITPR_DepartmentalSuperUsers_share.cls
/******************************************************************************************************************
*Class            : ITPR_DepartmentalSuperUsers_Share
*Author           : Capgemini
*Version History  : 1.0
*Creation         : 15/12/2014
*Assumptions      : N/A
*Description      : This class is used to share the IT-SES record of user in Requestor field with users selected in viewer fields.
******************************************************************************************************************/

public class ITPR_DepartmentalSuperUsers_share
{
    /********* Initialisation of variables *************/
    //List to add new ITPR__Share objects
    List<ITPR__Share> lstITPRShare = new List<ITPR__Share>();
    Map<Id, ITPR__Share> maptemp = new Map<Id, ITPR__Share>();
    ITPR__Share ITPRshare1;
    ITPR__Share ITPRshare2;
    ITPR__Share ITPRshare3;
    ITPR__Share ITPRshare4;
    ITPR__Share ITPRshare5;
    /********* End of Initialisation of variables ******/
    
    public List<ITPR__Share> DSU_ITPR_Share(ITPR__c ITPR)
    {
        
        if(ITPR != null)
        {
            System.debug('In DSU_ITPR_Share...');
            list<id>assigneeuserslist=new list<id>();
            if(ITPR.CreatedById !=null)     
            assigneeuserslist.add(ITPR.CreatedById);
            system.debug('Createdby'+ITPR.CreatedById);  
            if(ITPR.Procurement_Assignee__c !=null)
            assigneeuserslist.add(ITPR.Procurement_Assignee__c);
            system.debug('Procurment Assignee'+ ITPR.Procurement_Assignee__c);
            if(ITPR.Legal_Assignee__c !=null)       
            assigneeuserslist.add(ITPR.Legal_Assignee__c);
            system.debug('Legal Assignee'+ ITPR.Legal_Assignee__c);
            if(ITPR.Finance_Assignee__c !=null)     
            assigneeuserslist.add(ITPR.Finance_Assignee__c);
            system.debug('Finance Assignee'+ ITPR.Finance_Assignee__c);
            if(ITPR.Vendor_Governance__c!=null)     
            assigneeuserslist.add(ITPR.Vendor_Governance__c);
            system.debug('VG Assignee'+ ITPR.Vendor_Governance__c);
            system.debug('assigneeuserslist'+assigneeuserslist);
            //Query All related Departmental Super user records
            list<DepartmentalSuperUser__c>dsulist=[select id,Viewer1__c,Viewer2__c,Viewer3__c,Viewer4__c,Viewer5__c,Type_of_Access_1__c,Type_of_Access_2__c,Type_of_Access_3__c,Type_of_Access_4__c,Type_of_Access_5__c,Additional_Access_1_Department__c,Additional_Access_2_Department__c,Additional_Access_3_Department__c,Additional_Access_4_Department__c,Additional_Access_5_Department__c from DepartmentalSuperUser__c where OwnerId in:assigneeuserslist];
            system.debug('dsulist...'+dsulist.isEmpty());
            for (DepartmentalSuperUser__c DSU :dsulist)
            {
                System.debug('Inside DSU_ITPR_Share....');
                if(DSU.Viewer1__c != null)
            {
        
                ITPRshare1 = new ITPR__Share();                    
                
                ITPRshare1.ParentId = ITPR.Id;
                ITPRshare1.UserOrGroupId = DSU.Viewer1__c;
                ITPRshare1.AccessLevel = 'Read';
                // If Type of Access Defined as Read/Edit then check
                system.debug('xxxx'+DSU.Type_of_Access_1__c +'zzzz'+DSU.Viewer1__c + 'yyy'+DSU.Additional_Access_1_Department__c);
                If(DSU.Type_of_Access_1__c == 'Read/Edit')
                {
                  If(ITPR.Status__c == 'Draft')   
                { 
                  if (DSU.Additional_Access_1_Department__c == 'ITSES - Requestor'){
                       ITPRshare1.AccessLevel = 'Edit';
                       
                 }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Procurement')
                  {
                      ITPRshare1.AccessLevel = 'Read';
                       
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare1.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }
               } else if(ITPR.Status__c == 'Submitted' || ITPR.Status__c == 'Assigned')
                  {
                   if (DSU.Additional_Access_1_Department__c == 'ITSES - Requestor'){
                      ITPRshare1.AccessLevel = 'Read';
                       
                } else if(DSU.Additional_Access_1_Department__c == 'ITSES - Finance')
                  {
                      ITPRshare1.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare1.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare1.AccessLevel = 'Edit';
                      
                  } else if(DSU.Additional_Access_1_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare1.AccessLevel = 'Edit';
                      
                  }
               }else if(ITPR.Status__c == 'In Process' ){
                   if (DSU.Additional_Access_1_Department__c == 'ITSES - Requestor'){
                     ITPRshare1.AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Finance')
                  {
                    ITPRshare1.AccessLevel = 'Edit';
                     
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare1.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare1.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare1.AccessLevel = 'Edit';
                      
                  }
               }else if((ITPR.Status__c == 'Pending Project Final Budget') || (ITPR.Status__c == 'Pending More Info Needed' )){
                   if (DSU.Additional_Access_1_Department__c == 'ITSES - Requestor'){
                  ITPRshare1.AccessLevel = 'Edit';
                   
                 }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }
               }                
                  
                  else if(ITPR.Status__c == 'In Approvals' ){
                  system.debug('InApprovals');
                  if (DSU.Additional_Access_1_Department__c == 'ITSES - Requestor'){
                      
                      ITPRshare1.AccessLevel = 'Read';
                       
                 }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Finance')
                  {  
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Legal')
                  {  
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Vendor Governance')
                  {  
                      
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'All Digital Initials Obtained' ){
                   if(DSU.Additional_Access_1_Department__c =='ITSES - Requestor'){
                     ITPRshare1.AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare1.AccessLevel = 'Edit';
                      
                  }
               }  else if((ITPR.Status__c == 'Cancelled') || (ITPR.Status__c == 'On Hold') || (ITPR.Status__c == 'Complete') || (ITPR.Status__c == 'Executed and Filed') || (ITPR.Status__c == 'Not Executed and Closed')){
                   if (DSU.Additional_Access_1_Department__c == 'ITSES - Requestor'){
                       ITPRshare1.AccessLevel = 'Read';
                        
                 }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Finance')
                  {    
                     ITPRshare1.AccessLevel = 'Read';
                      
                  } else if(DSU.Additional_Access_1_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_1_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare1.AccessLevel = 'Read';
                      
                  }
              }                       
            }
                
                ITPRshare1.RowCause = Schema.ITPR__Share.RowCause.Departmental_User_Sharing__c;
                //lstITPRShare.add(ITPRshare1);
                maptemp.put(ITPRshare1.UserOrGroupId,ITPRshare1);
            }
                
            if(DSU.Viewer2__c != null)
            {
                ITPRshare2 = new ITPR__Share();
                
                ITPRshare2.ParentId = ITPR.Id;
                ITPRshare2.UserOrGroupId = DSU.Viewer2__c;
                ITPRshare2.AccessLevel = 'Read';
           // If Type of Access Defined as Read/Edit then check     
                If(DSU.Type_of_Access_2__c == 'Read/Edit')
                {
                  If(ITPR.Status__c == 'Draft')   
                { 
                  if (DSU.Additional_Access_2_Department__c == 'ITSES - Requestor'){
                       ITPRshare2.AccessLevel = 'Edit';
                       
                 }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Procurement')
                  {
                      ITPRshare2.AccessLevel = 'Read';
                       
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare2.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }
               } else if(ITPR.Status__c == 'Submitted' || ITPR.Status__c == 'Assigned')
                  {
                   if (DSU.Additional_Access_2_Department__c == 'ITSES - Requestor'){
                      ITPRshare2.AccessLevel = 'Read';
                       
                } else if(DSU.Additional_Access_2_Department__c == 'ITSES - Finance')
                  {
                      ITPRshare2.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare2.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare2.AccessLevel = 'Edit';
                      
                  } else if(DSU.Additional_Access_2_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare2.AccessLevel = 'Edit';
                      
                  }
               }else if(ITPR.Status__c == 'In Process' ){
                   if (DSU.Additional_Access_2_Department__c == 'ITSES - Requestor'){
                     ITPRshare2.AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Finance')
                  {
                    ITPRshare2.AccessLevel = 'Edit';
                     
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare2.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare2.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare2.AccessLevel = 'Edit';
                      
                  }
               }else if((ITPR.Status__c == 'Pending Project Final Budget') || (ITPR.Status__c == 'Pending More Info Needed' )){
                   if (DSU.Additional_Access_2_Department__c == 'ITSES - Requestor'){
                  ITPRshare2.AccessLevel = 'Edit';
                   
                 }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'In Approvals' ){
                  if (DSU.Additional_Access_2_Department__c == 'ITSES - Requestor'){
                      ITPRshare2.AccessLevel = 'Read';
                       
                 }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'All Digital Initials Obtained' ){
                   if (DSU.Additional_Access_2_Department__c =='ITSES - Requestor'){
                     ITPRshare2.AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare2.AccessLevel = 'Edit';
                      
                  }
               }  else if((ITPR.Status__c == 'Cancelled') || (ITPR.Status__c == 'On Hold') || (ITPR.Status__c == 'Complete') || (ITPR.Status__c == 'Executed and Filed') || (ITPR.Status__c == 'Not Executed and Closed')){
                   if (DSU.Additional_Access_2_Department__c == 'ITSES - Requestor'){
                       ITPRshare2.AccessLevel = 'Read';
                        
                 }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Finance')
                  {    
                     ITPRshare2.AccessLevel = 'Read';
                      
                  } else if(DSU.Additional_Access_2_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_2_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare2.AccessLevel = 'Read';
                      
                  }
              }                       
            }                  
                ITPRshare2.RowCause = Schema.ITPR__Share.RowCause.Departmental_User_Sharing__c;
                //lstITPRShare.add(ITPRshare2);
                maptemp.put(ITPRshare2.UserOrGroupId,ITPRshare2);
            }
            
            if(DSU.Viewer3__c != null)
            {
                ITPRshare3 = new ITPR__Share();
                
                ITPRshare3.ParentId = ITPR.Id;
                ITPRshare3.UserOrGroupId = DSU.Viewer3__c;
                ITPRshare3.AccessLevel = 'Read';
                // If Type of Access Defined as Read/Edit then check
                If(DSU.Type_of_Access_3__c == 'Read/Edit')
                 {
                  If(ITPR.Status__c == 'Draft')   //If(DSU.Type_of_Access_4__c == 'Read/Edit')
                { 
                  if (DSU.Additional_Access_3_Department__c == 'ITSES - Requestor'){
                       ITPRshare3.AccessLevel = 'Edit';
                       
                 }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Procurement')
                  {
                      ITPRshare3.AccessLevel = 'Read';
                       
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare3.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }
               } else if(ITPR.Status__c == 'Submitted' || ITPR.Status__c == 'Assigned')
                  {
                   if (DSU.Additional_Access_3_Department__c == 'ITSES - Requestor'){
                      ITPRshare3.AccessLevel = 'Read';
                       
                } else if(DSU.Additional_Access_3_Department__c == 'ITSES - Finance')
                  {
                      ITPRshare3.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare3.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare3.AccessLevel = 'Edit';
                      
                  } else if(DSU.Additional_Access_3_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare3.AccessLevel = 'Edit';
                      
                  }
               }else if(ITPR.Status__c == 'In Process' ){
                   if (DSU.Additional_Access_3_Department__c == 'ITSES - Requestor'){
                     ITPRshare3.AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Finance')
                  {
                    ITPRshare3.AccessLevel = 'Edit';
                     
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare3.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare3.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare3.AccessLevel = 'Edit';
                      
                  }
               }else if((ITPR.Status__c == 'Pending Project Final Budget') || (ITPR.Status__c == 'Pending More Info Needed' )){
                   if (DSU.Additional_Access_3_Department__c == 'ITSES - Requestor'){
                  ITPRshare3.AccessLevel = 'Edit';
                   
                 }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'In Approvals' ){
                  if (DSU.Additional_Access_3_Department__c == 'ITSES - Requestor'){
                      ITPRshare3.AccessLevel = 'Read';
                       
                 }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'All Digital Initials Obtained' ){
                   if (DSU.Additional_Access_3_Department__c =='ITSES - Requestor'){
                     ITPRshare3.AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare3.AccessLevel = 'Edit';
                      
                  }
               }  else if((ITPR.Status__c == 'Cancelled') || (ITPR.Status__c == 'On Hold') || (ITPR.Status__c == 'Complete') || (ITPR.Status__c == 'Executed and Filed') || (ITPR.Status__c == 'Not Executed and Closed')){
                   if (DSU.Additional_Access_3_Department__c == 'ITSES - Requestor'){
                       ITPRshare3.AccessLevel = 'Read';
                        
                 }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Finance')
                  {    
                     ITPRshare3.AccessLevel = 'Read';
                      
                  } else if(DSU.Additional_Access_3_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_3_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare3.AccessLevel = 'Read';
                      
                  }
              }                       
            }
               ITPRshare3.RowCause = Schema.ITPR__Share.RowCause.Departmental_User_Sharing__c;
                //lstITPRShare.add(ITPRshare3);
                maptemp.put(ITPRshare3.UserOrGroupId,ITPRshare3);
            }
            
            if(DSU.Viewer4__c != null)
            {
                ITPRshare4 = new ITPR__Share();
                
                ITPRshare4.ParentId = ITPR.Id;
                ITPRshare4.UserOrGroupId = DSU.Viewer4__c;                                       
                ITPRshare4.AccessLevel = 'Read';
                // If Type of Access Defined as Read/Edit then check
                If(DSU.Type_of_Access_4__c == 'Read/Edit')
                {
                  If(ITPR.Status__c == 'Draft')  
                { 
                  if (DSU.Additional_Access_4_Department__c == 'ITSES - Requestor'){
                       ITPRshare4.AccessLevel = 'Edit';
                       
                 }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Procurement')
                  {
                      ITPRshare4.AccessLevel = 'Read';
                       
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare4.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }
               } else if(ITPR.Status__c == 'Submitted' || ITPR.Status__c == 'Assigned')
                  {
                   if (DSU.Additional_Access_4_Department__c == 'ITSES - Requestor'){
                      ITPRshare4.AccessLevel = 'Read';
                       
                } else if(DSU.Additional_Access_4_Department__c == 'ITSES - Finance')
                  {
                      ITPRshare4.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare4.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare4.AccessLevel = 'Edit';
                      
                  } else if(DSU.Additional_Access_4_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare4.AccessLevel = 'Edit';
                      
                  }
               }else if(ITPR.Status__c == 'In Process' ){
                   if (DSU.Additional_Access_4_Department__c == 'ITSES - Requestor'){
                     ITPRshare4.AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Finance')
                  {
                    ITPRshare4.AccessLevel = 'Edit';
                     
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare4.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare4.AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare4.AccessLevel = 'Edit';
                      
                  }
               }else if((ITPR.Status__c == 'Pending Project Final Budget') || (ITPR.Status__c == 'Pending More Info Needed' )){
                   if (DSU.Additional_Access_4_Department__c == 'ITSES - Requestor'){
                  ITPRshare4.AccessLevel = 'Edit';
                   
                 }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'In Approvals' ){
                  if (DSU.Additional_Access_4_Department__c == 'ITSES - Requestor'){
                      ITPRshare4.AccessLevel = 'Read';
                       
                 }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'All Digital Initials Obtained' ){
                   if (DSU.Additional_Access_4_Department__c =='ITSES - Requestor'){
                     ITPRshare4.AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare4.AccessLevel = 'Edit';
                      
                  }
               }  else if((ITPR.Status__c == 'Cancelled') || (ITPR.Status__c == 'On Hold') || (ITPR.Status__c == 'Complete') || (ITPR.Status__c == 'Executed and Filed') || (ITPR.Status__c == 'Not Executed and Closed')){
                   if (DSU.Additional_Access_4_Department__c == 'ITSES - Requestor'){
                       ITPRshare4.AccessLevel = 'Read';
                        
                 }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Finance')
                  {    
                     ITPRshare4.AccessLevel = 'Read';
                      
                  } else if(DSU.Additional_Access_4_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_4_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare4.AccessLevel = 'Read';
                      
                  }
              }                       
            }
                ITPRshare4.RowCause = Schema.ITPR__Share.RowCause.Departmental_User_Sharing__c;
                //lstITPRShare.add(ITPRshare4);
                maptemp.put(ITPRshare4.UserOrGroupId,ITPRshare4);
           } 
            
            if(DSU.Viewer5__c != null)
            {
                ITPRshare5 = new ITPR__Share();
                
                ITPRshare5.ParentId = ITPR.Id;
                ITPRshare5.UserOrGroupId = DSU.Viewer5__c;
                ITPRshare5.AccessLevel = 'Read';
                // If Type of Access Defined as Read/Edit then check
                If(DSU.Type_of_Access_5__c == 'Read/Edit')
                {
                  If(ITPR.Status__c == 'Draft')   
                { 
                  if (DSU.Additional_Access_5_Department__c == 'ITSES - Requestor'){
                       ITPRshare5 .AccessLevel = 'Edit';
                       
                 }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Procurement')
                  {
                      ITPRshare5 .AccessLevel = 'Read';
                       
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare5 .AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }
               } else if(ITPR.Status__c == 'Submitted' || ITPR.Status__c == 'Assigned')
                  {
                   if (DSU.Additional_Access_5_Department__c == 'ITSES - Requestor'){
                      ITPRshare5 .AccessLevel = 'Read';
                       
                } else if(DSU.Additional_Access_5_Department__c == 'ITSES - Finance')
                  {
                      ITPRshare5 .AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare5 .AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare5 .AccessLevel = 'Edit';
                      
                  } else if(DSU.Additional_Access_5_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare5 .AccessLevel = 'Edit';
                      
                  }
               }else if(ITPR.Status__c == 'In Process' ){
                   if (DSU.Additional_Access_5_Department__c == 'ITSES - Requestor'){
                     ITPRshare5 .AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Finance')
                  {
                    ITPRshare5 .AccessLevel = 'Edit';
                     
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare5 .AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare5 .AccessLevel = 'Edit';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare5 .AccessLevel = 'Edit';
                      
                  }
               }else if((ITPR.Status__c == 'Pending Project Final Budget') || (ITPR.Status__c == 'Pending More Info Needed' )){
                   if (DSU.Additional_Access_5_Department__c == 'ITSES - Requestor'){
                  ITPRshare5 .AccessLevel = 'Edit';
                   
                 }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Finance')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'In Approvals' ){
                  if (DSU.Additional_Access_5_Department__c == 'ITSES - Requestor'){
                      ITPRshare5 .AccessLevel = 'Read';
                       
                 }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }
               }  else if(ITPR.Status__c == 'All Digital Initials Obtained' ){
                   if (DSU.Additional_Access_5_Department__c =='ITSES - Requestor'){
                     ITPRshare5 .AccessLevel = 'Read';
                      
                 }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Finance')
                  {
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare5 .AccessLevel = 'Edit';
                      
                  }
               }  else if((ITPR.Status__c == 'Cancelled') || (ITPR.Status__c == 'On Hold') || (ITPR.Status__c == 'Complete') || (ITPR.Status__c == 'Executed and Filed') || (ITPR.Status__c == 'Not Executed and Closed')){
                   System.debug('test..ITPR status'+ITPR.Status__c);
                   if (DSU.Additional_Access_5_Department__c == 'ITSES - Requestor'){
                       ITPRshare5 .AccessLevel = 'Read';
                        
                 }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Finance')
                  {    
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  } else if(DSU.Additional_Access_5_Department__c == 'ITSES - Procurement')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Legal')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }else if(DSU.Additional_Access_5_Department__c == 'ITSES - Vendor Governance')
                  { 
                     ITPRshare5 .AccessLevel = 'Read';
                      
                  }
              }                       
            }                 
                ITPRshare5.RowCause = Schema.ITPR__Share.RowCause.Departmental_User_Sharing__c;
                //lstITPRShare.add(ITPRshare5);
                maptemp.put(ITPRshare5.UserOrGroupId,ITPRshare5);
            }
            
            
            }
       }

        for(Id key : maptemp.keyset())
           {
               lstITPRShare.add(maptemp.get(key));
           }
        system.debug('lstITPRShare'+lstITPRShare);
        return lstITPRShare;
    }
}