Jann 30/objects/GS1_Country__c.object
<CustomObject>
    <label>GS1 Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GS1 Countries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/GS1_EAN__c.object
<CustomObject>
    <label>GS1 Barcode</label>
    <nameField>
        <label>Barcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GS1 Barcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/GS1_Request__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>GS1_Country__c</referenceTo>
        <relationshipLabel>Requests for this Country</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EAN_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Barcode</label>
        <referenceTo>GS1_EAN__c</referenceTo>
        <relationshipLabel>Requests Using this barcode</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GS1 Request</label>
    <nameField>
        <displayFormat>REQ-{YYYYMM}-{0000000000}</displayFormat>
        <label>Request Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GS1 Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/GS1_TestRequestCSVReport.cls
@isTest
private class GS1_TestRequestCSVReport {

    static testMethod void test1() {
        Test.startTest();
        User me = [select id from User where Id=:System.userInfo.getUserId()];
        System.runAs(me){          
            GS1_RequestCSVReport clas = new GS1_RequestCSVReport();
            
            GS1_EAN__c ean = GS1_TestHelper.createBarcodes(true, true, 1122331, 1122331)[0];
            GS1_Request__c[] reqs = GS1_TestHelper.createRequest(10, GS1_TestHelper.REQUEST_CUDU);
            GS1_Country__c ctry = GS1_TestHelper.createCountry(1)[0];
            ctry.Name = 'BELGIUM';
            update ctry;
            
            for(GS1_Request__c req : reqs) {
                req.Country__c = ctry.id;
                req.EAN_Code__c = ean.Id;
            }
            
            update reqs;
            
            clas.execute(null);
        }    
        Test.stopTest();
    }
}