Jann 30/objects/GS1_EAN__c.object
<CustomObject>
    <label>GS1 Barcode</label>
    <nameField>
        <label>Barcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GS1 Barcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/GS1_Request__c.object
<CustomObject>
    <fields>
        <fullName>BBN__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>BBN</label>
        <referenceTo>GS1_BBN__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Capacity</label>
        <referenceTo>GS1_Unit_Capacity__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>GS1_Country__c</referenceTo>
        <relationshipLabel>Requests for this Country</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Design</label>
        <referenceTo>GS1_Design__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EAN_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Barcode</label>
        <referenceTo>GS1_EAN__c</referenceTo>
        <relationshipLabel>Requests Using this barcode</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flavour__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flavour</label>
        <referenceTo>GS1_Flavour__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>GS1_Material__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Multipack__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Multipack</label>
        <referenceTo>GS1_Multipack__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Packs_Case__c</fullName>
        <label>Packs/Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pallet_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pallet Design</label>
        <referenceTo>GS1_Pallet_Design__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pallet_Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pallet Material</label>
        <referenceTo>GS1_Pallet_Material__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Amount__c</fullName>
        <label>Amount (ex. 5 or 3.23)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promo_Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promo Currency</label>
        <referenceTo>GS1_Currency__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Other__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Other</label>
        <referenceTo>GS1_Promo_Other__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Quantity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Type &apos;*free*&apos; to show all items with free</inlineHelpText>
        <label>Additional Free Product</label>
        <referenceTo>GS1_Promo_Free_Product__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedByUserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RequestedByUserId (Hidden)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GS1_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trademark__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trademark</label>
        <referenceTo>GS1_Trademark__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>GS1_Unit__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units_Pack__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Units/Pack</label>
        <referenceTo>GS1_Multipack_Value__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GS1 Request</label>
    <nameField>
        <displayFormat>REQ-{YYYYMM}-{0000000000}</displayFormat>
        <label>Request Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GS1 Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/GS1_TestRequestCtrl.cls
/**
* Author,email :     Madel Pascua , mpascua@coca-cola.com
* Date Create  :     September 26, 2013
* Description  :     Test method for GS1_RequestCtrl
*
* REVISION HISTORY
*
* Author,email :
* Date Revised :
* Description  :
*
**/

@isTest //(SeeAllData=true)
private class GS1_TestRequestCtrl{ 
    static testMethod void successfulTest(){    
        Test.startTest();
        User me = [select id from User where Id=:System.userInfo.getUserId()];
        System.runAs(me){        
            GS1_EAN__c ean = GS1_TestHelper.createBarcodes(true, true, 1000000, 1000000)[0];    
            List<GS1_Request__c>  gs1ListTest = GS1_TestHelper.createRequest(1, GS1_TestHelper.REQUEST_CUDU);
            GS1_Request__c req = new GS1_Request__c();
            req.RecordTypeId = gs1ListTest[0].RecordTypeId;
            req.Country__c = gs1ListTest[0].Country__c;
            req.Trademark__c = gs1ListTest[0].trademark__c;
            req.Flavour__c = gs1ListTest[0].Flavour__c;
            req.Unit__c = gs1ListTest[0].Unit__c;
            req.Capacity__c = gs1ListTest[0].Capacity__c;
            req.BBN__c = gs1ListTest[0].BBN__c;
            req.Multipack__c = gs1ListTest[0].Multipack__c; 
            req.Units_Pack__c = gs1ListTest[0].Units_Pack__c;
            req.Packs_Case__c = 10;
            req.Material__c = gs1ListTest[0].Material__c;
            req.design__c = gs1ListTest[0].design__c;       
            req.Pallet_Material__c = gs1ListTest[0].Pallet_Material__c;
            req.Pallet_Design__c = gs1ListTest[0].Pallet_Design__c;
            req.Promo_Other__c = gs1ListTest[0].Promo_Other__c;       
            req.Promo_Amount__c = gs1ListTest[0].Promo_Amount__c;
            req.Promo_Currency__c = gs1ListTest[0].Promo_Currency__c;
            req.Promo_Quantity__c = gs1ListTest[0].Promo_Quantity__c;
            req.RequestedByUserId__c = system.Userinfo.getUserId();       
            req.EAN_Code__c = ean.id;
            insert req;      
          
            Pagereference pg = Page.GS1_Product_ViewMode;    
            Test.setCurrentPage(pg);    
            ApexPages.StandardController sc = new ApexPages.StandardController(gs1ListTest[0]);    
            GS1_RequestCtrl controller = new GS1_RequestCtrl(sc);
          
            controller.getSimilarRequests();
            controller.getCancelRequest();
            controller.getDialogTextError();
            controller.getDialogTextInformation();
            controller.getDialogTextWarning();
            controller.getHideAllocateEAN();
            controller.getHideCreateNewCopy();
            controller.getHideEdit();
            controller.getHideReactivate();
            controller.getHideShortLongAlloc();
            controller.getHideSubmit();
            controller.getHideWithdraw();
        }
        Test.stopTest();    
    }     
}