Jann 30/objects/GS1_BBN__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>BBN Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flavour__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flavour</label>
        <referenceTo>GS1_Flavour__c</referenceTo>
        <relationshipLabel>BBNs</relationshipLabel>
        <relationshipName>BBN_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trademark__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trademark</label>
        <referenceTo>GS1_Trademark__c</referenceTo>
        <relationshipLabel>BBNs</relationshipLabel>
        <relationshipName>BBN_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GS1 BBN</label>
    <nameField>
        <label>BBN Formula</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GS1 BBNs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/GS1_Request__c.object
<CustomObject>
    <fields>
        <fullName>BBN__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>BBN</label>
        <referenceTo>GS1_BBN__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Capacity</label>
        <referenceTo>GS1_Unit_Capacity__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count_per_Pallet__c</fullName>
        <label>Nr. Multipack or DU / Pallet</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>GS1_Country__c</referenceTo>
        <relationshipLabel>Requests for this Country</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Design</label>
        <referenceTo>GS1_Design__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EAN_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Barcode</label>
        <referenceTo>GS1_EAN__c</referenceTo>
        <relationshipLabel>Requests Using this barcode</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flavour__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Flavour</label>
        <referenceTo>GS1_Flavour__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Long_Short__c</fullName>
        <label>Long/Short</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Material</label>
        <referenceTo>GS1_Material__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Multipack_Type__c</fullName>
        <formula>IF (ISPICKVAL(Multipack__r.UnitType__c,&quot;C&quot;),&quot;Consumer Unit&quot;,
IF (ISPICKVAL(Multipack__r.UnitType__c,&quot;D&quot;),&quot;Despatch Unit&quot;, null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Multipack Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Multipack__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Multipack</label>
        <referenceTo>GS1_Multipack__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Layers__c</fullName>
        <label>Nr. Layers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packs_Case__c</fullName>
        <label>Packs/Case</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pallet_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pallet Design</label>
        <referenceTo>GS1_Pallet_Design__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pallet_Material__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pallet Material</label>
        <referenceTo>GS1_Pallet_Material__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <defaultValue>IF (
CONTAINS($RecordType.Name , &quot;Pallet&quot;), &quot;Pallet&quot;,
IF (CONTAINS($RecordType.Name , &quot;CU/DU&quot;), &quot;CU/DU&quot;, null))</defaultValue>
        <label>Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promo_Amount__c</fullName>
        <label>Amount (ex. 5 or 3.23)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promo_Currency__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Promo Currency</label>
        <referenceTo>GS1_Currency__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Other__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Other</label>
        <referenceTo>GS1_Promo_Other__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Quantity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Type &apos;*free*&apos; to show all items with free</inlineHelpText>
        <label>Additional Free Product</label>
        <referenceTo>GS1_Promo_Free_Product__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotion_type__c</fullName>
        <defaultValue>IF(CONTAINS( $RecordType.Name , &quot;Amount&quot;), &quot;Amount&quot;,
IF(CONTAINS( $RecordType.Name , &quot;Quantity&quot;), &quot;Quantity&quot;,
IF(CONTAINS( $RecordType.Name , &quot;Other&quot;), &quot;Other&quot;,
NULL)))</defaultValue>
        <label>Promotion type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <defaultValue>IF (CONTAINS($RecordType.Name , &quot;Normal&quot;), &quot;Normal&quot;, &quot;Promotion&quot;)</defaultValue>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;New&quot;</defaultValue>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trademark__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trademark</label>
        <referenceTo>GS1_Trademark__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Unit</label>
        <referenceTo>GS1_Unit__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Units_Pack__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Units/Pack</label>
        <referenceTo>GS1_Multipack_Value__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GS1 Request</label>
    <nameField>
        <displayFormat>REQ-{YYYYMM}-{0000000000}</displayFormat>
        <label>Request Ref #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GS1 Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/GS1_RequestCtrl.cls
/*
*
* Author,email :     Aldrin Rasdas , arasdas@coca-cola.com
* Date Create  :     Sept 5, 2013
* Description  :     A (controller) class used to manipulate request view mode entities (i.e. buttons hide-when)
*
* REVISION HISTORY
*
* Author,email :
* Date Revised :
* Description  :
*
*
*
*/
public with sharing class GS1_RequestCtrl {
    Id requestId = null;
    GS1_Request__c req = null;
    GS1_RequestAttribute ra = null;
    public GS1_RequestCtrl(ApexPages.StandardController controller) {
        this.requestId = controller.getRecord().id;
        //this.req = [select id, status__c, EAN_Code__c, Product_Type__c from GS1_Request__c where id=:this.requestId limit 1];
        this.req = [select id, Country__c, Flavour__c, Long_Short__c, Request_type__c, Design__c, Promotion_type__c, Promo_Quantity__c, Product_Type__c, Promo_Amount__c, Promo_Other__c, Promo_Currency__c, EAN_Code__c, BBN__c, BBN__r.code__c, Status__c, Packs_Case__c, Material__c, Capacity__c, Units_Pack__c, Unit__c, Trademark__c, Multipack__c, Multipack_Type__c,Pallet_Material__c, Pallet_Design__c, Number_of_Layers__c, Count_per_Pallet__c from GS1_Request__c where id=:this.requestId limit 1];
        ra = new GS1_RequestAttribute (this.req);
    }    
    
    public List<GS1_Request__c>getSimilarRequests() {
        GS1_Request__c[] reqs = GS1_AppWebHelperJSCtrl.findSameRequests(this.req);
        if ( !(reqs.size()>0)) {
            reqs = null;
        } 
        return reqs; 
    }
    
    public string getDialogTextWarning() {
        return GS1_Constants.DIALOG_TITLE_WARN;
    }
    
    public string getDialogTextInformation() {
        return GS1_Constants.DIALOG_TITLE_INFO;
    }
    
    public string getDialogTextError() {
        return GS1_Constants.DIALOG_TITLE_ERROR;
    }        
    
    public boolean getHideSubmit() {
        return !ra.userCanSubmit;
    }
        
    public boolean getHideAllocateEAN() {
        return !ra.userCanAllocateEAN;
    }

    public boolean getHideWithdraw() {
        return !ra.userCanWithdraw;
    }   
    
    public boolean getHideReactivate() {
        return !ra.userCanReactivate;
    } 
    
    public boolean getHideCreateNewCopy() {
        return !ra.userCanCreateCopy;       
    }
    
    public boolean getHideEdit() {
        return !ra.userCanEdit;
    }
    
    public boolean getHideShortLongAlloc() {
        return !ra.userCanAllocateShortLong;
    }
    
    public boolean getCancelRequest() {
        return !ra.userCanCancel;
    }
}