Jann 30/objects/IntermediaterfaAutoAppvr__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IntermediaterfaAutoAppvrs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExistingOne__c</fullName>
        <label>ExistingOne</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manual_Automated__c</fullName>
        <label>Manual/Automated</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleType__c</fullName>
        <label>RoleType</label>
        <picklist>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Creator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Point of Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IntermediaterfaAutoAppvr</label>
    <nameField>
        <label>intermediaterfaAutoAppvrs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IntermediaterfaAutoAppvrs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterCOAGroupJunctionobject__c.object
<CustomObject>
    <fields>
        <fullName>Profit_Center_Number__c</fullName>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipName>ProfitCenterCOAGroupJunctionobjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RFA_COA_Group_Name__c</fullName>
        <label>RFA COA Group Name</label>
        <referenceTo>RFA_COA_Group__c</referenceTo>
        <relationshipName>ProfitCenterCOAGroupJunctionobjects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ProfitCenter COAGroup</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>ProfitCenterCOAGroup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitCenter COAGroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFA_Approver__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserRole__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA_COA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA COA Group</label>
        <referenceTo>RFA_COA_Group__c</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserName</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <label>UserRole</label>
        <picklist>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Creator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Point of Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA Approver_old</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>RFA Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFA_Business_Unit__c.object
<CustomObject>
    <description>Stores all Business Units within the RFA Application.</description>
    <label>RFA Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFA Business Units</pluralLabel>
    <recordTypes>
        <fullName>CCNA</fullName>
        <active>true</active>
        <label>CCNA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFA_COA_Group__c.object
<CustomObject>
    <description>RFA object which is used for determining the automated list of approvers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DOA_Category__c</fullName>
        <label>DOA Category</label>
        <picklist>
            <picklistValues>
                <fullName>1.A.1 Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.a Capital Expenditures - Unbudgeted CPR or SPR Covered by Budget Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.b Capital Expenditures - Unbudgeted CPR or SPR Funded Partially or Fully from Corporate Reserve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.3 Capital Expenditures - Increase or Scope Change to Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.4 Capital Expenditures - Transfer of Capital Budget across Groups for a Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.5 Capital Expenditures - Foreign Exchange Fluctuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.8 Capital Expenditures - Advance Appropriations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.B Capital Expenditures - Capability and Performance Programs (CAPPrs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.C Capital Expenditures - Bottles and Cases, Including Overages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. IT Investments and Website Presence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.A Real Property - Acquisitions and Sales or Other Disposals of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.B Real Property - Donations of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.C Real Property - Condemnations or Easements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.A Leases - Operating Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.B Leases - Capital Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.A Inventory Adjustments and Disposals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.B Other Asset Impairments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.C Asset Transfers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.D Asset Disposals (Tangible Assets excluding Real Property and Inventory)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.A Treasury - Banking Information Reports (BIR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.B Treasury - External Borrowings and Lines of Credit (RFFs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.C Treasury - Intercompany Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.D Treasury - Loans Third Parties (Including CCFC Target Loan Programs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.1 Treasury - Guarantees to Third Parties - General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.2 Treasury - Guarantees Related to Tax Disputes or Other Matters Involving Governmental Bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.F Treasury - Comfort Letters and Other Financial Security Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.G Treasury - Accommodation Purchases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.H Treasury - Credit Terms/Policies or Incentives for Sales to Customers, Bottlers or Distributors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.1 Treasury - Exemption from Bad Debt Reserve Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.2 Treasury - Write-offs of Uncollectible Accounts Receivable from Bad Debt Reserve</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA COA Group old</label>
    <nameField>
        <label>RFA COA Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFA COA Groups old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_ObjectHierarchyViewctrl_Test.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/

@IsTest(SeeallData=true)
public class RFA_VFC_ObjectHierarchyViewctrl_Test 
{
    static testmethod void Apprvrdetailsmethod1()
    {
        
        RFATestData testData = new RFATestData();
        //RFA__c testRFA; 
        RFA_Business_Unit__c testBU= RFATestData.buildRFAHierarchyBusinessUnit();
        insert testBU;
        ProfitCenter__c pc=testData.buildRFAHierarchyProfitCenter(testBU.id); 
        RFA_COA_Group__c testgroup = new RFA_COA_Group__c();
        
        testgroup.Name = 'testGroup1';
        testgroup.Amount__c = 999999;
        testgroup.DOA_Category__c ='4.A Leases - Operating Leases';
        insert testgroup ;
        String profile = RFATestData.RFAStandardUserProfile;
        RFATestData RTData = new RFATestData();
        User grUser = new User();
        grUser = RTData.createUser(profile, 'TestUser', 'grlastt', grUser);
        
        User grUser2 = new User();
        grUser2 = RTData.createUser(profile, 'TUser2', 'grlas2', grUser2);
        
        RFA_Approver__c testapprover = new RFA_Approver__c();
        testapprover.UserName__c = grUser.Id;
        testapprover.UserRole__c = 'Approver';
        testapprover.RFA_COA_Group__c = testgroup.Id;
        insert testapprover;
        
        testapprover = new RFA_Approver__c();
        testapprover.UserName__c = grUser2.Id;
        testapprover.UserRole__c = 'Info Copy';
        testapprover.RFA_COA_Group__c = testgroup.Id;
        insert testapprover;
        
        //system.debug('Test class RFA is:' +testRFA);
        system.debug('Test class PC number is:' +RFATestData.testProfitCenter.Id);
        system.debug('Test class Group number is:' +testgroup.Id);
        
        ProfitCenterCOAGroupJunctionobject__c junobj = new ProfitCenterCOAGroupJunctionobject__c();        
        junobj.Profit_Center_Number__c = pc.Id;
        junobj.RFA_COA_Group_Name__c = testgroup.Id;  
        insert junobj ;  
         
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        
        
        User approverUser;
        
        System.runAs(RFATestData.requester)
        {
            //testRFA = RFATestData.buildTestRFA(testRFA, rt);
            
        }
        
        
        PageReference pageRef = Page.RFA_VFP_ObjectHierarchyViewPage;        
        Test.setCurrentPage(pageRef); 
        
        
        
        
        RFA_VFC_ObjectHierarchyViewController controller  = new RFA_VFC_ObjectHierarchyViewController();
        
        IntermediaterfaAutoAppvr__c  Interobj = new IntermediaterfaAutoAppvr__c ();
        
        controller.selectedRec='TestRec';
        
       
        controller.selectedRec='CCNA';
        controller.getBusinessUnits();
        controller.selectedUnit=testBU.name;        
        controller.getProfitcenters();
        controller.selectedPC=pc.Name;    
        controller.getDOACategories();
        controller.selectedDOA='4.A Leases - Operating Leases';
        controller.getGroupAmounts();
        controller.selectedAmount='999999';
        
        controller.selectedGroupNames=testgroup.Id;
        controller.viewApprovers();
        
        controller.selectedAmount='199999';        
        controller.selectedGroupNames=testgroup.Id;
        controller.viewApprovers();
        
        controller.selectedAmount='199999'; 
        controller.viewApprovers();
        
        controller.selectedGroupNames=testgroup.Id;
        controller.SelectedgroupUsers();
        controller.AddUsers();
        controller.selectedGroupNames=testgroup.Id;
        
        User testUser = new User();   
        testUser = new User();
        testUser.alias = 'tt';
        testUser.email = 'cok@cocacola1.com';
        testUser.emailencodingkey='UTF-8';
        testUser.lastName = 'ln';
        testUser.languagelocalekey='en_US';
        testUser.localesidkey='en_US';
        String profileId=RFATestData.getRFAStandardUserProfile();
        testUser.ProfileId = profileId;
        testUser.timezonesidkey='Europe/London';
        testUser.UserName = 'rt'+'@rfa.cocacola.com';
        insert testUser;
        
        RFA_Approver__c existingRFAApproversInsert=new RFA_Approver__c();
        existingRFAApproversInsert.Level__c='1. Key Operations';
        existingRFAApproversInsert.RFA_COA_Group__c=testgroup.Id;
        existingRFAApproversInsert.UserName__c=testUser.id;
        existingRFAApproversInsert.UserRole__c='Approver';             
        
        insert existingRFAApproversInsert;
        
        Test.startTest();
        List<IntermediaterfaAutoAppvr__c> intermTest1 = new  List<IntermediaterfaAutoAppvr__c>();
        User userobj=[Select id from User  where Profile.Name = 'RFA - Standard User' limit 1];
        controller  = new RFA_VFC_ObjectHierarchyViewController();
        intermTest1 = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();   
        Interobj.Approver__c=userobj.id;
        Interobj.RoleType__c='Approver';
        Interobj.Level__c='1. Key Operations'; 
        Interobj.ExistingOne__c=userobj.id;
        insert Interobj ;  
        
        intermTest1.add(Interobj);
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.intermediateObj=intermTest1; 
        
        controller.updateApprovers();
        Test.stopTest();
        
        controller.rowNum=0;
        Interobj = new IntermediaterfaAutoAppvr__c ();        
        Interobj.Manual_Automated__c='Manual';
        Interobj.Approver__c=userobj.id;
        insert Interobj ;
        List<IntermediaterfaAutoAppvr__c> listIntermediate = new List<IntermediaterfaAutoAppvr__c>();   
        listIntermediate.add(Interobj);
        controller.intermediateObj=listIntermediate;
        pageref.getParameters().put('DeleteId',Interobj.Id); 
        pageref.getParameters().put('indexid','0'); 
        
        pageref.getParameters().put('EditId',Interobj.Id); 
        controller.EditUsers(); 
        controller.selectedGroupNames=testgroup.Id;        
        controller.viewApprovers();
        pageref.getParameters().put('indexid','0');
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.Approver__c=userobj.id;
        Interobj.RoleType__c='Approver';
        insert Interobj ;    
        intermTest1 = new List<IntermediaterfaAutoAppvr__c>();
        intermTest1.add(Interobj);
        Test.setCurrentPage(pageRef);
        controller.intermediateObj=intermTest1;
        controller.DeleteUsers();   
        
    }    
    
    static testmethod void Apprvrdetailsmethod2()
    {
        RFA_VFC_ObjectHierarchyViewController controller  = new RFA_VFC_ObjectHierarchyViewController();
        
        controller.selectedRec='--Select--';
        controller.viewApprovers();        
        
    }
    
    static testmethod void Apprvrdetailsmethod3()
    {
        RFA_VFC_ObjectHierarchyViewController controller  = new RFA_VFC_ObjectHierarchyViewController();
        controller.selectedRec='CCNA'; 
        controller.selectedUnit='--Select--';
        controller.viewApprovers(); 
        
    }
    static testmethod void Apprvrdetailsmethod4()
    {
        RFA_VFC_ObjectHierarchyViewController controller  = new RFA_VFC_ObjectHierarchyViewController();
        controller.selectedRec='CCNA'; 
        controller.selectedUnit='Test';
        controller.selectedPc='--Select--';
        controller.viewApprovers(); 
        
    }
    static testmethod void Apprvrdetailsmethod5()
    {
        RFA_VFC_ObjectHierarchyViewController controller  = new RFA_VFC_ObjectHierarchyViewController();
        controller.selectedRec='CCNA'; 
        controller.selectedUnit='Test';
        controller.selectedPc='Test';
        controller.selectedDOA='--Select--';
        controller.viewApprovers(); 
        
    }
    static testmethod void Apprvrdetailsmethod6()
    {
        RFA_VFC_ObjectHierarchyViewController controller  = new RFA_VFC_ObjectHierarchyViewController();
        controller.selectedRec='CCNA'; 
        controller.selectedUnit='Test';
        controller.selectedPc='Test';
        controller.selectedDOA='Test';
        controller.selectedAmount='--Select--';
        controller.viewApprovers(); 
        
    }
    static testmethod void ApprvrdetailsmethodSaveUsers()
    {
        Test.startTest();
        RFA_VFC_ObjectHierarchyViewController controller  = new RFA_VFC_ObjectHierarchyViewController();
         User usrobj=[Select id from User  where Profile.Name = 'RFA - Standard User' limit 1];
        List<IntermediaterfaAutoAppvr__c> intermTest = new List<IntermediaterfaAutoAppvr__c>();                
        IntermediaterfaAutoAppvr__c  Interobj = new IntermediaterfaAutoAppvr__c ();        
        Interobj.Approver__c=usrobj.id;
        insert Interobj ;
        intermTest.add(Interobj);
        controller.intermediateObj=intermTest;
        PageReference pageRef = Page.RFA_VFP_ObjectHierarchyViewPage;
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.SaveUsers(); 
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();
        insert Interobj ;
        intermTest.add(Interobj);
        controller.intermediateObj=intermTest;
        pageRef = Page.RFA_VFP_ObjectHierarchyViewPage;
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.SaveUsers();  
        
        controller  = new RFA_VFC_ObjectHierarchyViewController();
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.Approver__c=usrobj.id;
        Interobj.RoleType__c='Approver';
        insert Interobj ;        
        intermTest.add(Interobj);
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.intermediateObj=intermTest;
        controller.SaveUsers();
        
        
        controller  = new RFA_VFC_ObjectHierarchyViewController();
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c (); 
        Interobj.Approver__c=usrobj.id;
        Interobj.RoleType__c='Co-Creator';
        insert Interobj ;        
        intermTest.add(Interobj);
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.intermediateObj=intermTest;
        controller.SaveUsers();
        
        controller  = new RFA_VFC_ObjectHierarchyViewController();
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.Approver__c=usrobj.id;
        Interobj.RoleType__c='Primary Point of Contact';
        Interobj.Level__c='1. Key Operations';        
        insert Interobj ;
        intermTest.add(Interobj);
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.intermediateObj=intermTest;
        controller.SaveUsers();
        
        controller  = new RFA_VFC_ObjectHierarchyViewController();
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.Approver__c=usrobj.id;
        Interobj.RoleType__c='Co-Creator';
        Interobj.Level__c='1. Key Operations';        
        insert Interobj ;
        intermTest.add(Interobj);
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.intermediateObj=intermTest;
        controller.SaveUsers();
        
        controller  = new RFA_VFC_ObjectHierarchyViewController();
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();   
        Interobj.Approver__c=usrobj.id;
        Interobj.RoleType__c='Approver';
        Interobj.Level__c='1. Key Operations'; 
        insert Interobj ;        
        intermTest.add(Interobj);
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.intermediateObj=intermTest;
        controller.SaveUsers();
        
        controller  = new RFA_VFC_ObjectHierarchyViewController();
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();   
        Interobj.Approver__c=usrobj.id;
        Interobj.RoleType__c='Approver';
        Interobj.Level__c='1. Key Operations'; 
        insert Interobj ;        
        intermTest.add(Interobj);
        pageref.getParameters().put('Saverownum', '0');
        Test.setCurrentPage(pageRef);
        controller.intermediateObj=intermTest;
        controller.SaveUsers();
        
        
        controller  = new RFA_VFC_ObjectHierarchyViewController();       
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();   
        Interobj.Approver__c=usrobj.id;
        Interobj.RoleType__c='Approver';
        Interobj.Level__c='1. Key Operations'; 
        insert Interobj ;          
        controller.tobeEdited=Interobj.id;
        intermTest.add(Interobj);
        controller.intermediateObj=intermTest;
        pageref.getParameters().put('Cancelrownum', '0');
        controller.Cancelusers();      
        
        controller  = new RFA_VFC_ObjectHierarchyViewController();       
        intermTest = new List<IntermediaterfaAutoAppvr__c>();
        Interobj = new IntermediaterfaAutoAppvr__c ();   
        Interobj.Approver__c=usrobj.id;
        Interobj.RoleType__c='Approver';
        Interobj.Level__c='1. Key Operations'; 
        insert Interobj ;          
        controller.tobeEdited=Interobj.id;
        intermTest.add(Interobj);
        controller.intermediateObj=intermTest; 
        PageReference pageRef1 = Page.RFA_VFP_ObjectHierarchyViewPage;        
        pageref1.getParameters().put('EditId', Interobj.id);
        controller.EditUsers();  
        Test.stopTest();
    }  
    
    
}