Jann 30/objects/IntermediaterfaAutoAppvr__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IntermediaterfaAutoAppvrs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IntermediaterfaAutoAppvrs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IntermediaterfaAutoAppvrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalComments__c</fullName>
        <label>ApprovalComments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IntermediaterfaAutoAppvrs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manual_Automated__c</fullName>
        <label>Manual/Automated</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFAId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFAId</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipLabel>IntermediaterfaAutoAppvrs</relationshipLabel>
        <relationshipName>IntermediaterfaAutoAppvrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IntermediaterfaAutoAppvr</label>
    <nameField>
        <label>intermediaterfaAutoAppvrs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IntermediaterfaAutoAppvrs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterCOAGroupJunctionobject__c.object
<CustomObject>
    <fields>
        <fullName>Profit_Center_Number__c</fullName>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipName>ProfitCenterCOAGroupJunctionobjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RFA_COA_Group_Name__c</fullName>
        <label>RFA COA Group Name</label>
        <referenceTo>RFA_COA_Group__c</referenceTo>
        <relationshipName>ProfitCenterCOAGroupJunctionobjects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ProfitCenter COAGroup</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>ProfitCenterCOAGroup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitCenter COAGroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountUSD__c</fullName>
        <formula>RequestAmountFunctionalCurrency__c *ARERate__c</formula>
        <inlineHelpText>TCCC portion only. Request Amt is based on DOA/LCOA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amt, etc.</inlineHelpText>
        <label>Request Amount (USD)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase.  (e.g.,  Write-off  45 non-working vending machines in Atlanta sales center)</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFA_Approver__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserRole__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA_COA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA COA Group</label>
        <referenceTo>RFA_COA_Group__c</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserName</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <label>UserRole</label>
        <picklist>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Creator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Point of Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA Approver_old</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>RFA Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFA_COA_Group__c.object
<CustomObject>
    <description>RFA object which is used for determining the automated list of approvers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RFA COA Group old</label>
    <nameField>
        <label>RFA COA Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFA COA Groups old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manual_Automated__c</fullName>
        <label>Manual/Automated</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_NewAutoApproverControllerTest.cls
@IsTest(seeAllData=true)
public class RFA_VFC_NewAutoApproverControllerTest 
{
    
     static testMethod void myUnitTest1() 
    {
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
                
         RFA__c testRFA; 
        User approverUser;
        
        System.runAs(RFATestData.requester)
        {
            testRFA = RFATestData.buildTestRFA(testRFA, rt);
            
        }
       system.debug('test RFA USDAmount is:' +testRFA.RequestAmountUSD__c);
        
        
        string profile = RFATestData.RFAStandardUserProfile;
        RFATestData RTData = new RFATestData();
        User grUser = new User();
        grUser = RTData.createUser(profile, 'TestUser', 'grlastt', grUser);

        User grUser2 = new User();
        grUser2 = RTData.createUser(profile, 'TUser2', 'grlas2', grUser2);
                
        RFAUserRole__c testRFARole = new RFAUserRole__c();
        testRFARole.UserName__c = grUser.Id;
        testRFARole.RFA__c = testRFA.ID;        
        testRFARole.Level__c = '1. Key Operations';
        insert testRFARole;
        RFAUserRole__c testRFARole1 = new RFAUserRole__c();
        testRFARole1.UserName__c = grUser2.Id;
        testRFARole1.RFA__c = testRFA.ID;        
        testRFARole1.Level__c = '2. Business Unit';
        insert testRFARole1;
        
        RFA_COA_Group__c testgroup = new RFA_COA_Group__c();
        testgroup.Name = 'testGroup1';
        testgroup.Amount__c = testRFA.RequestAmountUSD__c;
        insert testgroup ;
        
        RFA_Approver__c testapprover = new RFA_Approver__c();
        testapprover.UserName__c = grUser.Id;
        testapprover.UserRole__c = 'Approver';
        testapprover.RFA_COA_Group__c = testgroup.Id;
        insert testapprover;
        testapprover = new RFA_Approver__c();
        testapprover.UserName__c = grUser2.Id;
        testapprover.UserRole__c = 'Info Copy';
        testapprover.RFA_COA_Group__c = testgroup.Id;
        insert testapprover;
        system.debug('Test class RFA is:' +testRFA);
        system.debug('Test class PC number is:' +RFATestData.testProfitCenter.Id);
        system.debug('Test class Group number is:' +testgroup.Id);
        ProfitCenterCOAGroupJunctionobject__c junobj = new ProfitCenterCOAGroupJunctionobject__c();        
        junobj.Profit_Center_Number__c = testRFA.ProfitCenterNumber__c;
        junobj.RFA_COA_Group_Name__c = testgroup.Id;  
        insert junobj ; 
        
        IntermediaterfaAutoAppvr__c  Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='M';
        //Interobj.Approver__c='005g0000002jjTb';
        insert Interobj ; 
        List<ProfitCenterCOAGroupJunctionobject__c>  selectedGroupNames = [select RFA_COA_Group_Name__r.Name from ProfitCenterCOAGroupJunctionobject__c where Profit_Center_Number__r.Id =:testRFA.ProfitCenterNumber__c and RFA_COA_Group_Name__r.Amount__c =: testRFA.RequestAmountUSD__c ];       
        system.debug('junction obj values are:' +selectedGroupNames );
        List<RFA_Approver__c> criteriausers =[select Username__c,UserRole__c,Level__c,RFA_COA_Group__c,RFA_COA_Group__r.name from RFA_Approver__c];
        system.debug('test approvers  are:' +criteriausers );
        PageReference pageRef = Page.RFA_VFP_NewAutoApprover;        
        pageref.getParameters().put('id', testRFARole.id);
         pageref.getParameters().put('DeleteId', Interobj.id); 
        ApexPages.Standardcontroller stdController = new ApexPages.Standardcontroller(testRFA); 
        Test.setCurrentPage(pageRef); 
        RFA_VFC_NewAutoApproverController controller  = new RFA_VFC_NewAutoApproverController(stdController);
        controller.DeleteRFAUserrole();
        controller.insertInauObj();
        system.debug('getusers calling'+controller.getusers());
        controller.size=10;
       // controller.tobeDeleted=[select Id from IntermediaterfaAutoAppvr__c where RFAId__c=:testRFA.ID LIMIT 1].Id;
        //controller.intermApp=[select level__c,Agent1__c,Agent2__c,Agent3__c from RFAUserRole__c where RFA__c =:testRFA.ID ];
        controller.searchstring='Bindu';
        controller.searchUsers(); 
        controller.ClearUsers();
        controller.Addtotable();
        
        controller.InsertApprovers();
        controller.getSelected();        
        user uobj = new user();
        RFA_VFC_NewAutoApproverController.Userwrapper obj = new RFA_VFC_NewAutoApproverController.Userwrapper(uobj);
            
    
    }
     static testMethod void myUnitTest2() 
    {
        RFA__c testRFA = new RFA__c();
        testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
        RFATestData rtTest = new RFATestData();
         rtTest.buildProfitCenter();
        
        testRFA.RequestTitle__c = 'Capital Project Request RFA Title';
        testRFA.Stage__c = 'Draft';
        insert testRFA;
        string profile = RFATestData.RFAStandardUserProfile;
        RFATestData RTData = new RFATestData();
        User grUser = new User();
        grUser = RTData.createUser(profile, 'TestUser', 'grlastt', grUser);

        User grUser2 = new User();
        grUser2 = RTData.createUser(profile, 'TUser2', 'grlas2', grUser2);
                
        RFAUserRole__c testRFARole = new RFAUserRole__c();
        testRFARole.UserName__c = grUser.Id;
        testRFARole.RFA__c = testRFA.ID;
        
        testRFARole.Level__c = '1. Key Operations';
        insert testRFARole;
        RFA_COA_Group__c testgroup = new RFA_COA_Group__c();
        testgroup.Name = 'testGroup1';
        testgroup.Amount__c = testRFA.RequestAmountUSD__c;
        insert testgroup ;
        
        RFA_Approver__c testapprover = new RFA_Approver__c();
        testapprover.UserName__c = grUser.Id;
        testapprover.UserRole__c = 'Approver';
        testapprover.RFA_COA_Group__c = testgroup.Id;
        insert testapprover;
        system.debug('Test class PC number is:' +testRFA.ProfitCenterNumber__c);
        system.debug('Test class Group number is:' +testgroup.Id);
        
        
       /* ProfitCenterCOAGroupJunctionobject__c junobj = new ProfitCenterCOAGroupJunctionobject__c();
        
        junobj.Profit_Center_Number__c = testRFA.ProfitCenterNumber__c;
        junobj.RFA_COA_Group_Name__c = testgroup.Id;
        insert  junobj ; */
        
        
        IntermediaterfaAutoAppvr__c  Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='M';
        //Interobj.Approver__c='005g0000002jjTb';
        insert Interobj ;      
        

        PageReference pageRef = Page.RFA_VFP_NewAutoApprover;
        Test.setCurrentPage(pageRef); 
        System.currentPageReference().getParameters().put('id', testRFARole.id); 
        ApexPages.Standardcontroller stdController = new ApexPages.Standardcontroller(testRFA); 
        RFA_VFC_NewAutoApproverController controller  = new RFA_VFC_NewAutoApproverController(stdController);
        controller.size=10;
        //MyStandardClass instance = new MyStandardClass(controller);
        controller.approvedusers =[select Id,Level__c,UserName__c,Agent1__c,Agent2__c,Agent3__c,recordTypeId,Manual_Automated__c,ApprovalRecommendation__c from RFAUserRole__c where RFA__c='a0Gg000000AwNO5' and ApprovalRecommendation__c != null];
        //controller.intermApp=[select ApprovalComments__c,RFAId__c,Manual_Automated__c,Approver__c,Level__c,Agent1__c,Agent2__c,Agent3__c from IntermediaterfaAutoAppvr__c where RFAId__c='a0Gg000000AwNO5' order by Level__c asc]; 
        controller.searchstring='Bindu';
        controller.tablerendered=false;
        controller.searchUsers();
        }

}