Jann 30/objects/IntermediaterfaAutoAppvr__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manual_Automated__c</fullName>
        <label>Manual/Automated</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>IntermediaterfaAutoAppvr</label>
    <nameField>
        <label>intermediaterfaAutoAppvrs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IntermediaterfaAutoAppvrs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PrimaryDOACategorySubCategory__c</fullName>
        <inlineHelpText>This field allows the RFA Creator to select up to 3  DOA Categories that apply to the requested transaction.</inlineHelpText>
        <label>Primary DOA Category / Sub Category *</label>
        <picklist>
            <picklistValues>
                <fullName>1.A.1	Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.a	Capital Expenditures - Unbudgeted CPR or SPR Covered by Budget Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.b	Capital Expenditures - Unbudgeted CPR or SPR Funded Partially or Fully from Corporate Reserve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.3	Capital Expenditures - Increase or Scope Change to Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.4	Capital Expenditures - Transfer of Capital Budget across Groups for a Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.5	Capital Expenditures - Foreign Exchange Fluctuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.8	Capital Expenditures - Advance Appropriations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.B	Capital Expenditures - Capability and Performance Programs (CAPPrs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.C	Capital Expenditures - Bottles and Cases, Including Overages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.	IT Investments and Website Presence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.A	Real Property -  Acquisitions and Sales or Other Disposals of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.B	Real Property -  Donations of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.C	Real Property - Condemnations or Easements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.A	Leases - Operating Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.B	Leases - Capital Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.A	Inventory Adjustments and Disposals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.B	Other Asset Impairments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.C	Asset Transfers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.D	Asset Disposals (Tangible Assets excluding Real Property and Inventory)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.A	Treasury - Banking Information Reports (BIR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.B	Treasury - External Borrowings and Lines of Credit (RFFs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.C	Treasury - Intercompany Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.D	Treasury - Loans Third Parties (Including CCFC Target Loan Programs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.1	Treasury - Guarantees to Third Parties - General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.2	Treasury - Guarantees Related to Tax Disputes or Other Matters Involving Governmental Bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.F	Treasury - Comfort Letters and Other Financial Security Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.G	Treasury - Accommodation Purchases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.H	Treasury - Credit Terms/Policies or Incentives for Sales to Customers, Bottlers or Distributors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.1	Treasury - Exemption from Bad Debt Reserve Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.2	Treasury - Write-offs of Uncollectible Accounts Receivable from Bad Debt Reserve</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RequestAmountUSD__c</fullName>
        <formula>RequestAmountFunctionalCurrency__c *ARERate__c</formula>
        <inlineHelpText>TCCC portion only. Request Amt is based on DOA/LCOA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amt, etc.</inlineHelpText>
        <label>Request Amount (USD)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFA_Approver__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserRole__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA_COA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA COA Group</label>
        <referenceTo>RFA_COA_Group__c</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserName</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <label>UserRole</label>
        <picklist>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Creator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Copy Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Point of Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA Approver_old</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>RFA Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFA_COA_Group__c.object
<CustomObject>
    <description>RFA object which is used for determining the automated list of approvers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RFA COA Group old</label>
    <nameField>
        <label>RFA COA Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFA COA Groups old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manual_Automated__c</fullName>
        <label>Manual/Automated</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_AddMultipleUsersctlrTest.cls
@IsTest(seeAllData=true)
public class RFA_VFC_AddMultipleUsersctlrTest 
{
    static testMethod void AddMultipleusers() 
    {
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;              
        RFA__c testRFA; 
        User approverUser;
        System.runAs(RFATestData.requester)
        {
            testRFA = RFATestData.buildTestRFA(testRFA, rt);
            
        }        
        string profile = RFATestData.RFAStandardUserProfile;
        RFATestData RTData = new RFATestData();
        User grUser = new User();
        grUser = RTData.createUser(profile, 'TestUser', 'grlastt', grUser);

        User grUser2 = new User();
        grUser2 = RTData.createUser(profile, 'TUser2', 'grlas2', grUser2);
                
        RFAUserRole__c testRFARole = new RFAUserRole__c();
        testRFARole.UserName__c = grUser.Id;
        testRFARole.RFA__c = testRFA.ID;        
        testRFARole.Level__c = '1. Key Operations';
        testRFARole.Manual_Automated__c='Manual';
        insert testRFARole;
        RFAUserRole__c testRFARole1 = new RFAUserRole__c();
        testRFARole1.UserName__c = grUser2.Id;
        testRFARole1.RFA__c = testRFA.ID;        
        testRFARole1.Level__c = '2. Business Unit';        
        insert testRFARole1;
        string doacategory = testRFA.PrimaryDOACategorySubCategory__c;
        doacategory= doacategory.replaceAll('(\\s+)', '');        
        
        RFA_COA_Group__c testgroup = new RFA_COA_Group__c();
        testgroup.Name = 'testGroup1';
        testgroup.Amount__c = testRFA.RequestAmountUSD__c;
        testgroup.DOA_Category__c = doacategory; 
        insert testgroup ;
        
        ProfitCenterCOAGroupJunctionobject__c testjunobj = new ProfitCenterCOAGroupJunctionobject__c();
        testjunobj.RFA_COA_Group_Name__c = testgroup.id;
        testjunobj.Profit_Center_Number__c = testRFA.ProfitCenterNumber__c;
        insert testjunobj ;
        
        RFA_Approver__c testapprover = new RFA_Approver__c();
        testapprover.UserName__c = grUser.Id;
        testapprover.UserRole__c = 'Approver';
        testapprover.RFA_COA_Group__c = testgroup.Id;
        insert testapprover;
        
        testapprover = new RFA_Approver__c();
        testapprover.UserName__c = grUser2.Id;
        testapprover.UserRole__c = 'Info Copy';
        testapprover.RFA_COA_Group__c = testgroup.Id;
        insert testapprover;                
       
        
        IntermediaterfaAutoAppvr__c  Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Manual';
        Interobj.Approver__c=grUser.Id;
        insert Interobj ;
       
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Auto';
        Interobj.Approver__c=grUser.Id;
        insert Interobj ;
                
        PageReference pageRef = Page.RFA_VFP_AddMultipleUsers;        
        pageref.getParameters().put('id', testRFARole.id);        
        ApexPages.Standardcontroller stdController = new ApexPages.Standardcontroller(testRFA); 
        Test.setCurrentPage(pageRef); 
        RFA_VFC_AddMultipleUsersctlr controller  = new RFA_VFC_AddMultipleUsersctlr(stdController);        
        controller.insertInauObj();
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Manual';
        Interobj.Approver__c=grUser.Id;
        insert Interobj ;        
        pageref.getParameters().put('DeleteId', Interobj.id);
        pageref.getParameters().put('EditId', Interobj.id);
        pageref.getParameters().put('Saverownum','0');
        pageref.getParameters().put('Cancelrownum','0');
        pageref.getParameters().put('indexid', '0');               
      
        controller.size=10;      
        controller.EditUsers(); 
        controller.DeleteUsers();
        controller.SaveUsers();
        controller.Cancelusers();
        controller.updateagentsinfo();
        controller.InsertUsers();
        controller.pagination(); 
        controller.previous();
        controller.next();
        controller.first();
        controller.last(); 
        controller.getprv(); 
        controller.getnxt();
        controller.getfst();
        controller.getlst();
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Manual';
        Interobj.Approver__c=grUser.Id;
        Interobj.ApprovalComments__c='Approved';
        insert Interobj ;
        Test.startTest(); 
        pageref.getParameters().put('EditId', Interobj.id);
        pageref.getParameters().put('indexid', '0');
        controller.EditUsers(); 
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Auto';
        Interobj.Approver__c=grUser.Id;
        Interobj.RoleType__c=null;
        insert Interobj ;  
         pageref.getParameters().put('Saverownum','0'); 
         controller.SaveUsers(); 
        Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Auto'; 
        Interobj.Approver__c=null;       
        Interobj.RoleType__c='Approver';
        Interobj.Level__c=null;
        insert Interobj ;  
         pageref.getParameters().put('Saverownum','0'); 
         controller.SaveUsers();
         Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Auto';        
        Interobj.RoleType__c='Approver';
        Interobj.Level__c='1. Key Operations' ;
        insert Interobj ;  
         pageref.getParameters().put('Saverownum','0'); 
         controller.SaveUsers();
         controller.validateemptyrow();
       
            
    
    }
     static testMethod void AddMultipleusersmethod2() 
   {
        RFATestData testData = new RFATestData();
        testData.buildProfitCenter();
        testData.createRequester();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;              
        RFA__c testRFA; 
        User approverUser;
        System.runAs(RFATestData.requester)
        {
            testRFA = RFATestData.buildTestRFA(testRFA, rt);
            
        }
         string profile = RFATestData.RFAStandardUserProfile;
        RFATestData RTData = new RFATestData();
        User grUser = new User();
        grUser = RTData.createUser(profile, 'TestUser', 'grlastt', grUser);

        User grUser2 = new User();
        grUser2 = RTData.createUser(profile, 'TUser2', 'grlas2', grUser2);
                
        RFAUserRole__c testRFARole = new RFAUserRole__c();
        testRFARole.UserName__c = grUser.Id;
        testRFARole.RFA__c = testRFA.ID;        
        testRFARole.Level__c = '1. Key Operations';
        testRFARole.Manual_Automated__c='Manual';
        insert testRFARole;
         PageReference pageRef = Page.RFA_VFP_AddMultipleUsers;        
        pageref.getParameters().put('id', testRFARole.id);
         ApexPages.Standardcontroller stdController = new ApexPages.Standardcontroller(testRFA); 
        Test.setCurrentPage(pageRef); 
        RFA_VFC_AddMultipleUsersctlr controller  = new RFA_VFC_AddMultipleUsersctlr(stdController);        
        controller.insertInauObj();
        IntermediaterfaAutoAppvr__c  Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Auto';        
        Interobj.RoleType__c='Approver';
        Interobj.Level__c='1. Key Operations' ;
        Interobj.ExistingOne__c='';
        Interobj.Approver__c=grUser.Id;
        insert Interobj;
       controller.InsertUsers();
       pageref.getParameters().put('DeleteId', Interobj.id);
       pageref.getParameters().put('indexid', '0');
       Interobj = new IntermediaterfaAutoAppvr__c ();
        Interobj.RFAId__c = testRFA.ID;
        Interobj.Manual_Automated__c='Manual';
        Interobj.Approver__c=grUser.Id;
        Interobj.ApprovalComments__c='Approved';
        insert Interobj ;        
        controller.DeleteUsers();
        
    }
}