Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>CAPEX1__c</fullName>
        <label>CAPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Category is the IT Procurement category for which you are requesting assistance.  Please see the attached PDF entitled “IT-SES Categories” for a depiction of the categories.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Assets &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application and SaaS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/Preferred Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Supplier Vendor Governance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Needed_By__c</fullName>
        <inlineHelpText>Please enter the date by which you would like this work request completed.  For example, if this is a request for an RFP, indicate the date by which you would like a supplier selection made and a contract executed with selected supplier</inlineHelpText>
        <label>Date Needed By</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Engagement_Of_A_New_Supplier__c</fullName>
        <inlineHelpText>Answer ‘Yes’ if this is a supplier that does not have a master agreement with The Company.</inlineHelpText>
        <label>Engagement Of A New Supplier?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Finance_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>I_Have_Read_The_Provided_ITP_OLA__c</fullName>
        <inlineHelpText>Please refer to the “ITP OLA” document link under the “IT-SES Help” section on the left.</inlineHelpText>
        <label>I Have Read The Provided ITP OLA</label>
        <picklist>
            <picklistValues>
                <fullName>My Request Is Within The ITP OLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Request Is Not Within The ITP OLA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7m</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Manager of the person in ‘Submitted On Behalf Of&apos;.</inlineHelpText>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXpnP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPEX1__c</fullName>
        <label>OPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Statement__c</fullName>
        <inlineHelpText>Provide a description of the project which is associated with this request.</inlineHelpText>
        <label>Opportunity Statement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <inlineHelpText>This is the TCCC company which has budget responsibility for the request.  This field drives both initial assignment and Chart of Authority during the approval process.</inlineHelpText>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>GIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Use this field to identify the type of assistance you are requesting.  Please see the attached PDF entitled “Request Type” for a definition of the different request types.</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change In Existing Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Of Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Access Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Legal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Phone_Number__c</fullName>
        <inlineHelpText>Enter the telephone number for the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/ITPRDelegation__c.object
<CustomObject>
    <fields>
        <fullName>Delegate_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegate To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPR_Delegation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>IT-SES Delegation</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delegation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES Delegation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/ITPR_Test_DelgStartBatch.cls
@isTest
private class ITPR_Test_DelgStartBatch{
    static testmethod void test1(){
        test.startTest();
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        String jobId = System.schedule('ITPR_Test_DelgStartBatch', CRON_EXP ,new ITPR_Delegation_OldDocumentStartSchedule());
        CronTrigger ct = [SELECT id, CronExpression, TimesTriggered,NextFireTime FROM CronTrigger WHERE id = :jobId];
        test.stopTest();
    }
    
  static testmethod void test2(){
  Test.startTest();
       List<ITPRDelegation__c> lst = new List<ITPRDelegation__c>();
       List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
        }
    }
       List<User> lstUsers = new List<User>();
User user1 = new User(
            username = 'testdel1' + DateTime.now().getTime() + '@test.com',
            alias = 'del1',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'del1',
            profileId = mapProfiles.get('ITSES - Procurement'),
            ITPR_Department__c =  'ITSES - Procurement',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(user1);
        User user2 = new User(
            username = 'testdel2' + DateTime.now().getTime() + '@test.com',
            alias = 'del2',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'deltest2',
            profileId = mapProfiles.get('ITSES - Procurement'),
            ITPR_Department__c =  'ITSES - Procurement',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            isactive = true
        );
        lstUsers.add(user2);
        
        User user3 = new User(
            username = 'testdel3' + DateTime.now().getTime() + '@test.com',
            alias = 'del3',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'deltest3',
            profileId = mapProfiles.get('ITSES - Finance'),
            ITPR_Department__c =  'ITSES - Finance',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(user3);
        
        
        User user4 = new User(
            username = 'testdel4' + DateTime.now().getTime() + '@test.com',
            alias = 'del4',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'deltest3',
            profileId = mapProfiles.get('ITSES - Legal'),
            ITPR_Department__c =  'ITSES - Legal',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(user4);
        
        User user5 = new User(
            username = 'testdel5' + DateTime.now().getTime() + '@test.com',
            alias = 'del5',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'deltest5',
            profileId = mapProfiles.get('ITSES - Legal'),
            ITPR_Department__c =  'ITSES - Legal',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            isactive = true
        );
        lstUsers.add(user5);
        
        User user6 = new User(
            username = 'testdel6' + DateTime.now().getTime() + '@test.com',
            alias = 'del6',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'deltest6',
            profileId = mapProfiles.get('System Administrator'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            isactive = true
        );
        lstUsers.add(user6);
        
        User user7 = new User(
            username = 'testdel7' + DateTime.now().getTime() + '@test.com',
            alias = 'del7',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'deltest7',
            profileId = mapProfiles.get('System Administrator'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            isactive = true
        );
        lstUsers.add(user7);
        
        insert lstUsers;
       System.runAs(user5){
       ITPRDelegation__c delObj = new ITPRDelegation__c ();
       
       delObj.Delegate_To__c= user4.Id;
       delObj.start_Date__c = Date.Today() +5;
       delObj.End_Date__c = Date.Today() +10;
       insert delObj;
        
       lst.add(delObj);
       }
       System.runAs(user1) {
       ITPRDelegation__c delObj1 = new ITPRDelegation__c ();
       delObj1.Delegate_To__c= user2.Id;
       delObj1.start_Date__c = Date.Today() +5;
       delObj1.End_Date__c = Date.Today() +10;
       insert delObj1;
       lst.add(delObj1);
       }
       
       
       ITPR__c ITPRObj = new ITPR__c();
       ITPRObj.Procurement_Assignee__c = User2.Id;
       ITPRObj.Request_Type__c = System.Label.ITPR_Request_type_RFI;
    ITPRObj.category__c = 'Telecom';
    ITPRObj.Organization__c = 'CONA';
    ITPRObj.Finance_Assignee__c = user3.Id;
    ITPRObj.I_Have_Read_The_Provided_ITP_OLA__c = 'test';
     ITPRObj.Date_Needed_by__c =  Date.today();
    ITPRObj.Supplier_Contact_Phone_Number__c = '9998889898';
    ITPRObj.Engagement_Of_A_New_Supplier__c = 'No';
    ITPRObj.Manager__C = user2.Id;
    ITPRObj.Opportunity_Statement__c = 'test';
    ITPRObj.CAPEX1__c = 200;
    ITPRObj.OPEX1__c = 100;
    ITPRObj.Procurement_Assignee__c= user1.Id;
       insert ITPRObj;
       
       
       
       ITPR__c ITPRObj1 = new ITPR__c();
       ITPRObj1.Procurement_Assignee__c = User2.Id;
       ITPRObj1.Request_Type__c = System.Label.ITPR_Request_type_RFI;
    ITPRObj1.category__c = 'Telecom';
    ITPRObj1.Organization__c = 'CONA';
    ITPRObj1.Finance_Assignee__c = user3.Id;
    ITPRObj1.I_Have_Read_The_Provided_ITP_OLA__c = 'test';
     ITPRObj1.Date_Needed_by__c =  Date.today();
    ITPRObj1.Supplier_Contact_Phone_Number__c = '9998889898';
    ITPRObj1.Engagement_Of_A_New_Supplier__c = 'No';
    ITPRObj1.Manager__c = user2.Id;
    ITPRObj1.Opportunity_Statement__c = 'test';
    ITPRObj1.CAPEX1__c = 200;
    ITPRObj1.OPEX1__c = 100;
    ITPRObj1.Legal_Assignee__c= user4.Id;
    insert ITPRObj1;
       
       
        Database.BatchableContext BC;
        List<sObject> scope = new List<sobject>();
        scope.add(ITPRObj);
        scope.add(ITPRObj1);
        
       ITPR_Delegation_OldDocumentsStartBatch obj = new ITPR_Delegation_OldDocumentsStartBatch();
       obj.lstDelegation = lst;
       obj.start(BC);
        obj.execute(BC, scope);
        obj.finish(BC);
        
        Test.stopTest();
    }
}