Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Delegated_Finance_Assignee__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the assignee listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Finance Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Legal_Assignee__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the assignee listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Legal Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Procurement_Assignee__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the assignee listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Procurement Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRYAdQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegated_Requestor_check__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the Requestor listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Requestor Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Vendor_Governance_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the assignee listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Vendor Governance Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finance_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7m</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Indicates where the request is in the process flow.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending More Info Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Project Final Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Digital Initials Obtained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reactivate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed and Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Executed and Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_Governance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Governance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU81</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/ITPRDelegation__c.object
<CustomObject>
    <fields>
        <fullName>Delegate_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegate To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPR_Delegation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Undo Delegation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>IT-SES Delegation</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Delegation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES Delegation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/ITPR_Delegation_OldDocumentsEndBatch.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : ITPR_Delegation_OldDocumentsEndBatch
 *  Author           : Infosys
 *  Version History  : 1.0
 *  Creation         : 22/03/2014
 *  Assumptions      : N/A 
 *  Description      : This class is written to clear off the delegated requestors based on the end date of the delegated request and
                       removes the permissions off the delegated requestor.                                   
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/
global class ITPR_Delegation_OldDocumentsEndBatch implements Database.Batchable<sObject>
{
    /*Variable declaration*/
    public string query;
    public set<id> ds = new set<id>();
    List<ITPR__c> lt = new List<ITPR__c>();
    Date dt = Date.Today() - 1;
    /*End of variable declaration*/
    
    //fetch the delegation records which have end date as one daye prior to the day on which the batch is run   
    public List<ITPRDelegation__c> lstDelegation = new List<ITPRDelegation__c>([Select Start_Date__c,End_Date__c,Reset__c,Delegate_To__c,CreatedById from ITPRDelegation__c where End_Date__c = :dt]);
    
    //overridden start method of Batchable interface which returns the query
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        for(ITPRDelegation__c i: lstDelegation )
        {
            ds.add(i.CreatedById);
        }
       
        List<String> lstStatus = new List<String>();
        lstStatus.add(System.Label.ITPR_Complete_Status);
        lstStatus.add(System.Label.ITPR_All_Digital_Initials_Obtained_Status);
        lstStatus.add(System.Label.ITPR_Not_executed_and_Closed_Status);
        lstStatus.add(System.Label.ITPR_Executed_and_Filed_Status);
        lstStatus.add(System.Label.ITPR_Cancelled_Status);
        //fetch the ITPR records(with status other than complete) where the assignees/requestors are the ones who created the ITPR Delegation records 
        query = 'SELECT id,Status__c,Delegated_Requestor__c,Delegated_Finance_Assignee__c,Delegated_Vendor_Governance_User__c,Delegated_Requestor_check__c,Delegated_Legal_Assignee__c,Procurement_Assignee__c,Delegated_Procurement_Assignee__c,CreatedById,Legal_Assignee__c,Finance_Assignee__c,Vendor_Governance__c FROM ITPR__c WHERE Status__c not in :lstStatus and CreatedById IN: ds';
        return Database.getQueryLocator(query);
    }
    
    //covers the logic for clearing off the delegated requests from the delegators
    global void execute(Database.BatchableContext BC,  List<ITPR__c> scope)
    {    
           
        if(lstDelegation .size()>0)
        {
            for(ITPR__c itpr : scope)
            {
                for(ITPRDelegation__c dl: lstDelegation )
                { 
                    //checks for the crresponding requestor/assignee
                    if(itpr.CreatedById == dl.CreatedById)
                    {                          
                        //clears off the delegated requestor fields
                        itpr.Delegated_Requestor__c = null;
                        itpr.Delegated_Requestor_check__c = False;
                    }                    
                }
                lt.add(itpr);
            }
 
        }
        
        //update the ITPR records
        if(lt.size() >0)
        {
            update lt;
        }
    }
    
     //overridden method of batchable interface
    global void finish(Database.BatchableContext BC)
    {
        
    }
}
/*********************************************END*****************************************************************************************************************/