Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Addressee_Name__c</fullName>
        <inlineHelpText>Please enter the name of the person to whom the NDA is to be presented.  This does not have to be the name of the person signing it, although many supplier&apos;s prefer that it is.</inlineHelpText>
        <label>Addressee Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAPEX1__c</fullName>
        <label>CAPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Category is the IT Procurement category for which you are requesting assistance.  Please see the attached PDF entitled “IT-SES Categories” for a depiction of the categories.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Assets &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application and SaaS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/Preferred Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Supplier Vendor Governance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Needed_By__c</fullName>
        <inlineHelpText>Please enter the date by which you would like this work request completed.  For example, if this is a request for an RFP, indicate the date by which you would like a supplier selection made and a contract executed with selected supplier</inlineHelpText>
        <label>Date Needed By</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration_Of_NDA__c</fullName>
        <inlineHelpText>Please indicate the term for the NDA. Generally this is one year from the date on the NDA.</inlineHelpText>
        <label>Duration of NDA [# of year(s)]</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Of_A_New_Supplier__c</fullName>
        <inlineHelpText>Answer ‘Yes’ if this is a supplier that does not have a master agreement with The Company.</inlineHelpText>
        <label>Engagement Of A New Supplier?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Finance_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>I_Have_Read_The_Provided_ITP_OLA__c</fullName>
        <inlineHelpText>Please refer to the “ITP OLA” document link under the “IT-SES Help” section on the left.</inlineHelpText>
        <label>I Have Read The Provided ITP OLA</label>
        <picklist>
            <picklistValues>
                <fullName>My Request Is Within The ITP OLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Request Is Not Within The ITP OLA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_this_NDA_to_be_mutual_or_will_the_com__c</fullName>
        <inlineHelpText>Indicate whether this project is for the Freestyle program.</inlineHelpText>
        <label>Is This a Freestyle Project?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7m</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Manager of the person in ‘Submitted On Behalf Of&apos;.</inlineHelpText>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXpnP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPEX1__c</fullName>
        <label>OPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Statement__c</fullName>
        <inlineHelpText>Provide a description of the project which is associated with this request.</inlineHelpText>
        <label>Opportunity Statement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <inlineHelpText>This is the TCCC company which has budget responsibility for the request.  This field drives both initial assignment and Chart of Authority during the approval process.</inlineHelpText>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>GIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Use this field to identify the type of assistance you are requesting.  Please see the attached PDF entitled “Request Type” for a definition of the different request types.</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change In Existing Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Of Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Access Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Legal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Indicates where the request is in the process flow.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending More Info Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Project Final Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Digital Initials Obtained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reactivate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed and Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Executed and Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_On_Behalf_Of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted On Behalf Of</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRX6CY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Email__c</fullName>
        <inlineHelpText>Enter the email address for the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Name__c</fullName>
        <inlineHelpText>Enter the name of the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Phone_Number__c</fullName>
        <inlineHelpText>Enter the telephone number for the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter the name of the company which the contract will be with. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IT-SES</relationshipLabel>
        <relationshipName>ITPR1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_s_Legal_Entity_Name__c</fullName>
        <inlineHelpText>Provide the legal entity name including type (e.g. Inc., LLC, Corp)</inlineHelpText>
        <label>Supplier&apos;s Legal Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Governance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Governance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU81</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave1_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbUs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave1_Approver_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbV7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave1_Approver_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbVH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave1_Approver_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbVR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave1_Approver_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbVb</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave2_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXVRn</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/ITSES_FlagAllDigitalInitialsObtainedTEST.cls
@isTest

private class ITSES_FlagAllDigitalInitialsObtainedTEST {

	static testMethod void testScheduleFlagAllDigitalInitials (){
		
	List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
        }
    }
    
        
      List<USer> lstUsers = new List<User>();  
      
   	User u = new User(Alias = '5andt11', Email='standarduser@testorg.com',
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Procurement'),ITPR_Department__c =  'ITSES - Procurement', 
      TimeZoneSidKey='America/Los_Angeles', UserName='1standarduser34@testorg.com');
      lstUsers.add(u);
      
      User u1 = new User(Alias = '5sand8t', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Finance'),ITPR_Department__c =  'ITSES - Finance', 
      TimeZoneSidKey='America/Los_Angeles', UserName='2standarduser35@testorg.com');
      lstUsers.add(u1);
    
     User u2 = new User(Alias = '2stat6', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Procurement'),ITPR_Department__c =  'ITSES - Procurement', 
      TimeZoneSidKey='America/Los_Angeles', UserName='5standarduser36@testorg.com');
      lstUsers.add(u2);
      
      User u3 = new User(Alias = 'stand877', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('System Administrator'), 
      TimeZoneSidKey='America/Los_Angeles', UserName='7standarduser38@testorg.com');
      lstUsers.add(u3);
      
            User u5 = new User(Alias = '4stadt4', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Vendor Governance'),ITPR_Department__c =  'ITSES - Vendor Governance', 
      TimeZoneSidKey='America/Los_Angeles', UserName='3standarduser39@testorg.com');
      lstUsers.add(u5);
      
       User u6 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser51@testorg.com');
      lstUsers.add(u6);
      
       User u7 = new User(Alias = '5andt11', Email='standarduser@testorg.com',
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Requestor'),ITPR_Department__c =  'ITSES - Requestor', 
      TimeZoneSidKey='America/Los_Angeles', UserName='1standarduser350@testorg.com');
      lstUsers.add(u7);
      
      User u29 = new User(Alias = '5andt11', Email='standarduser@testorg.com',
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Requestor'),ITPR_Department__c =  'ITSES - Requestor', 
      TimeZoneSidKey='America/Los_Angeles', UserName='1standarduser358@testorg.com');
      lstUsers.add(u29);
      
       User u8 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser40@testorg.com');
      lstUsers.add(u8);
       User u9 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser49@testorg.com');
      lstUsers.add(u9);
       User u10 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser48@testorg.com');
      lstUsers.add(u10);
       User u11 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser47@testorg.com');
      lstUsers.add(u11);
       User u12 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser46@testorg.com');
      lstUsers.add(u12);
       User u13 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'), ITPR_Department__c =  'ITSES - Legal',
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser45@testorg.com');
      lstUsers.add(u13);
       User u14 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'), ITPR_Department__c =  'ITSES - Legal',
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser44@testorg.com');
      lstUsers.add(u14);
       User u15 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'), ITPR_Department__c =  'ITSES - Legal',
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser43@testorg.com');
      lstUsers.add(u15);
       User u16 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser42@testorg.com');
      lstUsers.add(u16);
       User u17 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'), ITPR_Department__c =  'ITSES - Legal',
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser41@testorg.com');
      lstUsers.add(u17);
      
      User u18 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser419@testorg.com');
      lstUsers.add(u18);
      User u19 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser418@testorg.com');
      lstUsers.add(u19);
      User u20 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser417@testorg.com');
      lstUsers.add(u20);
      User u21 = new User(Alias = '3stant5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapProfiles.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='4standarduser416@testorg.com');
      lstUsers.add(u21);
      
      insert lstUsers;
      
    Account supplier = new Account(Name = 'TestSupplier');
        insert supplier;
       
       Test.startTest(); 
               ITPR__c itpr = new ITPR__c();
    itpr.Request_Type__c = 'Eval Agreement';
    itpr.Date_Needed_by__c =  Date.newInstance(2098, 1, 1);
    itpr.category__c = 'Telecom';
    itpr.Organization__c = 'CONA';
    itpr.Supplier_Name__c = supplier.id;
    itpr.Supplier_Contact_Name__c = 'test';
    itpr.I_Have_Read_The_Provided_ITP_OLA__c = 'test';
    itpr.Supplier_Contact_Phone_Number__c = '9998889898';
    itpr.Engagement_Of_A_New_Supplier__c = 'No';
    itpr.Manager__C = u2.Id;
    itpr.Opportunity_Statement__c = 'test';
    itpr.CAPEX1__c = 200;
    itpr.OPEX1__c = 100;
    itpr.Supplier_s_Legal_Entity_Name__c = 'test';
    itpr.Duration_Of_NDA__c = 30.0;
    itpr.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';  
    itpr.Supplier_Contact_email__c = 'test@test.com';
    itpr.Finance_Assignee__c = u1.Id;
    itpr.Addressee_Name__c = 'test';
    itpr.Status__c = 'Draft';
    itpr.Procurement_Assignee__c = u2.id;
    itpr.Vendor_Governance__c = u5.id;
    itpr.Legal_Assignee__c = u6.id;
    itpr.OwnerId = u3.Id; 
    itpr.Submitted_on_behalf_of__c = u29.Id;
    itpr.wave2_approver_1__c = u6.Id;
    itpr.wave1_approver_1__c = u2.Id;
    itpr.wave1_approver_2__c = u9.Id;
    itpr.wave1_approver_3__c = u10.Id;
    itpr.wave1_approver_4__c = u11.Id;
    itpr.wave1_approver_5__c = u12.Id;
    itpr.wave2_approver_2__c = u13.Id;
    itpr.wave2_approver_3__c = u14.Id;
    itpr.wave2_approver_4__c = u15.Id;
    itpr.wave2_approver_5__c = u16.Id;
    itpr.wave3_approver_1__c = u17.Id;
    itpr.wave3_approver_2__c = u18.Id;
    itpr.wave3_approver_3__c = u19.Id;
    itpr.wave3_approver_4__c = u20.Id;
    itpr.wave3_approver_5__c = u21.Id;
    itpr.delegated_Requestor__c = u7.id;
    itpr.transfered_Requestor__c = u7.id;
    insert itpr; 
    
        itpr.status__c = 'All Digital Initials Obtained';
        update itpr;
	
	 	//Test ITSES_FlagAllDigitalInitialsObtained class
        ITSES_FlagAllDigitalInitialsObtained skedule = new ITSES_FlagAllDigitalInitialsObtained();
        String timeOfRun = '0 0 * * * ?'; //every hour is scheduling 
        system.schedule('Test Schedule for All Digital Initials Obratined', timeOfRun, skedule);
        Test.stopTest();
	
	 List<ITPR__c> testITSES = [SELECT ID, Name, Status__c, Flag_as_All_Digital_Initials_Obtained__c from ITPR__c where Status__c = 'All Digital Initials Obtained' AND ID=:itpr.Id];
	
	for (ITPR__c testitpr: testITSES)
	{
		if(testitpr.Status__c=='All Digital Initials Obtained'){
			//do nothing..
		}
	}
	
		
		
	}

}