Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <inlineHelpText>Select the IT team that owns this agreement</inlineHelpText>
        <label>Business Area</label>
        <picklist>
            <picklistValues>
                <fullName>CONA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GIT: HQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services and Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Technology Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Risk Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottler Service Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIO Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCCC selling licneses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EU IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E&amp;A IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT: CIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT: CTO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT: CDO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT: Integration Planning, PMO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT: Global Dev Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT: OSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT: Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT: CIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT: Finance and Enabling Functions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT: Mktg, Comm, FR, Sales &amp; Decision Science</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT: Mktg &amp; R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT: CIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT: IT Operations &amp; Enabling Function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT:  Sales, Customer &amp; Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT: Product Supply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CAPEX1__c</fullName>
        <label>CAPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAPEX2__c</fullName>
        <label>CAPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAPEX3__c</fullName>
        <label>CAPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Category is the IT Procurement category for which you are requesting assistance.  Please see the attached PDF entitled “IT-SES Categories” for a depiction of the categories.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Assets &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application and SaaS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/Preferred Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Supplier Vendor Governance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Currency_Type__c</fullName>
        <inlineHelpText>Enter the currency for which you expect this effort to be billed.</inlineHelpText>
        <label>Currency Type</label>
        <picklist>
            <picklistValues>
                <fullName>$ USD</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>€ EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Guarantees__c</fullName>
        <label>Guarantees?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>If_No_Explain1__c</fullName>
        <inlineHelpText>Please provide an explanation as to why a Financial Analysis was not conducted for this new supplier.</inlineHelpText>
        <label>If No, Explain</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Long_Term_Commitments_Obligations__c</fullName>
        <label>Long-Term Commitments/Obligations?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Manager of the person in ‘Submitted On Behalf Of&apos;.</inlineHelpText>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXpnP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Supplier_Financial_Analysis_Done__c</fullName>
        <inlineHelpText>Finance should review D&amp;B or some other source to determine if entering into an agreement with this company is low or high risk.</inlineHelpText>
        <label>New Supplier Financial Analysis Done?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OPEX1__c</fullName>
        <label>OPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPEX2__c</fullName>
        <label>OPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPEX3__c</fullName>
        <label>OPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Statement__c</fullName>
        <inlineHelpText>Provide a description of the project which is associated with this request.</inlineHelpText>
        <label>Opportunity Statement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Portfolio_Department__c</fullName>
        <inlineHelpText>Please enter the name of the Department responsible for approving the contract</inlineHelpText>
        <label>Portfolio/Department</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Cost_Center1__c</fullName>
        <label>Project/Cost Center</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Cost_Center2__c</fullName>
        <label>Project/Cost Center</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Cost_Center3__c</fullName>
        <label>Project/Cost Center</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Cost_Center4__c</fullName>
        <label>Project/Cost Center</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Cost_Center5__c</fullName>
        <label>Project/Cost Center</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Cost_Center6__c</fullName>
        <label>Project/Cost Center</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Use this field to identify the type of assistance you are requesting.  Please see the attached PDF entitled “Request Type” for a definition of the different request types.</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change In Existing Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Of Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Access Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Legal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SFAS_133_Embedded_Derivatives__c</fullName>
        <inlineHelpText>Derivative includes certain commodity-based contracts and purchase agreements that contain embedded derivative-like structures (such as price caps and floors, cash settlement provisions).</inlineHelpText>
        <label>SFAS 133 - Embedded Derivatives?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <formula>CreatedBy.FirstName  + &quot; &quot; +CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is auto populated with the name of the person who is submitting the request</inlineHelpText>
        <label>Submitted By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter the name of the company which the contract will be with. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IT-SES</relationshipLabel>
        <relationshipName>ITPR1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year_1__c</fullName>
        <label>Year 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_2__c</fullName>
        <label>Year 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_3__c</fullName>
        <label>Year 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_4__c</fullName>
        <label>Year 4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_5__c</fullName>
        <label>Year 5</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/ITPR_PrintCoverSheetPDF.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : ITPR_PrintCoverSheetPDF
 *  Author           : Infosys
 *  Version History  : 1.0
 *  Creation         : 26/03/2014
 *  Assumptions      : N/A 
 *  Description      : This class is written to print the cover sheet details for a corresponding ITPR request.                                   
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/
public with sharing class ITPR_PrintCoverSheetPDF {
    
    /*variable declaration and initialization*/
    public ITPR__c objITPR {get; set;}
    //public List<Budget_Detail__c> lstBudgetDetails {get; set;}
    public List<ApprovalDetail> lstApprovalDetails {get; set;}
    
    /*end of variable declaration and initialization*/
        
    public ITPR_PrintCoverSheetPDF(ApexPages.StandardController controller) {
        //query the fields of the ITPR object to display on the cover sheet
        // added Currency_Type__c on query 5-5-2015
        objITPR = [Select Id, Name, Request_Type__c, Supplier_Name__r.Name, Submitted_By__c, Opportunity_Statement__c, Manager__r.Name,
                        Category__c, Business_Area__c, Portfolio_Department__c,Currency_Type__c, CAPEX1__c,CAPEX2__c,CAPEX3__c,OPEX1__c,OPEX2__c,OPEX3__c,
                        Project_Cost_Center1__c,Project_Cost_Center2__c,Project_Cost_Center3__c,
                        Project_Cost_Center4__c,Project_Cost_Center5__c,Project_Cost_Center6__c,
                        Long_Term_Commitments_Obligations__c, Guarantees__c, SFAS_133_Embedded_Derivatives__c, New_Supplier_Financial_Analysis_Done__c,
                        If_No_Explain1__c, Year_1__c, Year_2__c, Year_3__c, Year_4__c, Year_5__c, Thereafter__c,
                        Any_Noteworthy_Exceptional_Risk__c, Will_Supplier_Retain_Rights_To_New_IP__c, Are_There_Fees_For_Early_Termination__c,
                        If_Yes_Explain1__c, If_Yes_Explain2__c, If_Yes_Explain3__c, Cost_Avoidance__c, Savings__c,
                        Is_System_Participation_Allowed__c, If_Required_Has_IT_Security_Approved__c, If_Rqd_Has_Hosting_Cert_Team_Approved__c
                        From ITPR__c where Id = :controller.getId()];
        System.Debug('~~~~objITPR'+objITPR);
                        
        //query the approval fields
        List<ProcessInstance> lstApprovedSteps = [SELECT Id, (SELECT ActorId, OriginalActorId, stepStatus, Comments, CreatedDate FROM StepsAndWorkitems where stepStatus in ('Reassigned', 'Approved') order by OriginalActorId, CreatedDate)
                                                    FROM ProcessInstance where TargetObjectId = :controller.getId()];
            
       /*          List<ProcessInstance> lstApprovedSteps = [SELECT Id, (SELECT OriginalActorId, stepStatus, Comments, CreatedDate FROM StepsAndWorkitems where stepStatus = 'Approved')
                                                   FROM ProcessInstance where TargetObjectId = :controller.getId()];
        */
         System.debug('~~~lstApprovedSteps' +lstApprovedSteps);       
        lstApprovalDetails = new List<ApprovalDetail>();
         
        for(ProcessInstance pi : lstApprovedSteps){
        
            Map<Id, ProcessInstanceHistory> MapPIH = new Map<Id, ProcessInstanceHistory>();
            
            for(ProcessInstanceHistory wi : pi.StepsAndWorkitems){ If(wi.stepStatus == 'Reassigned') { MapPIH.put(wi.OriginalActorId, wi); }
                else { User Appr = GetApproverDetails(wi.ActorId); string Comments = wi.Comments; string Name = Appr.Name; string Department = Appr.ITPR_Department__c;
                     If(wi.ActorId != wi.OriginalActorId)  { ProcessInstanceHistory wi_temp; User OrgAppr = GetApproverDetails(wi.OriginalActorId);
                            
                            If(MapPIH.size() > 0) {  wi_temp = MapPIH.get(wi.OriginalActorId);   }
                        
                                If(wi_temp != null)   {  Comments = 'Reassigned from ' + OrgAppr.Name + ' : ' + Comments; }
                                else { Name = OrgAppr.Name; Department = OrgAppr.ITPR_Department__c;
                                       Comments = 'Approved by Business Admin (' + Appr.Name + ') on behalf of ' + OrgAppr.Name + ' : ' + Comments;
                                     }
                                                            }     
                    ApprovalDetail detail = new ApprovalDetail(Department, Name, wi.CreatedDate, Comments); lstApprovalDetails.add(detail);
                }
            }
        }        
    }
    
    public User GetApproverDetails(string UserId)
    {
        User usr; List<User> lstUser = [Select Name, ITPR_Department__c from User where Id = :UserId];
        
        If(lstUser.size() > 0) { usr = lstUser[0]; }
        return usr;
    }
    
    //wrapper class to capture approver details
    class ApprovalDetail{
        public String deptName {get; set;}
        public String approverName {get; set;}
        public DateTime dateApproved {get; set;}
        public String comments {get; set;}
        ApprovalDetail(String deptName, String approverName, DateTime dateApproved, String comments)
        { this.deptName = deptName; this.approverName = approverName; this.dateApproved = dateApproved; this.comments = comments; }
    }
}
/*********************************************END*****************************************************************************************************************/