Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Addressee_Name__c</fullName>
        <inlineHelpText>Please enter the name of the person to whom the NDA is to be presented.  This does not have to be the name of the person signing it, although many supplier&apos;s prefer that it is.</inlineHelpText>
        <label>Addressee Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAPEX1__c</fullName>
        <label>CAPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Category is the IT Procurement category for which you are requesting assistance.  Please see the attached PDF entitled “IT-SES Categories” for a depiction of the categories.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Assets &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application and SaaS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/Preferred Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Supplier Vendor Governance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Needed_By__c</fullName>
        <inlineHelpText>Please enter the date by which you would like this work request completed.  For example, if this is a request for an RFP, indicate the date by which you would like a supplier selection made and a contract executed with selected supplier</inlineHelpText>
        <label>Date Needed By</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Do_you_want_additional_approver__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do you want additional approver?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Duration_Of_NDA__c</fullName>
        <inlineHelpText>Please indicate the term for the NDA. Generally this is one year from the date on the NDA.</inlineHelpText>
        <label>Duration of NDA [# of year(s)]</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engagement_Of_A_New_Supplier__c</fullName>
        <inlineHelpText>Answer ‘Yes’ if this is a supplier that does not have a master agreement with The Company.</inlineHelpText>
        <label>Engagement Of A New Supplier?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Final_Budget_Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Budget Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finance_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>I_Have_Read_The_Provided_ITP_OLA__c</fullName>
        <inlineHelpText>Please refer to the “ITP OLA” document link under the “IT-SES Help” section on the left.</inlineHelpText>
        <label>I Have Read The Provided ITP OLA</label>
        <picklist>
            <picklistValues>
                <fullName>My Request Is Within The ITP OLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Request Is Not Within The ITP OLA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_this_NDA_to_be_mutual_or_will_the_com__c</fullName>
        <inlineHelpText>Indicate whether this project is for the Freestyle program.</inlineHelpText>
        <label>Is This a Freestyle Project?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7m</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Manager of the person in ‘Submitted On Behalf Of&apos;.</inlineHelpText>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXpnP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OPEX1__c</fullName>
        <label>OPEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Statement__c</fullName>
        <inlineHelpText>Provide a description of the project which is associated with this request.</inlineHelpText>
        <label>Opportunity Statement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <inlineHelpText>This is the TCCC company which has budget responsibility for the request.  This field drives both initial assignment and Chart of Authority during the approval process.</inlineHelpText>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>GIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Use this field to identify the type of assistance you are requesting.  Please see the attached PDF entitled “Request Type” for a definition of the different request types.</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change In Existing Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Of Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Access Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Legal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Indicates where the request is in the process flow.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending More Info Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Project Final Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Digital Initials Obtained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reactivate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed and Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Executed and Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_On_Behalf_Of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted On Behalf Of</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRX6CY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Email__c</fullName>
        <inlineHelpText>Enter the email address for the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Name__c</fullName>
        <inlineHelpText>Enter the name of the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Phone_Number__c</fullName>
        <inlineHelpText>Enter the telephone number for the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter the name of the company which the contract will be with. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IT-SES</relationshipLabel>
        <relationshipName>ITPR1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_s_Legal_Entity_Name__c</fullName>
        <inlineHelpText>Provide the legal entity name including type (e.g. Inc., LLC, Corp)</inlineHelpText>
        <label>Supplier&apos;s Legal Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Governance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Governance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU81</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave1_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wave1 Approved?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wave1_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbUs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave2_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wave2 Approved?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wave2_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXVRn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave3_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbVl</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/ITPR_TestSubmitForApproval.cls
@isTest
private class ITPR_TestSubmitForApproval
{

 static testMethod void populateAssignee3() 
    {
    Test.startTest();
map<string,Id> mapPNames = new map<string,Id>();
    List<profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name ='System Administrator'];
    List<User> usr = new List<User>();
    List<User> us = new List<User>();
    
    for(Profile p : lstProfiles){
    
    mapPNames.put(p.name, p.Id);
    
    }

     User u = new User(Alias = 'standt11', Email='standarduser@testorg.com',
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('ITSES - Requestor'),ITPR_Department__c =  'ITSES - Requestor',
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser34@testorg.com');
      us.add(u);
     // insert u;
      User u1 = new User(Alias = 'stand8t', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('ITSES - Finance'),ITPR_Department__c =  'ITSES - Finance', 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser35@testorg.com');
      us.add(u1);
      //insert u1;
      User u5 = new User(Alias = 'standt4', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('ITSES - Vendor Governance'),ITPR_Department__c =  'ITSES - Vendor Governance',
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser39@testorg.com');
     us.add(u5);
       User u6 = new User(Alias = 'standt5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId =  mapPnames.get('ITSES - Legal'),ITPR_Department__c =  'ITSES - Legal', 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser40@testorg.com');
      us.add(u6);
      User u2 = new User(Alias = 'standt6', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('ITSES - Procurement'),ITPR_Department__c =  'ITSES - Procurement', 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser36@testorg.com');
     us.add(u2);
      User u3 = new User(Alias = 'standt77', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('System Administrator'), 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser38@testorg.com');
     us.add(u3);
      
     insert us;
           
    Account acc = new Account();
    acc.Name = 'Infosys';
    insert acc;
      
    ITPR__c lt5 = new ITPR__c();
    lt5.Request_Type__c = 'Other Legal';
    lt5.Date_Needed_by__c =  Date.newInstance(2098, 1, 1);
    lt5.category__c = 'Telecom';
    lt5.Organization__c = 'CONA';
    lt5.Supplier_Name__c = acc.id;
    lt5.Supplier_Contact_Name__c = 'test';
    lt5.I_Have_Read_The_Provided_ITP_OLA__c = 'test';
    lt5.Supplier_Contact_Phone_Number__c = '9998889898';
    lt5.Engagement_Of_A_New_Supplier__c = 'No';
    lt5.Manager__C = u2.Id;
    lt5.Opportunity_Statement__c = 'test';
    lt5.CAPEX1__c = 200;
    lt5.OPEX1__c = 100;
    lt5.Supplier_s_Legal_Entity_Name__c = 'test';
    //lt5.Duration_Of_NDA__c = 30.0;
    lt5.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';  
    lt5.Supplier_Contact_email__c = 'test@test.com';
    lt5.Finance_Assignee__c = u1.Id;
    lt5.Addressee_Name__c = 'test';
    lt5.Status__c = 'Draft';
    lt5.Procurement_Assignee__c = null;
    lt5.Vendor_Governance__c = u5.id;
    lt5.Legal_Assignee__c = u6.id;
    lt5.OwnerId = u3.Id;
    lt5.Wave2_Approver_1__c = u6.id; 
    lt5.Wave1_Approver_1__c = u5.id;
    lt5.Submitted_on_behalf_of__c = null;
    

    insert lt5; 
    lt5.Wave1_Approved__c = False;
    lt5.Wave2_Approved__c = False;
    lt5.Status__c = 'Pending Project Final Budget';
    update lt5;
    
   /* lt5.Status__c = 'In Approvals';
    lt5.Final_Budget_Validated__c = True;
    lt5.Wave1_Approved__c = true;
    update lt5; */
    
    Test.stopTest();
   }
   
   static testMethod void populateAssignee4() 
    {
    Test.startTest();
map<string,Id> mapPNames = new map<string,Id>();
    List<profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name ='System Administrator'];
    List<User> usr = new List<User>();
    List<User> us = new List<User>();
    
    for(Profile p : lstProfiles){
    
    mapPNames.put(p.name, p.Id);
    
    }

     User u = new User(Alias = 'standt11', Email='standarduser@testorg.com',
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('ITSES - Requestor'),ITPR_Department__c =  'ITSES - Requestor', 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser34@testorg.com');
      us.add(u);
     // insert u;
      User u1 = new User(Alias = 'stand8t', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('ITSES - Finance'),ITPR_Department__c =  'ITSES - Finance', 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser35@testorg.com');
      us.add(u1);
      //insert u1;
      User u5 = new User(Alias = 'standt4', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('ITSES - Vendor Governance'),ITPR_Department__c =  'ITSES - Vendor Governance',
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser39@testorg.com');
     us.add(u5);
       User u6 = new User(Alias = 'standt5', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId =  mapPnames.get('ITSES - Legal'), ITPR_Department__c =  'ITSES - Legal',
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser40@testorg.com');
      us.add(u6);
      User u2 = new User(Alias = 'standt6', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('ITSES - Procurement'),ITPR_Department__c =  'ITSES - Procurement', 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser36@testorg.com');
     us.add(u2);
      User u3 = new User(Alias = 'standt77', Email='standarduser1@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = mapPnames.get('System Administrator'), 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser38@testorg.com');
     us.add(u3);
     insert us;
          
    Account acc = new Account();
    acc.Name = 'Infosys';
    insert acc;
      
    ITPR__c lt5 = new ITPR__c();
    lt5.Request_Type__c = 'Other Legal';
    lt5.Date_Needed_by__c =  Date.newInstance(2098, 1, 1);
    lt5.category__c = 'Telecom';
    lt5.Organization__c = 'CONA';
    lt5.Supplier_Name__c = acc.id;
    lt5.Supplier_Contact_Name__c = 'test';
    lt5.I_Have_Read_The_Provided_ITP_OLA__c = 'test';
    lt5.Supplier_Contact_Phone_Number__c = '9998889898';
    lt5.Engagement_Of_A_New_Supplier__c = 'No';
    lt5.Manager__C = u2.Id;
    lt5.Opportunity_Statement__c = 'test';
    lt5.CAPEX1__c = 200;
    lt5.OPEX1__c = 100;
    lt5.Supplier_s_Legal_Entity_Name__c = 'test';
   // lt5.Duration_Of_NDA__c = 30.0;
    lt5.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';  
    lt5.Supplier_Contact_email__c = 'test@test.com';
    lt5.Finance_Assignee__c = u1.Id;
    lt5.Addressee_Name__c = 'test';
    lt5.Status__c = 'Draft';
    lt5.Procurement_Assignee__c = null;
    lt5.Vendor_Governance__c = u5.id;
    lt5.Legal_Assignee__c = u6.id;
    lt5.OwnerId = u3.Id;
    lt5.Wave2_Approver_1__c = u2.Id; 
    lt5.Wave3_Approver_1__c = u6.Id; 
    lt5.Final_Budget_Validated__c = True;
    lt5.Wave1_Approved__c = true;
    lt5.Submitted_on_behalf_of__c = null;
    lt5.Do_you_want_additional_approver__c = False;
    lt5.If_Required_Has_The_TRB_Approved__c = 'Yes';
    lt5.If_Rqd_Has_Hosting_Cert_Team_Approved__c = 'Yes';
    
    insert lt5;
    /* Attachment attach=new Attachment();   
    attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=lt5.id;
        insert attach; */
     
   lt5.Wave2_Approver_1__c = null; 
    lt5.Wave1_Approved__c = False;
    lt5.Wave2_Approved__c = False;
    lt5.Status__c = 'Pending Project Final Budget';
    update lt5;
   /* 
    lt5.Status__c = 'In Approvals';
    lt5.Final_Budget_Validated__c = True;
    lt5.Wave1_Approved__c = true;
    update lt5; */
    
   /* try
    {
    delete attach;
    }
    catch(Exception e){}*/
     
     lt5.Status__c = 'All Digital Initials Obtained';  
    lt5.Wave1_Approved__c = true;
    lt5.Wave2_Approved__c = true;
    update lt5; 
    
        /*ITPR__c lt6 = new ITPR__c();
    lt6.Request_Type__c = 'Other Legal';
    lt6.Date_Needed_by__c =  Date.newInstance(2098, 1, 1);
    lt6.category__c = 'Telecom';
    lt6.Organization__c = 'CONA';
    lt6.Supplier_Name__c = acc.id;
    lt6.Supplier_Contact_Name__c = 'test';
    lt6.I_Have_Read_The_Provided_ITP_OLA__c = 'test';
    lt6.Supplier_Contact_Phone_Number__c = '9998889898';
    lt6.Engagement_Of_A_New_Supplier__c = 'No';
    lt6.Manager__C = u2.Id;
    lt6.Opportunity_Statement__c = 'test';
    lt6.CAPEX1__c = 200;
    lt6.OPEX1__c = 100;
    lt6.Supplier_s_Legal_Entity_Name__c = 'test';
   // lt6.Duration_Of_NDA__c = 30.0;
    lt6.Is_this_NDA_to_be_mutual_or_will_the_com__c = 'No';  
    lt6.Supplier_Contact_email__c = 'test@test.com';
    lt6.Finance_Assignee__c = u1.Id;
    lt6.Addressee_Name__c = 'test';
    lt6.Status__c = 'Draft';
    lt6.Procurement_Assignee__c = null;
    lt6.Vendor_Governance__c = u5.id;
    lt6.Legal_Assignee__c = u6.id;
    lt6.OwnerId = u3.Id;
    lt6.Wave2_Approver_1__c = u2.Id; 
    lt6.Wave3_Approver_1__c = u6.Id; 
    lt6.Final_Budget_Validated__c = True;
    lt6.Wave1_Approved__c = true;
    lt6.Submitted_on_behalf_of__c = null;
    lt6.Do_you_want_additional_approver__c = False;
    lt6.If_Required_Has_The_TRB_Approved__c = 'Yes';
    lt6.If_Rqd_Has_Hosting_Cert_Team_Approved__c = 'Yes';
    insert lt6;
     
   lt6.Wave2_Approver_1__c = null; 
    lt6.Wave1_Approved__c = False;
    lt6.Wave2_Approved__c = False;
    lt6.Status__c = 'Pending Project Final Budget';
    update lt6;*/

  /*  try{
    lt6.Status__c = 'In Approvals';
    lt6.Final_Budget_Validated__c = False;
    lt6.Wave1_Approved__c = true;
    update lt6;
} catch(Exception e){}*/
    
    
    
   /* lt5.Wave2_Approver_1__c = null; 
    lt5.Wave1_Approved__c = False;
    lt5.Wave2_Approved__c = False;
    
    lt5.Final_Budget_Validated__c = True;
    lt5.Wave1_Approved__c = true;
    
    lt5.Status__c = 'All Digital Initials Obtained';  
    lt5.Wave1_Approved__c = true;
    lt5.Wave2_Approved__c = true;
    update lt5;*/
     
   /* try{
    lt5.Status__c = 'In Approvals';
    lt5.Final_Budget_Validated__c = True;
    lt5.Wave1_Approved__c = true;
    lt5.wave3_Approver_1__c = null;
    lt5.wave2_Approver_1__c = null;
    update lt5;
    }*/
    
    Test.stopTest();
   
   }
 
   
   
}