Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Delegated_Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRYAdQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7m</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Manager of the person in ‘Submitted On Behalf Of&apos;.</inlineHelpText>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXpnP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Assignee__c</fullName>
        <label>Primary Assignee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Use this field to identify the type of assistance you are requesting.  Please see the attached PDF entitled “Request Type” for a definition of the different request types.</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change In Existing Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Of Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Access Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Legal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Indicates where the request is in the process flow.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending More Info Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Project Final Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Digital Initials Obtained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reactivate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed and Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Executed and Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <formula>CreatedBy.FirstName  + &quot; &quot; +CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is auto populated with the name of the person who is submitting the request</inlineHelpText>
        <label>Submitted By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_On_Behalf_Of__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitted On Behalf Of</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRX6CY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transfered_Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transfered Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IT_SES</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Governance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Governance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU81</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave1_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbUs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave3_Approver_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXbVl</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/ITSES_Additional_Attachment__c.object
<CustomObject>
    <description>Created for seperate attachment section for all user can attach the document at any stage.</description>
    <fields>
        <fullName>Attachment_Type__c</fullName>
        <label>Attachment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Normal Attachment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Final Attachment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IT_SES_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>IT-SES Request</label>
        <referenceTo>ITPR__c</referenceTo>
        <relationshipLabel>IT-SES Additional Attachments</relationshipLabel>
        <relationshipName>IT_SES_Additional_Attachments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>IT-SES Additional Attachment</label>
    <nameField>
        <displayFormat>AA-{0}</displayFormat>
        <label>Additional Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES Additional Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/ITSES_ViewAttachments.cls
/**************************************************************************************************************************************** 
****************************************************************************************************************************************     
*  Class            : ITSES_ViewAttachments
*  Author           : Capgemini 
*  Version History  : 1.0 
*  Creation         : 12/17/2014 
*  Assumptions      : N/A  
*  Description      : This class is the controller for the inline visualforce page which was emebedded on an ITPR object
                       This returns the list of additional attachments.                                    
**************************************************************************************************************************************** 
****************************************************************************************************************************************/

public class ITSES_ViewAttachments
{
    //Variables Initiialisation
    private ITPR__c objITPR {get; set;}
    public ITSES_Additional_Attachment__c objAA; 
        
    //Pagination
    public Integer pageSize = 5;
    Integer counter;
    
    public Id AttachId {get; set;}
    
    public boolean DisplayViewAttachments {get; set;}
    public boolean DisplayAddAttachments {get; set;}
    
    public Id ITPRid
    {
      get
      {
          If(ITPRid == null)
          {
              ITPRid = ApexPages.currentPage().getParameters().get('id');
              
              If(ITPRid == null)
              {
                  ITPRid = ApexPages.CurrentPage().getParameters().get('id1');
              }
          }
          return ITPRid;
      }
      set;
    }
    
    public User LoggedInUser
    {
      get
      {
          If(LoggedInUser == null)
          {
              LoggedInUser = [select Profile.Name,ITPR_Department__c from User where Id = :Userinfo.getUserId() limit 1];
          }
          return LoggedInUser;
      }
      set;
    }  
    
    public ITPR__c Check
    {
      get
      {
          If(objITPR == null)
          {
              objITPR = [select Id,Status__c,transfered_requestor__c,RecordTypeId,Request_Type__c,Manager__c,Wave1_Approver_1__c,Wave3_Approver_1__c,
                          Primary_Assignee__c,Vendor_Governance__c,Finance_Assignee__c, Legal_Assignee__c, Procurement_Assignee__c, 
                          Submitted_By__c,Delegated_Requestor__c,Submitted_On_Behalf_Of__c from ITPR__c where Id =:ITPRid];
          }
          return objITPR;
      }
      set;
    }
    
    public boolean IsUploadAllowed
    {
      get
      {
          If(Userinfo.getUserId() == Check.Delegated_Requestor__c || Userinfo.getUserId() == Check.Vendor_Governance__c || 
              Userinfo.getUserId() == Check.Finance_Assignee__c || Userinfo.getUserId() == Check.Legal_Assignee__c ||
              Userinfo.getUserId() == Check.Manager__c || Userinfo.getUserId() == Check.Procurement_Assignee__c ||
              (LoggedInUser.Profile.Name.Contains('ITSES') &&  LoggedInUser.Profile.Name.Contains('Business Administrator')) ||
              LoggedInUser.Profile.Name == System.Label.ITPR_System_Admin || LoggedInUser.Profile.Name == System.Label.ITPR_Requestor_profile)
          {
              return true;
          }
          else
          {
              return false;
          }
      }
    }
    
    public boolean IsDeleteAllowed
    {
      get
      {
          If(Userinfo.getUserId() == Check.Delegated_Requestor__c || Userinfo.getUserId() == Check.Vendor_Governance__c || 
              Userinfo.getUserId() == Check.Finance_Assignee__c || Userinfo.getUserId() == Check.Legal_Assignee__c ||
              Userinfo.getUserId() == Check.Manager__c || Userinfo.getUserId() == Check.Procurement_Assignee__c ||
              (LoggedInUser.Profile.Name.Contains('ITSES') &&  LoggedInUser.Profile.Name.Contains('Business Administrator')) ||
              LoggedInUser.Profile.Name == System.Label.ITPR_System_Admin || LoggedInUser.Profile.Name == System.Label.ITPR_Requestor_profile)
          {
              return true;
          }
          else
          {
              return false;
          }
      }
    }
    
    
    
    
    
    private List<Attachment> lstAttach;
    public list<Attachment> AttachmentsToDisplay{get; set;}    
        
    public List<Attachment> getAttachments()
    {
        return AttachmentsToDisplay;
    }
    
    public Boolean hasNextFind
    {
        get
        {
            if(counter >= lstAttach.size() || lstAttach.size() <= 0)
                return false;
            else
                return true;
        }
        set;
    }
    
    public Boolean hasPreviousFind
    {
        get
        {
            if((counter <= lstAttach.size()) && !(counter <= pageSize))
                return true;
            else
                return false;
        }
        set;
    }
    
    public List<Attachment> nextRequest()
    {
        system.debug('##############this.pageSize############'+this.pageSize);
        system.debug('##############this.counter############'+this.counter);
        List<Attachment> AttachmentsToDisplay_temp = new List<Attachment>();
        Integer startNumber;
        Integer size = lstAttach.size();
        if(hasNextFind )
        {
            if(size <= (this.counter + this.pageSize))
            {
                startNumber = this.counter; this.counter = size;
            }
            else
            {
                this.counter = (this.counter + this.pageSize); startNumber = (this.counter - this.pageSize);
            }
            
            for(Integer start = startnumber; start < this.counter; start++)
            {
                AttachmentsToDisplay_temp.add(lstAttach[start]);
            }
        }
        return AttachmentsToDisplay_temp;
    }
    
    public list<Attachment> previousRequest()
    {      
        List<Attachment> AttachmentsToDisplay_temp = new list<Attachment>(); 
        Integer size = lstAttach.size(); 
       system.debug('##############this.pageSize############'+this.pageSize);
        system.debug('##############this.counter############'+this.counter);
        if(this.counter == size)
        {
           if(math.mod(size, this.pageSize) >= 0)
          
           {    
               size = math.mod(size, this.pageSize);
           }
           else
           {
               this.counter = (size - this.pageSize);
           }    
            
        }
        else
        {
            this.counter = (this.counter - this.pageSize);
        }
        
        If(size > 0)
        {
            //for(Integer start = (counter - this.pageSize); start < this.counter; ++start)
            for(Integer start = 0; start < this.counter; ++start)
            {
                AttachmentsToDisplay_temp.add(lstAttach[start]);
            } 
        }
        return AttachmentsToDisplay_temp;
    }
    
    public void BindAttachments()
    {
        List<ITSES_Additional_Attachment__c> lstAA = [Select Id from ITSES_Additional_Attachment__c 
                    where IT_SES_Request__c = :ITPRid and Attachment_Type__c = 'Normal Attachment'];
        
         If(LstAA.size() > 0)    
         {        
             for(ITSES_Additional_Attachment__c AA : LstAA)
             {
                 lstAttach = [SELECT Description,Id,Name,ParentId, CreatedById, CreatedDate FROM Attachment where ParentId = :AA.Id order by CreatedDate desc];    
             }
             
             list<Attachment> AttachmentsToDisplay_temp = new list<Attachment>();
             If(counter == 0 || counter == null)
             {
                 Integer startNumber = 0;
                 If(pageSize > lstAttach.size())
                     counter = lstAttach.size();
                 else
                     counter = this.pageSize;
                 
                for(Integer start = startnumber; start < this.counter; start++)
                {
                    AttachmentsToDisplay_temp.add(lstAttach[start]);
                }
                
                AttachmentsToDisplay = AttachmentsToDisplay_temp;
             }
         }
         else
         {
             lstAttach = new List<Attachment>();
             AttachmentsToDisplay = lstAttach;
         }
    }
    
    //Controller
    public ITSES_ViewAttachments(ApexPages.StandardController controller)
    {
        DisplayViewAttachments = true;
        DisplayAddAttachments = false;
        BindAttachments();
                
    }
        
    //Actions
    public PageReference PreviousPage()
    {
        try
        {
            AttachmentsToDisplay = previousRequest();
        }
        catch (DMLException e) 
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error fetching records.')); return null;
        }
        
        return null;
    }
    
    public PageReference NextPage()
    {
        try
        {
            AttachmentsToDisplay = nextRequest();
        }
        catch (DMLException e) 
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error fetching records.')); return null;
        }
        
        return null;
    }
    
    public PageReference NewPage()
    {
        try 
        {
            //PageReference newocp = new PageReference('/apex/ITSES_Attachment?id1=' + ITPRid);
            //newocp.setRedirect(true);
            counter = 0;
            BindAttachments();
            DisplayViewAttachments = false;
            DisplayAddAttachments = true;
            return null;
        } 
        catch (DMLException e) 
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error redirecting to Attachments List.')); return null;
        }
        
        return null;
    }
    
    public PageReference DeleteAttachment()
    {
        try
        {
            List<Attachment> Lst_DelAttach = [SELECT Id FROM Attachment where Id = :AttachId];
            
            If(Lst_DelAttach.size() > 0)
            {
                for(Attachment att : Lst_DelAttach)
                {
                    delete att;
                }
            }
            
            //PageReference newocp = new PageReference('/apex/ITPR_Addl_Attachment_New_Page?id1=' + ITPRid);
            //newocp.setRedirect(true);
            
            counter = 0;
            BindAttachments();
            DisplayViewAttachments = true;
            DisplayAddAttachments = false;
            return null;
        }
        catch (DMLException e) 
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error deleting Attachment.')); return null;
        }
        
        return null;

    }
    
    
    // Code to upload the attachments
      public Attachment attachment {
       get {
          if (attachment == null)
            attachment = new Attachment();
          return attachment;
        }
          set;
      }
      
      //Actions
  public PageReference upload() {
  
    List<ITSES_Additional_Attachment__c> LstAA = [Select Id from ITSES_Additional_Attachment__c where IT_SES_Request__c = :ITPRid and Attachment_Type__c = 'Normal Attachment'];
    
    If(LstAA.size() > 0)
    {
        objAA = LstAA[0];
    }
    else
    {
        objAA = new ITSES_Additional_Attachment__c();
        objAA.IT_SES_Request__c = ITPRid;
        objAA.Attachment_Type__c = 'Normal Attachment';
        insert objAA;
    }
    
    attachment.OwnerId = UserInfo.getUserId();
    attachment.ParentId = objAA.Id; // the record the file is attached to
    attachment.IsPrivate = false;

    try 
    {
        insert attachment;
        //PageReference newocp = new PageReference('/apex/ITPR_Addl_Attachment_New_Page?id1=' + ITPRid);
        //newocp.setRedirect(true);
        counter = 0;
        BindAttachments();
        DisplayViewAttachments = true;
        DisplayAddAttachments = false;
        return null;
    } 
    catch (DMLException e) 
    {
      ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error uploading attachment')); return null;
    } 
    finally 
    {
      attachment = new Attachment(); 
    }
  }
  
  public PageReference cancel() 
  {   
        //PageReference newocp = new PageReference('/apex/ITPR_Addl_Attachment_New_Page?id1=' + ITPRid);
        //newocp.setRedirect(true);
        DisplayViewAttachments = true;
        DisplayAddAttachments = false;
        return null;
  }
}