Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Actionable_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Actionable Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Any_Noteworthy_Exceptional_Risk__c</fullName>
        <inlineHelpText>Answer ‘Yes’ if there are any risks to supply, cost escalations, etc. that approvers should be aware of. Describe the risks in the following explanation field.</inlineHelpText>
        <label>Any Noteworthy/Exceptional Risk?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Are_There_Exceptions_To_LoL__c</fullName>
        <label>Are There Exceptions To LoL?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Are_There_Fees_For_Early_Termination__c</fullName>
        <inlineHelpText>Answer ‘Yes’ if there is a penalty for early termination. Describe how the early termination fee is calculated in the following explanation field.</inlineHelpText>
        <label>Are There Fees For Early Termination?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assign_check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assign check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Category is the IT Procurement category for which you are requesting assistance.  Please see the attached PDF entitled “IT-SES Categories” for a depiction of the categories.</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Assets &amp; Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application and SaaS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/Preferred Suppliers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solution Delivery w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Support w/non-Preferred Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic Supplier Vendor Governance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Delegated_Finance_Assignee__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the assignee listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Finance Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Legal_Assignee__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the assignee listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Legal Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Procurement_Assignee__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the assignee listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Procurement Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Requestor_check__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the Requestor listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Requestor Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Vendor_Governance_User__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this box is checked, it means the assignee listed to the left has been temporarily delegated this request.</inlineHelpText>
        <label>Vendor Governance Delegated Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_not_Auto_Assign__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Changing organization, category, and/or request type normally re-assigns this request according to pre-determined assignment routing rules. Check this box to override the pre-loaded assignment routing rules and maintain present assignment as is</inlineHelpText>
        <label>Do not Auto Assign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <inlineHelpText>Enter the date this contract expires.</inlineHelpText>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Budget_Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Final Budget Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Finance_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7r</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>If_Yes_Explain1__c</fullName>
        <inlineHelpText>Detail the risks that should be called to the attention of the approvers.</inlineHelpText>
        <label>If Yes, Explain</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>If_Yes_Explain2__c</fullName>
        <inlineHelpText>Explain the situation(s) in which the supplier will retain any rights to newly developed IP under this effort.</inlineHelpText>
        <label>If Yes, Explain</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>If_Yes_Explain3__c</fullName>
        <inlineHelpText>Detail the early termination fees.</inlineHelpText>
        <label>If Yes, Explain</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>If_yes_Explain4__c</fullName>
        <inlineHelpText>Detail the early termination fees</inlineHelpText>
        <label>If Yes, Explain</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Legal_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7m</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <inlineHelpText>This is the TCCC company which has budget responsibility for the request.  This field drives both initial assignment and Chart of Authority during the approval process.</inlineHelpText>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>GIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIG IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCNA IT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Assignee__c</fullName>
        <label>Primary Assignee</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Procurement_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Procurement Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ITPRXU7c</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Use this field to identify the type of assistance you are requesting.  Please see the attached PDF entitled “Request Type” for a definition of the different request types.</inlineHelpText>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>NDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RFP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change In Existing Master</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter Of Termination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Access Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Legal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Standard_Indemnifications_Including_IP__c</fullName>
        <label>Standard Indemnifications, Including IP?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Standard_Representations_Warranties__c</fullName>
        <label>Standard Representations/Warranties?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Indicates where the request is in the process flow.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending More Info Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Project Final Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Digital Initials Obtained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reactivate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed and Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Executed and Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_By_Phone_Number__c</fullName>
        <label>Submitted By Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Contact_Email__c</fullName>
        <inlineHelpText>Enter the email address for the supplier representative for this effort. If you are requesting an RFI or RFP, leave this field blank.</inlineHelpText>
        <label>Supplier Contact Email</label>
        <type>Email</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RequestNotes__c.object
<CustomObject>
    <fields>
        <fullName>ITPR__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ITSES</label>
        <referenceTo>ITPR__c</referenceTo>
        <relationshipLabel>IT-SES Status Notes</relationshipLabel>
        <relationshipName>Request_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IT-SES Status Notes</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES Status Notes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/classes/ITPR_Test_Notes.cls
@IsTest
private class ITPR_Test_Notes { 

    static testMethod void test01(){
    Test.startTest();
        //Get Profile to use for creating users
        //Profile p = [Select Id From Profile where Name like '%ITSES%' limit 1];
        
        List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
        }
    }
        
        List<User> lstUsers = new List<User>();
        //Create Approver 1
        User approver1 = new User(
            username = 'test' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
             ITPR_Department__c = 'ITSES - Procurement',
            firstName = 'test',
            lastName = 'approver1',
            profileId = mapProfiles.get('ITSES - Procurement'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approver1);
        
        User approverFin = new User(
            username = 'test1' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
             ITPR_Department__c = 'ITSES - Finance',
            firstName = 'test',
                        lastName = 'approverFin',
            profileId = mapProfiles.get('ITSES - Finance'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approverFin);
        
        User approver2 = approver1.clone();
        approver2.username = 'test2' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver2);
        
        User approver3 = approver1.clone();
        approver3.username = 'test3' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver3);
        
        insert lstUsers;
        
        Account supplier = new Account(Name = 'TestSupplier');
        insert supplier;
        
        ITPR__c itpr = new ITPR__c(
            Actionable_Request__c = FALSE,
            Any_Noteworthy_Exceptional_Risk__c = 'Yes',
            Are_There_Exceptions_To_LoL__c = 'Yes',
            Are_There_Fees_For_Early_Termination__c = 'Yes',
            Assign_check__c = FALSE,
            Submitted_By_Phone_Number__c='46894686', 
            Category__c = 'Telecom',
            Delegated_Finance_Assignee__c = FALSE,
            Delegated_Legal_Assignee__c = TRUE,
            Delegated_Procurement_Assignee__c = TRUE,
            Delegated_Requestor_check__c = FALSE,
            Delegated_Vendor_Governance_User__c = FALSE,
            Do_not_Auto_Assign__c = FALSE,
            Expiration_Date__c = Date.today().addDays(20),
            Final_Budget_Validated__c = TRUE,
            Finance_Assignee__c = approverFin.Id,
            If_Yes_Explain1__c = 'test',
            If_Yes_Explain2__c = 'test',
            If_Yes_Explain3__c = 'test',
            If_yes_Explain4__c = 'test',
            //Legal_Assignee__c = approver2.Id,
            Organization__c = 'CONA',
            Primary_Assignee__c = 'Jackie Wang',
            //Procurement_Assignee__c = approver1.Id,
            Request_Type__c = 'New Master',
            Standard_Indemnifications_Including_IP__c = 'Yes',
            Standard_Representations_Warranties__c = 'Yes',
            Status__c = 'Pending Project Final Budget',
            Supplier_Contact_Email__c = 'test@infy.com',
            Supplier_Contact_Name__c = 'test',
            Supplier_Contact_Phone_Number__c = '1111111111',
            Supplier_Name__c = supplier.Id,
            //Vendor_Governance__c = approver3.Id,
            Wave1_Approved__c = FALSE,
            Wave1_Approver_1__c = approver1.Id,
            Wave1_Rejected__c = FALSE,
            Wave2_Approved__c = FALSE,
            Wave2_Approver_1__c = approver2.Id,
            Wave2_Rejected__c = FALSE,
            Wave3_Approver_1__c = approver3.Id,
            Wave3_Rejected__c = FALSE,
            Will_Supplier_Retain_Rights_To_New_IP__c = 'Yes',
            ownerId = approver1.Id
        );
        
        insert itpr;
        
        RequestNotes__c notes = new RequestNotes__c(
            ITPR__c = itpr.Id,
            Title__c = 'test',
            Comments__c = 'test'
        );
        
        insert notes;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(notes);
        ITPR_Notes itprNotesPage = new ITPR_Notes(sc);
        
        Boolean bShow = itprNotesPage.show;
        bShow = itprNotesPage.notshow;
        
        itprNotesPage.Save2();
        
        
        Test.stopTest();
    }
    
        static testMethod void test02(){
    Test.startTest();
        //Get Profile to use for creating users
        //Profile p = [Select Id From Profile where Name like '%ITSES%' limit 1];
        List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
        }
        }


        List<User> lstUsers = new List<User>();
        //Create Approver 1
        User approver1 = new User(
            username = 'test' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'approver1',
             ITPR_Department__c = 'ITSES - Procurement',
            profileId = mapProfiles.get('ITSES - Procurement'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approver1);
        
        User approverFin = new User(
             username = 'test1' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
             ITPR_Department__c = 'ITSES - Finance',
            firstName = 'test',
                        lastName = 'approverFin',
            profileId = mapProfiles.get('ITSES - Finance'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approverFin);
        
        User approver2 = approver1.clone();
        approver2.username = 'test2' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver2);
        
        User approver3 = approver1.clone();
        approver3.username = 'test3' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver3);
        
        insert lstUsers;
        
        Account supplier = new Account(Name = 'TestSupplier');
        insert supplier;
        
        ITPR__c itpr = new ITPR__c(
            Actionable_Request__c = FALSE,
            Any_Noteworthy_Exceptional_Risk__c = 'Yes',
            Are_There_Exceptions_To_LoL__c = 'Yes',
            Are_There_Fees_For_Early_Termination__c = 'Yes',
            Assign_check__c = FALSE,
            Category__c = 'Telecom',
            Submitted_By_Phone_Number__c='46894686', 
            Delegated_Finance_Assignee__c = FALSE,
            Delegated_Legal_Assignee__c = TRUE,
            Delegated_Procurement_Assignee__c = TRUE,
            Delegated_Requestor_check__c = FALSE,
            Delegated_Vendor_Governance_User__c = FALSE,
            Do_not_Auto_Assign__c = FALSE,
            Expiration_Date__c = Date.today().addDays(20),
            Final_Budget_Validated__c = TRUE,
            Finance_Assignee__c = approverFin.Id,
            If_Yes_Explain1__c = 'test',
            If_Yes_Explain2__c = 'test',
            If_Yes_Explain3__c = 'test',
            If_yes_Explain4__c = 'test',
            //Legal_Assignee__c = approver2.Id,
            Organization__c = 'CONA',
            Primary_Assignee__c = 'Jackie Wang',
            //Procurement_Assignee__c = approver1.Id,
            Request_Type__c = 'New Master',
            Standard_Indemnifications_Including_IP__c = 'Yes',
            Standard_Representations_Warranties__c = 'Yes',
            Status__c = 'Pending Project Final Budget',
            Supplier_Contact_Email__c = 'test@infy.com',
            Supplier_Contact_Name__c = 'test',
            Supplier_Contact_Phone_Number__c = '1111111111',
            Supplier_Name__c = supplier.Id,
            //Vendor_Governance__c = approver3.Id,
            Wave1_Approved__c = FALSE,
            Wave1_Approver_1__c = approver1.Id,
            Wave1_Rejected__c = FALSE,
            Wave2_Approved__c = FALSE,
            Wave2_Approver_1__c = approver2.Id,
            Wave2_Rejected__c = FALSE,
            Wave3_Approver_1__c = approver3.Id,
            Wave3_Rejected__c = FALSE,
            Will_Supplier_Retain_Rights_To_New_IP__c = 'Yes',
            ownerId = approver1.Id
        );
        
        insert itpr;
        
        RequestNotes__c notes = new RequestNotes__c(
            ITPR__c = itpr.Id,
            Title__c = 'test',
            Comments__c = 'test'
        );
        
        insert notes;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(notes);
        ITPR_Notes itprNotesPage = new ITPR_Notes(sc);
        
        Boolean bShow = itprNotesPage.show;
        bShow = itprNotesPage.notshow;
        
        itprNotesPage.check = itpr;
        
        itprNotesPage.check.Status__c = System.Label.ITPR_Submitted_Status;
        itprNotesPage.id2 = 'pendingmoreinfo';
        
        itprNotesPage.Save1();
        
        
        Test.stopTest();
    }
    
            static testMethod void test03(){
    Test.startTest();
        //Get Profile to use for creating users
        //Profile p = [Select Id From Profile where Name like '%ITSES%' limit 1];
        
        List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
             }
        }


   
        List<User> lstUsers = new List<User>();
        //Create Approver 1
        User approver1 = new User(
            username = 'test' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'approver1',
             ITPR_Department__c = 'ITSES - Procurement',
            profileId = mapProfiles.get('ITSES - Procurement'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approver1);
        
         User approverFin = new User(
            username = 'test1' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test123@test.com',
             ITPR_Department__c = 'ITSES - Finance',
            firstName = 'test',
             lastName = 'approverFin',
            profileId = mapProfiles.get('ITSES - Finance'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approverFin);
        
        User approver2 = approver1.clone();
        approver2.username = 'test2' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver2);
        
        User approver3 = approver1.clone();
        approver3.username = 'test3' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver3);
        
        insert lstUsers;
        
        Account supplier = new Account(Name = 'TestSupplier');
        insert supplier;
        
        ITPR__c itpr = new ITPR__c(
            Actionable_Request__c = FALSE,
            Any_Noteworthy_Exceptional_Risk__c = 'Yes',
            Are_There_Exceptions_To_LoL__c = 'Yes',
            Are_There_Fees_For_Early_Termination__c = 'Yes',
            Assign_check__c = FALSE,
            Category__c = 'Telecom',
            Submitted_By_Phone_Number__c='46894686', 
            Delegated_Finance_Assignee__c = FALSE,
            Delegated_Legal_Assignee__c = TRUE,
            Delegated_Procurement_Assignee__c = TRUE,
            Delegated_Requestor_check__c = FALSE,
            Delegated_Vendor_Governance_User__c = FALSE,
            Do_not_Auto_Assign__c = FALSE,
            Expiration_Date__c = Date.today().addDays(20),
            Final_Budget_Validated__c = TRUE,
            Finance_Assignee__c = approverFin.Id,
            If_Yes_Explain1__c = 'test',
            If_Yes_Explain2__c = 'test',
            If_Yes_Explain3__c = 'test',
            If_yes_Explain4__c = 'test',
            //Legal_Assignee__c = approver2.Id,
            Organization__c = 'CONA',
            Primary_Assignee__c = 'Jackie Wang',
            //Procurement_Assignee__c = approver1.Id,
            Request_Type__c = 'New Master',
            Standard_Indemnifications_Including_IP__c = 'Yes',
            Standard_Representations_Warranties__c = 'Yes',
            Status__c = 'Pending Project Final Budget',
            Supplier_Contact_Email__c = 'test@infy.com',
            Supplier_Contact_Name__c = 'test',
            Supplier_Contact_Phone_Number__c = '1111111111',
            Supplier_Name__c = supplier.Id,
            //Vendor_Governance__c = approver3.Id,
            Wave1_Approved__c = FALSE,
            Wave1_Approver_1__c = approver1.Id,
            Wave1_Rejected__c = FALSE,
            Wave2_Approved__c = FALSE,
            Wave2_Approver_1__c = approver2.Id,
            Wave2_Rejected__c = FALSE,
            Wave3_Approver_1__c = approver3.Id,
            Wave3_Rejected__c = FALSE,
            Will_Supplier_Retain_Rights_To_New_IP__c = 'Yes',
            ownerId = approver1.Id
        );
        
        insert itpr;
        
        RequestNotes__c notes = new RequestNotes__c(
            ITPR__c = itpr.Id,
            Title__c = 'test',
            Comments__c = 'test'
        );
        
        insert notes;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(notes);
        ITPR_Notes itprNotesPage = new ITPR_Notes(sc);
        
        Boolean bShow = itprNotesPage.show;
        bShow = itprNotesPage.notshow;
        
        itprNotesPage.check = itpr;
        
        itprNotesPage.check.Status__c = System.Label.ITPR_In_Process_Status;
        itprNotesPage.id2 = 'pendingbudget';
        
        itprNotesPage.Save1();
        
        
        Test.stopTest();
    }
    
                static testMethod void test04(){
    Test.startTest();
        //Get Profile to use for creating users
        //Profile p = [Select Id From Profile where Name like '%ITSES%' limit 1];
        List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
        }
        
        }
        List<User> lstUsers = new List<User>();
        //Create Approver 1
        User approver1 = new User(
            username = 'test' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'approver1',
             ITPR_Department__c = 'ITSES - Procurement',
            profileId = mapProfiles.get('ITSES - Procurement'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approver1);
        
        
    User approverFin = new User(
             username = 'test1' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test111@test.com',
             ITPR_Department__c = 'ITSES - Finance',
            firstName = 'test',
                         lastName = 'approverFin',
            profileId = mapProfiles.get('ITSES - Finance'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approverFin);
        
        User approver2 = approver1.clone();
        approver2.username = 'test2' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver2);
        
        User approver3 = approver1.clone();
        approver3.username = 'test3' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver3);
        
        insert lstUsers;
        
        Account supplier = new Account(Name = 'TestSupplier');
        insert supplier;
        
        ITPR__c itpr = new ITPR__c(
            Actionable_Request__c = FALSE,
            Any_Noteworthy_Exceptional_Risk__c = 'Yes',
            Are_There_Exceptions_To_LoL__c = 'Yes',
            Are_There_Fees_For_Early_Termination__c = 'Yes',
            Assign_check__c = FALSE,
            Category__c = 'Telecom',
            Delegated_Finance_Assignee__c = FALSE,
            Delegated_Legal_Assignee__c = TRUE,
            Delegated_Procurement_Assignee__c = TRUE,
            Delegated_Requestor_check__c = FALSE,
            Delegated_Vendor_Governance_User__c = FALSE,
            Do_not_Auto_Assign__c = FALSE,
            Expiration_Date__c = Date.today().addDays(20),
            Final_Budget_Validated__c = TRUE,
            Submitted_By_Phone_Number__c='46894686', 
            Finance_Assignee__c = approverFin.Id,
            If_Yes_Explain1__c = 'test',
            If_Yes_Explain2__c = 'test',
            If_Yes_Explain3__c = 'test',
            If_yes_Explain4__c = 'test',
            //Legal_Assignee__c = approver2.Id,
            Organization__c = 'CONA',
            Primary_Assignee__c = 'Jackie Wang',
            //Procurement_Assignee__c = approver1.Id,
            Request_Type__c = 'New Master',
            Standard_Indemnifications_Including_IP__c = 'Yes',
            Standard_Representations_Warranties__c = 'Yes',
            Status__c = 'Pending Project Final Budget',
            Supplier_Contact_Email__c = 'test@infy.com',
            Supplier_Contact_Name__c = 'test',
            Supplier_Contact_Phone_Number__c = '1111111111',
            Supplier_Name__c = supplier.Id,
            //Vendor_Governance__c = approver3.Id,
            Wave1_Approved__c = FALSE,
            Wave1_Approver_1__c = approver1.Id,
            Wave1_Rejected__c = FALSE,
            Wave2_Approved__c = FALSE,
            Wave2_Approver_1__c = approver2.Id,
            Wave2_Rejected__c = FALSE,
            Wave3_Approver_1__c = approver3.Id,
            Wave3_Rejected__c = FALSE,
            Will_Supplier_Retain_Rights_To_New_IP__c = 'Yes',
            ownerId = approver1.Id
        );
        
        insert itpr;
        
        RequestNotes__c notes = new RequestNotes__c(
            ITPR__c = itpr.Id,
            Title__c = 'test',
            Comments__c = 'test'
        );
        
        insert notes;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(notes);
        ITPR_Notes itprNotesPage = new ITPR_Notes(sc);
        
        Boolean bShow = itprNotesPage.show;
        bShow = itprNotesPage.notshow;
        
        itprNotesPage.check = itpr;
        
        itprNotesPage.check.Status__c = System.Label.ITPR_In_Process_Status;
        itprNotesPage.id2 = 'onhold';
        
        itprNotesPage.Save1();
        
        
        Test.stopTest();
    }
    
 static testMethod void test05(){
    Test.startTest();
        //Get Profile to use for creating users
        //Profile p = [Select Id From Profile where Name like '%ITSES%' limit 1];
        
        List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
        }}
        
        
        List<User> lstUsers = new List<User>();
        //Create Approver 1
        User approver1 = new User(
            username = 'test' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'approver1',
             ITPR_Department__c = 'ITSES - Procurement',
            profileId = mapProfiles.get('ITSES - Procurement'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approver1);
        
        User approverFin = new User(
            username = 'test1' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test123@test.com',
             ITPR_Department__c = 'ITSES - Finance',
            firstName = 'test',
                         lastName = 'approverFin',
            profileId = mapProfiles.get('ITSES - Finance'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approverFin);
        
        User approver2 = approver1.clone();
        approver2.username = 'test2' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver2);
        
        User approver3 = approver1.clone();
        approver3.username = 'test3' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver3);
        
        insert lstUsers;
        
        Account supplier = new Account(Name = 'TestSupplier');
        insert supplier;
        
        ITPR__c itpr = new ITPR__c(
            Actionable_Request__c = FALSE,
            Any_Noteworthy_Exceptional_Risk__c = 'Yes',
            Are_There_Exceptions_To_LoL__c = 'Yes',
            Are_There_Fees_For_Early_Termination__c = 'Yes',
            Assign_check__c = FALSE,
            Category__c = 'Telecom',
            Delegated_Finance_Assignee__c = FALSE,
            Delegated_Legal_Assignee__c = TRUE,
            Delegated_Procurement_Assignee__c = TRUE,
            Delegated_Requestor_check__c = FALSE,
            Delegated_Vendor_Governance_User__c = FALSE,
            Do_not_Auto_Assign__c = FALSE,
            Expiration_Date__c = Date.today().addDays(20),
            Submitted_By_Phone_Number__c='46894686', 
            Final_Budget_Validated__c = TRUE,
            Finance_Assignee__c = approverFin.Id,
            If_Yes_Explain1__c = 'test',
            If_Yes_Explain2__c = 'test',
            If_Yes_Explain3__c = 'test',
            If_yes_Explain4__c = 'test',
            //Legal_Assignee__c = approver2.Id,
            Organization__c = 'CONA',
            Primary_Assignee__c = 'Jackie Wang',
            //Procurement_Assignee__c = approver1.Id,
            Request_Type__c = 'New Master',
            Standard_Indemnifications_Including_IP__c = 'Yes',
            Standard_Representations_Warranties__c = 'Yes',
            Status__c = 'Pending Project Final Budget',
            Supplier_Contact_Email__c = 'test@infy.com',
            Supplier_Contact_Name__c = 'test',
            Supplier_Contact_Phone_Number__c = '1111111111',
            Supplier_Name__c = supplier.Id,
            //Vendor_Governance__c = approver3.Id,
            Wave1_Approved__c = FALSE,
            Wave1_Approver_1__c = approver1.Id,
            Wave1_Rejected__c = FALSE,
            Wave2_Approved__c = FALSE,
            Wave2_Approver_1__c = approver2.Id,
            Wave2_Rejected__c = FALSE,
            Wave3_Approver_1__c = approver3.Id,
            Wave3_Rejected__c = FALSE,
            Will_Supplier_Retain_Rights_To_New_IP__c = 'Yes',
            ownerId = approver1.Id
        );
        
        insert itpr;
        
        RequestNotes__c notes = new RequestNotes__c(
            ITPR__c = itpr.Id,
            Title__c = 'test',
            Comments__c = 'test'
        );
        
        insert notes;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(notes);
        ITPR_Notes itprNotesPage = new ITPR_Notes(sc);
        
        Boolean bShow = itprNotesPage.show;
        bShow = itprNotesPage.notshow;
        
        itprNotesPage.check = itpr;
        
        itprNotesPage.check.Status__c = System.Label.ITPR_In_Process_Status;
        itprNotesPage.id2 = 'cancel';
        
        itprNotesPage.Save1();
        
        
        Test.stopTest();
    }

   static testMethod void test06(){
    Test.startTest();
        //Get Profile to use for creating users
        //Profile p = [Select Id From Profile where Name like '%ITSES%' limit 1];
        
        List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
        }
        }
        List<User> lstUsers = new List<User>();
        //Create Approver 1
        User approver1 = new User(
            username = 'test' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
            firstName = 'test',
            lastName = 'approver1',
          profileId = mapProfiles.get('ITSES - Procurement'),
             ITPR_Department__c = 'ITSES - Procurement',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approver1);
        
        
    User approverFin = new User(
             username = 'test1' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test123@test.com',
             ITPR_Department__c = 'ITSES - Finance',
            firstName = 'test',
             lastName = 'approverFin',
            profileId = mapProfiles.get('ITSES - Finance'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approverFin);
        
        User approver2 = approver1.clone();
        approver2.username = 'test2' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver2);
        
        User approver3 = approver1.clone();
        approver3.username = 'test3' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver3);
        
        insert lstUsers;
        
        Account supplier = new Account(Name = 'TestSupplier');
        insert supplier;
        
        ITPR__c itpr = new ITPR__c(
            Actionable_Request__c = FALSE,
            Any_Noteworthy_Exceptional_Risk__c = 'Yes',
            Are_There_Exceptions_To_LoL__c = 'Yes',
            Are_There_Fees_For_Early_Termination__c = 'Yes',
            Assign_check__c = FALSE,
            Category__c = 'Telecom',
            Delegated_Finance_Assignee__c = FALSE,
            Delegated_Legal_Assignee__c = TRUE,
            Delegated_Procurement_Assignee__c = TRUE,
            Delegated_Requestor_check__c = FALSE,
            Delegated_Vendor_Governance_User__c = FALSE,
            Do_not_Auto_Assign__c = FALSE,
            Expiration_Date__c = Date.today().addDays(20),
            Final_Budget_Validated__c = TRUE,
            Finance_Assignee__c = approverFin.Id,
            If_Yes_Explain1__c = 'test',
            If_Yes_Explain2__c = 'test',
            If_Yes_Explain3__c = 'test',
            If_yes_Explain4__c = 'test',
            //Legal_Assignee__c = approver2.Id,
            Organization__c = 'CONA',
            Primary_Assignee__c = 'Jackie Wang',
            //Procurement_Assignee__c = approver1.Id,
            Request_Type__c = 'New Master',
            Standard_Indemnifications_Including_IP__c = 'Yes',
            Standard_Representations_Warranties__c = 'Yes',
            Status__c = 'Pending Project Final Budget',
            Supplier_Contact_Email__c = 'test@infy.com',
            Supplier_Contact_Name__c = 'test',
            Supplier_Contact_Phone_Number__c = '1111111111',
            Supplier_Name__c = supplier.Id,
            //Vendor_Governance__c = approver3.Id,
            Wave1_Approved__c = FALSE,
            Wave1_Approver_1__c = approver1.Id,
            Wave1_Rejected__c = FALSE,
            Wave2_Approved__c = FALSE,
            Wave2_Approver_1__c = approver2.Id,
            Wave2_Rejected__c = FALSE,
            Wave3_Approver_1__c = approver3.Id,
            Wave3_Rejected__c = FALSE,
            Will_Supplier_Retain_Rights_To_New_IP__c = 'Yes',
            Submitted_By_Phone_Number__c='46894686', 
            ownerId = approver1.Id
        );
        
        insert itpr;
        
        RequestNotes__c notes = new RequestNotes__c(
            ITPR__c = itpr.Id,
            Title__c = 'test',
            Comments__c = 'test'
        );
        
        insert notes;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(notes);
        ITPR_Notes itprNotesPage = new ITPR_Notes(sc);
        
        Boolean bShow = itprNotesPage.show;
        bShow = itprNotesPage.notshow;
        
        itprNotesPage.check = itpr;
        
        itprNotesPage.check.Status__c = System.Label.ITPR_In_Process_Status;
        itprNotesPage.id2 = 'complete';
        
        itprNotesPage.Save1();
        
        
        Test.stopTest();
    }
    
                       static testMethod void test07(){
    Test.startTest();
        //Get Profile to use for creating users
        //Profile p = [Select Id From Profile where Name like '%ITSES%' limit 1];
        
        
List<Profile> lstProfiles = [select Id,Name from Profile where Name like 'ITSES%' or Name = 'System Administrator'];
    Map<String,String> mapProfiles = new Map<String, String>();
    if(lstProfiles != null && lstProfiles.size() > 0) {
        for(Profile p : lstProfiles){
           mapProfiles.put(p.name,p.Id); 
        }
       } 
        List<User> lstUsers = new List<User>();
        //Create Approver 1
        User approver1 = new User(
            username = 'test' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
           email = 'test123@test.com',
            firstName = 'test',
            lastName = 'approver1',
             ITPR_Department__c = 'ITSES - Procurement',
            profileId = mapProfiles.get('ITSES - Procurement'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approver1);
        
        User approverFin = new User(
             username = 'test1' + DateTime.now().getTime() + '@test.com',
            alias = 'test1111',
            email = 'test@test.com',
             ITPR_Department__c = 'ITSES - Finance',
            firstName = 'test',
            lastName = 'approverFin',
            profileId = mapProfiles.get('ITSES - Finance'),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US'
        );
        lstUsers.add(approverFin);
        
        User approver2 = approver1.clone();
        approver2.username = 'test2' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver2);
        
        User approver3 = approver1.clone();
        approver3.username = 'test3' + DateTime.now().getTime() + '@test.com';
        lstUsers.add(approver3);
        
        insert lstUsers;
        
        Account supplier = new Account(Name = 'TestSupplier');
        insert supplier;
        
        ITPR__c itpr = new ITPR__c(
            Actionable_Request__c = FALSE,
            Any_Noteworthy_Exceptional_Risk__c = 'Yes',
            Are_There_Exceptions_To_LoL__c = 'Yes',
            Are_There_Fees_For_Early_Termination__c = 'Yes',
            Assign_check__c = FALSE,
            Category__c = 'Telecom',
            Delegated_Finance_Assignee__c = FALSE,
            Delegated_Legal_Assignee__c = TRUE,
            Delegated_Procurement_Assignee__c = TRUE,
            Delegated_Requestor_check__c = FALSE,
            Delegated_Vendor_Governance_User__c = FALSE,
            Do_not_Auto_Assign__c = FALSE,
            Expiration_Date__c = Date.today().addDays(20),
            Final_Budget_Validated__c = TRUE,
            Finance_Assignee__c = approverFin.Id,
            If_Yes_Explain1__c = 'test',
            If_Yes_Explain2__c = 'test',
            If_Yes_Explain3__c = 'test',
            If_yes_Explain4__c = 'test',
            //Legal_Assignee__c = approver2.Id,
            Organization__c = 'CONA',
            Primary_Assignee__c = 'Jackie Wang',
            //Procurement_Assignee__c = approver1.Id,
            Request_Type__c = 'New Master',
            Standard_Indemnifications_Including_IP__c = 'Yes',
            Standard_Representations_Warranties__c = 'Yes',
            Status__c = 'Pending Project Final Budget',
            Supplier_Contact_Email__c = 'test@infy.com',
            Supplier_Contact_Name__c = 'test',
            Supplier_Contact_Phone_Number__c = '1111111111',
            Supplier_Name__c = supplier.Id,
            //Vendor_Governance__c = approver3.Id,
            Wave1_Approved__c = FALSE,
            Wave1_Approver_1__c = approver1.Id,
            Wave1_Rejected__c = FALSE,
            Wave2_Approved__c = FALSE,
            Wave2_Approver_1__c = approver2.Id,
            Wave2_Rejected__c = FALSE,
            Wave3_Approver_1__c = approver3.Id,
            Wave3_Rejected__c = FALSE,
            Will_Supplier_Retain_Rights_To_New_IP__c = 'Yes',
            ownerId = approver1.Id,
            Submitted_By_Phone_Number__c='46894686' 
        );
        
        insert itpr;
        
        RequestNotes__c notes = new RequestNotes__c(
            ITPR__c = itpr.Id,
            Title__c = 'test',
            Comments__c = 'test'
        );
        
        insert notes;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(notes);
        ITPR_Notes itprNotesPage = new ITPR_Notes(sc);
        
        Boolean bShow = itprNotesPage.show;
        bShow = itprNotesPage.notshow;
        
        itprNotesPage.check = itpr;
        
        itprNotesPage.check.Status__c = System.Label.ITPR_All_Digital_Initials_Obtained_Status;
        itprNotesPage.id2 = 'notexecuted';
        
        itprNotesPage.Save1();
        
        
        Test.stopTest();
    }
}