Jann 30/objects/ITPR__c.object
<CustomObject>
    <fields>
        <fullName>Flag_as_All_Digital_Initials_Obtained__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is to fix the current issue of no email notification when ITSES request is set to &quot;All Digital Initials Obtained&quot; status</description>
        <label>Flag as All Digital Initials Obtained</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Indicates where the request is in the process flow.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending More Info Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Project Final Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Digital Initials Obtained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reactivate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed and Filed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Executed and Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>IT-SES Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{00000}</displayFormat>
        <label>IT-SES ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT-SES</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/ITSES_FlagAllDigitalInitialsObtained.cls
global class ITSES_FlagAllDigitalInitialsObtained implements Schedulable, Database.Batchable<sObject> {   
	String query='SELECT Name, Status__c, Flag_as_All_Digital_Initials_Obtained__c from ITPR__c where Flag_as_All_Digital_Initials_Obtained__c=FALSE AND Status__c =\''+System.Label.ITPR_All_Digital_Initials_Obtained_Status+'\'';
	global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('RSAS value of query ' + query);
        return Database.getQueryLocator(this.query);
    } 
	
	global void execute(Database.BatchableContext BC,  List<ITPR__c> ITSESlist) {
        this.FlagAllDigitalInitialsObtained(ITSESlist);
    }
	
	 global void FlagAllDigitalInitialsObtained(List<ITPR__c> itseslst) {
        
        system.debug('RSAS went to the FlagAllDigitalInitialsObtained part');
        
        List<ITPR__c> ITSESListToUpdate = new List<ITPR__c>();
        
        
        for(ITPR__c eachITSES: itseslst) {
            if(eachITSES.Status__c== System.Label.ITPR_All_Digital_Initials_Obtained_Status && eachITSES.Flag_as_All_Digital_Initials_Obtained__c==False)
            {
            eachITSES.Flag_as_All_Digital_Initials_Obtained__c=True;
            ITSESListToUpdate.add(eachITSES);
            }          
        }

        if(ITSESListToUpdate.size() > 0) {
            system.debug('RSAS went to the Update part' + ITSESListToUpdate.size());
           try {
                update ITSESListToUpdate;
                 system.debug('RSAS ITSESListToUpdate Updated Successfully');
                } catch (Exception e) {
                System.debug('Update exception: ' + e.getMessage());
            }

        } 
         
    }
    
    global void execute(SchedulableContext sc) {
        Database.executeBatch(this); 
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }    



}