Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>CO_CREATOR_Name__c</fullName>
        <label>CO-CREATOR Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ControlNumber__c</fullName>
        <inlineHelpText>A unique identifier will be assigned automatically by the RFA system when the request is created.</inlineHelpText>
        <label>Control Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExecutiveSummary__c</fullName>
        <label>Executive Summary *</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FunctionalCurrencyNameFC__c</fullName>
        <formula>Functional_Currency__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Functional Currency Name (FC)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The three-character abbreviation for the functional currency in which the request amount will be denominated.</inlineHelpText>
        <label>Functional Currency (FC) *</label>
        <referenceTo>ARE_RFA__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LOC_Name__c</fullName>
        <label>LOC Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LevelStage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Level / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POC_Name__c</fullName>
        <label>POC Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Category__c</fullName>
        <label>Policy Category*</label>
        <picklist>
            <picklistValues>
                <fullName>1.1 - Introduction to Finance Manuals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.2 - Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.3 - Common Innovation Standards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1 - Internal Controls Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.2 - Delegation of Authority &amp; Related Governance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.3 - Section 404 Internal Controls Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.4 - Segretation of Duties, Risk Management &amp; Violation Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.5 - Audit &amp; Non-Audit Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.6 - Certification &amp; Representation Letters Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.7 - Outsourcing Controls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.8 - Government Payment &amp; Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.9 - US Foreign Trade Controls &amp; Anti-Boycott Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.10 - Postmix Revenue Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.11 - Financial Confirmations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.1 - General Ledger &amp; Closing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.2 - Information Access/Records Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.3 - Economic Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.4 - Income Statement Variance Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.5 - Statement of Cash Flows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.6 - Beverage Partners Worldwide (BPW)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.1 - Consolidated Affiliate and Administrative Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.4 - Entity Creation, Liquidation &amp; Headquarters Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.5 - Annual Clearing Entries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.1 - Procurement, Purchasing &amp; Payables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.2 - Unclaimed Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.1 - Cash Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.2 - Debt &amp; Equity Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.3 - Employee Retirement Plan Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.1 - Currency Remeasurement &amp; Translation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.2 - Currency Hedging</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumberName__c</fullName>
        <formula>ProfitCenterNumber__r.Name  + &quot; - &quot; +  ProfitCenterName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Profit Center Number/Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>TCCC portion only. Request Amt is based on DOA/LCOA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amt, etc.</inlineHelpText>
        <label>Request Amount (FC) *</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestAmountUSD__c</fullName>
        <formula>RequestAmountFunctionalCurrency__c *ARERate__c</formula>
        <inlineHelpText>TCCC portion only. Request Amt is based on DOA/LCOA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amt, etc.</inlineHelpText>
        <label>Request Amount (USD)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase.  (e.g.,  Write-off  45 non-working vending machines in Atlanta sales center)</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Summary__c</fullName>
        <inlineHelpText>Refer to ‘Request Summary Guidelines’ above</inlineHelpText>
        <label>Request Summary *</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReturnReason__c</fullName>
        <description>Comments to be entered by a Location Coordinator or Capital Management team member when an RFA is placed into Return to Sender Stage.</description>
        <label>Return Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFATriggerHelperClass.cls
/* Author,email :     Mads Pascua , mpascua@coca-cola.com
*  Date Create  :     Nov 8, 2013
*  Description  :     The Apex Class that contains methods used by the main trigger for RFA_RFATrigger
*                    
****** REVISION HISTORY*****
*  Author,email : 
*  Date Revised : 
*  Description  : 
*
*
*/

public class RFATriggerHelperClass{

/**
*  @ Description : This method contains logic to notify local ccordinator when the RFA Stage is set to
*                  "Return To Sender" or "Pre-Circulation"                    
*  @ param : Set<String>, Map<String, RFA__c>
*  @ return : void
*/
public  static void notifyLocalCoordinator2(Map<Id, String> levelMap,  Map<String, String> rfaMap){
        System.debug('\n level map :'+levelMap);
        System.debug('\n rfa map :'+rfaMap);
          
        Map<String, Map<String, RecordType>> RECORDTYPESMAP = RFAGlobalConstants.RECORDTYPESMAP;
        Map<String, RecordType> rfaRecordTypeMap = RECORDTYPESMAP.get(Schema.sObjectType.RFA__c.getName());
    
        Set<String> profitCenterNumbers = new Set<String>();
        Set<String> uniqueLevels = new Set<String>();
         
        RFA__c currRFA=[SELECT Id,Name,FunctionalCurrencyNameFC__c, RecordTypeId,Functional_Currency__c,RequestAmountFunctionalCurrency__c,RequestAmountUSD__c,ExecutiveSummary__c, POC_Name__c,CO_CREATOR_Name__c,LOC_Name__c, Stage__c,RequestTitle__c,ReturnReason__c, CreatedById, LevelStage__c,ControlNumber__c,Policy_Category__c,Request_Summary__c, ProfitCenterNumberName__c from RFA__c WHERE Id=:rfaMap.keyset() LIMIT 1];
        System.debug('\n RSAS currRFA ID:'+currRFA.Id);
        System.debug('\n RSAS currRFA LevelStage:'+currRFA.LevelStage__c);   
                                  
        profitCenterNumbers.addAll(rfaMap.values());
        uniqueLevels.addAll(levelMap.values());
        
        System.debug('\n rowcause for the share :'+levelMap);
        System.debug('\n Rfa map :'+rfaMap);
        System.debug('\n Profit center set :'+profitCenterNumbers);
                                             
        ProfitCenterUserRole__c[] profitCenterUserRoles = [Select Id, UserName__c, UserType__c, ProfitCenter__c, Level__c FROM ProfitCenterUserRole__c WHERE Level__c IN: uniqueLevels AND ProfitCenter__c IN: profitCenterNumbers AND UserType__c = 'Location Coordinator'];                                
        String breakString = '<BR/>';
        Set<Id> lcSetId = new Set<Id>();
        for(ProfitCenterUserRole__c profitCenter : profitCenterUserRoles)
        {
             lcSetId.add(profitCenter.UserName__c);
        }  
        lcSetId.add(currRFA.CreatedById);

        List<User> lcUsers = [SELECT Id, Email, Name FROM User WHERE ID IN: lcSetId LIMIT 1000];
        List<String> addresses = new List<String>();
        Map<Id, User> userMap = new Map<Id, User>();

        for (User u : lcUsers){
             addresses.add(u.Email);
             if(!userMap.containsKey(u.Id)){ 
                 userMap.put(u.Id,u);
             }
        }
    
       
        System.debug(' Debug RFA ID: ' + currRFA.Id);
        System.debug('\n RSAS value of levelMap.get(rfaId): ' +levelMap.get(currRFA.Id) ) ;           
        System.debug('\n RSAS value of currRFA Stage:'+currRFA.Stage__c); 
        System.debug('\n RSAS value of currRFA LevelStage__c:'+currRFA.LevelStage__c); 

        if(currRFA.LevelStage__c == RFAGlobalConstants.RETURN_TO_SENDER)
        {   
             //Apexpages.StandardController sc = new Apexpages.StandardController(currRFA);
             //PageReference pr = Page.RFAReturnToSenderEmailContent;
             //pr.getParameters().put('id', String.valueOf(currRFA.Id));
             String htmlBodyEmail = '';
             String ccAddress = '';
             //Added by Mads 4-29-2014;
             Pattern dollarPattern = Pattern.compile('[$]');
             String strReason = currRFA.returnReason__c;
             String strControlNumber = currRFA.ControlNumber__c;
             String strProfitCenter = currRFA.ProfitCenterNumberName__c; // added by RLC for Profit Center May 2, 2014
             String strRequestTitle = currRFA.RequestTitle__c;

             strReason = dollarPattern.matcher(strReason).replaceAll('xxRSASxx');
             strControlNumber = dollarPattern.matcher(strControlNumber).replaceAll('xxRSASxx');
             strRequestTitle = dollarPattern.matcher(strRequestTitle).replaceAll('xxRSASxx');  

             if(currRFA.POC_Name__c != null){ccAddress = currRFA.POC_Name__c;}   
             if(currRFA.CO_CREATOR_Name__c != null){ccAddress += ', '+currRFA.CO_CREATOR_Name__c;}   
             if(currRFA.LOC_Name__c != null){ccAddress += ', '+currRFA.LOC_Name__c;}
             String strSubject = 'Action Required: ' + currRFA.ControlNumber__c+' Returned to Sender';
             if(currRFA.RecordTypeId == rfaRecordTypeMap.get(RFAGlobalConstants.RECORDTYPE_POLICY_EXEMPTION_REQUEST).Id){
                String strRequestSummary = currRFA.Request_Summary__c;
                String strPolicyCategory = currRFA.Policy_Category__c;
                strRequestSummary = dollarPattern.matcher(strRequestSummary).replaceAll('xxRSASxx');
                strPolicyCategory = dollarPattern.matcher(strPolicyCategory).replaceAll('xxRSASxx');


                 htmlBodyEmail  = Label.RFA_CL_PE_ReturnToSender;
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%REASON%' , strReason);
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%CONTROL_NUM%' , strControlNumber);
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%REQUEST_TITLE%' , strRequestTitle);  
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%REQUEST_TYPE%' , RFAGlobalConstants.RECORDTYPE_POLICY_EXEMPTION_REQUEST);  
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%REQUEST_SUMMARY%' , strRequestSummary);    
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%POLICY_CATEGORY%' , strPolicyCategory);      
      
             }else{    
                 htmlBodyEmail  = Label.RFA_CL_NonPE_ReturnToSender;
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%REQUEST_TITLE%' , strRequestTitle);  
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%REASON%' , strReason);
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%CONTROL_NUM%' , strControlNumber);
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%PROFIT_CENTER%' , strProfitCenter); //Added by RLC for Profit Center may 2, 2014


                 String strFC = currRFA.FunctionalCurrencyNameFC__c;
                 String strRequestAmountUSD = String.valueOf(currRFA.RequestAmountUSD__c);  
                 String strRequestAmountFC = String.valueOf(currRFA.RequestAmountFunctionalCurrency__c); 
                 String strExecSummary = currRFA.ExecutiveSummary__c; 
  
                 strFC = dollarPattern.matcher(strFC).replaceAll('xxRSASxx');
                 strRequestAmountUSD = dollarPattern.matcher(strRequestAmountUSD).replaceAll('xxRSASxx');  
                 strRequestAmountFC = dollarPattern.matcher(strRequestAmountFC).replaceAll('xxRSASxx');
                 strExecSummary = dollarPattern.matcher(strExecSummary).replaceAll('xxRSASxx');
    
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%REQ_AMT_USD%' , strRequestAmountUSD);
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%FC%' , strFC);    
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%REQ_AMT_FC%' ,  strRequestAmountFC);     
                 htmlBodyEmail  = htmlBodyEmail.replaceAll('%EXEC_SUMMARY%' , strExecSummary);      
             }   
  
             htmlBodyEmail  = htmlBodyEmail.replaceAll('%TO_ADDRESS%' , userMap.get(currRFA.CreatedById).Name);
             htmlBodyEmail  = htmlBodyEmail.replaceAll('%CC_ADDRESS%' , ccAddress);
             htmlBodyEmail  = htmlBodyEmail.replaceAll('%URL1%' , Label.RFA_CL026+'/'+currRFA.Id);
             htmlBodyEmail  = htmlBodyEmail.replaceAll('%URL2%' , currRFA.Name);
             htmlBodyEmail  = htmlBodyEmail.replaceAll('%EMAIL1%' , 'mailto:'+userMap.get(currRFA.CreatedById).Email+'?subject=RE : '+strSubject );    
             htmlBodyEmail  = htmlBodyEmail.replaceAll('%EMAIL2%' , userMap.get(currRFA.CreatedById).Name);  
             System.debug('ROYCASTILLO inside RETURN_TO_SENDER');
             Messaging.Singleemailmessage mail = new Messaging.Singleemailmessage();
             mail.setToAddresses(addresses);
             mail.setSubject(strSubject);
             mail.setSaveAsActivity(false);
             mail.orgWideEmailAddressId=Label.RFA_CL131; //-added by RSAS 11-Oct-2012 for INC0075225
             htmlBodyEmail  = htmlBodyEmail.replaceAll('xxRSASxx','\\$');//Added mpascua@coca-cola.com April 29, 2014
             mail.setHtmlBody(htmlBodyEmail);
             System.debug('ROYCASTILLO sending email');
             Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }                       
                               
    }
   
    
}