Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>LevelStage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Level / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_SkipLevelController.cls
/****************************************************************************************************************************************
****************************************************************************************************************************************    
*  Class            : RFA_VFC_SkipLevelController
*  Author           : Infosys
*  Version History  : 1.0
*  Creation         : 18/11/2015
*  Description      : This class updates RFA's level to its next level and stage if there are no coordinators defined for the profit center

****************************************************************************************************************************************
****************************************************************************************************************************************/


public class RFA_VFC_SkipLevelController{
    
    public Id validationOfskipLevel()
    {    
        String skippedlevel='';         
        List<RFA__c> rfalist= [SELECT Id, level__C, stage__C, ProfitCenterNumber__c ,levelstage__C FROM RFA__c WHERE Id IN: Trigger.newMap.keySet()];
        RFA__c rfaobj=rfalist.get(0);
        Boolean hascoord= false;   
        //List to fetch the next level for current level
        Map<String, String> pcnextLevelMap = new Map<String, String>{
            '1. Key Operations'    =>  '2. Business Unit',
                '2. Business Unit'  =>  '3. Group',
                '3. Group'  =>  '4. Corporate',
                '4. Corporate'  =>  '5. Executive',
                '5. Executive'  =>  '6. Senior Executive'
                }; 
                    
        if(RFAStaticVariables.doskiplevelProcess==true)
        { 
            String nextLevel=pcnextLevelMap.get(rfaobj.level__c);
            //This loop iterates until it finds the level for which the location coordinators are defined for the RFA's related Profit center.
            Map<String,Integer> CoordinaorsList=null;
            if(nextLevel!=null)
            {
                CoordinaorsList = getCordinatordetails(rfaobj);                    
                while(hascoord==false){ 
                   
                    //If profit center users are not present for the nextLevel, then fetch the next level from pcnextLevelMap
                    if(CoordinaorsList.get(nextLevel)==null)
                    {                    
                        skippedlevel=nextLevel;                    
                        nextLevel=pcnextLevelMap.get(nextLevel); 
                        //To stop from looping after the last level
                        if(skippedlevel==RFAStaticVariables.Level6)
                        {
                            hascoord=true;   
                        }
                    }  
                    else{
                        hascoord=true;                   
                    } 
                }
            }           
            RFAStaticVariables.skiplevel=true;            
            RFAStaticVariables.doskiplevelProcess=false;
            RFAStaticVariables.level =skippedlevel;
            futureMethodskipLevel(rfaobj.id,skippedlevel);
            return rfaobj.id; 
        }
        else
        {
            return null;
        } 
    }
    
    //Below method gets the coordinators present on the Profit Ceneter linked to RFA    
    public  Map<String,Integer> getCordinatordetails(RFA__c rfaobj)
    { 
        //The list "aggres" stores all the Location coordinators for each level defined on the Profit center
        List <AggregateResult> aggres = [SELECT Level__c,count(id) PFUsersCount from ProfitCenterUserRole__c WHERE ProfitCenter__c =:rfaObj.ProfitCenterNumber__c
                                        GROUP BY Level__c];
        
        Map<String,Integer> LocationCordinatorsList= new  Map<String,Integer>();        
        for (AggregateResult res : aggres)
        {           
            String level=(String)res.get('Level__c');
            Integer userCount=(Integer)res.get('PFUsersCount');
            LocationCordinatorsList.put(level,userCount );
        }
        
        return LocationCordinatorsList;
    }    
    
    //Future method to update RFA's level and stage when no coordinators are present for Profit center
    @future(callout=true)        
    static void  futureMethodskipLevel( Id id,string nxtLevel)
    { 
        
        List<RFA__c> rfalist= [SELECT Id, level__C, stage__C, levelstage__C FROM RFA__c WHERE Id =:id ]; 
        
        //To push RFA's level to its Post-Circulation if no coordinators are present for it's Profit center.    
        try{
            if(nxtlevel!='')
            { 
                for(RFA__C rf:rfalist)
                {                
                    rf.level__c=nxtLevel;
                    rf.stage__C=RFAGlobalConstants.RFA_POST_CIRCULATION_STAGE;
                } 
                update rfalist;
            }
        }
        catch(Exception ex)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage()));       
        }
    }    
}