Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>Profit_Center_Type__c</fullName>
        <label>Profit Center Type_old</label>
        <picklist>
            <picklistValues>
                <fullName>CCNA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>CapitalizedInterestUSD__c</fullName>
        <inlineHelpText>Charged on projects which are greater than U.S. $500,000 and involve a preparation period of more than 3 months (see Standard Practices and Procedures manual, Bulletin 8.1).</inlineHelpText>
        <label>Capitalized Interest (USD)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CashflowYears__c</fullName>
        <label>Cashflow Years</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DiscountedPaybackPeriodYears__c</fullName>
        <label>Discounted Payback Period (Years)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Downside_Discounted_Payback_Years__c</fullName>
        <label>Downside Discounted Payback (Years)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Downside_Internal_Rate_Of_Return__c</fullName>
        <label>Downside Internal Rate Of Return</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Downside_NPV_Investment__c</fullName>
        <label>Downside NPV/Investment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Downside_NPV_WACC__c</fullName>
        <label>Downside NPV@WACC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EconomicProfitUSD__c</fullName>
        <inlineHelpText>Income from continuing operations, after giving effect to taxes and excluding the effects of interest (commonly referred to as NOPAT), in excess of a computed capital charge for average operating capital employed.</inlineHelpText>
        <label>Economic Profit (USD)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Discounted_Payback_Years__c</fullName>
        <label>Expected Discounted Payback (Years)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_NPV_Investment__c</fullName>
        <label>Expected NPV/Investment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IRR__c</fullName>
        <inlineHelpText>Internal Rate of Return is the expected growth rate.</inlineHelpText>
        <label>IRR (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NPVUSD__c</fullName>
        <inlineHelpText>Net present value.</inlineHelpText>
        <label>NPV (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>Tax Rate (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Upside_Discounted_Payback_Years__c</fullName>
        <label>Upside Discounted Payback (Years)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upside_Internal_Rate_Of_Return__c</fullName>
        <label>Upside Internal Rate Of Return</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upside_NPV_Investment__c</fullName>
        <label>Upside NPV/Investment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upside_NPV_WACC__c</fullName>
        <label>Upside NPV@WACC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WACC__c</fullName>
        <inlineHelpText>Weighted average cost of capital is provided by Treasury by Country.</inlineHelpText>
        <label>WACC (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_PaceRangeOfoutcomesController.cls
public class RFA_VFC_PaceRangeOfoutcomesController {
 
    //jyoshna code start
    public boolean editable{get;set;}
    public boolean displayBusinessCaseFinancial {get;set;}
    public RFA__c rfaobj{get;set;}
    public ProfitCenter__c pcobj {get;set;}
    public ApexPages.StandardController stdController { get; set; }
    public Boolean refreshPage { get; set; }
    
    public RFA_VFC_PaceRangeOfoutcomesController(ApexPages.StandardController controller) {
        displayBusinessCaseFinancial = true;
        stdController = controller;
        rfaObj = (RFA__c)controller.getRecord();
        rfaObj=[select id, ProfitCenterNumber__c, EconomicProfitUSD__c, CashflowYears__c, TaxRate__c,
                        CapitalizedInterestUSD__c, WACC__c,
                        Upside_Internal_Rate_Of_Return__c,Expected_Discounted_Payback_Years__c,IRR__c,Downside_Internal_Rate_Of_Return__c,Upside_NPV_WACC__c,NPVUSD__c,Downside_NPV_WACC__c,Upside_NPV_Investment__c,Expected_NPV_Investment__c,
                Downside_NPV_Investment__c,Upside_Discounted_Payback_Years__c,DiscountedPaybackPeriodYears__c,Downside_Discounted_Payback_Years__c from RFA__c where Id=:rfaObj.Id];
        List<ProfitCenter__c> listProfitCenters = [select id,Profit_Center_Type__c from ProfitCenter__c where Id = : rfaobj.ProfitCenterNumber__c];                
        if(listProfitCenters.size()>0) {
            pcobj = listProfitCenters.get(0);
            if(pcobj!=null && pcobj.Profit_Center_Type__c=='CCR') {
                displayBusinessCaseFinancial = false;
            }
        }
        editable=false;
        system.debug('ProfitCenter Type is:'+pcobj.Profit_Center_Type__c);
        system.debug('Boolean Value is:'+displayBusinessCaseFinancial);
    }
    
    public pageReference editpacerangefields() {
        if(editable)        
        editable = false;
        else
         editable = true;   
        return null;
    }
    
    public pageReference savepacerangefields() {       
        rfaobj.NPVUSD__c = rfaobj.Expected_NPV_Investment__c;
        update rfaobj; 
        editable = false;
        //refreshPage = true;
        return null;
        
    }
      
    public pageReference cancelpacerangefields()
    {
        
            editable=false;
           // refreshPage = true;
        
        return null;
    }
}