Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>MinLevel__c</fullName>
        <label>Min Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NeedRecalculation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for recalculation of sharing model</description>
        <label>Need Recalculation</label>
        <type>Checkbox</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_AP01_ProfitCenterUserRole.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_AP01_ProfitCenterUserRole
 *  Author           : Accenture
 *  Version History  : 1.0
 *  Creation         : 31/05/2012
 *  Assumptions      : N/A
 *  Description      : To - Do
                                    
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/

public class RFA_AP01_ProfitCenterUserRole
{
    /**
     * Constructor
     */
    public RFA_AP01_ProfitCenterUserRole()
    {
    }
    
    /*~~~~Start of Initialization~~~~*/
    public Map<Id , ProfitCenterUserRole__c > ProfitCenterErrorStatus=new Map<Id, ProfitCenterUserRole__c >();
    public Map<Id, List<ProfitCenterUserRole__c>> profitCenterMap=new Map<Id, List<ProfitCenterUserRole__c>>();
    public Set<Id> profitCenterIds=new Set<Id>(); 
    /*~~~~End of Initialization~~~~*/
    
    /**
     *  processRecords method
     *  @param profitCenterUserRoleList, processItem( Trigger.new,Trigger.old)
     *  @return Database.Querylocator
     */
     
    public void processRecords(list<ProfitCenterUserRole__c> profitCenterUserRoleList,String processItem)
    {         
        for(ProfitCenterUserRole__c profitCenterUserRole: profitCenterUserRoleList)
        {
               profitCenterIds.add(profitCenterUserRole.ProfitCenter__C);
     
  
        }
        for(ProfitCenter__c profitCenter: [Select Id, (Select id,UserName__c,Level__c,Usertype__c from Profit_Center_Associated_Users__r where UserType__c=:RFAGlobalConstants.PC_USERTYPE_LC and UserName__c=:UserInfo.getUserId() order by level__c desc limit 1),name from ProfitCenter__c where Id IN:profitCenterIds ])
         {
         	if(!profitCenter.Profit_Center_Associated_Users__r.IsEmpty())
            	profitCenterMap.put(profitCenter.Id, profitCenter.Profit_Center_Associated_Users__r);            
         
         }
         
         
         for(ProfitCenterUserRole__c profitCenterUserRole: profitCenterUserRoleList)
         {
             Boolean allowAccess=false;
             if(!profitCenterMap.IsEmpty())
             {
             	for(ProfitCenterUserRole__c tempMap: profitCenterMap.get(profitCenterUserRole.profitCenter__c) )
              	{
                    
                    if (processItem=='Trigger.New'  || processItem=='Trigger.Update')
                    {
                            if(tempMap.UserName__C==UserInfo.getUserId() )
                            {
                                   allowAccess=True;
                            }
                           if((tempMap.UserName__C == UserInfo.getUserId() && tempMap.UserType__c!=RFAGlobalConstants.PC_USERTYPE_LC) )
                            {
                                if(processItem=='Trigger.New')
                            	{
                            		profitCenterUserRole.addError(RFAGlobalConstants.INSUFFICIENT_PERMISSION);
                            	}
                            	else if(processItem=='Trigger.Update')
                            	{
                            		ProfitCenterUserRole__c pcur=(ProfitCenterUserRole__c)Trigger.newMap.get(profitCenterUserRole.Id);
                                   	pcur.addError(RFAGlobalConstants.INSUFFICIENT_PERMISSION);
                            	}
                                   
                                   
                             
                            }  
                            else if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 && (profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C == UserInfo.getUserId() && tempMap.Level__c.contains(System.Label.RFA_CL001) && (profitCenterUserRole.Level__c.contains(System.Label.RFA_CL002) || profitCenterUserRole.Level__c.contains(System.Label.RFA_CL003) || profitCenterUserRole.Level__c.contains(System.Label.RFA_CL004) || (profitCenterUserRole.Level__c.contains(System.Label.RFA_CL005) && !profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006)) ||  profitCenterUserRole.level__c.contains(System.Label.RFA_CL006))  )
                            {
                            	if(processItem=='Trigger.New')
                            	{
                            		profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                            	}
                            	else if(processItem=='Trigger.Update')
                            	{
                            		ProfitCenterUserRole__c pcur=(ProfitCenterUserRole__c)Trigger.newMap.get(profitCenterUserRole.Id);
                                   	pcur.addError(RFAGlobalConstants.INSUFFICIENT_EDIT_PERMISSION);
                            	}
                                   
                            }  
                            else if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 &&(profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && tempMap.Level__c.contains(System.Label.RFA_CL002) && ( profitCenterUserRole.Level__c.contains(System.Label.RFA_CL003) || profitCenterUserRole.Level__c.contains(System.Label.RFA_CL004) || (profitCenterUserRole.Level__c.contains(System.Label.RFA_CL005) && !profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006)) ||  profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006))   )
                            {
                                if(processItem=='Trigger.New')
                            	{
                            		profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                            	}
                            	else if(processItem=='Trigger.Update')
                            	{
                            		ProfitCenterUserRole__c pcur=(ProfitCenterUserRole__c)Trigger.newMap.get(profitCenterUserRole.Id);
                                   	pcur.addError(RFAGlobalConstants.INSUFFICIENT_EDIT_PERMISSION);
                            	}
                             
                            } 
                            else if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 &&(profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && tempMap.Level__c.contains(System.Label.RFA_CL003) && (  profitCenterUserRole.Level__c.contains(System.Label.RFA_CL004) || (profitCenterUserRole.Level__c.contains(System.Label.RFA_CL005) && !profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006)) ||  profitCenterUserRole.level__C.contains(System.Label.RFA_CL006))  )
                            {
                                if(processItem=='Trigger.New')
                            	{
                            		profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                            	}
                            	else if(processItem=='Trigger.Update')
                            	{
                            		ProfitCenterUserRole__c pcur=(ProfitCenterUserRole__c)Trigger.newMap.get(profitCenterUserRole.Id);
                                   	pcur.addError(RFAGlobalConstants.INSUFFICIENT_EDIT_PERMISSION);
                            	}
                             
                            } 
                            else if( profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 &&(profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && tempMap.Level__c.contains(System.Label.RFA_CL004) && (  (profitCenterUserRole.Level__c.contains(System.Label.RFA_CL005) && !profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006)) ||  profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006))  )
                            {
                                if(processItem=='Trigger.New')
                            	{
                            		profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                            	}
                            	else if(processItem=='Trigger.Update')
                            	{
                            		ProfitCenterUserRole__c pcur=(ProfitCenterUserRole__c)Trigger.newMap.get(profitCenterUserRole.Id);
                                   	pcur.addError(RFAGlobalConstants.INSUFFICIENT_EDIT_PERMISSION);
                            	}
                             
                            } 
                            else if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 && (profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && (tempMap.Level__c.contains(System.Label.RFA_CL005) && !tempMap.Level__c.contains(System.Label.RFA_CL006)) && (   profitCenterUserRole.Level__C.contains(System.Label.RFA_CL006))  )
                            {
                                if(processItem=='Trigger.New')
                            	{
                            		profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                            	}
                            	else if(processItem=='Trigger.Update')
                            	{
                            		ProfitCenterUserRole__c pcur=(ProfitCenterUserRole__c)Trigger.newMap.get(profitCenterUserRole.Id);
                                   	pcur.addError(RFAGlobalConstants.INSUFFICIENT_EDIT_PERMISSION);
                            	}
                             
                            }
                              
                    
                    }
            
                    else if(processItem=='Trigger.Old' )
                    {
                             if(tempMap.UserName__C==UserInfo.getUserId()  )
                                {
                                       allowAccess=True;
                                
                                }
                             if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 && (profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006) && (tempMap.Level__c.contains(System.Label.RFA_CL001) || tempMap.Level__c.contains(System.Label.RFA_CL002) || tempMap.Level__c.contains(System.Label.RFA_CL003) || profitCenterUserRole.Level__c.contains(System.Label.RFA_CL004) || (profitCenterUserRole.Level__c.contains(System.Label.RFA_CL005) && !profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006)) )  )
                                {
                                       profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                                }  
                                else if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 && (profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && (profitCenterUserRole.Level__c.contains(System.Label.RFA_CL005) && !profitCenterUserRole.Level__c.contains(System.Label.RFA_CL006)) && (tempMap.Level__c.contains(System.Label.RFA_CL001) || tempMap.Level__c.contains(System.Label.RFA_CL002) || tempMap.Level__c.contains(System.Label.RFA_CL003) || tempMap.Level__c.contains(System.Label.RFA_CL004) )   )
                                {
                                       profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                                 
                                } 
                                else if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 && (profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && profitCenterUserRole.Level__c.contains(System.Label.RFA_CL004) && ( tempMap.Level__c.contains(System.Label.RFA_CL001) || tempMap.Level__c.contains(System.Label.RFA_CL002) || tempMap.Level__c.contains(System.Label.RFA_CL003))  )
                                {
                                       profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                                 
                                } 
                                else if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 &&(profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && profitCenterUserRole.Level__c.contains(System.Label.RFA_CL003) && ( tempMap.Level__c.contains(System.Label.RFA_CL001) || tempMap.Level__c.contains(System.Label.RFA_CL002) )  )
                                {
                                       profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                                 
                                } 
                                else if(profitCenterUserRole.UserType__c!=Label.RFA_Cl067 && profitCenterUserRole.UserType__c!=Label.RFA_Cl066 &&(profitCenterUserRole.Level__c!=null && profitCenterUserRole.Level__c!='') && tempMap.UserName__C==UserInfo.getUserId() && profitCenterUserRole.Level__c.contains(System.Label.RFA_CL002) && (tempMap.Level__c.contains(System.Label.RFA_CL001))   )
                                {
                                       profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_HIGHER_LEVEL);
                                 
                                }
                    }
              	}
                }
                if(allowAccess==false)
                {
                	if(processItem=='Trigger.Update')
                	{
                		  ProfitCenterUserRole__c pcur=(ProfitCenterUserRole__c)Trigger.newMap.get(profitCenterUserRole.Id);
                          pcur.addError(RFAGlobalConstants.INSUFFICIENT_EDIT_PERMISSION);
                	}
                   	else
                   		profitCenterUserRole.addError(RFAGlobalConstants.EXCEPTION_NOT_PART_OF_PC);
                    
                }
            
         }
         
         
    }
    
    // This method is used to update the min level & update the flag at profit center for recalculation of sharing model
    public void updateProfitCenterForMinLevelRecords(list<ProfitCenterUserRole__c> profitCenterUserRoleList)
    {
        /*~~~~Start of Initialization~~~~*/
        
        List<profitCenter__c> profitCenterList=new List<ProfitCenter__c>();
        Set<Id> profitCenterIds=new Set<Id>();
        Map<Id, ProfitCenterUserRole__c> profitCenterMap=new Map<Id, ProfitCenterUserRole__c>();
        /*~~~~End of Initialization~~~~*/
        
        /********fetching all the profit center Ids**/
        for(ProfitCenterUserRole__c profitCenterUserRole: profitCenterUserRoleList)
        {
               profitCenterIds.add(profitCenterUserRole.ProfitCenter__C);
        }
        
        
        /*****************Add Min level and Recalculation flag to profit center block starts here**********************/
        
        for(ProfitCenter__C profitCenter:[Select id, MinLevel__C,(Select id, UserName__c,Level__c,Usertype__c from Profit_Center_Associated_Users__r where Usertype__c =: RFAGlobalConstants.PC_USERTYPE_LC order by Level__c ASC limit 1) from ProfitCenter__C where Id In: profitCenterIds])
        {
        	if(!profitCenter.Profit_Center_Associated_Users__r.IsEmpty())
            	profitCenterMap.put(profitCenter.Id,profitCenter.Profit_Center_Associated_Users__r);
        }
         for(Id tempProfitCenterId:profitCenterIds )
	        {
	                ProfitCenter__c profitCenter=new ProfitCenter__c(id=tempProfitCenterId);
	    			if(!profitCenterMap.IsEmpty())
	                	profitCenter.MinLevel__c=profitCenterMap.get(tempProfitCenterId).Level__c;  // update the min level
	    			else
	    				profitCenter.MinLevel__c='';
	                profitCenter.NeedRecalculation__c=true;  // update the flag to ture for recalculation the sharing model
	                profitCenterList.add(profitCenter);
	        }
        
        /*****************Add Min level and Recalculation flag to profit center block Ends here**********************/
        
        // Update the profit Center list
        if(profitCenterList.Size()>0)
        {
            update profitCenterList;
        }
  
    }
    
    
    
}