Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <label>Profit Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalLetterComments__c</fullName>
        <inlineHelpText>Standard comments describing conditional approval requirements.</inlineHelpText>
        <label>Follow-up: Approver Comments/Conditions</label>
        <picklist>
            <picklistValues>
                <fullName>The requesting party must ensure appropriate coordination with the above approver(s) to fully address any and all approval conditions.  Any failure to fully address these conditions will be subject to Audit review.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The requesting party must fully comply with the above approval conditions, although explicit communication or follow up with these approvers is not required.  Any failure to fully address these conditions will be subject to Audit review.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <formula>ProfitCenterNumber__r.Business_Unit_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CCEmailAddressCM__c</fullName>
        <label>CCEmailAddressCM</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CommentsConditions__c</fullName>
        <inlineHelpText>Text provided by approvers of approval condition that must be accomplished before transaction initiation.</inlineHelpText>
        <label>Comments/Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comments_aboutr__c</fullName>
        <description>Comments About Expiration Date</description>
        <inlineHelpText>For Administrative Purposes Only.</inlineHelpText>
        <label>Expiration Date Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ControlNumber__c</fullName>
        <inlineHelpText>A unique identifier will be assigned automatically by the RFA system when the request is created.</inlineHelpText>
        <label>Control Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Expiration Date</description>
        <inlineHelpText>Date by which compliance with company policy will be achieved and exemption will no longer be effective.</inlineHelpText>
        <label>Expiration Date*</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Functional_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The three-character abbreviation for the functional currency in which the request amount will be denominated.</inlineHelpText>
        <label>Functional Currency (FC) *</label>
        <referenceTo>ARE_RFA__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LocalReferenceNumber__c</fullName>
        <inlineHelpText>A reference number used by the originating location to track the request. It is recommended that the local reference number start with the two-digit year followed by a sequential number.  For example,  11/05 represents the 5th RFA submitted in 2011.</inlineHelpText>
        <label>Local Reference Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <formula>ProfitCenterNumber__r.ProfitCenterName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically assigned based on profit center number selected.</inlineHelpText>
        <label>Profit Center Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>TCCC portion only. Request Amt is based on DOA/LCOA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amt, etc.</inlineHelpText>
        <label>Request Amount (FC) *</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestAmountUSD__c</fullName>
        <formula>RequestAmountFunctionalCurrency__c *ARERate__c</formula>
        <inlineHelpText>TCCC portion only. Request Amt is based on DOA/LCOA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amt, etc.</inlineHelpText>
        <label>Request Amount (USD)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase.  (e.g.,  Write-off  45 non-working vending machines in Atlanta sales center)</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>RFA R1 - To store the subject of the Completion Memo</description>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Theapprovalstatusofyourrequestis__c</fullName>
        <description>Approval Status of the RFA Request</description>
        <inlineHelpText>Displays the approval status of the RFA (unconditionally approved, conditionally approved, etc.)</inlineHelpText>
        <label>This request has been</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed / Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / Not Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Thefollowingitem__c</fullName>
        <inlineHelpText>Select level/stage the RFA was approved through according to the DOA/LCOA.</inlineHelpText>
        <label>This request was circulated to</label>
        <picklist>
            <picklistValues>
                <fullName>Key Operation level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Executive level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The appropriate Board of Directors for approval as required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ToEmailAddressCM__c</fullName>
        <label>ToEmailAddressCM</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalComments__c</fullName>
        <defaultValue>IF($RecordType.Name == &apos;Info Copy Only&apos;, &quot;Info Copy Only&quot;, &quot;&quot;)</defaultValue>
        <label>Approval Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC04_CompletionMemoController.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_VFC04_CompletionMemoController
 *  Author           : Accenture
 *  Version History  : 1.0
 *  Creation         : 4/6/2012 
 *  Assumptions      : N/A
 *  Description      : Class for sending email to group of people chosen by the user when the RFA is either Approved or Rejected 
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/

public class RFA_VFC04_CompletionMemoController {
    
    // instance of RFA__c
    public RFA__c rfaObj{get;set;}
    
    // List of type selectOption for available list of org recipients
    public list<user> toList{get;set;}

    // List of type selectOption for available list of org recipients
    public SelectOption[] selectableRecipients{get;set;}
    
    // List of type SelectOption for list of selected recipients from the visualforce page.
    public SelectOption[] selectedRecipients{get;set;}
    
    // String variable for user inputed CC list of recipients.        
    public String selectedCCusers{get; set;}    

    // boolean variable used as identifier for any failures.
    public boolean hasError{get; private set;}
    public boolean hideOKButton{get;set;}
    public Boolean isRFAPolicy{get;set;} //added mpascua 10/14/2013 for checking if rfa type  is policy exemption
  
    public static Map<String, Map<String, RecordType>> RECORDTYPESMAP = RFAGlobalConstants.RECORDTYPESMAP;
    public static Map<String, RecordType> toLstRecordTypeMap = RECORDTYPESMAP.get(Schema.sObjectType.RFAUserRole__c.getName());
    //for FR 1.26 Q3 RLC
    public static Map<String, RecordType> rfaRecordTypeMap = RECORDTYPESMAP.get(Schema.sObjectType.RFA__c.getName());
    Apexpages.StandardController ctlr = null;

    // constructor for the class            
    public RFA_VFC04_CompletionMemoController(ApexPages.StandardController controller) {
        this.hideOKButton = true;
        this.rfaObj = (RFA__c)controller.getRecord();
        ctlr= controller;
        
        if(rfaObj.Id <> null)
        {
            this.rfaObj = [Select Id, Subject__c, Thefollowingitem__c, ProfitCenterNumber__c,
                       ProfitCenterName__c, ControlNumber__c, Functional_Currency__c, Functional_Currency__r.Name,
                       Theapprovalstatusofyourrequestis__c, CommentsConditions__c,
                       ApprovalLetterComments__c, Business_Unit__c, RequestTitle__c,   
                       LocalReferenceNumber__c, RequestAmountFunctionalCurrency__c, RequestAmountUSD__c,
                       toEmailAddressCM__c,ccEmailAddressCM__c, CreatedById, RecordTypeId, Stage__c, Expiration_Date__c, Comments_aboutr__c  
                       FROM RFA__c 
                       WHERE Id =: rfaObj.Id];
        
            //---Added by mpasccua@coca-cola.com Aug 22, 2013 for FR 1.32
            if(this.rfaObj.RecordTypeId == rfaRecordTypeMap.get(RFAGlobalConstants.RECORDTYPE_POLICY_EXEMPTION_REQUEST).Id) {
                 this.isRFAPolicy = true;
            }else{
                 this.isRFAPolicy = false;
            }

            ApexPages.Message rfaStageMessage = new ApexPages.Message(ApexPages.Severity.INFO, 'RFA has been successfully '+this.rfaObj.Stage__c + '. Complete the form below to send a Completion Memo.');
            ApexPages.addmessage(rfaStageMessage);
            //-----------------
         /*         
         Requirement #FR1.89
         Description #On Completion Memo, To have default value as "Not Applicable" in the ApprovalLetterComments__c picklist.
         History     #Added by ASHWANI KAUSHIK on 03-May-2013
         */
         if(rfaObj.ApprovalLetterComments__c==NULL) rfaObj.ApprovalLetterComments__c=Label.RFA_FR1_89;                   
         
         /*
         Requirement #FR1.26
         Description #To populate Comments/Condition field with Approver comments and recommendations if the approval is (Conditionally Approved OR Rejected).
         History     #Added by ASHWANI KAUSHIK on 03-May-2013
         */
         list<RFAUserRole__c> rfaUserList = [Select Id,UserName__r.name,ApprovalRecommendation__c,ApprovalComments__c FROM RFAUserRole__c 
                                   where (RecordTypeId =: toLstRecordTypeMap.get(RFAGlobalConstants.APPROVER_RECORDTYPE).Id ) 
                                   and (ApprovalRecommendation__c=:Label.RFA_CL058 OR ApprovalRecommendation__c=:Label.RFA_CL059) 
                                   and RFA__c =: rfaObj.Id];
                                   
          // For Defect 26 comments not always showing up - Roy Castillo Nov 4, 2013
          // Original Code =  if(rfaObj.CommentsConditions__c ==NULL && rfaUserList.size()>0)
               
        // if(rfaObj.CommentsConditions__c ==NULL || rfaObj.CommentsConditions__c !=NULL)
         //{      
                        
        //if(rfaUserList.size()>0)- COMMENTED FOR DEBUGGING PURPOSES - ROY FEB 3, 2014
        if(rfaObj.CommentsConditions__c ==NULL && rfaUserList.size()>0)

            {
            String defaultComments= '';
            
            
             Integer TextLimit=Schema.SObjectType.RFA__c.fields.CommentsConditions__c.getLength();
            
            
                for(RFAUserRole__c ur:rfaUserList)
                if (!string.isblank(ur.ApprovalComments__c) ) // added this line not to include null comments
                {
                  defaultComments+=ur.UserName__r.name+' - '+ur.ApprovalRecommendation__c+' - '+ur.ApprovalComments__c+'\n\n';

                }
                
                
                system.debug('Value of the comments field '+defaultComments.length());
              
              if(defaultComments.length() > TextLimit )
                {
                   ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'Comments/Conditions has been truncated as the text size exceeded the maximum allowed character limit i.e. '+TextLimit+' Characters');
                   ApexPages.addmessage(myMsg);
                   rfaObj.CommentsConditions__c=defaultComments.substring(0,TextLimit);
                }
                else
                {
                    rfaObj.CommentsConditions__c=defaultComments ;
                } 
            }                           
              
           //   }                     
        //End               
                 
                 
           
                 
                       
                       
        }
        selectedRecipients = new List<SelectOption>();
        
        selectableRecipients = getSelectableUsers();

        toList = new list<user>();
        toList = gettoList();
        
    }
    //---- added by mpascua@coca-cola.com Aug 22, 2013
    public pageReference cancelSendEmail()
    {
                    
        ApexPages.Message rfaStageMessage = new ApexPages.Message(ApexPages.Severity.INFO, 'RFA Completion Memo has not been sent. Contact Corporate Capital Management if RFA Completion Memo is needed.');
        ApexPages.addmessage(rfaStageMessage);
        
        hideOKButton = false;
        return null;
    }
    
    //---------
    
     /* @Method <This method sends completion memo to selected list of recipients in TO and CC list>
        @param <None> 
        @return <pagereference>
     */
    public pageReference sendEmail()
    {   
        //reset the error variable
        hasError = false;   
        Database.Saveresult[] result;   
        
        Savepoint sp = Database.setSavepoint();
        
        List<String> toAddresses = new List<String>();
        
        List<String> ccdUsers = new List<String>();
        String toEmailAddressCM, ccEmailAddressCM;
        
        try{
                        
            System.debug('\n Selected CCd users :'+selectedCCusers);
            
            System.debug('\n selected recipients :' +selectedRecipients);
                        
           /*if(selectedCCusers <> null || selectedCCusers <> '')
            {
                if(selectedCCusers.contains(';'))ccdUsers.addAll(selectedCCusers.split(';',0));
                else if(!RFAGlobalConstants.isBlank(selectedCCusers))ccdUsers.add(selectedCCusers);
            }*/
            /*if(selectedRecipients.isEmpty()) throw new CompletionMemoException('Please select recipients in To Addresses');*/
            
            /*for(SelectOption option : selectedRecipients)
            {
                toAddresses.add(option.getValue()); 
            }*/
            for(User toUser : toList){
                toAddresses.add(toUser.Email); 
                if(toEmailAddressCM!=null){toEmailAddressCM = toEmailAddressCM+','+toUser.Name;}
                else{toEmailAddressCM = toUser.Name;}
                
            }
            for(SelectOption option : selectedRecipients)
            {
                ccdUsers.add(option.getValue()); 
                if(ccEmailAddressCM!=null){ccEmailAddressCM = ccEmailAddressCM+','+option.getLabel();}
                else{ccEmailAddressCM = option.getLabel();}
            }            
            
            
            if((rfaObj.Thefollowingitem__c == null || rfaObj.Thefollowingitem__c == '') && !(this.isRFAPolicy)) throw new CompletionMemoException('Please Select a value for This Request was Circulated To:');
            
            if(rfaObj.Theapprovalstatusofyourrequestis__c == null || rfaObj.Theapprovalstatusofyourrequestis__c == '') throw new CompletionMemoException('Please select Final Approval Status for the Request');
            // - added && condition in following line by Ashwani on 22 Apr 2013 for FR1.88
            if((rfaObj.CommentsConditions__c == null || rfaObj.CommentsConditions__c == '') && (rfaObj.Theapprovalstatusofyourrequestis__c!=Label.RFA_CL057)) throw new CompletionMemoException('Please Add Comments/Conditions');
            
            if((rfaObj.ApprovalLetterComments__c == null || rfaObj.ApprovalLetterComments__c == '') && !(this.isRFAPolicy)) throw new CompletionMemoException('Please select Followup: Approver Comments/Conditions');
            
           
            /****/
            rfaObj.toEmailAddressCM__c=null; //assigning null value before updating.
            rfaObj.ccEmailAddressCM__c=null; //assigning null value before updating.
                if(toEmailAddressCM!=null)rfaObj.toEmailAddressCM__c = toEmailAddressCM;
                if(ccEmailAddressCM!=null)rfaObj.ccEmailAddressCM__c = ccEmailAddressCM;
            
            /****/
                

            result = Database.update(new List<RFA__c>{rfaObj});
            
            if(result[0].isSuccess())
            {
                sendCompletionMemoEmail(toAddresses, ccdUsers, UserInfo.getUserId(), rfaObj.Id);            
                RFA_WS04_PDFGeneratorCM.PDFGenerator(rfaObj.Id,UserInfo.getSessionId());
            }
          
            
      }
        catch(Exception ex)
        {
            Database.rollback(sp);
            hasError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
            
            return null;
        }
        
        //ApexPages.StandardController sc = new ApexPages.StandardController(rfaObj);
        
        //return sc.view();
        ApexPages.Message rfaStageMessage = new ApexPages.Message(ApexPages.Severity.INFO, 'RFA Completion Memo has been sent. Click OK to close this message.');
        ApexPages.addmessage(rfaStageMessage);
        hideOKButton = false;

        return null;
    }
    
    
    /* @Method <This method sends completion memo to selected list of recipients in TO and CC list>
        @param <List<String>, List<String>, String, String> 
        @return <pagereference>
     */
    public void sendCompletionMemoEmail(List<String> toAddresses, List<String> ccAddresses, String targetObjectId, String whatId)
    {
        System.debug('\n To recipient address :'+toAddresses);
        System.debug('\n To CCD address :'+ccAddresses);
           
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        Messaging.Singleemailmessage mail = new Messaging.Singleemailmessage();
        mail.setToAddresses(toAddresses);
        // for Completion memo - Policy Exemption Request FR 1.26 Q3 Release RLC
        //if (rfaobj.RecordType == Label.RFA_FR_1_11)
         system.debug('*****rfaObj.RecordTypeId : ' + rfaObj.RecordTypeId );
        system.debug('*****rfaRecordTypeMap.get :' +  rfaRecordTypeMap.get(RFAGlobalConstants.RECORDTYPE_POLICY_EXEMPTION_REQUEST).Id);

        if ((rfaObj.RecordTypeId == rfaRecordTypeMap.get(RFAGlobalConstants.RECORDTYPE_POLICY_EXEMPTION_REQUEST).Id)) {
            system.debug('*****inside if');
            mail.setTemplateId(Label.RFA_CL146);
        } else {
            mail.setTemplateId(Label.RFA_CL048);
        }
        system.debug('*****Line 225');
        if(ccAddresses.size() > 0)mail.setCcAddresses(ccAddresses);
        mail.setWhatId(whatId);
        mail.setTargetObjectId(targetObjectId);
        mail.saveAsActivity = false;
        
        mail.orgWideEmailAddressId=Label.RFA_CL131; //-added by RSAS 11-Oct-2012 for INC0075225
        
        mails.add(mail);
        Messaging.sendEmail(mails);      
       
    }
      
    public List<SelectOption> getSelectableUsers()
    {
        List<SelectOption> options = new List<SelectOption>();
        Set<String> associatedUsersIds = new Set<String>();
        
        Schema.DescribeSObjectResult d = Schema.SObjectType.User;
        String userKeyPrefix = d.getKeyPrefix();  
                                     
        for(RFA__Share rfaShare : [Select ParentId, RowCause, UserOrGroupId FROM RFA__Share WHERE ParentId = : rfaObj.Id LIMIT 1000])
        {
            String userAssociated = rfaShare.UserOrGroupId;
            if(userAssociated.substring(0,3) == userKeyPrefix)
                associatedUsersIds.add(rfaShare.UserOrGroupId); 
        }
               
        for(User user : [Select Id, Name, FirstName, LastName, Email From User where isActive = true AND Id IN: associatedUsersIds ORDER BY FirstName LIMIT 1000])
        {
            //if(user.Id <> userInfo.getUserId())
            //{
            if(user.Name <> 'RFA System')
                options.add(new SelectOption(user.Email, user.Name));
           // }
        }
        
        return options;                                                 
    }

/*
Function for ToList user's
*/

    public List<user> gettoList()
    {
        List<User> toListVal = new List<User>();
        Set<String> associatedUsersIds = new Set<String>();
        
        Schema.DescribeSObjectResult d = Schema.SObjectType.User;
        String userKeyPrefix = d.getKeyPrefix();  
                                     
        /*for(RFA__Share rfaShare : [Select ParentId, RowCause, UserOrGroupId FROM RFA__Share WHERE ParentId = : rfaObj.Id LIMIT 1000])
        {
            String userAssociated = rfaShare.UserOrGroupId;
            if(userAssociated.substring(0,3) == userKeyPrefix)
                associatedUsersIds.add(rfaShare.UserOrGroupId); 
        }*/
        set<string> AppRec = new set<string>();
        AppRec.add('Unconditionally Approved');
        AppRec.add('Conditionally Approved');
        AppRec.add('Rejected'); //add for defect 17 to add Group Coordinator when request is Rejected - RLC Nov 21, 2013
        set<string> AppLevel = new set<string>();
        appLevel.add('3. Group');
        AppLevel.add('4. Corporate');
        AppLevel.add('5. Executive');
        AppLevel.add('6. Senior Executive');
        
        associatedUsersIds.add(rfaObj.CreatedById);
        associatedUsersIds.add(UserInfo.getUserId());
        
        
        /*****************************************************************************/
           list<RFAUserRole__c> rfaUserList = [Select Id FROM RFAUserRole__c 
                                   where (RecordTypeId =: toLstRecordTypeMap.get(RFAGlobalConstants.APPROVER_RECORDTYPE).Id ) 
                                   and RFA__c =: rfaObj.Id
                                   and ApprovalRecommendation__c in : AppRec
                                   and Level__c in: AppLevel];
                if(rfaUserList.size()>0 && rfaObj.ProfitCenterName__c!=null)
                {
                    for(ProfitCenterUserRole__c PCUR: [select ProfitCenter__c, UserName__c, UserName__r.Name from ProfitCenterUserRole__c 
                                                       where  ProfitCenter__c =:rfaObj.ProfitCenterNumber__c 
                                                       and  UserType__c ='Location Coordinator'
                                                       and Level__c='3. Group'])
                    {   
                        if(PCUR.UserName__c!=null)
                        {
                           associatedUsersIds.add(PCUR.UserName__c);
                        }
                    }
                } 
        /*****************************************************************************/
         set<ID> rtID = new set<ID>();
         rtID.add(toLstRecordTypeMap.get(RFAGlobalConstants.RECORDTYPE_PRIMARY_POC).Id);
         rtID.add(toLstRecordTypeMap.get(RFAGlobalConstants.RECORDTYPE_CO_CREATOR).Id);
         for(RFAUserRole__c rfaUser : [Select UserName__c FROM RFAUserRole__c where (RecordTypeId in: rtID ) and RFA__c =: rfaObj.Id])
        {
            String userAssociated = rfaUser.UserName__c;
            if(userAssociated.substring(0,3) == userKeyPrefix)
                associatedUsersIds.add(rfaUser.UserName__c); 
        }


        for(User user : [Select Id, Name, FirstName, LastName, Email From User where isActive = true AND Id IN: associatedUsersIds ORDER BY FirstName LIMIT 1000])
        {
            //if(user.Id <> userInfo.getUserId())
            //{
            if(user.Name <> 'RFA System')
                toListVal.add(user);
           // }
        }
        return toListVal;                                                 
    }



    public String notNull(String check)
    {
        String returnString = ' ';
        if(check <> null) returnString = check;
        return returnString ;
    }
    
    public Class CompletionMemoException extends Exception{}
   
 }