Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_CoordinatorLevelHelper.cls
public  class RFA_VFC_CoordinatorLevelHelper {
    static Id username;
    static String ProfileName;
    static Id profileId;
    static Map<String,List<String>> availableLevels;
    static Map<String,List<String>> availableControlLevels = new Map<String,List<String>>{'1. Key Operations'=> new  List <String> {'KEYOP'}};
    public static List<SelectOption> getAvailableLevels()
    {
        username = userinfo.getUserId();
        ProfileName=null;
        profileId=userinfo.getProfileId();              
        availableLevels = new Map<String,List<String>>();        
        ProfileName=[Select Id,Name from Profile where Id=:profileId].Name;
        
        availableLevels.put('1. Key Operations', new  List <String> {'KEYOP'});
        availableLevels.put('2. Business Unit', new  List <String> {'KEYOP','BU'});
        availableLevels.put('3. Group', new  List <String> {'KEYOP','BU','GROUP'});
        availableLevels.put('4. Corporate', new  List <String> {'KEYOP','BU','GROUP','CORP'}); 
        availableLevels.put('5. Executive', new  List <String> {'KEYOP','BU','GROUP','CORP','EXEC'});
        availableLevels.put('6. Senior Executive', new  List <String> {'KEYOP','BU','GROUP','CORP','EXEC','Sr. EXEC'});
        List<selectOption> returnLevel = LevelsAccessed(availableLevels);
        
        return returnLevel;
      
    } 
    public Static List<SelectOption> getAvailableControlLevels()
    {
        username = userinfo.getUserId();
        ProfileName=null;
        profileId=userinfo.getProfileId();              
        availableControlLevels = new Map<String,List<String>>();        
        ProfileName=[Select Id,Name from Profile where Id=:profileId].Name;
         
        availableControlLevels.put('1. Key Operations', new  List <String> {'KEYOP'});
        availableControlLevels.put('2. Business Unit', new  List <String> {'KEYOP','BU'});
        availableControlLevels.put('3. Group', new  List <String> {'KEYOP','BU','GROUP'});
        availableControlLevels.put('4. Corporate', new  List <String> {'KEYOP','BU','GROUP','CORP'}); 
        availableControlLevels.put('5. Executive', new  List <String> {'KEYOP','BU','GROUP','CORP'});
        availableControlLevels.put('6. Senior Executive', new  List <String> {'KEYOP','BU','GROUP','CORP'});
		List<selectOption> returnLevel = LevelsAccessed(availableControlLevels);
        
        return returnLevel;
    }
	
    public static List<selectOption> LevelsAccessed(Map<String,List<String>> maplevel)
    {
         
        List<ProfitCenterUserRole__c> PCUobj = [select Level__c from ProfitCenterUserRole__c where UserName__c = : username and UserType__c = 'Location Coordinator'  order by  Level__c desc];             
        System.debug('hii'+PCUobj);
        List<SelectOption> levels = new List<SelectOption>(); 
        levels.add(new SelectOption('--Select--','--Select--'));
        List<String> levelsList=null;
        System.debug('hii profile'+ProfileName);
        if(ProfileName=='System Administrator')
        {
             levelsList=maplevel.get('6. Senior Executive');
             for(String eachLevel:levelsList)
             {
                 Levels.add(new SelectOption(eachLevel,eachLevel));
             }
        }
        else if(PCUobj!=null )
        {
                String UserLevel = PCUobj.get(0).Level__c;
                System.debug('Users Highest level is..'+UserLevel); 
                levelsList = maplevel.get(UserLevel);
                
                System.debug('levelsList for '+'current level'+UserLevel+' is '+levelsList);
               
                for(String eachLevel:levelsList)
                {
                    Levels.add(new SelectOption(eachLevel,eachLevel));
                }
        }  
        System.debug('hello im at end');
        return Levels;
    }
}