Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <label>Profit Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <formula>ProfitCenterNumber__r.ProfitCenterName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically assigned based on profit center number selected.</inlineHelpText>
        <label>Profit Center Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalComments__c</fullName>
        <defaultValue>IF($RecordType.Name == &apos;Info Copy Only&apos;, &quot;Info Copy Only&quot;, &quot;&quot;)</defaultValue>
        <label>Approval Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ApprovalRecievedDateTime__c</fullName>
        <label>ApprovalRecieved DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC04_ApprovalProcessController.cls
/****************************************************************************************************************************************
****************************************************************************************************************************************    
*  Class            : RFA_VFC04_ApprovalProcessController extends RFA_Util_SecurityMatrix
*  Author           : Accenture
*  Version History  : 1.0
*  Creation         : 4/6/2012 
*  Assumptions      : N/A
*  Description      : This class contains logic for taking approval recommendation from the approvers/agents.
****************************************************************************************************************************************
****************************************************************************************************************************************/
public class RFA_VFC04_ApprovalProcessController extends RFA_Util_SecurityMatrix
{
    // instance variable for UserAccess set in RFA_Util_SecurityMatrix
    private UserAccess uAccess;
    
    // instance variable of RFAuserRole__c
    public RFAUserRole__c appWorkItem{get;set;}
    
    // variable for selected approval workitem
    public String selectedWorkItem{get; set;}
    
    // variable for storing the recommendation selected by the user
    public String selectedRecommendation{get;set;}
    
    // instance variable of RFA__c
    public RFA__c rfaObj{get; private set;}
    
    // variable for storing the approval comments provided by the user
    public String approvalComments{get;set;}
    
    // instance list variable for workitem options
    public List<SelectOption> workItemOptions{get;set;}
    
    // identifier variable for transaction failure
    public boolean hasError{get;private set;}
    
    // list variable of workitem list with approver/agent details
    public static List<RFAUserRole__c> onBehalfList = new List<RFAUserRole__c>();
    
    // constructor for the class.  
    public RFA_VFC04_ApprovalProcessController(ApexPages.StandardController controller)
    {
        // call parent class constructor
        super(controller);  
        // set rfaobj
        this.rfaObj = (RFA__c)controller.getRecord();
        // get UserAccess security settings
        uAccess = getRFAUserAccess();
        
        if(uAccess.isApprover() || uAccess.isAgent())
            prepareWorkItem();            
    }
    
    /*@Method <getter and setter method to check if the logged in user is agent>
@param <None> 
@return <boolean>
*/
    public boolean isAgent{
        get{
            return uAccess.isAgent();
        }
        private set;
    }
    
    
    /*@Method <getter and setter method to check if the logged in user is approve>
@param <None> 
@return <boolean>
*/
    public boolean isApprover{
        get{
            return uAccess.isApprover();
        }
        private set;
    }
    
    /*@Method Prepare ACT ON BEHALF select list for the usert>
@param <None> 
@return <void>
*/    
    public void prepareWorkItem()
    {
        String loggedInUser = UserInfo.getUserId();
        onBehalfList = RFA_AP03_ApprovalProcessHelper.getApproversForProcess(loggedInUser, rfaObj);  
        workItemOptions = new List<SelectOption>();
        
        for(RFAUserRole__c wi : onBehalfList)
        {
            if(wi.UserName__c == loggedInUser)
            {
                workItemOptions.add(new SelectOption(wi.Id, wi.UserName__r.Name));  
            }
            else if(wi.Agent1__c == loggedInUser)
            {
                workItemOptions.add(new SelectOption(wi.Id, wi.UserName__r.Name));  
            }
            else if(wi.Agent2__c == loggedInUser)
            {
                workItemOptions.add(new SelectOption(wi.Id, wi.UserName__r.Name)); 
            }
            else if(wi.Agent3__c == loggedInUser)
            {
                workItemOptions.add(new SelectOption(wi.Id, wi.UserName__r.Name)); 
            }
        }                          
    }
    
    
    /*@Method <Action method executed when the user clicks on "Submit" button, method contains logic to insert recommendation>
@param <None> 
@return <pagereference>
*/
    public pageReference submitRecommendation()
    {
        try{
            hasError = false;
             
            if(selectedRecommendation == '--Select Recommendation--') throw new ApprovalException('Please provide a Recommendation');
            if(selectedRecommendation == 'Conditionaly Approved' && approvalComments == ' ') throw new ApprovalException('Please enter comments');  
            
            
            // Gary Arsenian 8/19: Validation to check user is updated and RFA Approver/User record which is pending recommendation.
            List<RFAUserRole__c> RFAUserRoleList = [Select ApprovalRecommendation__c From RFAUserRole__c Where id = :selectedWorkItem];
            for (RFAUserRole__c RFAUserRole: RFAUserRoleList)
                if (RFAUserRole.ApprovalRecommendation__c != RFAGlobalConstants.PROCESS_PENDING_RECOMMENDATION) throw new ApprovalException('Approval Recommendation has already been submitted by this user for this RFA');
            
            System.debug('\n Selected Approval workitem :'+selectedWorkItem);
            RFAUserRole__c approval = new RFAUserRole__c(Id=selectedWorkItem);
            approval.ApprovedBy__c = UserInfo.getUserId();
            approval.ApprovalRecievedDateTime__c = DateTime.now();
            approval.ApprovalComments__c = approvalComments;
            approval.ApprovalRecommendation__c = selectedRecommendation;
            update approval;
            
            //---- added by mpascua@coca-cola.com Aug 23, 2013
            if(selectedRecommendation == 'Rejected'){
                List<String> toAddresses = new List<String>();                
                List<String> ccdUsers = new List<String>();
                
                if(rfaObj.Id <> null)        {          
                    this.rfaObj = [Select Id, Level__c,ProfitCenterNumber__c,ProfitCenterName__c,ProfitCenterNumber__r.name                       
                                   FROM RFA__c WHERE Id =: rfaObj.id];        
                }                 
                // commented For REQ 23(12) "AND Level__c =: this.rfaObj.Level__c"
                // This populates the list of all level coordinators in the profit center
                List<ProfitCenterUserRole__c> locationCoordinatorsList = [SELECT ProfitCenter__c,UserName__r.name,UserName__r.email,UserName__c,Level__c,UserType__c                                  
                                                                          FROM ProfitCenterUserRole__c WHERE ProfitCenter__c=:rfaObj.ProfitCenterNumber__c  AND userType__c=:Label.RfA_Cl065                                
                                                                          order by Level__c limit :1000];
                System.debug('locationCoordinatorsList'+locationCoordinatorsList);
                Id targetObject = null; //added 21.feb
                for(ProfitCenterUserRole__c pc : locationCoordinatorsList){
                    
                    if (string.isblank(targetObject )){
                        targetObject = pc.UserName__c;
                        System.debug('targetObject Email id'+pc.UserName__r.Email);
                    }
                    else{
                        System.debug('adding Email id'+pc.UserName__r.email);
                        toAddresses.add(pc.UserName__r.email);
                    }
                    
                    //targetObject = pc.UserName__c; // add 21.feb
                }
                System.debug('toAddresses'+toAddresses);
                sendEmailNotification(toAddresses, ccdUsers, targetObject, rfaObj.Id, Label.RFA_CL147);
                //  sendEmailNotification(toAddresses, ccdUsers, UserInfo.getUserId(), rfaObj.Id, Label.RFA_CL147); - Orig Code
                
            }
            //-----
        }
        catch(ApprovalException appEx)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, appEx.getMessage()));
            hasError = true;
            return null;    
        } 
        catch(Exception ex)
        {
            if(!ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'))              
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage())); 
            system.debug('ex.getMessage()'+ex.getMessage());                          
            hasError = true;
            return null;
        }  
        return null;
    }
    
    
    /*@Method <getter and setter method for approval recommendation option>
@param <None> 
@return <List<SelectOption>>
*/
    public List<SelectOption> recommendationOptions{
        get{
            List<SelectOption> options = new List<SelectOption>();
            List<Schema.PicklistEntry> ple = RFAUserRole__c.ApprovalRecommendation__c.getDescribe().getPicklistvalues();
            options.add(new SelectOption('--Select Recommendation--', '--Select Recommendation--'));
            for(Schema.PicklistEntry schemaPle : ple)
            {
                if(!schemaPle.getLabel().contains('Awaiting Approval'))  
                    options.add(new SelectOption(schemaPle.getLabel(), schemaPle.getValue()));
            }
            return options;
            
        }
        private set;
    }
    
    // Custom Exception class extending Exception.
    public class ApprovalException extends Exception{}
    
    
    /*    
@Method <This method sends email notification to target recepients in TO and CC list>        
@param <List<String>, List<String>, String, String>         
@return <pagereference>     
*/    
    public void sendEmailNotification(List<String> toAddresses, List<String> ccAddresses, String targetObjectId, String whatId, String strTemplateId){        
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();        
        Messaging.Singleemailmessage mail = new Messaging.Singleemailmessage();        
        
        if(ToAddresses.size() > 0) mail.setToAddresses(toAddresses); 
        mail.setTemplateId(strTemplateId);               
        //mail.setTemplateId(Label.RFA_CL147);        
        
        if(ccAddresses.size() > 0) mail.setCcAddresses(ccAddresses);        
        mail.setWhatId(whatId);        
        mail.setTargetObjectId(targetObjectId);        
        mail.saveAsActivity = false;                
        mail.orgWideEmailAddressId=Label.RFA_CL131; 
        mails.add(mail);        
        Messaging.sendEmail(mails);                 
    }
}