Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <label>Profit Center Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenterName__c</fullName>
        <formula>ProfitCenterNumber__r.ProfitCenterName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically assigned based on profit center number selected.</inlineHelpText>
        <label>Profit Center Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_RF1_50_LocationCoordinator_V2.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_RF1_50_LocationCoordinator_V2
 *  Author           : Accenture
 *  Version History  : 1.0
 *  Creation         : 23/4/2013 
 *  Assumptions      : N/A
 *  Description      : Class for display all the location co-ordinators attached with Profit Center. 
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/
public with sharing class RFA_RF1_50_LocationCoordinator_V2 {

    private integer counter=0;  //keeps track of the offset
    private integer list_size=100; //sets the page size or number of rows
    public integer total_size; //used to show user the total size of the list
    
  public List<ProfitCenterUserRole__c> LocationCoordinators { get {
 
 
    return sortList(LocationCoordinators);
  } set; }
  public String sortBy { get; set; }
  public String sortDir { get; set; }
  // instance of RFA__c
    public RFA__c rfaObj{get;set;}
    
    public RFA_RF1_50_LocationCoordinator_V2(ApexPages.StandardController controller) {
     this.rfaObj = (RFA__c)controller.getRecord();
        
        if(rfaObj.Id <> null)
        {
          this.rfaObj = [Select ProfitCenterNumber__c,ProfitCenterName__c,ProfitCenterNumber__r.name
                       FROM RFA__c 
                       WHERE Id =: rfaObj.id];
        }
        
         total_size = [select count()   
                                from ProfitCenterUserRole__c where ProfitCenter__c=:rfaObj.ProfitCenterNumber__c and userType__c=:Label.RfA_Cl065
                                ]; //set the total size in the constructor

         
         LocationCoordinators = [select ProfitCenter__c,UserName__r.name,UserName__c,Level__c,UserType__c  
                                from ProfitCenterUserRole__c where ProfitCenter__c=:rfaObj.ProfitCenterNumber__c  and userType__c=:Label.RfA_Cl065
                                order by Level__c
                                limit :list_size 
                                offset :counter];

    }
    
   public PageReference empty() { return null; }

  
  // The sorting function works on all SObjects sorting on all fields
  public List<SObject> sortList(List<SObject> cleanList)
  {
    if (sortBy == null) { return cleanList; }
    List<SObject> resultList = new List<SObject>();
    Map<Object, List<SObject>> objectMap = new Map<Object, List<SObject>>();
    for (SObject item : cleanList) {
      if (objectMap.get(item.get(sortBy)) == null) {
        objectMap.put(item.get(sortBy), new List<SObject>());
      }
      objectMap.get(item.get(sortBy)).add(item);
    }
    List<Object> keys = new List<Object>(objectMap.keySet());
    keys.sort();
    for(Object key : keys) {
      resultList.addAll(objectMap.get(key));
    }
    cleanList.clear();
    if (sortDir == 'ASC') {
      for (SObject item : resultList) {
        cleanList.add(item);
      }
    } else {
      for (Integer i = resultList.size()-1; i >= 0; i--) {
        cleanList.add(resultList[i]);
      }
    }
  
    return cleanList;
  }   

   
  
  
     
    public PageReference Beginning() { //user clicked beginning
      counter = 0; 
      return null;
   }
 
   public PageReference Previous() { //user clicked previous button
      counter -= list_size; 
      return null;
   }
 
   public PageReference Next() { //user clicked next button
      counter += list_size; 
      return null;
   }
 
   public PageReference End() { //user clicked end
      counter = total_size - math.mod(total_size, list_size);
      return null;
   }
 
   public Boolean getDisablePrevious() { 
      //this will disable the previous and beginning buttons
      if (counter>0) return false; else return true;
   }
 
   public Boolean getDisableNext() { //this will disable the next and end buttons
      if (counter + list_size < total_size) return false; else return true;
   }
 
   public Integer getTotal_size() {
      return total_size;
   }
 
   public Integer getPageNumber() {
      return counter/list_size + 1;
   }
 
   public Integer getTotalPages() {
      if (math.mod(total_size, list_size) > 0) {
         return total_size/list_size + 1;
      } else {
         return (total_size/list_size);
      }
   }

}