Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterCOAGroupJunctionobject__c.object
<CustomObject>
    <fields>
        <fullName>Profit_Center_Number__c</fullName>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipName>ProfitCenterCOAGroupJunctionobjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RFA_COA_Group_Name__c</fullName>
        <label>RFA COA Group Name</label>
        <referenceTo>RFA_COA_Group__c</referenceTo>
        <relationshipName>ProfitCenterCOAGroupJunctionobjects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ProfitCenter COAGroup</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>ProfitCenterCOAGroup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitCenter COAGroups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA_Approver__c.object
<CustomObject>
    <fields>
        <fullName>RFA_COA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RFA COA Group</label>
        <referenceTo>RFA_COA_Group__c</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserName</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver_old</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>RFA Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFA_Business_Unit__c.object
<CustomObject>
    <description>Stores all Business Units within the RFA Application.</description>
    <label>RFA Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFA Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/objects/RFA_COA_Group__c.object
<CustomObject>
    <description>RFA object which is used for determining the automated list of approvers.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RFA COA Group old</label>
    <nameField>
        <label>RFA COA Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFA COA Groups old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/sample.cls
public class sample
{
/*
    public String selectedRec{get;set;}
    public String selectedCategory{get;set;}
    public String selectedUnit{get;set;}
    public String selectedPC{get;set;}    
    public List<String> pcStringList{get;set;}
    public List<RFA_Approver__c> RFAApprovers{get;set;}
    public List<RFA_COA_Group__c> coaGroups{get;set;}
    public List<SelectOption> BusRecordTypes{get;set;}
    public String[] BusRecTypes{set;get;}
    
    public List<SelectOption> selectedBusRecordTypes{get;set;}
    public sample()
    {
        List<RecordType> results = [Select Id ,DeveloperName  From RecordType  Where SobjectType = 'RFA_Business_Unit__c'];
        
        BusRecordTypes=new List<SelectOption>();
       
        BusRecordTypes.add(new SelectOption('--Select--','--Select--'));
        for(RecordType rt: results)
        {            
            BusRecordTypes.add(new SelectOption(rt.DeveloperName,rt.DeveloperName));            
             
        }
        
        system.debug('selectedRec in const'+selectedRec);
    }
    
    public List<SelectOption> getBusinessUnits()
    {
        system.debug('selectedRec'+selectedRec);
        List<selectoption> BusinessUnits=null;
        //not
        if(selectedRec!=null)
        {
            BusinessUnits= new List<SelectOption>();
            //BusRecTypes[0] = selectedRec;
             //where RecordType.name=:selectedRec
             //system.debug('In if');
            List<RFA_Business_Unit__c> listunits=[select id,name from RFA_Business_Unit__c  where RecordType.name = :selectedRec];
            BusinessUnits.add(new SelectOption('--Select--','--Select--'));
            for(RFA_Business_Unit__c cat: listunits)
            {
                
                BusinessUnits.add(new SelectOption(cat.name,cat.name));
            }
            system.debug('BusinessUnits size'+BusinessUnits.size());
            system.debug('Business unit'+BusinessUnits);
           //  
        }
        
        return BusinessUnits;
    }   
    public list<selectoption> getCategories()
    {
        system.debug('selectedUnit'+selectedUnit);
        List<SelectOption> Categorieslist=null;
        List<RFA_Category__c> categories;
        if(!(selectedRec==null))
        {
            
            Categorieslist = new List<SelectOption>();
            Categorieslist.add(new SelectOption('--Select--','--Select--'));
            categories=[select id,Category__c,RFA_Business_Unit__r.Name,name from RFA_Category__c where RFA_Business_Unit__r.Name=:selectedUnit];
            for(RFA_Category__c cat:categories)
            {                
                Categorieslist.add(new SelectOption(cat.name,cat.name));
            }
        }
        return Categorieslist;
    }    
    public list<selectoption> getProfitcenters()
    {
        system.debug('selectedpc'+selectedPC);
        List<SelectOption>  pclist=null;
        List<ProfitCenter__c> profitcenters;
        if(!(selectedCategory==null))
        {            
            Pclist = new List<SelectOption>();
            pcStringList = new List<String>();
            system.debug('selectedCategory'+selectedCategory);
            Pclist.add(new SelectOption('--Select--','--Select--'));
            profitcenters=[select id,name from ProfitCenter__c where Category__r.name=:selectedCategory];
            for(ProfitCenter__c pc:profitcenters)
            {                
                Pclist.add(new SelectOption(pc.name,pc.name));
                pcStringList.add(pc.name);
            }
        }
        return Pclist;
    } 
    
    public RFA_Approver__c  getApprovers()
    {
        RFA_Approver__c obj=[select id,UserName__c from RFA_Approver__c limit 1];  
        List<ProfitCenterCOAGroupJunctionobject__c> PfCOA= [select id,RFA_COA_Group_Name__r.name,RFA_COA_Group_Name__c,Profit_Center_Number__c,name from ProfitCenterCOAGroupJunctionobject__c where Profit_Center_Number__r.name in :pcStringList];
        system.debug('PfCOA..'+PfCOA);       
        coaGroups=new List<RFA_COA_Group__c>();
        for(ProfitCenterCOAGroupJunctionobject__c pfCOAObj: PfCOA)
        {
            coaGroups.add(pfCOAObj.RFA_COA_Group_Name__r);
        }
        List<RFA_Approver__c> applist=[select id,UserName__c from RFA_Approver__c where RFA_COA_Group__c in :coaGroups];
        obj=applist.get(0);
        return obj;
    }
    
    public PageReference viewApprovers()
    {
        
        List<ProfitCenterCOAGroupJunctionobject__c> PfCOA= [select id,RFA_COA_Group_Name__r.name,RFA_COA_Group_Name__c,Profit_Center_Number__c,name from ProfitCenterCOAGroupJunctionobject__c where Profit_Center_Number__r.name in :pcStringList];
        system.debug('PfCOA..'+PfCOA);       
        coaGroups=new List<RFA_COA_Group__c>();
        for(ProfitCenterCOAGroupJunctionobject__c pfCOAObj: PfCOA)
        {
            coaGroups.add(pfCOAObj.RFA_COA_Group_Name__r);
        }
        List<AggregateResult> ListGroupbyamount =[select count(id),amount__C from RFA_COA_Group__c where id in :coaGroups group by amount__c ];
        for(AggregateResult ar: ListGroupbyamount )
        {
            //String ar=ar.get('');
            system.debug('agregated result: '+ar);
            
        }
        
        
        
        //List<RFA_Approver__c> approversList=[select id from RFA_Approver__c where RFA_COA_Group__r in:coaGroups ];
        
        return null;
    }
  */  
    
}