Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_WS06_CheckLC.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_AP14CheckLC
 *  Author           : Accenture
 *  Version History  : 3.0
 *  Creation         : 07/10/2012
 *  Assumptions      : N/A
 *  Description      : Class for checking the location coordinator for logged in user. This class is used in custom button at profit center level.
                                    
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/
global class RFA_WS06_CheckLC{

    /**
     *  WebService method
     *  @param profitCenterId
     *  @return boolean(true, false)   
     */
    WebService static Boolean isLocationCoorinator(Id pfId)
    {
        
        User usr=[Select Profile.Name, id from User where id=:UserInfo.getUserId() Limit 1]; // User query to fetch profile Name for logged In user to bypass the custom validation
        String UserNameProfile=usr.Profile.Name; //storing the profile name
        Boolean flag=false;    
        if(UserNameProfile!=Label.RFA_CL053 &&  UserNameProfile!=Label.RFA_CL052 && UserNameProfile!=Label.RFA_CL054 && UserNameProfile!=Label.RFA_CL055)  // Bypass for System Admin profile
        { 
            // Query to get the profit center & associated users role into profit center
            for(ProfitCenter__C profitCenter : [Select id,(Select id from Profit_Center_Associated_Users__r where UserType__c =:RFAGlobalConstants.PC_USERTYPE_LC and UserName__c =:UserInfo.getUserId()  ) from ProfitCenter__c where Id=:pfId])
            {    
                system.debug(profitCenter);
                if(!profitCenter.Profit_Center_Associated_Users__r.IsEmpty())
                    flag=true;        
            }
        }
        else
        {
            flag=true;
        }
        return flag;
    }

}