Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <controllingField>UserType__c</controllingField>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserType__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Location Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer - Capital Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_WS06_CheckLC_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */ 
@isTest
private class RFA_WS06_CheckLC_Test {

    static testMethod void myUnitTest() {
    test.StartTest();
       
        RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	//testData.buildProfitCenterUserRole(RFATestData.testProfitCenter.Id); 
    	testData.createRequester();
  		
  		//Adding loggedIn User
    	
    	
    	ProfitCenterUserRole__c koUserRole_User = new ProfitCenterUserRole__c();
    	koUserRole_User.Level__c = '1. Key Operations';
    	koUserRole_User.ProfitCenter__c =RFATestData.testProfitCenter.Id;
    	koUserRole_User.UserName__c = RFATestData.requester.Id;
    	koUserRole_User.UserType__c = 'Location Coordinator';
    	insert koUserRole_User;
    	
    	koUserRole_User.UserName__c=UserInfo.getUserId();
    	koUserRole_User.UserType__c='2. Business Unit';
    	update koUserRole_User;
    	System.RunAs(RFATestData.requester)
    	{
    		
  		RFA_WS06_CheckLC.isLocationCoorinator(RFATestData.testProfitCenter.Id);
    	}
    	System.RunAs(RFATestData.requester)
    	{
    	koUserRole_User.UserType__c='2. Business Unit';
    	try{
    	update koUserRole_User;
    	}catch (DMLException e)
    	{	
    		System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));	
    	}
    	koUserRole_User.UserName__c=UserInfo.getUserId();
    	try{
    		
    	}catch(DMLException e)
    	{
    			System.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));	
    	
    	}
    	
    	}
    	RFA_WS06_CheckLC.isLocationCoorinator(RFATestData.testProfitCenter.Id);
    	}
}