Jann 30/objects/ProfitCenter__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Hierarchy within the RFA Application. Profit Centers will also be referenced on specific RFAs.</description>
    <label>Profit Center</label>
    <nameField>
        <label>Profit Center Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profit Centers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/ProfitCenterUserRole__c.object
<CustomObject>
    <description>RFA R1 - Stores the Profit Center Associated Location Coordinators and Viewers (Hierarchy) within the RFA Application.</description>
    <fields>
        <fullName>ProfitCenter__c</fullName>
        <label>Profit Center</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>Profit Center User Roles</relationshipLabel>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Profit_Center_Associated_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Profit Center User Role</label>
    <nameField>
        <displayFormat>Users-{00000000}</displayFormat>
        <label>Profit Center User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center User Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_EditPopupforApprvrsControler.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_VFC_EditPopupforApprvrsControler
 *  Author           : infosys
 *  Version History  : 1.0
 *  Creation         : 11/18/2015
 *  Assumptions      : N/A
 *  Description      : Controller Class for restricts the RFA users to edit the approvers when RFA is in Circulation Stage
                       
 * Change History    : --NA--
 
 * Author            : jyoshna_g@infosys.com
 * Date of Change    : Nov 18, 2015
                                             
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/

public with sharing class RFA_VFC_EditPopupforApprvrsControler 
{
    public RFAUserrole__c rfauseroleobj{get;set;} 
    public RFAUserrole__c rfaobj {get;set;}
    public RFA__c stage {get;set;}
    public string usertype {get;set;}
    public string ProfileName {get;set;}
    public boolean userexistinPC {get;set;}
    //Controller gets the RFA current stage and user profile information
    public RFA_VFC_EditPopupforApprvrsControler(ApexPages.StandardController ctlr)
    {
       userexistinPC  = false;
        try
        {
            Id userId = userinfo.getUserId();
            Id profileId=userinfo.getProfileId();
            ProfileName=[Select Id,Name from Profile where Id=:profileId].Name;        
            rfaobj = new RFAUserrole__c();
            rfauseroleobj= (RFAUserrole__c)ctlr.getRecord();              
            rfaobj = [select RFA__c,RecordtypeId from RFAUserRole__c where id=: rfauseroleobj.Id];        
            usertype = [select Name from Recordtype where SobjectType='RFAUserRole__c' and ID =: rfaobj.RecordtypeId].Name;        
            stage = [select stage__c from RFA__c where ID =: rfaobj.RFA__c ];
            ID profitcenter =[select ProfitCenterNumber__c from RFA__c where ID =: rfaobj.RFA__c].ProfitCenterNumber__c ;
            List<ProfitCenterUserRole__c> pcusrobj = [select UserName__c from ProfitCenterUserRole__c where UserName__c =:userId and ProfitCenter__c =:profitcenter]; 
            if(pcusrobj !=null)
            {
              //userexistinPC  = true;
            }
        }
        catch(Exception ex)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage())); 
        }
             
        
    }
}