Jann 30/objects/ReportingUnit__c.object
<CustomObject>
    <description>RFA R1 - Stores all Reporting Units within the RFA Application to be referenced on a specific RFA.</description>
    <fields>
        <fullName>ActiveInactive__c</fullName>
        <label>Active/Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NeedRecalculation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Recalculation</label>
        <type>Checkbox</type>
    </fields>
    <label>Reporting Unit</label>
    <nameField>
        <label>Reporting Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Units</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreviousLevel__c</fullName>
        <description>Preserves the Stage value when the RFA is put into &quot;Return to Sender&quot;, &quot;Capital Management Hold&quot; or &quot;Pending Board Review&quot; stage</description>
        <label>Previous Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryReportingUnitNumber__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reporting Unit (RU) is the same as Co. Code and is either a legal entity or an acctg location.  RU is a four-digit code with an “RU” prefix in this system (e.g. RU0101 – North America).  Select the RU(s) recording the transaction.</inlineHelpText>
        <label>Primary Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SecondReportingUnitNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A four-digit code that is the lowest level at which consolidation occurs. Same as Co. code and is either a legal entity or an acctg. location (e.g., 0101 - North America). Select the reporting unit(s) recording the transaction.</inlineHelpText>
        <label>Second Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA (Secondary Reporting Unit Number)</relationshipLabel>
        <relationshipName>RFA1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThirdReportingUnitNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A four-digit code that is the lowest level at which consolidation occurs. Same as Co. code and is either a legal entity or an acctg. location (e.g., 0101 - North America). Select the reporting unit(s) recording the transaction.</inlineHelpText>
        <label>Third Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA (Third Reporting Unit Number)</relationshipLabel>
        <relationshipName>RFA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC11_ReportingUnitRecalculation.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_VFC11_ReportingUnitRecalculation
 *  Author           : Accenture
 *  Version History  : 1.0
 *  Creation         : 04/28/2013
 *  Assumptions      : N/A
 *  Description      : Class for calling the schedule function for sharing recalculation from RFA_VFP11_ReportingUnitRecalculation. 
                                    
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/

public class RFA_VFC11_ReportingUnitRecalculation {
    
    /*~~~~Start of Variable Initialization~~~~*/ 
    public ReportingUnit__c reportingUnit{get;set;}
    public String Query;
    /*~~~~End of Variable Initialization~~~~*/
    
    /**
     * Constructor
     */
    public RFA_VFC11_ReportingUnitRecalculation (ApexPages.StandardController stdController) {
    reportingUnit = (ReportingUnit__c)stdController.getRecord ();
    }
    
    /**
     *  pageReference method
     *  @param 
     *  @return pageReference   
     */
            
    public pageReference callRecalculationMethod()
    {
    /*Query='Select Id ,name from ReportingUnit__c where Id=\''+reportingUnit.Id+'\' and NeedRecalculation__c=true and ActiveInactive__c=\'Active\' ';
    System.debug(Query);
    RFA_AP20_ReportingUnitRealignment controller = new RFA_AP20_ReportingUnitRealignment(Query);
    Integer batchSize = 200;
    */
    Set<id> reportingUnitIds = new Set<Id>(); 
        List<ReportingUnit__c> reportingUnitList = [Select Id ,name from ReportingUnit__c where NeedRecalculation__c=true and ActiveInactive__c='Active'];
        for(ReportingUnit__c reportingUnitObj : reportingUnitList)
            reportingUnitIds.add(reportingUnitObj.Id);
        String Query = 'Select PrimaryReportingUnitNumber__c,SecondReportingUnitNumber__c,ThirdReportingUnitNumber__c,id,Level__c, PreviousLevel__c from RFA__c where ' 
          +'PrimaryReportingUnitNumber__c IN :reportingUnitIds OR SecondReportingUnitNumber__c IN :reportingUnitIds OR ThirdReportingUnitNumber__c IN :reportingUnitIds '
          +'ORDER BY CreatedDate DESC';
   	RFA_AP20_ReportingUnitRealignmentFix controller = new RFA_AP20_ReportingUnitRealignmentFix(Query,reportingUnitIds) ;
    Integer batchSize = 100;      
    database.executebatch(controller , batchSize);
    pageReference pref;
    ApexPages.StandardController sc = new ApexPages.StandardController(reportingUnit);
    pref = sc.view();
    pref.setRedirect(true);
    return pref;
    }
    

}