Jann 30/objects/ReportingUnit__c.object
<CustomObject>
    <description>RFA R1 - Stores all Reporting Units within the RFA Application to be referenced on a specific RFA.</description>
    <fields>
        <fullName>NeedRecalculation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Recalculation</label>
        <type>Checkbox</type>
    </fields>
    <label>Reporting Unit</label>
    <nameField>
        <label>Reporting Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Units</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreviousLevel__c</fullName>
        <description>Preserves the Stage value when the RFA is put into &quot;Return to Sender&quot;, &quot;Capital Management Hold&quot; or &quot;Pending Board Review&quot; stage</description>
        <label>Previous Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryReportingUnitNumber__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reporting Unit (RU) is the same as Co. Code and is either a legal entity or an acctg location.  RU is a four-digit code with an “RU” prefix in this system (e.g. RU0101 – North America).  Select the RU(s) recording the transaction.</inlineHelpText>
        <label>Primary Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SecondReportingUnitNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A four-digit code that is the lowest level at which consolidation occurs. Same as Co. code and is either a legal entity or an acctg. location (e.g., 0101 - North America). Select the reporting unit(s) recording the transaction.</inlineHelpText>
        <label>Second Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA (Secondary Reporting Unit Number)</relationshipLabel>
        <relationshipName>RFA1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThirdReportingUnitNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A four-digit code that is the lowest level at which consolidation occurs. Same as Co. code and is either a legal entity or an acctg. location (e.g., 0101 - North America). Select the reporting unit(s) recording the transaction.</inlineHelpText>
        <label>Third Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA (Third Reporting Unit Number)</relationshipLabel>
        <relationshipName>RFA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_AP20_ReportingUnitRealignment.cls
/**
* Class Name: RFA_AP20_ReportingUnitRealignment
* Author: Accenture
* Date: 04-28-2013
* Project Name: Coke-RFA
 * Requirement Description: This batch is used for realignment for security of Reporting Unit.
 **/


global class RFA_AP20_ReportingUnitRealignment implements Database.Batchable<SObject>{

    // Variables
    global string query;
    public Static String errorString;
    
    /**
     * Constructor
     */
      public RFA_AP20_ReportingUnitRealignment (String query)
      {
            this.query=query;
      }
      
      /**
     *  start method
     *  @param Database.BatchableContext
     *  @return Database.Querylocator
     */
    global Database.Querylocator start(Database.BatchableContext bc){
        return DataBase.getQueryLocator(query);
    }
    
    /**
     *  execute method
     *  @param Database.BatchableContext
     *  @param List<SObject>
     */
    global void execute(Database.BatchableContext bC, List<sObject> reportingUnitRecords){
      Map<Id, Set<Id>> reportingUnitMap=new Map<Id, Set<Id>>(); // RFAId, Set of (potentially three) Reporting Unit ID on the RFA
      Set<id> reportingUnitIds=new Set<Id>(); // used for storing list of Profit Center record IDs impacted
      Set<id> reportingUnitSet; // set of (potentially three) Reporting Unit ID on the RFA
      List<ReportingUnit__c> reportingUnitUpdateList=new List<ReportingUnit__c>(); // used to reset NeedRecalculation flag
      RFA_AP02_Shareutil shareUtil=new RFA_AP02_Shareutil(); //Instantiate ShareUtil class
      
      for(sObject s : reportingUnitRecords)
      {
            ReportingUnit__c reportingUnit=(ReportingUnit__c)s;
            reportingUnitIds.add(reportingUnit.Id);
      }
      
      for(RFA__c rfaRecord: [Select PrimaryReportingUnitNumber__c,SecondReportingUnitNumber__c,ThirdReportingUnitNumber__c,id,Level__c, PreviousLevel__c from RFA__c where 
      		PrimaryReportingUnitNumber__c IN :reportingUnitIds OR SecondReportingUnitNumber__c IN :reportingUnitIds OR ThirdReportingUnitNumber__c IN :reportingUnitIds
      		ORDER BY CreatedDate DESC
      		LIMIT : (limits.getLimitQueryRows() - limits.getQueryRows())])
      {
      		reportingUnitSet=new Set<Id>();
      	
      		if(rfaRecord.PrimaryReportingUnitNumber__c<>null)
                reportingUnitSet.add(rfaRecord.PrimaryReportingUnitNumber__c);
            if(rfaRecord.SecondReportingUnitNumber__c<>null)
                reportingUnitSet.add(rfaRecord.SecondReportingUnitNumber__c);
            if(rfaRecord.ThirdReportingUnitNumber__c<>null)
                reportingUnitSet.add(rfaRecord.ThirdReportingUnitNumber__c);
            reportingUnitMap.put(rfaRecord.id,reportingUnitSet);
      	
      	// confirm what this looks like in the system debug
      	System.debug('reportingUnitMap <RFA Id, ReportingUnitSet>: ' + reportingUnitMap);
        }
        
        if(!reportingUnitMap.IsEmpty())
        {
            shareUtil.rfaReportingUnitChangeDelete(reportingUnitMap);
            shareUtil.reportingUnitCreteShare(reportingUnitMap);
        }
        
        // Reset NeedRecalculation field flag on Profit Center to False
        for(Id reportingUnitId:reportingUnitIds) 
        {
            ReportingUnit__c reportingUnit=new ReportingUnit__c(id=reportingUnitId);
            reportingUnit.NeedRecalculation__c=false;
            reportingUnitUpdateList.add(reportingUnit);
                
        }
        
        if(!reportingUnitUpdateList.IsEmpty())
        {
            update reportingUnitUpdateList;
        }
    }
   
    /**
     *  finish method
     *  @param Database.BatchableContext
     */
    global void finish(Database.BatchableContext BC){
           
    }
     
}