Jann 30/objects/ReportingUnit__c.object
<CustomObject>
    <description>RFA R1 - Stores all Reporting Units within the RFA Application to be referenced on a specific RFA.</description>
    <fields>
        <fullName>ActiveInactive__c</fullName>
        <label>Active/Inactive</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NeedRecalculation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Recalculation</label>
        <type>Checkbox</type>
    </fields>
    <label>Reporting Unit</label>
    <nameField>
        <label>Reporting Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Units</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Jann 30/classes/RFA_BC02_ReportingUnitRealignment.cls
/**
* Class Name: RFA_BC02_ReportingUnitRealignment
* Author: Accenture
* Date: 05-08-2013
* Project Name: Coke-RFA
* Requirement Description: This is schedule batch which will call the RFA_AP20_ReportingUnitRealignment class.
 
 **/
global class RFA_BC02_ReportingUnitRealignment implements Schedulable{
    
    /**
     *  execute  method
     *  @param Crone Time
     *  @return null    
     */
    global void execute(SchedulableContext sc) {
        String Query='Select Id ,name from ReportingUnit__c where NeedRecalculation__c=true and ActiveInactive__c=\'Active\'';
        RFA_AP20_ReportingUnitRealignment controller = new RFA_AP20_ReportingUnitRealignment(Query) ;
        Integer batchSize = 200;
        database.executebatch(controller , batchSize);
   }

}