Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase.  (e.g.,  Write-off  45 non-working vending machines in Atlanta sales center)</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Agent1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agent3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agent3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_WS02_KOApprove_getAllRequests.cls
/* WebService to get All Requests*/ 
     
global class RFA_WS02_KOApprove_getAllRequests {
 
 /* @Method <This webservice method is creating the response to return fetched the attachment details based on the passed Atatchment SFDC Id. >
       @param 
       @return <rfaFinalWrapper> - Returning Data type of inner class. Method Output includes RFADetail,Approvers details and the Service Status (Suuccess or Failure) in the form of Code and Description.
       @throws exception - <Throwing Query Exception>
    */
     WebService static list<rfaFinalWrapper> getAllRFADetails()
        {
            /*~~~~Start of Variable Initialization~~~~*/ 
            List<rfaFinalWrapper> finalResult=new List<rfaFinalWrapper>(); // Final Wrapper to pass the pending request details and message
            List<rfaDataContainer> dataContainer=new List<rfaDataContainer>(); // Data container for contain all the requets
            List<rfaWrappersForAllRequests> result =new List<rfaWrappersForAllRequests>(); // RFADetails added into result Wrapper
            List<usersWrappers> resultUsers=new List<usersWrappers>(); // User Role Objects added into usersWrappers
            List<userDetailWapper> usersDetailWapper=new List<userDetailWapper>();
            Map<Id,Boolean> attachmentFlagMap=new Map<Id,Boolean>();
            statusMessageWrapper message=new statusMessageWrapper();//Message class instance
            RFA_Util_ObjectQuery qry = New RFA_Util_ObjectQuery(); // Instance of the Util class to call the Attachment query method
            List<RFA__c> rfaList=new List<RFA__c>();  
            
            /*~~~~End of Variable Initialization~~~~*/
            
            Map<RFA__c,List<RFAUserRole__c>> mapRFAUserRoleRecords=new Map<RFA__c,List<RFAUserRole__c>>();      
            try{  
                rfaList=qry.getAllRFADetailsForAwaitingApprovers(); // Query to get all the RFA details with user role records.
            }catch(System.QueryException e) 
            {
                message.code=Label.RFA_CL034; // Message Exception in Query - Error
                message.description=e.getMessage(); // Description of the Query Exception
                finalResult.add(
                    new rfaFinalWrapper(message));
                System.debug('#######Catched Exception :'+e);
                System.debug('#######Query Error Message :'+message);
                return finalResult;
            }
            /**************Adding records to all the wrapper ************/
            for(RFA__c rfaRecord:rfaList)
            {
                if(rfaRecord.RFA_User_Roles__r.size()>0) // if no approval records is pending then donot add into map. 
                {
                    mapRFAUserRoleRecords.put(rfaRecord,rfaRecord.RFA_User_Roles__r);   
                    if((rfaRecord.Attachments).size()>0)   // check the attachment exist at RFA level.
                    {
                        attachmentFlagMap.put(rfaRecord.Id,True);   
                    }
                    else
                    {
                        attachmentFlagMap.put(rfaRecord.Id,false);  
                    }
                }
            }
            /**************Adding records to all the wrapper ends here************/
            
            // check the Map Size and return the exception
            if(mapRFAUserRoleRecords.size()==0)
            {
                message.code=Label.RFA_CL034; // Message Exception in Query - Error
                message.description=Label.RFA_CL037; // No pending record in the RFA 
                finalResult.add(
                    new rfaFinalWrapper(message));
                return finalResult;
            }
            try{
                // Traverse the map of all the records and add into different wrapper.
                
                for(RFA__c rfaRecord:mapRFAUserRoleRecords.keySet())
                {
                    resultUsers=new List<usersWrappers>();
                    usersDetailWapper=new List<userDetailWapper>();
                    for(RFAUserRole__c rfaUserRoleRecord:mapRFAUserRoleRecords.get(rfaRecord)) // traverse the map values.
                    {
                        // add all the user role details into userDetailWrapper.
                        
                         usersDetailWapper.add(
                            new userDetailWapper(rfaUserRoleRecord.UserName__r.Email,String.valueof(rfaUserRoleRecord.UserName__r.FederationIdentifier)));
                        if(rfaUserRoleRecord.Agent1__c!=null)
                                usersDetailWapper.add(
                            new userDetailWapper(rfaUserRoleRecord.Agent1__r.Email,String.valueof(rfaUserRoleRecord.Agent1__r.FederationIdentifier)));
                        if(rfaUserRoleRecord.Agent2__c!=null)
                                usersDetailWapper.add(
                            new userDetailWapper(rfaUserRoleRecord.Agent2__r.Email,String.valueof(rfaUserRoleRecord.Agent2__r.FederationIdentifier)));
                        if(rfaUserRoleRecord.Agent3__c!=null)
                                usersDetailWapper.add(
                            new userDetailWapper(rfaUserRoleRecord.Agent3__r.Email,String.valueof(rfaUserRoleRecord.Agent3__r.FederationIdentifier)));        
                     }
                    // once users details are added for one rfa then add into parent usersWrapper
                    resultUsers.add(
                        new usersWrappers(usersDetailWapper)); 
                        Boolean attachmentFlag= attachmentFlagMap.get(rfaRecord.Id);    // find the attachment flag into existing attachmentMap
                   // add one complete request into rfaWrappersForAllRequests
                    result.add(
                        new rfaWrappersForAllRequests(rfaRecord.Id,rfaRecord.Level__C,rfaRecord.requestTitle__C,rfaRecord.CreatedDate,attachmentFlag,resultUsers));         
                }
                // add all complete requests into rfaDataContainer
                dataContainer.add(
                    new rfaDataContainer(result));
                    message.Code=label.RFA_CL028; //SUCCESS
                    message.Description=label.RFA_CL028; //SUCCESS
                // add data container & message details into rfaFinalWrapper.   
                finalResult.add(
                    new rfaFinalWrapper(dataContainer,message));    
                
                return finalResult;
            }catch(Exception e)
            {
                // catch the exceptions if any.
                
                message.code=Label.RFA_CL034; // Message Exception in Query - Error
                message.description=e.getMessage(); // No pending record in the RFA 
                finalResult.add(
                    new rfaFinalWrapper(message));
                return finalResult;
            
            }
        }          
        /*
        Class Type     : Inner Class
        Date Created  : 06/08/2012
        Description     : This is our wrapper/container Inner class to display the RFA Details along with the Service StatusMessage. 
                               The wrapper class contains requests DataContainerWrappers inner class and Inner class value for status message .
        Version          : 1.0 
    */ 
    
        global class rfaFinalWrapper{
             /*~~~~Start of Variable Initialization~~~~*/     
            WebService List<rfaDataContainer> requests;  //DeclarerfaDataContainerWrapper
            WebService statusMessageWrapper message; // Message Wrapper 
            /*~~~~End of Variable Initialization~~~~*/
            
            /*~~~~Constructors~~~~*/ 
            public rfaFinalWrapper(){}
            /*~~~~Constructors with message parameter~~~~*/ 
            public rfaFinalWrapper(statusMessageWrapper message){
                this.message=message;
            }
            // Contructor Overloading to pass rfaDataContainer and Status Message
            public rfaFinalWrapper(List<rfaDataContainer> requests,statusMessageWrapper message) 
            {
                this.requests=requests;
                this.message=message;
            }
        }
     /*
        Class Type     : Inner Class
        Date Created  : 06/08/2012
        Description     : This is our wrapper/container Inner class to add the rfaWrappersForAllRequests. 
                               
        Version          : 1.0 
    */
        global class rfaDataContainer{
             /*~~~~Start of Variable Initialization~~~~*/     
            WebService List<rfaWrappersForAllRequests> request;
            /*~~~~Constructors~~~~*/ 
            public rfaDataContainer(){}
            // Contructor Overloading to pass rfa details wrapper- rfaWrappersForAllRequests
            public rfaDataContainer(List<rfaWrappersForAllRequests> request) 
            {
                this.request=request;
            }
        }
     /*
        Class Type     : Inner Class
        Date Created  : 06/08/2012
        Description     : This is our wrapper/container Inner class to add the rfaDetails & user details wrapper. 
                               
        Version          : 1.0 
    */
        global class rfaWrappersForAllRequests{
              /*~~~~Start of Variable Initialization~~~~*/     
            WebService String rfaId; // rfaId represents as UserId
            WebService String level; // RFA Level
            WebService String requestTitle; // RFA Request Title
            WebService DateTime submitDate;  // RFA CreatedDate
            WebService Boolean hasAttachment; // RFA Attachments exists
            WebService List<usersWrappers> users; // Users details wrapper
           /*~~~~End of Variable Initialization~~~~*/
           
           /*~~~~Constructors~~~~*/ 
            public rfaWrappersForAllRequests(){}
            // Contructor Overloading to pass rfa details- rfaId, level, requestTitle, submitDate,hasAttachment,usersWrappers
            public rfaWrappersForAllRequests(String rfaId,String level,String requestTitle,DateTime submitDate,Boolean hasAttachment,List<usersWrappers> users)
            {
                this.rfaId=rfaId;
                this.level=level;
                this.requestTitle=requestTitle;
                this.submitDate=submitDate;
                this.hasAttachment=hasAttachment;
                this.users=users;      
            
            }
            
        }
    /*
        Class Type     : Inner Class
        Date Created  : 06/08/2012
        Description     : This is our wrapper/container Inner class to add the user details wrapper. 
                               
        Version          : 1.0 
    */
        global class usersWrappers{
             /*~~~~Start of Variable Initialization~~~~*/     
            WebService List<userDetailWapper> user;
            /*~~~~End of Variable Initialization~~~~*/
            
             // Contructor Overloading to pass USerRole details wrapper- userDetailWapper
            public usersWrappers(List<userDetailWapper> user)
            {
                this.user=user;
            }
            
        }
    /*
        Class Type     : Inner Class
        Date Created  : 06/08/2012
        Description     : This is our wrapper/container Inner class to display the email and federationId in the Service . 
        Version          : 1.0 
    */ 
        global class userDetailWapper{
            WebService String email;
            WebService String federationId;
            /*~~~~End of Variable Initialization~~~~*/
            
            // Contructor Overloading to pass USerRole details - Email, UserName__C
            public userDetailWapper(String email,String federationId)
            {
                this.email=email;
                this.federationId=federationId;
            }
            
        } 
        
        /*
        Class Type     : Inner Class
        Date Created  : 06/08/2012
        Description     : This is our wrapper/container Inner class to display the code and description Service StatusMessage. 
                               The wrapper class contains the 2 string values to display the code and description of the Status.
        Version          : 1.0 
    */
        global class statusMessageWrapper{
       /*~~~~Start of Variable Initialization~~~~*/
        WebService String description; // Status Description 
        WebService String code; // Status Code
        /*~~~~End of Variable Initialization~~~~*/
        
        /*~~~~Constructors~~~~*/ 
        public statusMessageWrapper(){} // Default Constructor
        
        // Constructor Overloading to pass the Status Code and Description
        public statusMessageWrapper(String code, String description)
        {
            this.code=code;
            this.description=description;
        }
    }
        
}