Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>POC_Total__c</fullName>
        <description>Counts all POC in an RFA</description>
        <label>POC Total</label>
        <summaryFilterItems>
            <field>RFAUserRole__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Primary Point of Contact</value>
        </summaryFilterItems>
        <summaryForeignKey>RFAUserRole__c.RFA__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RFA_Level__c</fullName>
        <formula>TEXT(RFA__r.Level__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RFA Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFAUserRoleManager.cls
/**
* Author,email :     Mads Pascua , mpascua@coca-cola.com
* Date Create  :     Nov 5, 2013
* Description  :     The Apex Class that contains methods used by the main trigger for RFAUserRole__c.
*                    
* REVISION HISTORY
*
* Author,email :
* Date Revised :
* Description  :
**/

public class RFAUserRoleManager {

    public class RFAUserRoleException extends Exception {}
    // Get RecordTypes associated to RFAUser Role    
    public static Map<String, RecordType> approverRecordTypeMap = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.sObjectType.RFAUserRole__c.getName());
  
    public static void preventPointOfContactDeletionWhenNotInDraft(List<RFAUserRole__c> oldRFAUserRole) { 
        Map<Id, RFA__c> rfaMap = new Map<Id, RFA__c>();
        Set<Id> idSet = new Set<Id>();
        for(RFAUserRole__c rfaur : oldRFAUserRole){
           idSet.add(rfaur.RFA__c);
        }
        List<RFA__c> rfaList = [SELECT Id, Level__c, POC_Total__c from RFA__c WHERE Id IN: idSet LIMIT 1000];
        for(RFA__c rfa: rfaList){
            rfaMap.put(rfa.Id, rfa);
        }
  
        for(RFAUserRole__c rfaur : oldRFAUserRole){

               if(rfaur.RecordTypeId == approverRecordTypeMap.get(RFAGlobalConstants.RECORDTYPE_PRIMARY_POC).Id && !rfaur.RFA_Level__c.equalsIgnoreCase(RFAGlobalConstants.RFA_STAGE_DRAFT)){
                   //rfaur.addError('Cannot delete Primary Point Of Contact. RFA no longer in Draft.');
                   Integer counterPOC = Integer.valueOf(rfaMap.get(rfaur.RFA__c).POC_Total__c);
                   if(counterPOC < 2){
                       rfaur.addError('Cannot delete Primary Point Of Contact. At least 1 Primary Point of Contact is needed when as RFA is no longer in Draft.');
                   }    
               }                
          
        }   
           
    }   
}