Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <inlineHelpText>A field used for Capital Management to capture comments concerning the RFA.  These comments will not be viewable by the RFA Creator or Approvers.  Example:  Explanation of why an RFA was closed.</inlineHelpText>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LevelStage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Level / Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VC_CloseDraftRFA.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_VC_CloseDraftRFA
 *  Author           : mpascua@coca-cola.com
 *  Version History  : 1.0
 *  Creation         : 08/19/2013
 *  Assumptions      : N/A
 *  Description      : This is a controller class which provide functoinality to close Draft RFAs.
                       Users can add comments when closing draft RFAs in the visualforce page (RFA_VFP_CloseDraftRFA) where this class is used.
                       Visualforce page (pop-up) is attached to button("Close RFA") on RFA page.             
 ****************************************************************************************************************************************
 ****************************************************************************************************************************************/
 public class RFA_VC_CloseDraftRFA{

    public RFA__c rfaObj {get;set;}
    public List<RFA__c> rfaList {get;set;}
    public String defaultURL {get;set;}
    public String userComment {get;set;}
    public Set<Id> rfaIdSet {get;set;}   
    public boolean hasError{get; private set;}
    
    public RFA_VC_CloseDraftRFA(ApexPages.StandardController controller) {
        
        this.hasError = false;
        this.rfaObj = (RFA__c)controller.getRecord();
        this.userComment = '';
        rfaIdSet = new Set<Id>();
        rfaIdSet.add(this.rfaObj.Id);
        
        this.rfaList = [SELECT Level__c, Name, Stage__c, Id FROM RFA__c WHERE Id IN:rfaIdSet LIMIT 1 ];

        //ApexPages.addMessage(﻿ new ApexPages.Message(ApexPages.Severity.FATAL, 'my error msg')﻿);

        defaultURL = URL.getSalesforceBaseUrl().toExternalForm()+'/apex/RFA_VFP11_RFATab?save_new=1&sfdc.override=1';
    
    }
    
    public void closeDraftRFA(){
        /*  
        this.hasError = true;
        String errString = 'Test';
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errString)); 
        */
        
        try{
            this.hasError = false;
            
            if(rfaList.size() > 0){
                //rfaList[0].Level__c = '';
                rfaList[0].Stage__c = 'Draft Closed';
                rfaList[0].LevelStage__c = 'Draft Closed';
                if(userComment!= null && userComment != ''){
                    rfaList[0].Comments__c = '[Draft Close] '+ userComment;
                }
                //rfaList[0].Level__c = 'Draft Closed';
                update rfaList;
          }
            
        }catch(Exception ex){
            ApexPages.addMessages(ex);
            this.hasError = true;
        }
    }
    
    public void reopenCloseDraftRFA(){
        /*  
        this.hasError = true;
        String errString = 'Test';
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errString)); 
        */
        
        try{
            this.hasError = false;
            
            if(rfaList.size() > 0){
                //rfaList[0].Level__c = '';
                rfaList[0].Stage__c = 'Draft';
                //rfaList[0].LevelStage__c = 'Draft Closed';
                //rfaList[0].Level__c = 'Draft Closed';
                update rfaList;
            }
            
        }catch(Exception ex){
            ApexPages.addMessages(ex);
            this.hasError = true;
        }
    }

    
 }