Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalLetterComments__c</fullName>
        <inlineHelpText>Standard comments describing conditional approval requirements.</inlineHelpText>
        <label>Follow-up: Approver Comments/Conditions</label>
        <picklist>
            <picklistValues>
                <fullName>The requesting party must ensure appropriate coordination with the above approver(s) to fully address any and all approval conditions.  Any failure to fully address these conditions will be subject to Audit review.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The requesting party must fully comply with the above approval conditions, although explicit communication or follow up with these approvers is not required.  Any failure to fully address these conditions will be subject to Audit review.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CommentsConditions__c</fullName>
        <inlineHelpText>Text provided by approvers of approval condition that must be accomplished before transaction initiation.</inlineHelpText>
        <label>Comments/Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Theapprovalstatusofyourrequestis__c</fullName>
        <description>Approval Status of the RFA Request</description>
        <inlineHelpText>Displays the approval status of the RFA (unconditionally approved, conditionally approved, etc.)</inlineHelpText>
        <label>This request has been</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed / Not Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected / Not Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Thefollowingitem__c</fullName>
        <inlineHelpText>Select level/stage the RFA was approved through according to the DOA/LCOA.</inlineHelpText>
        <label>This request was circulated to</label>
        <picklist>
            <picklistValues>
                <fullName>Key Operation level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Executive level for approval and/or for information only as required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The appropriate Board of Directors for approval as required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC04_CompletionMemoController_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RFA_VFC04_CompletionMemoController_Test
{

    static testmethod void RFA_VFC04_Completion_Test()
    {
    
    	RFATestData testData = new RFATestData();
    	testData.buildProfitCenter();
    	testData.createRequester();
    	String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;    	
    	RFA__c testRFA;
    	    	
    	System.runAs(RFATestData.requester)
    	{
    		testRFA = RFATestData.buildTestRFA(testRFA, rt);    		
    	}
    	ApexPages.Standardcontroller stdController1 = new ApexPages.Standardcontroller(testRFA);
    	RFA_VFC04_CompletionMemoController controller1 = new RFA_VFC04_CompletionMemoController(stdController1);
    	List<SelectOption> options = controller1.getSelectableUsers();
    	controller1.selectedRecipients.add(options[0]);
    	controller1.selectedCCusers = 'test@coke.com';
    	controller1.rfaObj.Thefollowingitem__c = 'Key Operation level for approval and/or for information only as required';
    	controller1.rfaObj.Theapprovalstatusofyourrequestis__c = 'Unconditionally Approved';
    	controller1.rfaObj.CommentsConditions__c = 'This is for the purpose of testing';
    	controller1.rfaObj.ApprovalLetterComments__c = 'The requesting party must ensure appropriate coordination with the above approver(s) to fully address any and all approval conditions. Any failure to fully address these conditions will be subject to Audit review.';
    	controller1.sendEmail();
    
    }

}