Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>AREMonth__c</fullName>
        <inlineHelpText>The month used to calculate the ARE value for the  RFA.  The current month should be used as the ARE month regardless of the Expected Commitment Date of the RFA transaction.</inlineHelpText>
        <label>A.R.E. Month *</label>
        <picklist>
            <picklistValues>
                <fullName>Select ARE</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BudgetType__c</fullName>
        <inlineHelpText>Identifies the capital budget request (CPR) as &quot;formal&quot; or &quot;initial&quot; . Initial is only used when details are not complete, but enough details exist to request initial budget allocation. Not available for SPR requests.</inlineHelpText>
        <label>Budget Type *</label>
        <picklist>
            <picklistValues>
                <fullName>Formal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DataClassification__c</fullName>
        <inlineHelpText>Select the appropriate Data Classification for this request. Note: Highly Restricted information cannot be entered into the sytem. If your request is Highly Restricted  or contains Highly Restricted information please contact your Location Coordinator.</inlineHelpText>
        <label>Data Classification *</label>
        <picklist>
            <picklistValues>
                <fullName>Restricted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confidential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Use</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ExecutiveSummary__c</fullName>
        <label>Executive Summary *</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Functional_Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The three-character abbreviation for the functional currency in which the request amount will be denominated.</inlineHelpText>
        <label>Functional Currency (FC) *</label>
        <referenceTo>ARE_RFA__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InitialBudgetYear__c</fullName>
        <inlineHelpText>The year the capital project is expected to begin spending.</inlineHelpText>
        <label>Initial Budget Year *</label>
        <picklist>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsthisanAnnualCapitalPlanrequest__c</fullName>
        <inlineHelpText>Used by Corporate Capital Management to flag annual capital plan requests for reporting purposes.</inlineHelpText>
        <label>Is this an Annual Capital Plan request?*</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>Hierarchy levels assigned as RFA Coordinators move RFAs to sets of approvers based upon DOA/LCOA approval levels.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1. Key Operations</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2. Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3. Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4. Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5. Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6. Senior Executive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Management Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Board Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return To Sender</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PrimaryDOACategorySubCategory__c</fullName>
        <inlineHelpText>This field allows the RFA Creator to select up to 3  DOA Categories that apply to the requested transaction.</inlineHelpText>
        <label>Primary DOA Category / Sub Category *</label>
        <picklist>
            <picklistValues>
                <fullName>1.A.1	Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.a	Capital Expenditures - Unbudgeted CPR or SPR Covered by Budget Shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.2.b	Capital Expenditures - Unbudgeted CPR or SPR Funded Partially or Fully from Corporate Reserve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.3	Capital Expenditures - Increase or Scope Change to Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.4	Capital Expenditures - Transfer of Capital Budget across Groups for a Previously Approved CPR or SPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.5	Capital Expenditures - Foreign Exchange Fluctuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.A.8	Capital Expenditures - Advance Appropriations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.B	Capital Expenditures - Capability and Performance Programs (CAPPrs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.C	Capital Expenditures - Bottles and Cases, Including Overages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.	IT Investments and Website Presence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.A	Real Property -  Acquisitions and Sales or Other Disposals of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.B	Real Property -  Donations of Real Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.C	Real Property - Condemnations or Easements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.A	Leases - Operating Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.B	Leases - Capital Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.A	Inventory Adjustments and Disposals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.B	Other Asset Impairments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.C	Asset Transfers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.D	Asset Disposals (Tangible Assets excluding Real Property and Inventory)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.A	Treasury - Banking Information Reports (BIR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.B	Treasury - External Borrowings and Lines of Credit (RFFs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.C	Treasury - Intercompany Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.D	Treasury - Loans Third Parties (Including CCFC Target Loan Programs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.1	Treasury - Guarantees to Third Parties - General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.E.2	Treasury - Guarantees Related to Tax Disputes or Other Matters Involving Governmental Bodies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.F	Treasury - Comfort Letters and Other Financial Security Instruments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.G	Treasury - Accommodation Purchases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.H	Treasury - Credit Terms/Policies or Incentives for Sales to Customers, Bottlers or Distributors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.1	Treasury - Exemption from Bad Debt Reserve Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.I.2	Treasury - Write-offs of Uncollectible Accounts Receivable from Bad Debt Reserve</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PrimaryReportingUnitNumber__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reporting Unit (RU) is the same as Co. Code and is either a legal entity or an acctg location.  RU is a four-digit code with an “RU” prefix in this system (e.g. RU0101 – North America).  Select the RU(s) recording the transaction.</inlineHelpText>
        <label>Primary Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestAmountFunctionalCurrency__c</fullName>
        <inlineHelpText>TCCC portion only. Request Amt is based on DOA/LCOA financial parameters e.g., Forecasted Contractual Spend, Financial Commitment, Impairment amt, etc.</inlineHelpText>
        <label>Request Amount (FC) *</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase.  (e.g.,  Write-off  45 non-working vending machines in Atlanta sales center)</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_AP14_DraftRFAReminder_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RFA_AP14_DraftRFAReminder_Test {

    static testMethod void testDraftReminder() {
        RFATestData testData = new RFATestData();
        testData.createRequester();
        testData.buildProfitCenter();
        String rt = RFAGlobalConstants.RECORDTYPESMAP.get(Schema.Sobjecttype.RFA__c.getName()).get(RFAGlobalConstants.RECORDTYPE_SMALL_PROJECT_REQUEST).Id;
        
        System.runAs(RFATestData.requester)
        {
            RFA__c testRFA1 = new RFA__c();
            testRFA1.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA1.RecordTypeId =     rt;
            testRFA1.RequestTitle__c = 'Capital Project Request RFA Title';
            testRFA1.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA1.Stage__c = 'Draft';
            testRFA1.RequestAmountFunctionalCurrency__c = 1200;     
            testRFA1.Functional_Currency__c = RFATestData.testARE.Id;
            testRFA1.Stage__c = 'Pre-Circulation';
            testRFA1.Level__c = 'Draft';
            testRFA1.DataClassification__c = 'Internal Use';
            testRFA1.AREMonth__c = 'February';
            testRFA1.InitialBudgetYear__c = '2013';
            testRFA1.BudgetType__c = 'Formal';
            testRFA1.IsthisanAnnualCapitalPlanrequest__c = 'No';
            testRFA1.ExecutiveSummary__c = 'This is for the purpose of testing';
            testRFA1.PrimaryDOACategorySubCategory__c = '1.A.1  Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA1;
            
            RFA__c testRFA2 = new RFA__c();
            testRFA2.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA2.RecordTypeId =     rt;
            testRFA2.RequestTitle__c = 'Capital Project Request RFA Title';
            testRFA2.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA2.Stage__c = 'Draft';
            testRFA2.RequestAmountFunctionalCurrency__c = 1200;     
            testRFA2.Functional_Currency__c = RFATestData.testARE.Id;
            testRFA2.Stage__c = 'Pre-Circulation';
            testRFA2.Level__c = 'Draft';
            testRFA2.DataClassification__c = 'Internal Use';
            testRFA2.AREMonth__c = 'February';
            testRFA2.InitialBudgetYear__c = '2013';
            testRFA2.BudgetType__c = 'Formal';
            testRFA2.IsthisanAnnualCapitalPlanrequest__c = 'No';
            testRFA2.ExecutiveSummary__c = 'This is for the purpose of testing';
            testRFA2.PrimaryDOACategorySubCategory__c = '1.A.1  Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA2;
            
            RFA__c testRFA3 = new RFA__c();
            testRFA3.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA3.RecordTypeId =     rt;
            testRFA3.RequestTitle__c = 'Capital Project Request RFA Title';
            testRFA3.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA3.Stage__c = 'Draft';
            testRFA3.RequestAmountFunctionalCurrency__c = 1200;     
            testRFA3.Functional_Currency__c = RFATestData.testARE.Id;
            testRFA3.Stage__c = 'Pre-Circulation';
            testRFA3.Level__c = 'Draft';
            testRFA3.DataClassification__c = 'Internal Use';
            testRFA3.AREMonth__c = 'February';
            testRFA3.InitialBudgetYear__c = '2013';
            testRFA3.BudgetType__c = 'Formal';
            testRFA3.IsthisanAnnualCapitalPlanrequest__c = 'No';
            testRFA3.ExecutiveSummary__c = 'This is for the purpose of testing';
            testRFA3.PrimaryDOACategorySubCategory__c = '1.A.1  Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA3;
            
            RFA__c testRFA4 = new RFA__c();
            testRFA4.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
            testRFA4.RecordTypeId =     rt;
            testRFA4.RequestTitle__c = 'Capital Project Request RFA Title';
            testRFA4.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
            testRFA4.Stage__c = 'Draft';
            testRFA4.RequestAmountFunctionalCurrency__c = 1200;     
            testRFA4.Functional_Currency__c = RFATestData.testARE.Id;
            testRFA4.Stage__c = 'Pre-Circulation';
            testRFA4.Level__c = 'Draft';
            testRFA4.DataClassification__c = 'Internal Use';
            testRFA4.AREMonth__c = 'February';
            testRFA4.InitialBudgetYear__c = '2013';
            testRFA4.BudgetType__c = 'Formal';
            testRFA4.IsthisanAnnualCapitalPlanrequest__c = 'No';
            testRFA4.ExecutiveSummary__c = 'This is for the purpose of testing';
            testRFA4.PrimaryDOACategorySubCategory__c = '1.A.1  Capital Expenditures - Annual Capital Plan Request or Formal Approval of Annual Capital Plan Request';
            insert testRFA4;
        }
        
        String jobId = System.schedule('testDraftBatchReminderApex',
        RFA_AP14_DraftRFAReminderSchedulable.CRON_EXP,  
        new RFA_AP14_DraftRFAReminderSchedulable());
        
        String baseQuery = 'Select ProfitCenterNumber__c, Id, CreatedById, ControlNumber__c, Stage__c, RequestTitle__c FROM RFA__c WHERE';
        //baseQuery = baseQuery + ' ' + 'createdDate < NEXT_N_DAYS:1';
        baseQuery = baseQuery + ' ' + 'Stage__c =' + '\'' + RFAGlobalConstants.RFA_STAGE_DRAFT + '\'';  
        baseQuery = baseQuery + ' ' + ' ' + 'ORDER BY CreatedById LIMIT 20';
        
        RFA_AP15_RFADraftReminderBatchable draftBatchReminder = new RFA_AP15_RFADraftReminderBatchable(baseQuery);
        //execute batch
        database.executebatch(draftBatchReminder); 
    }
}