Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>PrimaryReportingUnitNumber__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reporting Unit (RU) is the same as Co. Code and is either a legal entity or an acctg location.  RU is a four-digit code with an “RU” prefix in this system (e.g. RU0101 – North America).  Select the RU(s) recording the transaction.</inlineHelpText>
        <label>Primary Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProfitCenterNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>An org. unit designated as a separate entity for revenue generation and cost collection. Profit centers (PC) listed depend on the Group selected. Select the PC primarily responsible for the transaction. RFA coordinators are assigned by PC.</inlineHelpText>
        <label>Profit Center Number</label>
        <referenceTo>ProfitCenter__c</referenceTo>
        <relationshipLabel>RFA</relationshipLabel>
        <relationshipName>RFA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestTitle__c</fullName>
        <inlineHelpText>A concise description of the transaction, which is written as a phrase.  (e.g.,  Write-off  45 non-working vending machines in Atlanta sales center)</inlineHelpText>
        <label>Request Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondReportingUnitNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A four-digit code that is the lowest level at which consolidation occurs. Same as Co. code and is either a legal entity or an acctg. location (e.g., 0101 - North America). Select the reporting unit(s) recording the transaction.</inlineHelpText>
        <label>Second Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA (Secondary Reporting Unit Number)</relationshipLabel>
        <relationshipName>RFA1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ThirdReportingUnitNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A four-digit code that is the lowest level at which consolidation occurs. Same as Co. code and is either a legal entity or an acctg. location (e.g., 0101 - North America). Select the reporting unit(s) recording the transaction.</inlineHelpText>
        <label>Third Reporting Unit #</label>
        <referenceTo>ReportingUnit__c</referenceTo>
        <relationshipLabel>RFA (Third Reporting Unit Number)</relationshipLabel>
        <relationshipName>RFA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC11_ReportingUnitRecalc_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class RFA_VFC11_ReportingUnitRecalc_Test {

    static testMethod void myUnitTest() {
    	RFATestData testData = new RFATestData();
    	RFA__c testRFA = new RFA__c();
    	
    	testData.buildProfitCenter();
    	
    	testRFA.ProfitCenterNumber__c = RFATestData.testProfitCenter.Id;
		testRFA.RecordTypeId = 	RFATestData.getRecordType('General Request', 'RFA__c'); 
		testRFA.RequestTitle__c = 'General Request RFA Title';
		testRFA.PrimaryReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
		testRFA.SecondReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
		testRFA.ThirdReportingUnitNumber__c = RFATestData.testReportingUnit.Id;
		testRFA.Stage__c = 'Draft';
		
		insert testRFA;
    	
    	PageReference pg = Page.RFA_RF1_10_ReportingUnitRecalculation;
    	Test.setCurrentPage(pg);
 		pg.getParameters().put('id', RFATestData.testReportingUnit.Id);
 		ApexPages.StandardController sc = new ApexPages.StandardController(RFATestData.testReportingUnit);
     	RFA_VFC11_ReportingUnitRecalculation control=new RFA_VFC11_ReportingUnitRecalculation(sc);
    	control.callRecalculationMethod();
    }
}