Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>LevelStageCopy__c</fullName>
        <label>LevelStageCopy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC_AsyncronusclasstoReset.cls
//ASynchronous class to reset a value

Public class RFA_VFC_AsyncronusclasstoReset{
    public static boolean asyn = true;
@future
    public static void resetRFALevelStageCopyfield(List<id> rfaids){
        system.debug('---Asyncronusclass--->');
        list<RFA__c> rfas= new list<RFA__c>();
        rfas=[select id,levelStageCopy__c from RFA__C where id in: rfaids];
        
        for(RFA__C rfaObj:rfas){
            rfaObj.levelStageCopy__c=null; 
        }
        if(asyn == true){
            asyn = false;
            update rfas;
        } 
    } 
}