Jann 30/objects/RFA__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>Automatically assigned by the RFA database based upon the stage of the RFA approval.</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Circulation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RFA</label>
    <nameField>
        <displayFormat>RFA#-{0000000}</displayFormat>
        <label>RFA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Jann 30/objects/RFAUserRole__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalRecommendation__c</fullName>
        <label>Approval Recommendation</label>
        <picklist>
            <picklistValues>
                <fullName>Unconditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notifyuserfirsttime__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notifyuserfirsttime</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RFA__c</fullName>
        <label>RFA</label>
        <referenceTo>RFA__c</referenceTo>
        <relationshipName>RFA_User_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFAUserRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver/User</label>
    <nameField>
        <displayFormat>Details-{00000000}</displayFormat>
        <label>Approval Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers/Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Jann 30/classes/RFA_VFC05_RFAClosingController.cls
/*
    Author           : Accenture
    Date Created     :  5/18/2012
    Description      : This class is called from the visualforce page <PAGE NAME> and contains logic pertaining to the closing of an RFA    
                       
    Version          : 2.0 
*/ 
public class RFA_VFC05_RFAClosingController{
    
    // variable for holding the user selected stage value
    public String selectedStage{get;set;}   
    // variable for holding the in context rfa
    public RFA__c rfaObj{get;set;}
    // variable for determining the error during the processing
    public boolean hasError{get; private set;}
    // variable for determining the validation check for Approver
    public boolean hasApproved{get; private set;}
    public boolean atInfoCopy{get; private set;}
    // variable for holding the approver ID's
    public String approverIds{get;set;}   

    public static Map<String, Map<String, RecordType>> RECORDTYPESMAP = RFAGlobalConstants.RECORDTYPESMAP;
    public static Map<String, RecordType> approverInfoCopyMap = RECORDTYPESMAP.get(Schema.sObjectType.RFAUserRole__c.getName());

    
    //constructor for the class    
    public RFA_VFC05_RFAClosingController() {
          
    }

    // override constructor
    public RFA_VFC05_RFAClosingController(ApexPages.StandardController controller) {
        hasApproved = false;
        atInfoCopy = false;
        this.rfaObj = (RFA__c)controller.getRecord();
        
         /*set<ID> rtID = new set<ID>();
         rtID.add(approverInfoCopyMap.get(RFAGlobalConstants.RECORDTYPE_INFOONLY).Id);
         rtID.add(approverInfoCopyMap.get(RFAGlobalConstants.APPROVER_RECORDTYPE).Id);*/
        
        list<RFAUserRole__c> RFA_UUR = [select UserName__r.Name from RFAUserRole__c where RFA__c=: rfaObj.Id 
                                            and (
                                                    (
                                                        recordtypeId =: approverInfoCopyMap.get(RFAGlobalConstants.APPROVER_RECORDTYPE).Id 
                                                        and ApprovalRecommendation__c not in ('Unconditionally Approved','Conditionally Approved','Rejected', 'No Longer Needed', 'Ratification')
                                                    )
                                                OR (
                                                        Notifyuserfirsttime__c=false 
                                                        and recordtypeId =: approverInfoCopyMap.get(RFAGlobalConstants.RECORDTYPE_INFOONLY).Id
                                                    )
                                                )
                                            ];
        if (RFA_UUR.size()>0){
            hasApproved= true;
            for(RFAUserRole__c UUR : RFA_UUR){
                if(approverIds== null){approverIds = UUR.UserName__r.Name;}
                else{approverIds = approverIds +', '+ UUR.UserName__r.Name;}
            }
        }
    }
    
    /* @Method <This method evaluates is called from the action button of the page and contains logic to update an RFA >
       @param <None>
       @return <pagereference>        
    */
    public pageReference updateRFA()
    {   
        try{
            // if user has not selected a stage for the error,force an error
            if(selectedStage == null || selectedStage == ' ') throw new RFAException('Please select an Action');
            // set the selected stage
            rfaObj.Stage__c = selectedStage;
            // update the rfa
            update rfaObj;
            
        }catch(Exception ex){
            // catch exception
            hasError = true;
            return null;
        }
            /*PageReference pref;
            ApexPages.StandardController sc = new ApexPages.StandardController(rfaObj);
            pref = sc.view();
            pref.setRedirect(true); 
            */
            //return null;
             return new pageReference('/apex/RFA_VFP04_CompletionMemo?id='+rfaObj.Id);
    }
   
   /*
        Class Type     : Inner Class (RFAException) extends Exception
        Date Created   : 5/18/2012
        Description    : Custom Exception class extending the parent exeption class.
        Version        : 1.0 
    */ 
   public class RFAException extends Exception{ }
   
}