Jann 30/objects/RFA_Approver__c.object
<CustomObject>
    <fields>
        <fullName>UserName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UserName</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RFA_Approvers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFA Approver_old</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>RFA Approver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RFA Approvers_old</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Jann 30/classes/RFA_RemoveInactiveApprovers.cls
/****************************************************************************************************************************************
 ****************************************************************************************************************************************    
 *  Class            : RFA_RemoveInactiveApprovers
 *  Author           : Infosys
 *  Version History  : 1.0
 *  Creation         : 22/12/2015
 *  Description      : Class to remove the user from RFA Approver object when the user gets inactivated.
                                    
 ****************************************************************************************************************************************/
Public class RFA_RemoveInactiveApprovers
{
    Public void removeAfterUpdate(List<User> usersList)
    {
        List<Id> userId = new List<Id> ();
        for(User userObj : usersList)
        {
            system.debug('userObj.IsActive'+userObj.IsActive);
                
            if(userObj.IsActive == false)
            {
                userId.add(userObj.Id);
            }
        }
        if(userId!=null&&userId.size()>0)
        {
            futureRemoveApprovers(userId);
        }
        
    }
    @future
    public static void futureRemoveApprovers(List<ID> userIDs)
    {
        try{
        //Fetch all the RFA approvers 
        List<RFA_Approver__c> rfaApproversToBeDeleted = [select id,UserName__c from RFA_Approver__c where UserName__c in : userIDs];
        System.debug('RFA Approver List to be deleted : ' + rfaApproversToBeDeleted);        
        //Deleting the inactivated users from the RFA COA Group object
        if (rfaApproversToBeDeleted != null)
        {
                        Delete rfaApproversToBeDeleted;
        }
        }
        catch(Exception ex)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage()));       
        }
    }
}